window.MONTALE_DATA = {
  sources: [
    {kind:"Fonte dell'utente", title:"Analisi opera poetica di Montale", note:"Usata come repertorio iniziale; cronologia e interpretazioni sono state ricontrollate. La data di nascita indicata nel documento è stata corretta.", url:"https://docs.google.com/document/d/1lvuyFsMNepU9pfCYuH5MlX4twhQjG-p1nDc2GAPtLvw/edit?usp=drivesdk"},
    {kind:"Università", title:"La letteratura italiana del Novecento: un itinerario europeo", note:"Griseldaonline, Università di Bologna: formazione, poetica, continuità delle prime raccolte, svolta di Satura.", url:"https://site.unibo.it/griseldaonline/it/letteratura-italiana/filippo-milani-letteratura-italiana-novecento-itinerario-europeo"},
    {kind:"Università", title:"Per una mappatura delle carte montaliane", note:"Rivista dell'Università di Milano: documenti, rapporti editoriali, Vieusseux, Clizia, attività al Corriere.", url:"https://riviste.unimi.it/index.php/PEML/article/view/12411"},
    {kind:"Università", title:"Montale e i paradisi d'infanzia", note:"Configurazioni, Università di Milano: paesaggio ligure, memoria e trasformazione dei simboli nell'ultimo Montale.", url:"https://riviste.unimi.it/index.php/configurazioni/article/view/30086"},
    {kind:"Istituzionale", title:"Eugenio Montale – Premio Nobel 1975", note:"Nobel Prize: dati biografici, motivazione e conferenza «È ancora possibile la poesia?».", url:"https://www.nobelprize.org/prizes/literature/1975/montale/facts/"},
    {kind:"Istituzionale", title:"Dichiarazione per il 120° anniversario della nascita", note:"Quirinale: profilo civile, antifascismo, senatore a vita e rilievo europeo.", url:"https://www.quirinale.it/it/comunicato/dichiarazione-presidente-mattarella-120anniversario-nascita-eugenio-montale"}
  ],
  sections: [
    {
      id:"mondo", number:"01", title:"Il mondo precedente", subtitle:"Una tradizione ancora intatta in apparenza, un secolo già senza centro", question:"Quale realtà riceve Montale, e perché non può più parlare con la voce sicura del poeta-vate?", bridge:"Il mondo ereditato promette unità; la guerra e la crisi della conoscenza ne rivelano le crepe.",
      lesson:[
        {id:"m-tesi",title:"La poesia dopo la perdita del centro",paragraphs:[
          "Montale nasce a Genova il 12 ottobre 1896 e si forma mentre l'Europa entra nella modernità industriale, nelle società di massa e nella competizione imperialistica. Il dato decisivo non è soltanto storico: cambia il modo in cui l'individuo pensa di conoscere il mondo. Le filosofie della crisi, la psicoanalisi, la nuova fisica e l'esperienza delle avanguardie incrinano l'idea positivistica che la realtà sia pienamente misurabile e ordinabile. Il giovane poeta riceve dunque due eredità in conflitto: una grande tradizione letteraria, ancora capace di offrire forme e autorità, e una realtà che non sembra più obbedire a un disegno leggibile.",
          "Il problema iniziale della sua poesia nasce qui. Il poeta può ancora utilizzare il sonetto, l'endecasillabo, Dante, Petrarca o Leopardi; non può però fingere che quelle forme garantiscano da sole una verità condivisa. La tradizione resta un deposito di tecniche, ritmi e parole da sottoporre a pressione. Per questo Montale non distrugge semplicemente il passato: lo rende dissonante, lo accosta al parlato, ai termini tecnici, alla ruvidità delle cose. La modernità non coincide con la cancellazione della forma; coincide con la necessità di far sentire, dentro la forma, la crisi che la attraversa."
        ]},
        {id:"m-dannunzio",title:"Contro la voce che domina il mondo",paragraphs:[
          "All'inizio del Novecento la figura di Gabriele d'Annunzio rappresenta un modello quasi inevitabile. Il poeta-vate trasforma la parola in gesto pubblico, seduzione e potenza: nomina la realtà come se potesse possederla, celebra l'eccezione dell'artista e costruisce una lingua alta, sonora, espansiva. Montale parte anche da questa lezione, ma ne rovescia il presupposto. Nei suoi paesaggi non c'è fusione trionfale con la natura; ci sono muri, sterpi, pietre, scaglie, rive disseccate. La natura non restituisce all'io una pienezza: gli oppone la propria alterità.",
          "Sarebbe però superficiale ridurre Montale a un semplice anti-D'Annunzio. Egli impara dal predecessore la precisione sensoriale, l'attenzione musicale, la forza del nome concreto. Rifiuta invece l'idea che l'intensità della parola equivalga a una rivelazione. La sua dizione può essere alta o aspra, ma non pretende di trasformare il poeta in guida della nazione. In «Non chiederci la parola» la negazione è già una presa di posizione etica: meglio una parola incompleta che una formula capace di squadrare definitivamente l'animo umano."
        ]},
        {id:"m-liguria",title:"La periferia ligure come laboratorio",paragraphs:[
          "Genova e la Riviera di Levante non sono uno sfondo ornamentale. L'Università di Bologna ricorda che la Liguria costituisce la matrice della poesia montaliana: una regione periferica rispetto alle grandi capitali culturali, ma aperta ai commerci e alle lingue d'Europa. Questa posizione diventa una forma mentale. Il poeta osserva il mondo da un margine che permette di resistere ai centri, alle scuole e alle appartenenze troppo nette. Anche la sua formazione è irregolare: diploma tecnico, letture autonome, studio del canto, incontri con poeti liguri, attenzione alla cultura francese e anglosassone.",
          "Il paesaggio delle Cinque Terre concentra la contraddizione essenziale. Il mare suggerisce apertura, movimento e un altrove possibile; la terra assolata presenta muri, sentieri chiusi e materia consumata. L'osso di seppia, residuo leggero lasciato sulla riva, condensa questa condizione: è ciò che resta dopo che la vita organica è stata svuotata e levigata. Non è ancora un'allegoria chiusa con un significato fisso; è un oggetto che costringe il pensiero a muoversi tra perdita, resistenza e possibile rivelazione."
        ]},
        {id:"m-europa",title:"Simbolismo, vociani e modernismo europeo",paragraphs:[
          "Montale legge i simbolisti francesi, i poeti inglesi, i metafisici e autori come Valéry, Eliot, Svevo e Kafka. Da queste esperienze ricava una lezione comune: la realtà non si offre in modo diretto, e la poesia deve costruire rapporti tra frammenti senza cancellarne l'opacità. Il simbolo montaliano, tuttavia, non apre con sicurezza a un mondo superiore. Può indicare una soglia, un'anomalia, l'attesa di un evento; spesso lascia il lettore davanti a una promessa che non si compie. La poesia non decifra il reale una volta per tutte: registra i punti in cui il reale sembra sul punto di incrinarsi.",
          "Anche le riviste italiane contribuiscono alla sua educazione. Dalla «Voce» e dall'ambiente ligure riceve una lingua concreta e moralmente sorvegliata; da «Primo Tempo» e dal «Baretti» di Gobetti un'idea europea e non provinciale della cultura. Nel 1925, quando pubblica Ossi di seppia, Montale non si presenta come l'inventore isolato di una nuova poesia. Entra in una rete di discussioni sulla tradizione, sulla responsabilità dell'intellettuale e sulla possibilità di dire l'esperienza moderna senza trasformarla in propaganda."
        ]},
        {id:"m-ponte",title:"Il limite che prepara la frattura",paragraphs:[
          "Il mondo precedente consegna dunque a Montale strumenti potenti ma promesse ormai sospette. Il positivismo non basta a spiegare l'esistenza; il poeta-vate appare incompatibile con una coscienza che non domina la realtà; il simbolismo apre corrispondenze che possono restare mute. La questione non è scegliere tra passato e innovazione, ma trovare una forma che conservi il rigore della tradizione e ammetta l'incertezza moderna.",
          "La Prima guerra mondiale, il fascismo e le lacerazioni private renderanno questa tensione concreta. È importante non trasformare la biografia in una macchina causale: non si può dire che ogni immagine poetica derivi da un episodio. Le esperienze di Montale rendono però intelligibile il passaggio da una crisi culturale generale a una posizione individuale: la verità, se esiste, non coincide con le parole d'ordine del tempo. La prossima sezione seguirà proprio i momenti in cui il mondo ricevuto diventa insufficiente."
        ]}
      ],
      summary:"Montale riceve una tradizione letteraria prestigiosa, ma si forma nel momento in cui positivismo, centralità dell'io e fiducia nel progresso entrano in crisi. Di D'Annunzio conserva la precisione sensoriale e musicale, ma rifiuta la sicurezza del poeta-vate. La Liguria diventa una matrice conoscitiva: mare e terra arida rendono visibile la tensione tra apertura e limite. Simbolismo, cultura vociana e modernismo europeo gli insegnano che la realtà non si offre direttamente. La tradizione, quindi, non viene demolita: è sottoposta a dissonanza e contaminata con parole comuni e oggetti aspri. Il problema che prepara le fratture biografiche è decisivo: come conservare il rigore della forma quando nessuna forma garantisce più una verità condivisa?",
      essentials:["Spiegare perché la crisi del positivismo modifica la funzione della poesia.","Distinguere l'uso montaliano della tradizione da una semplice rottura avanguardistica.","Spiegare il rovesciamento del modello dannunziano del poeta-vate.","Mostrare perché la Liguria è una matrice conoscitiva e non uno sfondo.","Collegare simbolismo e modernismo alla difficoltà di conoscere il reale.","Formulare il problema iniziale: dire il vero senza possedere una verità totale."],
      glossary:[['Poeta-vate','Poeta che rivendica una funzione pubblica di guida e interprete della comunità.'],['Positivismo','Fiducia ottocentesca nella conoscenza scientifica e nel progresso, entrata in crisi nel Novecento.'],['Modernismo','Ricerca europea che rinnova le forme per rappresentare una realtà frammentata e una coscienza instabile.'],['Simbolismo','Poetica delle corrispondenze e dell’allusione; in Montale la rivelazione resta spesso sospesa.'],['Dissonanza','Attrito intenzionale tra registri, forme o immagini che impedisce una lettura armonica.'],['Tradizione','Repertorio attivo di forme e voci da trasformare, non autorità da ripetere.']],
      map:"maps/01-mondo.svg", mapAlt:"La modernità mette in crisi positivismo e poeta-vate; la Liguria, la tradizione e il modernismo europeo confluiscono nel problema di dire una realtà priva di centro.",
      quiz:[
        {q:"Qual è il conflitto fondamentale del mondo ricevuto da Montale?",o:["Tra una tradizione formale autorevole e una realtà non più leggibile come ordine unitario","Tra poesia dialettale e poesia latina","Tra cultura scientifica e rifiuto di ogni forma metrica"],a:0,e:"Montale eredita forme forti, ma non la certezza che esse garantiscano una verità condivisa.",r:{c:"Tradizione e crisi",x:"La modernità montaliana non elimina il passato: ne usa le forme facendovi entrare l'incertezza.",ex:"Un endecasillabo può restare riconoscibile mentre lessico e immagini producono attrito.",anchor:"m-tesi",retry:"Montale abbandona completamente la tradizione?"}},
        {q:"In che senso Montale è anti-dannunziano?",o:["Rifiuta ogni attenzione musicale","Rovescia la sicurezza del poeta-vate senza rinunciare alla precisione sensoriale","Sceglie esclusivamente il linguaggio quotidiano"],a:1,e:"Il rovesciamento riguarda la funzione e la certezza della parola, non la cancellazione di ogni lezione formale.",r:{c:"Il rovesciamento di D'Annunzio",x:"Montale apprende tecniche dal predecessore ma ne rifiuta la parola dominante e celebrativa.",ex:"Gli oggetti non celebrano la fusione dell'io con la natura: gli oppongono un limite.",anchor:"m-dannunzio",retry:"Che cosa conserva Montale di D'Annunzio?"}},
        {q:"Perché la Liguria non è un semplice sfondo?",o:["Perché documenta soltanto i viaggi del poeta","Perché sostituisce ogni tema storico","Perché organizza la tensione fra chiusura terrestre e apertura del mare"],a:2,e:"Il paesaggio ligure diventa una struttura del conoscere: soglia, limite, aridità e attesa.",r:{c:"Paesaggio come pensiero",x:"Muri, pietre e mare rendono visibile un conflitto esistenziale e conoscitivo.",ex:"L'osso di seppia è un residuo materiale che apre più significati.",anchor:"m-liguria",retry:"Quale coppia descrive meglio il paesaggio ligure?"}},
        {q:"Che cosa distingue il simbolo montaliano?",o:["Garantisce sempre l'accesso a una realtà superiore","Può indicare una soglia senza assicurare che la rivelazione avvenga","Possiede un significato unico fissato dal poeta"],a:1,e:"Il segno apre una possibilità, ma conserva opacità e rischio di fallimento.",r:{c:"Simbolo e soglia",x:"L'oggetto poetico non è un codice con soluzione automatica.",ex:"Un varco può essere atteso o intravisto senza diventare possesso definitivo.",anchor:"m-europa",retry:"Il simbolo montaliano risolve l'enigma del reale?"}},
        {q:"Quale problema conduce alla sezione delle fratture?",o:["Come eliminare la ragione dalla poesia","Come imitare fedelmente i simbolisti francesi","Come dire il vero senza fingere di possedere una verità totale"],a:2,e:"È il nucleo etico e conoscitivo da cui muove l'intero percorso.",r:{c:"Il problema iniziale",x:"Montale cerca una forma esatta che non si trasformi in formula assoluta.",ex:"La negazione può essere più onesta di una definizione totalizzante.",anchor:"m-ponte",retry:"Per Montale la poesia deve offrire certezze complete?"}}
      ]
    },
    {
      id:"fratture", number:"02", title:"Le fratture della vita", subtitle:"Guerra, fascismo, separazioni: la coscienza messa alla prova", question:"Che cosa rende insufficiente il mondo ricevuto, senza trasformare la vita in una spiegazione meccanica dei versi?", bridge:"Le crisi non producono automaticamente le opere: modificano però il rapporto fra coscienza, storia e linguaggio.",
      lesson:[
        {id:"f-formazione",title:"Una formazione laterale",paragraphs:[
          "Montale non segue il percorso universitario tipico dell'intellettuale di professione. Ottiene il diploma di ragioneria, studia canto da baritono e costruisce gran parte della propria cultura attraverso letture autonome. Questa lateralità non va romanticizzata come puro isolamento: intrattiene relazioni con poeti, critici, editori e musicisti, legge lingue straniere, partecipa alle riviste. La frattura è piuttosto tra l'identità sociale prevista e la vocazione lentamente riconosciuta. La competenza musicale lascia un segno profondo nella precisione ritmica della poesia, anche quando il verso sembra aspro o prosastico.",
          "La morte nel 1923 del maestro di canto Ernesto Sivori chiude simbolicamente una possibile carriera musicale. Non è corretto dedurne che da quell'evento nasca la poesia montaliana; l'esperienza offre però un contesto per comprendere la convivenza tra voce e impossibilità della voce. Montale conosce la disciplina del fiato, del timbro, della frase, ma sceglie una parola che diffida del canto pieno. Il poeta che sa come si costruisce una bella emissione decide spesso di far sentire l'attrito, il borbottio e la sillaba storta."
        ]},
        {id:"f-guerra",title:"La guerra senza diario lirico",paragraphs:[
          "Nel 1917 è chiamato alle armi e presta servizio come ufficiale di fanteria. A differenza di Ungaretti, non costruisce la propria identità poetica come testimonianza immediata del fronte. Perciò sarebbe arbitrario leggere ogni aridità degli Ossi come traduzione diretta della trincea. La guerra appartiene però alla frattura generazionale che rende poco credibili progresso, retorica nazionale e continuità civile. Il giovane europeo scopre che razionalità tecnica e distruzione di massa possono procedere insieme.",
          "Questa esperienza aiuta a capire il rifiuto montaliano delle parole assolute. I grandi vocaboli collettivi — patria, destino, vittoria — sono stati consumati dalla propaganda. La poesia deve tornare a misurare ciò che dice. Invece di offrire un diario eroico o una confessione nuda, Montale trasferisce la tensione negli oggetti e nei paesaggi. Il dato biografico non sparisce: viene sottratto all'esibizione e trasformato in struttura. È uno dei motivi per cui il lettore incontra l'effetto prima della causa occasionale."
        ]},
        {id:"f-fascismo",title:"Antifascismo come primato della coscienza",paragraphs:[
          "Il 1925 unisce due atti: la pubblicazione di Ossi di seppia presso Piero Gobetti e l'adesione al Manifesto degli intellettuali antifascisti promosso da Benedetto Croce. Il nesso non autorizza a leggere la raccolta come un programma politico; mostra però una coerenza. La parola poetica rifiuta formule positive e totalizzanti, mentre la coscienza civile diffida di un regime che impone appartenenza, linguaggio e mito collettivo. Nel 1938 Montale perde la direzione del Gabinetto Vieusseux dopo non essersi iscritto al Partito fascista.",
          "L'antifascismo montaliano non coincide sempre con una militanza organizzata. È un'etica della non adesione, esposta anche ai propri limiti: difesa dell'autonomia individuale, sospetto verso la retorica e i sistemi che chiedono di consegnare la coscienza. Durante la guerra e la Resistenza si avvicina brevemente al Partito d'Azione e partecipa alla vita culturale del CLN fiorentino. La storia entra così nella poesia non come illustrazione di un'ideologia, ma come pressione che rende impossibile l'innocenza privata."
        ]},
        {id:"f-clizia",title:"Clizia: presenza reale, funzione poetica",paragraphs:[
          "L'incontro con Irma Brandeis nel 1933 e la successiva separazione costituiscono una frattura affettiva e intellettuale. Nelle Occasioni la donna diventa Clizia, figura sottoposta a una trasformazione che non cancella la persona reale ma la inserisce in una costruzione simbolica. Le leggi razziali e la partenza per gli Stati Uniti collegano distanza amorosa e catastrofe europea. La figura femminile può così concentrare memoria privata, resistenza della cultura e attesa di un valore che attraversi la barbarie.",
          "Occorre evitare due errori. Il primo è ridurre Clizia a maschera biografica da decodificare, come se conoscere Irma esaurisse la poesia. Il secondo è chiamarla semplicemente «salvezza», senza vedere quanto quella funzione resti minacciata, intermittente e storicamente esposta. Le carte conservate negli archivi documentano la relazione; l'opera la ricrea. La biografia fornisce l'occasione, ma il testo costruisce rapporti che superano l'aneddoto."
        ]},
        {id:"f-mosca",title:"Mosca, il lutto e la misura quotidiana",paragraphs:[
          "Drusilla Tanzi, detta Mosca, condivide a lungo la vita di Montale e lo sposa nel 1962; muore l'anno seguente. Nei testi di Xenia, poi confluiti in Satura, il lutto non produce un monumento solenne. La memoria passa attraverso gesti, abitudini, oggetti e una sapienza pratica dello sguardo. Rispetto alla verticalità simbolica di Clizia, Mosca rappresenta una forma di orientamento terrestre: non promette di sciogliere il male del mondo, ma rende abitabile la sua confusione.",
          "Questa differenza illumina una trasformazione più ampia. Nel dopoguerra Montale lavora al Corriere della Sera, attraversa la società dei consumi e osserva la moltiplicazione dei linguaggi pubblici. Dopo un lungo silenzio poetico, Satura risponde con ironia, prosa, satira e affetto anti-monumentale. La frattura del lutto incontra la crisi della funzione sociale della poesia. Il poeta non rinuncia alla precisione: cambia registro perché è cambiato il rumore del mondo."
        ]},
        {id:"f-ponte",title:"Dalla vita alla visione, senza scorciatoie",paragraphs:[
          "Guerra, fascismo, espulsione dal Vieusseux, separazione da Irma, morte di Drusilla: sono eventi differenti e non una serie ordinata di cause letterarie. Ciò che li collega è la prova imposta alla coscienza. Ogni volta un sistema, una relazione o una continuità mostra il proprio limite. Montale risponde non con una dottrina, ma con una vigilanza: sottrarre la parola all'enfasi, trasformare l'esperienza in oggetti, conservare la fedeltà a presenze assenti.",
          "Da queste fratture emerge un'immagine del mondo nella quale il reale è discontinuo, la storia non garantisce progresso e la salvezza, se appare, ha la forma breve di un varco. Il passaggio non è psicologico — un uomo soffre e quindi diventa pessimista — ma conoscitivo: l'esperienza rende evidente che nessuna totalità protegge l'individuo. La sezione successiva chiederà come appare la realtà a una coscienza che ha attraversato queste prove."
        ]}
      ],
      summary:"Le fratture biografiche non spiegano automaticamente la poesia, ma rendono intelligibile la sua tensione. La formazione laterale e musicale prepara una parola rigorosa ma diffidente verso il canto pieno. La Prima guerra mondiale consuma le retoriche del progresso; Montale non la trasforma però in diario lirico. L'adesione al Manifesto antifascista e l'allontanamento dal Vieusseux mostrano il primato della coscienza sulle appartenenze imposte. Irma Brandeis diventa Clizia: l'occasione privata è trasfigurata in figura culturale e storica. Drusilla Tanzi, Mosca, introduce invece una misura quotidiana che orienta senza promettere redenzione. Da queste prove emerge una visione discontinua: la storia non garantisce senso e ogni apertura assume la forma precaria di un varco.",
      essentials:["Ricostruire il valore della formazione musicale senza farne una causa unica dello stile.","Distinguere l'esperienza bellica di Montale dal diario lirico di Ungaretti.","Spiegare l'antifascismo come autonomia della coscienza e rifiuto della retorica.","Distinguere la persona Irma Brandeis dalla funzione poetica di Clizia.","Spiegare la diversa funzione di Clizia e Mosca.","Usare con cautela il rapporto fra biografia e testo, evitando determinismi."],
      glossary:[['Occasione','Evento biografico assorbito e trasformato nella struttura del testo.'],['Trasfigurazione','Passaggio dalla persona o esperienza reale a una funzione poetica più ampia.'],['Clizia','Nome poetico legato a Irma Brandeis; figura di distanza, cultura e resistenza.'],['Mosca','Nome affettivo di Drusilla Tanzi; presenza concreta e orientamento quotidiano.'],['Antifascismo','In Montale, scelta civile e difesa dell’autonomia della coscienza.'],['Determinismo biografico','Errore che fa derivare automaticamente un’opera da un episodio della vita.']],
      map:"maps/02-fratture.svg", mapAlt:"Formazione musicale, guerra, antifascismo, Clizia e Mosca mettono alla prova la coscienza e confluiscono in una visione discontinua del reale.",
      quiz:[
        {q:"Come va interpretata la formazione musicale di Montale?",o:["Come unica causa della sua poetica","Come disciplina della voce e del ritmo che convive con il rifiuto del canto pieno","Come esperienza priva di conseguenze sulla scrittura"],a:1,e:"La musica offre competenze formali, ma la poesia le usa anche per produrre attrito.",r:{c:"Musica e parola",x:"Il canto non causa la poetica, ma aiuta a comprenderne la precisione ritmica.",ex:"Una voce tecnicamente sorvegliata può scegliere la dissonanza.",anchor:"f-formazione",retry:"La formazione musicale spiega da sola la poesia?"}},
        {q:"Che cosa distingue l'esperienza di guerra di Montale da quella di Ungaretti?",o:["Montale non costruisce la propria poesia come diario immediato del fronte","Montale non partecipò alla guerra","Montale celebra la vittoria militare"],a:0,e:"La guerra agisce come frattura generazionale, ma non diventa il centro autobiografico diretto degli Ossi.",r:{c:"Guerra e mediazione",x:"Montale oggettiva l'esperienza invece di presentarla come confessione frontale.",ex:"Il paesaggio e gli oggetti portano la tensione senza raccontarne sempre l'origine.",anchor:"f-guerra",retry:"Gli Ossi sono un diario di trincea?"}},
        {q:"Quale fatto mostra concretamente il costo dell'antifascismo di Montale?",o:["La rinuncia al Nobel","L'abbandono della Liguria","La perdita della direzione del Gabinetto Vieusseux nel 1938"],a:2,e:"Il rifiuto dell'iscrizione al Partito fascista contribuì al suo allontanamento.",r:{c:"Coscienza e istituzioni",x:"La non adesione non fu soltanto un atteggiamento astratto: ebbe conseguenze professionali.",ex:"Nel 1938 perde la direzione del Vieusseux.",anchor:"f-fascismo",retry:"Quale istituzione fiorentina diresse Montale?"}},
        {q:"Perché Clizia non coincide semplicemente con Irma Brandeis?",o:["Perché è una figura interamente inventata senza rapporti biografici","Perché il testo trasforma una persona reale in funzione affettiva, culturale e storica","Perché compare soltanto nelle prose giornalistiche"],a:1,e:"La biografia documenta l'occasione; l'opera costruisce una figura che supera l'aneddoto.",r:{c:"Persona e figura",x:"Conoscere Irma aiuta, ma non esaurisce il significato di Clizia.",ex:"La distanza amorosa si lega alla resistenza culturale contro la barbarie.",anchor:"f-clizia",retry:"La biografia esaurisce il significato di Clizia?"}},
        {q:"Che cosa rappresenta Mosca negli Xenia?",o:["Una guida pratica e affettiva che rende abitabile la confusione","Un'allegoria della vittoria politica","Una replica identica della funzione di Clizia"],a:0,e:"Mosca orienta nel quotidiano senza assumere la stessa verticalità simbolica di Clizia.",r:{c:"La misura di Mosca",x:"Il lutto passa attraverso gesti e oggetti anti-monumentali.",ex:"La memoria coniugale conserva una sapienza concreta dello sguardo.",anchor:"f-mosca",retry:"Mosca promette una redenzione totale?"}}
      ]
    },
    {
      id:"visione", number:"03", title:"L'immagine del mondo", subtitle:"Disarmonia, contingenza e improvvise possibilità di varco", question:"Come appare la realtà quando non è più garantita da un ordine, ma non è neppure riducibile a puro nulla?", bridge:"Se il reale non può essere spiegato in astratto, occorre costruire una lingua di oggetti, attriti e apparizioni.",
      lesson:[
        {id:"v-disarmonia",title:"La disarmonia come condizione",paragraphs:[
          "L'immagine del mondo di Montale viene spesso riassunta con l'espressione «male di vivere». È una formula utile solo se non diventa un'etichetta psicologica. Il male non è semplicemente tristezza personale: è l'esperienza di una realtà che non coincide con il desiderio umano di ordine. Il mondo appare opaco, accidentale, privo di un centro che distribuisca significati e giustizia. La coscienza cerca nessi; incontra materiali che resistono. Da questo scarto nasce la disarmonia.",
          "Negli Ossi la condizione prende corpo nel paesaggio disseccato e negli impedimenti: un fluire strozzato, una materia riarsa, un animale abbattuto. Queste immagini non decorano un pensiero già formulato; sono il luogo in cui il pensiero accade. Il lettore non riceve una definizione filosofica e poi un esempio. È costretto a sperimentare fisicamente ostacolo, attrito e consumo. Perciò il male di vivere è insieme esistenziale ed epistemologico: si soffre anche perché non si possiede la chiave del reale."
        ]},
        {id:"v-limite",title:"Il limite e la prigionia dell'io",paragraphs:[
          "Il muro con i frammenti di vetro è una delle immagini più note del primo Montale. Se lo si traduce subito in «pessimismo», lo si impoverisce. Il muro separa e impedisce, ma permette anche di intuire che esiste un oltre. La coscienza non sarebbe prigioniera se non concepisse una possibilità di uscita. Il limite contiene dunque una struttura doppia: certifica la chiusura e genera l'attesa del varco.",
          "L'io montaliano non è sovrano. Non ordina la natura, non si scioglie armoniosamente in essa, non possiede una confessione capace di ricomporlo. È una coscienza vigile che registra segnali, fallimenti e improvvise eccezioni. Proprio questa vigilanza impedisce di identificare la visione montaliana con un nichilismo semplice. Il poeta non afferma che nulla abbia valore; rifiuta piuttosto di trasformare un valore desiderato in certezza. La sua negatività protegge il pensiero dalle consolazioni premature."
        ]},
        {id:"v-varco",title:"Il varco: possibilità, non dottrina",paragraphs:[
          "Nei testi montaliani compaiono momenti in cui la trama ordinaria sembra sul punto di spezzarsi: un bagliore, un odore, un incontro, una porta malchiusa, un dettaglio che promette accesso a un ordine diverso. Il varco è il nome didatticamente più efficace per questa possibilità. Non è una via religiosa stabilita né una soluzione che il soggetto possa ripetere a comando. È un evento contingente, fragile, talvolta mancato.",
          "L'Università di Bologna collega questa attesa anche alla riflessione di Émile Boutroux sulla contingenza: le leggi del mondo non escludono in assoluto l'irruzione del nuovo. In Montale ciò non diventa sistema filosofico. La poesia resta davanti al punto in cui necessità e miracolo si sfiorano. I limoni possono aprire per un istante una solarità; il mare può suggerire libertà; una figura femminile può custodire una resistenza. Nessuno di questi segni annulla definitivamente la disarmonia."
        ]},
        {id:"v-storia",title:"La storia senza provvidenza",paragraphs:[
          "Con Le occasioni e soprattutto La bufera e altro, la crisi non riguarda più soltanto il rapporto individuale con la natura. Fascismo, leggi razziali e guerra mostrano una storia che non garantisce progresso morale. La bufera è evento meteorologico, catastrofe storica e pressione sulla vita privata. Montale rifiuta sia l'idea provvidenziale sia le filosofie che leggono ogni violenza come tappa necessaria verso un futuro migliore.",
          "Questa posizione non equivale all'indifferenza politica. Al contrario, intensifica la responsabilità individuale: se la storia non salva automaticamente nessuno, la coscienza deve scegliere senza la protezione di un esito garantito. In «Piccolo testamento» l'eredità non assume la forma di una grande fede pubblica, ma di una traccia fragile da conservare. La resistenza morale è piccola in scala, non in valore. Rifiutare i sistemi totali significa difendere un nucleo non disponibile alla propaganda."
        ]},
        {id:"v-massa",title:"La società di massa e il rovescio ironico",paragraphs:[
          "Nel secondo dopoguerra il mondo non torna leggibile. Alla violenza politica si aggiunge la saturazione dei messaggi, dei consumi e delle opinioni. La società di massa promette comunicazione continua, ma produce rumore e conformismo. Il poeta premio Nobel non occupa per questo un pulpito rassicurante: nella conferenza del 1975 si domanda se la poesia sia ancora possibile dentro una comunicazione che moltiplica prodotti e parole.",
          "Satura risponde cambiando sguardo. L'allegoria si svuota, i simboli possono apparire come resti di un sistema precedente, il tono diventa ironico e diaristico. Non è la semplice decadenza di un vecchio poeta. È l'immagine di un mondo nel quale perfino l'eccezione rischia di essere assorbita. L'ironia diventa una forma di distanza critica: non resta fuori dal caos, ma impedisce al linguaggio pubblico di coincidere interamente con la coscienza."
        ]},
        {id:"v-ponte",title:"Una verità negativa e relazionale",paragraphs:[
          "L'immagine montaliana del mondo può essere formulata così: la realtà è disarmonica e non offre un ordine garantito; tuttavia contiene differenze, presenze e possibilità che non devono essere cancellate. La verità disponibile è spesso negativa — riconoscere ciò che non siamo, ciò che non vogliamo — ma non per questo vuota. La negazione stabilisce un limite etico alle menzogne e mantiene aperta la domanda.",
          "Questa visione crea un problema espressivo preciso. Se il poeta spiegasse direttamente la propria filosofia, trasformerebbe l'incertezza in dottrina. Deve invece farla accadere nella forma: oggetti che concentrano emozioni, lessico plurale, metri tradizionali incrinati, omissione dell'occasione biografica, ironia. La poetica sarà la risposta tecnica e morale a questa immagine del mondo."
        ]}
      ],
      summary:"Il «male di vivere» non è semplice tristezza, ma esperienza della disarmonia fra bisogno umano di ordine e opacità del reale. Gli oggetti non illustrano un concetto: lo fanno accadere nella percezione. Il limite, come il muro, è doppio: imprigiona ma lascia intuire un oltre. Il varco indica una possibilità contingente, mai una soluzione garantita. Con la guerra la disarmonia diventa storica: nessuna provvidenza o ideologia assicura il progresso, quindi cresce la responsabilità della coscienza. Nella società di massa il problema diventa la saturazione dei messaggi; l'ironia protegge una distanza critica. La verità montaliana è spesso negativa, ma non nichilistica: rifiuta le consolazioni premature e conserva differenze e possibilità. Questa visione esige una poetica indiretta, fondata su oggetti, attriti e omissioni.",
      essentials:["Spiegare il male di vivere come disarmonia esistenziale ed epistemologica.","Interpretare il limite come chiusura che rende pensabile un oltre.","Definire il varco come possibilità contingente, non soluzione ripetibile.","Collegare La bufera a una storia priva di garanzie provvidenziali.","Spiegare il ruolo dell'ironia nella critica alla società di massa.","Distinguere verità negativa e nichilismo assoluto."],
      glossary:[['Male di vivere','Disarmonia fra bisogno di senso e opacità della realtà.'],['Epistemologico','Relativo ai limiti e alle condizioni della conoscenza.'],['Varco','Possibilità improvvisa di oltrepassare l’ordine chiuso dell’esperienza.'],['Contingenza','Possibilità che le cose accadano diversamente da una necessità assoluta.'],['Provvidenza','Disegno superiore che darebbe direzione e senso alla storia; Montale non lo assume.'],['Verità negativa','Conoscenza che delimita il falso senza offrire una formula totale positiva.']],
      map:"maps/03-visione.svg", mapAlt:"Disarmonia e limite generano l'attesa del varco; la storia senza provvidenza e la società di massa conducono a una verità negativa e a una responsabilità individuale.",
      quiz:[
        {q:"Che cosa indica il «male di vivere» nella lezione?",o:["Una patologia privata del poeta","La disarmonia fra domanda di senso e opacità del reale","Un rifiuto totale della natura ligure"],a:1,e:"La formula riguarda insieme esistenza e conoscenza, non una diagnosi personale.",r:{c:"Disarmonia",x:"Il male nasce dallo scarto fra il bisogno di ordine e una realtà resistente.",ex:"Gli impedimenti materiali fanno sperimentare l'ostacolo prima di spiegarlo.",anchor:"v-disarmonia",retry:"Il male di vivere è soltanto tristezza personale?"}},
        {q:"Perché il muro ha una struttura doppia?",o:["Chiude la coscienza ma rende pensabile un oltre","È insieme naturale e artificiale","Appartiene a due raccolte con lo stesso significato"],a:0,e:"Il limite produce prigionia e, proprio per questo, attesa di superamento.",r:{c:"Limite e oltre",x:"Senza l'idea di un oltre, il muro sarebbe solo un oggetto neutro.",ex:"La coscienza avverte la chiusura perché immagina una possibilità diversa.",anchor:"v-limite",retry:"Il limite elimina l'idea di un oltre?"}},
        {q:"Che cos'è il varco?",o:["Una dottrina religiosa definita","Una certezza politica futura","Un'apertura contingente, fragile e non ripetibile a comando"],a:2,e:"Il varco è possibilità, non possesso stabile di una verità.",r:{c:"Apertura contingente",x:"L'evento può apparire, mancare o richiudersi.",ex:"Un dettaglio sensoriale può promettere una rivelazione senza garantirla.",anchor:"v-varco",retry:"Il varco è una soluzione permanente?"}},
        {q:"Quale conseguenza etica deriva da una storia senza provvidenza?",o:["L'azione individuale diventa inutile","La coscienza deve scegliere senza garanzia dell'esito","Ogni ideologia diventa vera"],a:1,e:"L'assenza di garanzie aumenta, non cancella, la responsabilità.",r:{c:"Storia e responsabilità",x:"Montale rifiuta l'idea che il futuro giustifichi automaticamente il presente.",ex:"Una traccia fragile può avere valore senza promettere vittoria.",anchor:"v-storia",retry:"L'assenza di provvidenza elimina la responsabilità?"}},
        {q:"A che cosa serve l'ironia nell'ultimo Montale?",o:["A mantenere distanza critica dal rumore e dal conformismo","A rendere tutte le poesie comiche","A recuperare la voce del poeta-vate"],a:0,e:"L'ironia impedisce al linguaggio pubblico di occupare completamente la coscienza.",r:{c:"Ironia critica",x:"Il poeta lavora dentro la società di massa senza identificarsi con le sue formule.",ex:"Il tono diaristico può smontare il prestigio dei discorsi assoluti.",anchor:"v-massa",retry:"L'ironia ricostruisce un'autorità solenne?"}}
      ]
    },
    {
      id:"poetica", number:"04", title:"La poetica", subtitle:"Dire attraverso le cose, conservare la forma, sottrarre l'enfasi", question:"Come deve scrivere il poeta per rappresentare una realtà disarmonica senza trasformarla in una teoria astratta?", bridge:"La poetica degli oggetti mette alla prova la tradizione in raccolte che cambiano forma insieme al secolo.",
      lesson:[
        {id:"p-negativo",title:"Una poetica della conoscenza negativa",paragraphs:[
          "Montale non assegna alla poesia il compito di proclamare una verità positiva. Il poeta non possiede la parola capace di definire con esattezza l'identità umana o di risolvere il disordine storico. Può però esercitare una conoscenza negativa: riconoscere le formule false, opporsi alla retorica, indicare ciò che non coincide con la coscienza. Questa modestia non è debolezza. È una disciplina che impedisce al linguaggio di diventare ideologia.",
          "Ne deriva una voce spesso colloquiale, trattenuta o aspra. La poesia non rinuncia alla precisione; rinuncia alla pretesa che precisione significhi totalità. Persino quando il testo assume un tono alto, conserva un elemento che resiste alla chiusura: un oggetto incongruo, un salto temporale, un riferimento taciuto. Il lettore non deve soltanto ricevere un messaggio, ma ricostruire una relazione tra tracce."
        ]},
        {id:"p-oggetti",title:"Oggetti e correlativo: una distinzione necessaria",paragraphs:[
          "La cosiddetta poetica degli oggetti è il mezzo principale di questa conoscenza. Un oggetto concreto concentra una condizione emotiva o conoscitiva senza che il poeta debba nominarla direttamente. Per spiegare il procedimento si usa spesso la formula di T. S. Eliot, «correlativo oggettivo»: una situazione o catena di elementi sensibili capace di evocare un'emozione. L'Università di Bologna ricorda però che Montale dichiarò di essere giunto autonomamente a una soluzione analoga.",
          "Non ogni oggetto montaliano funziona allo stesso modo. Negli Ossi il paesaggio può diventare emblema esistenziale; nelle Occasioni l'evento originario è spesso omesso e restano gli oggetti che ne assorbono la tensione; nella Bufera il dettaglio privato incontra la storia; nell'ultimo Montale alcuni simboli vengono svuotati o ironicamente riutilizzati. Chiamare tutto «correlativo oggettivo» rischia di appiattire questa evoluzione. È più esatto osservare, testo per testo, quale relazione l'oggetto costruisce."
        ]},
        {id:"p-occasione",title:"L'occasione taciuta e il lettore attivo",paragraphs:[
          "Nelle Occasioni Montale mira a un assorbimento delle intenzioni nei risultati oggettivi. L'episodio biografico che ha originato il testo non viene raccontato per intero. Il lettore incontra resti, dettagli, nomi, spostamenti e presenze che non possiedono una didascalia completa. L'oscurità non nasce necessariamente dal desiderio di creare un codice elitario: deriva dalla scelta di non spiegare ciò che il testo deve far percepire.",
          "Questo procedimento cambia il patto di lettura. Non basta cercare la parafrasi lineare; occorre seguire ricorrenze, opposizioni, suoni e oggetti. La conoscenza biografica può aiutare, ma non sostituisce l'analisi. Se il lettore riduce ogni segno al fatto reale, elimina la trasformazione poetica; se ignora completamente l'occasione, perde la pressione concreta da cui la forma nasce. La lettura corretta tiene insieme documento e autonomia del testo."
        ]},
        {id:"p-lingua",title:"Plurilinguismo e attrito dei registri",paragraphs:[
          "La lingua montaliana combina termini comuni, letterari, tecnici, regionali e talvolta volutamente sgradevoli. Questo plurilinguismo non è esibizione di ricchezza lessicale. Riproduce una realtà non unificata e impedisce che il tono lirico diventi una superficie armoniosa. Una parola rara accanto a un oggetto umile, un tecnicismo dentro una frase alta, una cadenza parlata dentro una forma tradizionale: ogni accostamento rende percepibile la discontinuità del mondo.",
          "Anche il rapporto con la metrica è più complesso della formula «verso libero». Montale utilizza endecasillabi, rime, strutture strofiche e memorie della tradizione, ma le altera con enjambement, lunghezze variabili, consonanze aspre e sintassi spezzata. La forma conserva una resistenza razionale mentre viene attraversata dall'instabilità. In questo senso la sua poesia è moderna proprio perché non scambia l'innovazione con l'assenza di regole."
        ]},
        {id:"p-evoluzione",title:"Dall'altezza alla prosa che si nega",paragraphs:[
          "Le prime tre grandi raccolte mostrano continuità e innalzamento. Ossi di seppia costruisce una dizione scabra e paesaggistica; Le occasioni concentra e oscura, con una maggiore densità formale; La bufera e altro amplia i registri e fa entrare la violenza storica. Dopo il silenzio, Satura inaugura una svolta: il testo tende alla prosa, al diario, alla conversazione e alla satira, ma continua a organizzare ritmo, tagli e ritorni.",
          "Definire questa fase «abbassamento» è corretto solo se non implica perdita di controllo. La prosa viene imitata e insieme rifiutata: il testo sembra parlare come il quotidiano, ma ne altera cadenze e logica. L'ultimo Montale mette in crisi anche il proprio sistema simbolico. L'autore non ripete all'infinito il muro, il mare o il varco; verifica che cosa ne resta dentro una società che consuma rapidamente ogni segno."
        ]},
        {id:"p-ponte",title:"Una tecnica che è anche etica",paragraphs:[
          "Oggetti, omissioni, registri plurali, forme tradizionali incrinate e ironia sono decisioni tecniche. In Montale diventano anche decisioni etiche perché regolano il grado di autorità della voce. Il poeta non nasconde la difficoltà del reale dietro una lingua facile, ma non autorizza neppure l'oscurità gratuita. Costruisce un testo esatto che obbliga a sostare, collegare e dubitare.",
          "Le opere sono il laboratorio in cui questa poetica cambia sotto pressione. Gli Ossi verificano il rapporto tra paesaggio e condizione; Le occasioni tra memoria e oggetto; La bufera tra privato e storia; Satura tra poesia e rumore della società di massa. La prossima sezione non offrirà un catalogo: seguirà queste prove come quattro stazioni della stessa ricerca."
        ]}
      ],
      summary:"La poetica montaliana nasce da una conoscenza negativa: la poesia non consegna formule totali, ma delimita il falso e resiste alla retorica. Gli oggetti concentrano emozioni e problemi senza spiegarli in astratto; il «correlativo oggettivo» è una categoria utile, purché non appiattisca fasi diverse. Nelle Occasioni l'episodio biografico viene spesso assorbito nel risultato poetico, rendendo il lettore parte attiva. Il plurilinguismo accosta registri alti, comuni e tecnici per rappresentare una realtà discontinua. Anche la metrica conserva forme tradizionali sottoponendole ad attrito. Da Ossi a Bufera cresce densità e pressione storica; con Satura la poesia tende alla prosa e all'ironia senza perdere controllo. La tecnica è dunque anche etica: limita l'autorità della voce e obbliga a una lettura responsabile.",
      essentials:["Spiegare la conoscenza negativa come disciplina della parola.","Definire il correlativo oggettivo senza applicarlo meccanicamente a ogni oggetto.","Spiegare l'assorbimento dell'occasione biografica nel testo.","Collegare plurilinguismo e discontinuità del reale.","Mostrare la persistenza trasformata di metrica e tradizione.","Ricostruire il passaggio dalla densità delle prime raccolte alla prosa ironica di Satura."],
      glossary:[['Correlativo oggettivo','Insieme sensibile capace di evocare un’emozione senza nominarla direttamente.'],['Occasione taciuta','Evento originario non raccontato integralmente, assorbito negli oggetti del testo.'],['Plurilinguismo','Combinazione controllata di registri e lessici differenti.'],['Enjambement','Prosecuzione sintattica oltre il confine del verso, che crea tensione ritmica.'],['Conoscenza negativa','Sapere che riconosce limiti e falsità senza costruire una formula totale.'],['Prosastico','Andamento vicino al discorso comune, ma ancora organizzato poeticamente.']],
      map:"maps/04-poetica.svg", mapAlt:"La conoscenza negativa richiede oggetti, occasione taciuta, plurilinguismo e metrica trasformata; questi procedimenti evolvono fino alla prosa ironica di Satura.",
      quiz:[
        {q:"Che cos'è la conoscenza negativa in Montale?",o:["La capacità di delimitare il falso senza offrire una formula totale","Il rifiuto di conoscere qualunque cosa","Una dottrina scientifica pessimistica"],a:0,e:"La negazione è un esercizio critico, non la cancellazione di ogni sapere.",r:{c:"Conoscere per limite",x:"La poesia può dire con rigore che cosa non accetta.",ex:"Rifiutare una formula assoluta preserva la complessità del reale.",anchor:"p-negativo",retry:"La conoscenza negativa equivale a non sapere nulla?"}},
        {q:"Perché non conviene chiamare ogni oggetto «correlativo oggettivo»?",o:["Perché Montale non usa mai oggetti concreti","Perché la funzione degli oggetti cambia nelle diverse raccolte","Perché la formula appartiene alla pittura"],a:1,e:"La categoria è utile, ma deve rispettare l'evoluzione del sistema poetico.",r:{c:"Funzioni dell'oggetto",x:"Emblema, resto dell'occasione, nodo storico e riuso ironico non coincidono.",ex:"Un oggetto negli Ossi non opera necessariamente come in Satura.",anchor:"p-oggetti",retry:"Gli oggetti hanno sempre la stessa funzione?"}},
        {q:"Che cosa accade all'occasione biografica nelle Occasioni?",o:["È narrata in modo completo e cronologico","È eliminata senza lasciare tracce","È assorbita negli elementi oggettivi del testo"],a:2,e:"Il lettore incontra risultati e tracce, non una spiegazione autobiografica completa.",r:{c:"Assorbimento dell'occasione",x:"L'origine privata resta una pressione, ma non una didascalia.",ex:"Dettagli e presenze devono essere collegati dal lettore.",anchor:"p-occasione",retry:"Il testo offre sempre il racconto completo dell'evento?"}},
        {q:"Qual è la funzione del plurilinguismo?",o:["Esibire soltanto la cultura del poeta","Rendere l'eterogeneità e l'attrito della realtà moderna","Sostituire ogni forma metrica"],a:1,e:"La commistione dei registri è un modo di pensare il mondo, non semplice ornamento.",r:{c:"Registri in attrito",x:"Lessico alto e materiale comune convivono senza fondersi in armonia.",ex:"Un tecnicismo può interrompere una cadenza tradizionalmente lirica.",anchor:"p-lingua",retry:"Il plurilinguismo serve solo a mostrare erudizione?"}},
        {q:"Come va interpretato lo stile prosastico di Satura?",o:["Come perdita completa di tecnica","Come ritorno al poeta-vate","Come imitazione del discorso comune sottoposta a controllo ritmico e ironico"],a:2,e:"La poesia tende alla prosa e insieme la rifiuta.",r:{c:"Prosa controllata",x:"Il tono quotidiano è una nuova strategia, non abbandono della forma.",ex:"Tagli, cadenze e ritorni trasformano il parlato apparente.",anchor:"p-evoluzione",retry:"Satura coincide con prosa non organizzata?"}}
      ]
    },
    {
      id:"opere", number:"05", title:"Le opere decisive", subtitle:"Quattro prove della stessa ricerca, non quattro Montale separati", question:"Dove la poetica diventa forma e conflitto, e come cambia quando cambia la storia?", bridge:"Dalle quattro raccolte resta una traiettoria: fedeltà alla coscienza, mutazione delle forme, nessuna consolazione prefabbricata.",
      lesson:[
        {id:"o-ossi",title:"Ossi di seppia: il paesaggio come problema",paragraphs:[
          "Pubblicati da Piero Gobetti nel 1925 e ampliati nel 1928, gli Ossi di seppia sono il laboratorio del primo Montale. Il titolo mette al centro un residuo marino: materia impoverita, levigata, espulsa sulla terra. Il paesaggio ligure non offre un idillio. Calore, pietra, vegetazione e mare costruiscono un campo di forze fra aridità e apertura. L'io non contempla dall'alto; procede lungo sentieri, urta contro limiti, ascolta segnali.",
          "Tre testi permettono di seguire il progetto senza riprodurli integralmente. «I limoni» contrappone piante comuni ai nomi prestigiosi della lirica e attende un errore della natura capace di aprire il senso. «Non chiederci la parola» nega la definizione positiva dell'uomo e riduce la certezza a una presa di distanza. «Spesso il male di vivere ho incontrato» traduce la condizione in una breve serie di immagini materiali. L'unità della raccolta non è una dottrina pessimistica, ma l'esperimento ripetuto di una conoscenza attraverso le cose."
        ]},
        {id:"o-occasioni",title:"Le occasioni: memoria, assenza, densità",paragraphs:[
          "Nel 1939 Le occasioni presentano una lingua più concentrata e un sistema di riferimenti privati spesso taciuti. Il titolo non promette episodi raccontati: indica momenti in cui la realtà si carica di una possibilità e subito rischia di perderla. Oggetti, luoghi, viaggi e figure femminili trattengono l'energia di eventi che il lettore non vede per intero. La memoria non ricostruisce stabilmente il passato; conserva frammenti e distanze.",
          "Clizia occupa progressivamente una posizione centrale. Non è un personaggio narrativo con biografia lineare, ma una presenza che unisce desiderio, assenza e difesa di valori culturali minacciati. La difficoltà della raccolta nasce dall'ellissi e dalla precisione, non da un generico gusto dell'oscuro. Ogni dettaglio è carico perché una parte dell'occasione è stata sottratta. Il lettore deve ricostruire l'arco senza pretendere di colmare ogni vuoto."
        ]},
        {id:"o-bufera",title:"La bufera e altro: la storia attraversa il privato",paragraphs:[
          "La raccolta del 1956 riunisce testi nati durante e dopo la Seconda guerra mondiale. La bufera indica la catastrofe storica ma non resta un simbolo esterno: investe relazioni, corpi, memoria e linguaggio. In «La primavera hitleriana» la visita di Hitler a Firenze viene filtrata attraverso un'atmosfera festiva deformata e sinistra. Il testo non offre un resoconto; rende percepibile la contaminazione del quotidiano da parte della barbarie.",
          "Nelle sezioni finali la fiducia in una funzione salvifica di Clizia si modifica e si complica. «Piccolo testamento» consegna non un credo totale, ma una traccia individuale da difendere contro schieramenti opposti. «Il sogno del prigioniero» porta al limite la condizione di chi vive dentro apparati che vogliono trasformare la coscienza. La poesia civile montaliana non adotta una lingua oratoria: mostra come la storia si depositi negli oggetti e nelle scelte minute."
        ]},
        {id:"o-satura",title:"Satura e Xenia: il controcanto del quotidiano",paragraphs:[
          "Dopo anni di silenzio poetico, Satura esce nel 1971 e modifica il patto con il lettore. Il titolo suggerisce insieme mescolanza, varietà e satira. Il linguaggio si avvicina al discorso giornalistico e domestico, i componimenti assumono forma diaristica, l'io commenta il presente con ironia. La società dei consumi, i media e le mode culturali non vengono affrontati con un nuovo manifesto, ma esposti attraverso paradossi e abbassamenti.",
          "Il nucleo degli Xenia, dedicato a Mosca, impedisce di leggere la svolta soltanto come satira. «Ho sceso, dandoti il braccio, almeno un milione di scale» costruisce il lutto attraverso un gesto ordinario e rovescia l'idea di chi guidasse chi. La relazione coniugale diventa conoscenza: la vista imperfetta di Mosca coglieva forse meglio l'inganno delle apparenze. L'affetto non risolve il male di vivere, ma offre una misura concreta con cui attraversarlo."
        ]},
        {id:"o-dopo",title:"Diari, Quaderno e Opera in versi",paragraphs:[
          "Diario del '71 e del '72, Quaderno di quattro anni e Altri versi proseguono la forma discontinua dell'ultimo Montale. Il rischio è giudicarli semplicemente come ripetizione o declino. Gli studi dell'Università di Milano mostrano invece come paesaggi, oggetti e memorie delle prime raccolte vengano ricombinati, talvolta svuotati, talvolta riaccesi. Il poeta costruisce un rovescio della propria opera e mette alla prova i simboli che la critica aveva ormai reso riconoscibili.",
          "L'Opera in versi, curata filologicamente da Rosanna Bettarini e Gianfranco Contini, rende visibile un progetto unitario ma non lineare. Le raccolte dialogano a distanza, ritornano su immagini e ne cambiano il valore. Questo invita a leggere Montale non come autore di una sola formula — il male di vivere — bensì come poeta che controlla per oltre mezzo secolo l'efficacia dei propri strumenti."
        ]},
        {id:"o-ponte",title:"Che cosa resta dopo le opere",paragraphs:[
          "Le quattro stazioni non sono compartimenti. Gli Ossi stabiliscono il rapporto tra limite e possibile apertura; Le occasioni concentrano l'esperienza in oggetti e assenze; La bufera fa collidere il sistema privato con la storia; Satura osserva che anche i simboli possono essere consumati dalla comunicazione di massa. La continuità sta nella sorveglianza della coscienza; la differenza nelle forme necessarie a esercitarla.",
          "Dopo le opere resta dunque un metodo: non accettare il linguaggio che pretende di coincidere con la realtà, ma neppure fuggire dal concreto. Guardare gli oggetti, verificarne le relazioni, modificare la propria forma quando essa rischia di diventare formula. La conclusione dovrà valutare questa eredità e chiedere se una poesia priva di messaggi assoluti possa ancora trasformare il modo in cui pensiamo."
        ]}
      ],
      summary:"Ossi di seppia trasforma il paesaggio ligure in un laboratorio di conoscenza: limite e apertura vengono sperimentati attraverso oggetti. Le occasioni aumenta densità ed ellissi; memoria, assenza e Clizia concentrano eventi non narrati per intero. La bufera e altro fa entrare la catastrofe storica nella sfera privata senza adottare una retorica oratoria; l'eredità morale resta fragile ma non irrilevante. Satura cambia registro: prosa, diario, satira e linguaggio quotidiano rispondono alla società di massa. Gli Xenia uniscono questa svolta a un lutto concreto, nel quale Mosca offre una misura terrestre. Le raccolte successive ricombinano e talvolta svuotano i vecchi simboli. La continuità dell'opera non è una formula tematica: è la vigilanza con cui Montale verifica e trasforma i propri strumenti.",
      essentials:["Spiegare il titolo e il progetto conoscitivo di Ossi di seppia.","Collegare ellissi, memoria e densità nelle Occasioni.","Mostrare come La bufera unisca storia e privato senza oratoria.","Spiegare la svolta prosastica e satirica di Satura.","Distinguere la funzione affettiva e conoscitiva degli Xenia.","Leggere l'opera come continuità trasformativa, non come ripetizione del male di vivere."],
      glossary:[['Ossi di seppia','Prima raccolta: il residuo marino diventa immagine di impoverimento e resistenza.'],['Ellissi','Omissione di passaggi che il lettore deve ricostruire.'],['Bufera','Immagine della catastrofe storica che investe anche la vita privata.'],['Xenia','Ciclo in memoria di Mosca, poi incluso in Satura.'],['Satura','Raccolta di mescolanza e satira che inaugura il secondo tempo poetico.'],['Opera in versi','Edizione critica che rende leggibile il dialogo fra tutte le raccolte.']],
      map:"maps/05-opere.svg", mapAlt:"Ossi costruisce limite e varco; Occasioni concentra memoria e assenza; Bufera intreccia storia e privato; Satura risponde con ironia e quotidiano; insieme formano una continuità trasformativa.",
      quiz:[
        {q:"Qual è la funzione del paesaggio negli Ossi di seppia?",o:["Decorare una biografia ligure","Costruire un laboratorio di conoscenza attraverso limite e apertura","Celebrare l'armonia fra io e natura"],a:1,e:"La materia ligure organizza l'esperienza conoscitiva, non un idillio.",r:{c:"Il laboratorio degli Ossi",x:"Pietra, mare, calore e residui sono forze che fanno pensare.",ex:"L'osso di seppia unisce svuotamento e resistenza materiale.",anchor:"o-ossi",retry:"Il paesaggio degli Ossi è idillico?"}},
        {q:"Da che cosa deriva soprattutto la difficoltà delle Occasioni?",o:["Dall'uso esclusivo di parole inventate","Dall'assenza completa di oggetti","Dall'ellissi dell'occasione e dalla densità dei dettagli rimasti"],a:2,e:"Il testo sottrae l'episodio ma conserva tracce ad alta intensità.",r:{c:"Ellissi e densità",x:"Una parte del contesto viene taciuta e gli oggetti ne assorbono il peso.",ex:"Il lettore ricostruisce relazioni senza colmare ogni vuoto.",anchor:"o-occasioni",retry:"Le Occasioni raccontano sempre l'episodio completo?"}},
        {q:"Come entra la storia nella Bufera?",o:["Come pressione che attraversa oggetti, relazioni e coscienza","Come cronaca neutra degli eventi","Come prova sicura del progresso"],a:0,e:"La storia non è sfondo né lezione oratoria: contamina l'esperienza privata.",r:{c:"Storia incarnata",x:"La catastrofe viene resa percepibile dentro scene e scelte.",ex:"Una festa cittadina può assumere un'atmosfera sinistra.",anchor:"o-bufera",retry:"La Bufera è un resoconto storico lineare?"}},
        {q:"Perché gli Xenia non sono soltanto testi privati?",o:["Perché celebrano un evento politico","Perché il gesto quotidiano diventa una forma di conoscenza delle apparenze","Perché eliminano ogni riferimento a Mosca"],a:1,e:"La memoria coniugale produce una diversa intelligenza del mondo.",r:{c:"Lutto e conoscenza",x:"Il quotidiano non è chiuso nel privato: misura la capacità di orientarsi.",ex:"Chi vede meno può riconoscere meglio l'inganno delle apparenze.",anchor:"o-satura",retry:"Negli Xenia l'affetto ha anche valore conoscitivo?"}},
        {q:"Che cosa unifica le raccolte?",o:["La ripetizione invariata degli stessi simboli","Un'unica forma metrica","La vigilanza della coscienza e la trasformazione continua degli strumenti"],a:2,e:"La continuità è un metodo, non immobilità tematica o stilistica.",r:{c:"Continuità trasformativa",x:"Montale verifica i propri simboli e cambia registro quando rischiano di diventare formule.",ex:"Satura riusa e smonta il sistema precedente.",anchor:"o-ponte",retry:"Continuità significa ripetizione identica?"}}
      ]
    },
    {
      id:"conclusione", number:"06", title:"Conclusione", subtitle:"L'onestà dell'incompleto e l'eredità di una voce senza pulpito", question:"Che cosa resta vivo della traiettoria di Montale, e perché la sua negazione non coincide con la resa?", bridge:"Dal mondo ricevuto alle opere: la poesia non chiude il senso, ma rende più esigente il nostro rapporto con il vero.",
      lesson:[
        {id:"c-traiettoria",title:"Ricomporre i sei movimenti",paragraphs:[
          "La traiettoria inizia da una contraddizione: Montale riceve forme letterarie capaci di grande precisione, ma vive in un tempo che ha perduto il centro. Le fratture storiche e private non generano automaticamente i versi; mettono però alla prova ogni promessa di continuità. Da qui emerge un'immagine disarmonica del mondo: nessun ordine garantito, ma differenze e aperture che la coscienza deve sorvegliare.",
          "La poetica risponde a questa visione evitando due estremi. Non scioglie la difficoltà in una spiegazione astratta e non si abbandona a un'oscurità gratuita. Oggetti, omissioni, metri trasformati, registri plurali e ironia permettono al testo di conservare il conflitto. Le opere verificano la soluzione in epoche diverse, fino a mettere in discussione gli stessi simboli che avevano reso riconoscibile Montale."
        ]},
        {id:"c-ermetismo",title:"Oltre l'etichetta di ermetico",paragraphs:[
          "Nei manuali Montale viene spesso accostato all'Ermetismo. L'etichetta può essere utile per collocarlo nel rinnovamento della lirica fra le due guerre, ma diventa falsa se lo identifica con una scuola compatta o con il culto della parola pura. Montale stesso respinge una programmatica ricerca dell'oscurità. La difficoltà dei suoi testi deriva piuttosto dall'ellissi, dalla complessità dei rapporti e dall'opacità del reale.",
          "Anche il confronto con Ungaretti chiarisce la differenza. Dove Ungaretti tende a isolare la parola e a investirla di valore rivelativo, Montale spesso affida la conoscenza a catene di oggetti e a una sintassi che conserva controllo razionale. Non si tratta di stabilire una gerarchia, ma di distinguere due risposte alla crisi moderna. Ridurle entrambe a «ermetismo» cancella proprio ciò che la storia letteraria dovrebbe rendere visibile."
        ]},
        {id:"c-nobel",title:"Il Nobel e la poesia senza illusioni",paragraphs:[
          "Nel 1975 il Premio Nobel riconosce una poesia capace di interpretare valori umani dentro una visione della vita priva di illusioni. Il punto è apparentemente paradossale: come può una voce negativa custodire valori? La risposta è nell'uso montaliano del limite. Rifiutare menzogne, conformismi e consolazioni può essere già una forma di fedeltà all'umano. La speranza non coincide con la previsione ottimistica di un esito; può consistere nell'impedire che la coscienza venga interamente occupata dal falso.",
          "Nella conferenza «È ancora possibile la poesia?» Montale osserva il destino dell'arte nella comunicazione di massa. Non propone di restaurare il prestigio del vate. Difende la poesia proprio come produzione non programmabile, lenta, marginale rispetto alla logica del consumo. La sua inutilità immediata può diventare una risorsa: una parola che non serve a vendere, mobilitare o semplificare mantiene aperto uno spazio di esperienza non interamente amministrato."
        ]},
        {id:"c-eredita",title:"Un'eredità formale e civile",paragraphs:[
          "L'eredità di Montale agisce sulla lingua poetica italiana: possibilità di unire tradizione e modernità, lessico alto e materiale, musica e attrito, autobiografia e oggettivazione. Ma l'influenza più profonda riguarda il comportamento della voce. Il poeta non deve parlare più forte del mondo; deve controllare quanto può legittimamente affermare. Questa responsabilità stilistica possiede una dimensione civile, perché ogni propaganda comincia quando le parole smettono di misurare la propria pretesa.",
          "Il Quirinale ha ricordato Montale come interprete del malessere tra le guerre, intellettuale antifascista, giornalista e senatore a vita. Non bisogna trasformare questo riconoscimento istituzionale in santificazione. La sua opera resta significativa perché conserva conflitti: solitudine e comunicazione, negazione e attesa, autonomia e storia. Un classico non è un autore privo di contraddizioni, ma un autore le cui contraddizioni continuano a produrre domande."
        ]},
        {id:"c-oggi",title:"Montale nel presente: contro la saturazione",paragraphs:[
          "La società contemporanea sembra lontana dal mondo degli Ossi, eppure intensifica il problema di Satura. Siamo immersi in messaggi che chiedono una reazione rapida, riducono l'incertezza a opinione e trasformano l'identità in una formula pubblicabile. Montale educa a un gesto controcorrente: sostare davanti all'oggetto, distinguere il segnale dal rumore, accettare che una risposta rigorosa possa essere incompleta.",
          "Questo non significa usare il poeta come profeta dei social network. Significa trasferire il suo metodo: diffidare di chi promette la parola che squadri ogni esperienza; osservare come i linguaggi costruiscono realtà; riconoscere il valore di una negazione motivata. Nella scuola, Montale non dovrebbe diventare il poeta depresso da memorizzare. Può diventare un laboratorio di cittadinanza linguistica: imparare che il modo in cui formuliamo un giudizio modifica anche la qualità della nostra libertà."
        ]},
        {id:"c-domanda",title:"La domanda che resta aperta",paragraphs:[
          "Alla fine, la poesia montaliana non offre un passaggio sicuro oltre il muro. Offre qualcosa di meno consolatorio e forse più utile: la capacità di riconoscere il muro, di non chiamarlo porta, di cercarne le incrinature senza inventarle. Il varco resta possibilità perché il poeta non lo trasforma in prodotto. La fedeltà alla realtà comprende anche l'attesa, l'errore e il fallimento.",
          "La domanda conclusiva è quindi realmente discutibile: una parola che rinuncia al messaggio assoluto è politicamente e umanamente più debole, oppure crea l'unico spazio nel quale il lettore può diventare responsabile? Montale non decide al nostro posto. Costruisce le condizioni perché la risposta non sia uno slogan. È questa, più del pessimismo, la sua eredità: l'onestà dell'incompleto come forma attiva di conoscenza."
        ]}
      ],
      summary:"La traiettoria di Montale unisce tradizione e crisi, fratture biografiche e storia, disarmonia del reale e ricerca di forme esatte. La sua difficoltà non coincide con un programma ermetico: nasce dall'ellissi e dall'opacità dei rapporti. Il Nobel del 1975 riconosce il valore umano di una poesia senza illusioni; la negazione può infatti difendere la coscienza dal falso. Nella società di massa la poesia conserva uno spazio non programmabile e non immediatamente utile. L'eredità di Montale è formale e civile: misurare l'autorità della voce, trasformare la tradizione, resistere alla propaganda e alla saturazione. Oggi il suo metodo invita a distinguere segnali e rumore e ad accettare risposte rigorose ma incomplete. Resta aperta una domanda: rinunciare al messaggio assoluto indebolisce la parola o rende finalmente responsabile il lettore?",
      essentials:["Ricomporre il nesso completo fra mondo precedente, fratture, visione, poetica e opere.","Spiegare perché l'etichetta di Ermetismo è utile ma insufficiente.","Interpretare il Nobel come riconoscimento di valori senza illusioni.","Collegare responsabilità stilistica e responsabilità civile.","Attualizzare il metodo montaliano senza trasformarlo in profezia.","Argomentare la domanda finale sul rapporto fra parola incompleta e lettore responsabile."],
      glossary:[['Ermetismo','Categoria storica utile ma insufficiente a spiegare la specificità montaliana.'],['Illusione','Certezza consolatoria non verificata; rifiutarla non significa rifiutare ogni valore.'],['Responsabilità stilistica','Controllo del grado di verità e autorità rivendicato dalla voce.'],['Saturazione','Eccesso di messaggi che rende difficile distinguere esperienza, informazione e rumore.'],['Classico','Autore le cui tensioni continuano a generare domande oltre il proprio tempo.'],['Incompleto','Conoscenza aperta e rigorosa che non si spaccia per totalità.']],
      map:"maps/06-conclusione.svg", mapAlt:"Tradizione e fratture conducono alla disarmonia; poetica e opere trasformano il limite in responsabilità della voce; l'eredità è l'onestà dell'incompleto e un lettore attivo.",
      quiz:[
        {q:"Perché l'etichetta di Ermetismo è insufficiente per Montale?",o:["Perché Montale scrive soltanto prose","Perché la sua difficoltà deriva da ellissi e opacità del reale, non da un programma unitario di parola pura","Perché appartiene al Futurismo"],a:1,e:"La categoria colloca storicamente, ma non spiega la specifica costruzione montaliana.",r:{c:"Oltre le etichette",x:"Montale non cerca l'oscurità come fine autonomo.",ex:"La parte taciuta dell'occasione rende denso il testo.",anchor:"c-ermetismo",retry:"Montale vuole essere oscuro per programma?"}},
        {q:"Come può una poesia senza illusioni custodire valori?",o:["Rifiutando menzogne e conformismi e proteggendo l'autonomia della coscienza","Promettendo sempre un esito felice","Sostituendo la politica con l'estetica"],a:0,e:"La fedeltà all'umano può consistere nel non falsificare la condizione umana.",r:{c:"Valori senza ottimismo",x:"Speranza e previsione positiva non coincidono.",ex:"Impedire al falso di occupare la coscienza è già un atto di valore.",anchor:"c-nobel",retry:"Rifiutare illusioni significa rifiutare ogni valore?"}},
        {q:"Qual è la dimensione civile della responsabilità stilistica?",o:["Usare soltanto parole semplici","Scrivere sempre di politica","Misurare l'autorità delle parole e resistere alle formule propagandistiche"],a:2,e:"Lo stile diventa civile quando controlla la propria pretesa di verità.",r:{c:"Voce e cittadinanza",x:"La propaganda inizia quando la parola non riconosce più limiti.",ex:"Una negazione motivata può essere più responsabile di una certezza falsa.",anchor:"c-eredita",retry:"La responsabilità stilistica riguarda solo l'eleganza?"}},
        {q:"Come va attualizzato Montale?",o:["Chiamandolo profeta di ogni tecnologia","Trasferendo il suo metodo di attenzione e verifica senza inventare previsioni","Riducendolo al tema della depressione"],a:1,e:"L'attualità sta nel metodo critico, non in una profezia anacronistica.",r:{c:"Metodo nel presente",x:"Il poeta insegna a distinguere segnale, formula e rumore.",ex:"Una risposta incompleta può essere più rigorosa di un'opinione immediata.",anchor:"c-oggi",retry:"Attualizzare significa attribuire profezie?"}},
        {q:"Qual è la domanda conclusiva del percorso?",o:["Se Montale sia più importante di Ungaretti","Se la Liguria sia il vero tema di tutte le raccolte","Se la rinuncia al messaggio assoluto indebolisca la parola o responsabilizzi il lettore"],a:2,e:"La domanda riapre l'intera traiettoria e non ammette una risposta puramente mnemonica.",r:{c:"Lettore responsabile",x:"Un testo non totalizzante trasferisce al lettore parte del lavoro conoscitivo.",ex:"Il varco non è consegnato come prodotto: deve restare possibilità discussa.",anchor:"c-domanda",retry:"Chi deve completare responsabilmente il senso?"}}
      ]
    }
  ]
};
