(() => {
  "use strict";
  const R = (concept, clarification, example, question, answer) => ({concept, clarification, example, question, answer});
  window.BUZZATI_SOURCES = [
    {
      kind:"Istituzionale · Dizionario biografico", short:"Treccani · DBI", title:"Marcello Carlino, “Buzzati Traverso, Dino”", url:"https://www.treccani.it/enciclopedia/dino-buzzati-traverso_%28Dizionario-Biografico%29/",
      note:"Voce del Dizionario Biografico degli Italiani: dati biografici, attività al Corriere, cronologia delle opere e una lettura critica netta, talvolta severa.",
      use:"Cronologia, formazione, giornalismo, guerra, opere. I giudizi di Carlino sono presentati come posizione critica, non come fatti indiscutibili.", sections:"1, 2, 4, 5"
    },
    {
      kind:"Università di Padova · Terza missione", short:"Il Bo Live · UniPD", title:"Il fantastico nel quotidiano e il mistero dell’esistenza", url:"https://ilbolive.unipd.it/it/news/cultura/dino-buzzati-fantastico-quotidiano-mistero",
      note:"Intervento con Alessandra Grandelis, studiosa del Dipartimento di Studi Linguistici e Letterari: tempo, attesa, quotidiano perturbato, cibernetica e intermedialità.",
      use:"Asse interpretativo tempo–attesa; definizione del fantastico; lettura del Grande ritratto e del Poema a fumetti.", sections:"3, 4, 5, 6"
    },
    {
      kind:"Università di Padova · Archivio tesi", short:"Sartor · UniPD", title:"Il fantastico nei primi romanzi di Dino Buzzati", url:"https://thesis.unipd.it/handle/20.500.12608/41953",
      note:"Tesi magistrale del Dipartimento di Studi Linguistici e Letterari dedicata alle tecniche del fantastico in Bàrnabo, Bosco Vecchio e Deserto dei Tartari.",
      use:"Problemi e categorie: perturbante, attesa, tempo, rapporto fra tradizione fantastica europea e primi romanzi.", sections:"1, 3, 4, 5"
    },
    {
      kind:"Università di Padova · Archivio tesi", short:"D’Angelo · UniPD", title:"Dino Buzzati scrittore-giornalista", url:"https://thesis.unipd.it/handle/20.500.12608/19253",
      note:"Studio magistrale sul rapporto fra pratica giornalistica e stile fantastico, con testo integrale ad accesso aperto.",
      use:"Nesso prudente fra cronaca, chiarezza linguistica, montaggio dell’attesa e credibilità dell’evento impossibile.", sections:"2, 4, 5"
    },
    {
      kind:"Università di Bologna · Rivista scientifica", short:"Griseldaonline · UniBO", title:"Elvira Ghirlanda, “Poema a fumetti. Un serissimo gioco”", url:"https://doi.org/10.6092/issn.1721-4777/9395",
      note:"Saggio peer-reviewed sull’intreccio fra mito, parola, immagine, cultura di massa e gioco nell’opera verbo-visiva del 1969.",
      use:"Poema a fumetti come esperimento intermediale e riscrittura moderna di Orfeo, non come curiosità marginale.", sections:"4, 5, 6"
    },
    {
      kind:"Università Ca’ Foscari · Ricerca", short:"Ca’ Foscari · Buzzati e la parola", title:"Intermedialità e stratificazione espressiva nei Miracoli di Val Morel", url:"https://iris.unive.it/retrieve/f34b2a6d-90bc-4e03-afe4-c361c8f83a8d/Baglioni%20%282022%29_Intermedialit%C3%A0%20e%20stratificazione%20espressiva%20nei%20Miracoli%20di%20Val%20Morel.pdf",
      note:"Contributo in volume scientifico del Centro Studi Buzzati sulle opere doppie e sul rapporto fra parola e immagine.",
      use:"Intermedialità, funzione narrativa dell’immagine, continuità fra scrittura, pittura e falso documento.", sections:"4, 5, 6"
    },
    {
      kind:"Università Ca’ Foscari · Ricerca", short:"Ca’ Foscari · Pop Art", title:"Buzzati, Venezia e la Pop Art", url:"https://apps.unive.it/server/eventi/80823/Buzzati%2C%20Venezia%20Pop%20Art%20catalogo.pdf",
      note:"Catalogo universitario sulla svolta figurativa degli anni Sessanta e sulla fusione di pittura, pubblicità e fumetto.",
      use:"Contesto artistico e mediale dell’ultimo Buzzati; passaggio dalla sola pagina alla narrazione per immagini.", sections:"1, 4, 5"
    },
    {
      id:"poetica", title:"La poetica", short:"Cronaca dell’impossibile", subtitle:"Come scrivere quella realtà",
      question:"Come si racconta l’impossibile senza separarlo dalla vita quotidiana?",
      lesson:`
        <p class="eyebrow">Tesi</p><p>La poetica di Buzzati nasce da un paradosso: per far sentire il mistero non serve una lingua misteriosa. Serve una superficie chiara, controllata, quasi giornalistica, sulla quale l’anomalia compaia senza essere annunciata da fanfare. Il lettore entra in un mondo stabile; poi una piccola deviazione cambia retroattivamente tutto. Precisione, suspense, allegoria, ritmo e intreccio tra parola e immagine sono gli strumenti di questa “cronaca dell’impossibile”.</p>
        <h2 id="m4-tono">Il tono che non si scompone</h2><p>Buzzati evita in genere di segnalare l’evento fantastico con un improvviso cambio di registro. Il narratore continua a descrivere orari, stanze, gesti e procedure. Proprio questa continuità produce credibilità. Se la voce apparisse subito visionaria, il lettore collocherebbe l’anomalia in un mondo separato; la normalità del tono, invece, suggerisce che potrebbe accadere qui.</p><p>Il giornalismo conta in questa tecnica. Il dettaglio concreto stabilisce un patto: qualcuno sembra riferire fatti osservati. La frase è di norma leggibile, l’intreccio riconoscibile, il lessico non ostenta difficoltà. Ma sarebbe sbagliato confondere accessibilità e ingenuità. La semplicità è costruita. Determina quando il lettore sa qualcosa, quanto vede, quali informazioni gli vengono negate e con quale velocità cresce l’allarme.</p>
        <h2 id="m4-suspense">La suspense come forma del tempo</h2><p>La suspense non è soltanto un trucco per trattenere il pubblico. In Buzzati traduce formalmente l’attesa. Ripetizioni, segnali minimi, ritardi e false conferme fanno vivere al lettore la stessa struttura dei personaggi. In Qualcosa era successo, la velocità del treno impedisce di verificare: frammenti osservati fuori dal finestrino si accumulano, mentre la destinazione resta ignota. Nel Deserto, i cicli della vita militare rallentano l’evento e accelerano gli anni.</p><p>Questo doppio movimento è essenziale. Il racconto può essere rapido, ma il suo oggetto è una vita sprecata nella lentezza; oppure può dilatare pochi minuti fino a farli diventare decisivi. Il tempo narrativo non copia il tempo dell’orologio: lo monta. Buzzati usa il ritmo per trasformare una domanda filosofica in esperienza del lettore.</p>
        <h2 id="m4-allegoria">Allegoria, simbolo, fantastico</h2><p>Molte storie si prestano a una lettura allegorica: la fortezza come vita rinviata, i sette piani come discesa verso la morte, il Colombre come destino frainteso. Ma l’allegoria non deve diventare una chiave che chiude il testo. Se ogni elemento equivalesse a un solo concetto, il racconto perderebbe la sua inquietudine. Il Colombre è la paura, ma anche il dono mancato, la vocazione fuggita e l’errore ereditato. La forza del simbolo sta nella pluralità controllata.</p><p>Qui la critica non è unanime. La voce Treccani di Carlino insiste talvolta su un allegorismo troppo esplicito e su una poetica orientata alla commozione; altri studi valorizzano l’instabilità del fantastico e la capacità di contaminare linguaggi. La PWA non risolve la disputa per decreto: riconosce che Buzzati può essere insieme narrativamente efficace e incline alla semplificazione morale. Leggerlo bene significa valutare, opera per opera, quando l’emblema apre e quando chiude.</p>
        <h2 id="m4-oggetti">Oggetti, luoghi e personaggi-emblema</h2><p>Buzzati preferisce spesso pochi elementi fortemente visivi: una porta, una fortezza, una scala, un animale, una macchina. L’oggetto permette di rendere percepibile un processo invisibile. Non spiega il tempo: mostra un corridoio percorso nella direzione sbagliata. Non definisce l’angoscia: fa udire un rumore che si avvicina. Questa qualità visiva prepara il lavoro pittorico e fumettistico.</p><p>I personaggi possono risultare meno analitici di quelli del grande romanzo psicologico. Talvolta sono figure sottoposte a una prova più che individualità irripetibili. È un limite possibile, ma anche una scelta funzionale: la storia mira a far riconoscere al lettore un meccanismo umano generale. Drogo resta concreto, eppure la sua attesa oltrepassa la biografia personale.</p>
        <h2 id="m4-immagine">Raccontare con parole e immagini</h2><p>Nella maturità la poetica rende esplicito ciò che era già visivo. La famosa invasione degli orsi in Sicilia, Poema a fumetti e I miracoli di Val Morel coordinano testo e figura. Gli studi di Bologna e Ca’ Foscari mostrano che l’immagine non illustra soltanto una storia già completa: ne determina ritmo, ironia, montaggio e statuto. Nel Poema, il mito di Orfeo incontra fumetto, canzone, fotografia, pubblicità e cultura pop. Nei Miracoli, dipinti e brevi testi simulano un archivio devozionale mai esistito.</p><p>Questa tendenza impedisce di fissare Buzzati nell’etichetta dello scrittore tradizionale. La lingua resta accessibile, ma il supporto cambia; il racconto attraversa media diversi. L’antico mito non viene conservato sotto vetro: entra nella Milano contemporanea e nel consumo delle immagini.</p>
        <h2 id="m4-commozione">Commuovere senza spiegare tutto</h2><p>Buzzati vuole coinvolgere il lettore. La commozione non è per lui un effetto sospetto da evitare, ma un criterio di efficacia. Ciò espone al sentimentalismo; tuttavia consente anche di restituire peso a esperienze astratte. Il tempo diventa pietà per una vita, la paura diventa occasione perduta, la morte diventa prova di dignità. La domanda critica non è se il testo commuova, ma se l’emozione nasca dalla forma o venga imposta da una morale già pronta.</p><div class="interpretation"><strong>Criterio di lettura.</strong> Non basta etichettare un testo come “fantastico”. Occorre osservare il dispositivo: quale normalità viene costruita, dove appare la deviazione, come cambia il ritmo, quale scelta compie il personaggio e che cosa resta inspiegato.</div><div class="bridge"><strong>Ponte.</strong> La poetica acquista senso soltanto quando diventa forma. Le opere decisive mostreranno usi diversi dello stesso dispositivo: romanzo dell’attesa, racconto breve, fantascienza e narrazione verbo-visiva.</div>`,
      summary:`<p>La poetica di Buzzati può essere definita “cronaca dell’impossibile”: un evento anomalo entra in una lingua chiara e in ambienti concreti senza che il narratore cambi tono. La precisione giornalistica rende credibile il fantastico. La suspense non serve solo a intrattenere, ma fa vivere al lettore la struttura dell’attesa attraverso ripetizioni, ritardi e segnali. Allegorie e simboli rendono visibili processi astratti, ma non dovrebbero essere ridotti a equivalenze univoche. La critica discute proprio questo punto: alcuni giudizi sottolineano moralismo e semplificazione, altri l’instabilità e l’invenzione mediale. Oggetti e luoghi funzionano come macchine narrative. Nella maturità il rapporto fra parola e immagine diventa centrale: fumetto, pittura e falso documento determinano il racconto. La commozione è un obiettivo consapevole; va valutata distinguendo l’emozione prodotta dalla forma dalla morale imposta al lettore.</p>`,
      essentials:["Definire la cronaca dell’impossibile come continuità di tono fra normale e anomalo.","Spiegare il legame fra giornalismo e credibilità narrativa.","Analizzare la suspense come esperienza formale dell’attesa.","Distinguere simbolo plurale e allegoria ridotta a equivalenza.","Valutare il ruolo di oggetti e spazi nella resa dell’invisibile.","Spiegare perché parola e immagine formano un unico dispositivo narrativo.","Riconoscere la commozione come scelta poetica e come possibile rischio."],
      glossary:[{term:"Suspense",definition:"Organizzazione dell’informazione che produce attesa e tensione nel lettore."},{term:"Tempo narrativo",definition:"Durata e ritmo costruiti dal racconto, diversi dal semplice tempo cronologico."},{term:"Simbolo",definition:"Elemento concreto che concentra significati molteplici senza esaurirli."},{term:"Montaggio",definition:"Disposizione di scene, dettagli o immagini per creare ritmo e relazioni."},{term:"Registro",definition:"Livello e tono linguistico scelto in rapporto alla situazione comunicativa."},{term:"Graphic novel",definition:"Narrazione estesa in cui sequenza visiva e parola costruiscono insieme il senso."}],
      map:{src:"./maps/04-poetica.svg",alt:"Mappa: la cronaca dell’impossibile nasce da lingua chiara e dettaglio concreto; suspense e montaggio producono attesa, simboli rendono visibile il mistero e parola e immagine confluiscono nel racconto.",caption:"Gli strumenti della poetica: non oscurare la lingua, ma incrinare il mondo che essa descrive."},
      quiz:[
        {q:"Perché il narratore mantiene un tono normale davanti all’impossibile?",options:["Per rendere l’anomalia credibile nel nostro mondo","Per eliminare ogni tensione","Per imitare un trattato scientifico completo"],answer:0,explanation:"La continuità del registro impedisce di relegare subito il fantastico in un altrove separato.",recovery:R("Continuità di tono","Il mondo viene stabilizzato dalla voce prima di essere incrinato dall’evento.","La goccia impossibile è descritta come un rumore concreto e osservabile.","Che effetto ha il tono sobrio?","Fa sembrare l’anomalia vicina e possibile.")},
        {q:"Quale funzione profonda ha la suspense?",options:["Sostituire tutti i temi con l’azione","Far vivere al lettore la forma dell’attesa","Nascondere che il testo non ha una struttura"],answer:1,explanation:"Ritardo e informazione parziale trasformano il tema del tempo in esperienza di lettura.",recovery:R("Suspense e attesa","Il lettore non riceve soltanto un’idea: subisce il rinvio dell’informazione.","Dal treno si vedono frammenti della catastrofe senza poterli verificare.","Che cosa sperimenta il lettore?","Incertezza, ritardo e pressione del tempo.")},
        {q:"Quando l’allegoria rischia di indebolire il racconto?",options:["Quando conserva più significati","Quando ogni elemento viene ridotto a una sola equivalenza","Quando usa un oggetto concreto"],answer:1,explanation:"Una chiave univoca chiude l’inquietudine e trasforma la storia in dimostrazione.",recovery:R("Pluralità simbolica","Il simbolo resta produttivo se non è esaurito da una traduzione unica.","Il Colombre non è solo paura: è anche dono, destino e vocazione.","Una buona lettura esaurisce il simbolo?","No: ne ordina i significati senza cancellarne l’eccedenza.")},
        {q:"Che ruolo ha l’immagine nelle opere mature?",options:["Decora un testo già autosufficiente","Sostituisce sempre ogni parola","Partecipa a ritmo, montaggio e significato"],answer:2,explanation:"Negli esperimenti verbo-visivi l’immagine è una componente strutturale del racconto.",recovery:R("Immagine narrativa","La sequenza visiva decide che cosa vedere, in quale ordine e con quale durata.","Nel Poema le tavole costruiscono una metrica visiva.","Che cosa cambia se tolgo le immagini?","Perdo una parte della struttura, non soltanto un ornamento.")},
        {q:"Qual è il criterio proposto per valutare la commozione?",options:["Rifiutarla sempre come sentimentalismo","Accettarla sempre come prova di grandezza","Chiedere se nasce dalla forma o da una morale imposta"],answer:2,explanation:"L’emozione è legittima, ma deve essere prodotta dalla costruzione dell’esperienza.",recovery:R("Emozione e forma","Commuovere non è di per sé un pregio o un difetto; conta come il testo ottiene l’effetto.","La pietà per Drogo nasce dal tempo narrato e dalla scelta finale.","Quale domanda critica va posta?","Se l’emozione è costruita o prescritta.")}
      ]
    },
    {
      id:"opere", title:"Le opere decisive", short:"Quattro laboratori del mistero", subtitle:"Dove la poetica diventa forma",
      question:"In quali opere l’attesa, il fantastico e l’immagine diventano veri conflitti narrativi?",
      lesson:`
        <p class="eyebrow">Tesi</p><p>Un catalogo completo nasconderebbe la traiettoria. Conviene scegliere quattro laboratori: <em>Il deserto dei Tartari</em>, i racconti confluiti in <em>Sessanta racconti</em> e nel <em>Colombre</em>, <em>Il grande ritratto</em> e <em>Poema a fumetti</em>. Insieme mostrano che Buzzati non ripete semplicemente la stessa favola: sposta il problema del limite fra romanzo, forma breve, tecnologia e narrazione visiva.</p>
        <h2 id="m5-deserto">Il deserto dei Tartari: l’occasione che trattiene</h2><p>Pubblicato nel 1940, il romanzo segue il tenente Giovanni Drogo, assegnato alla Fortezza Bastiani davanti a un deserto da cui potrebbero arrivare i Tartari. All’inizio vuole andarsene; poi resta, attratto dalla possibilità di partecipare a un grande evento. La fortezza trasforma il futuro in dipendenza. Ogni indizio promette finalmente il senso, ogni delusione rende più difficile abbandonare gli anni già investiti.</p><p>La costruzione elimina coordinate storiche troppo precise e ripete gesti e situazioni. La fortezza è concreta, ma funziona come macchina del tempo. Quando l’occasione sembra arrivare, Drogo è malato e viene allontanato. La prova decisiva avviene altrove: affrontare la morte senza pubblico. Il finale non risarcisce la vita perduta; le restituisce però un ultimo spazio di scelta. Qui la commozione nasce dalla sproporzione fra attesa grandiosa e scena solitaria.</p>
        <h2 id="m5-racconti">I racconti: esperimenti a pressione</h2><p>La forma breve è forse il laboratorio più congeniale a Buzzati. In poche pagine una regola normale viene modificata e condotta alle conseguenze estreme. <em>Sette piani</em> trasforma la classificazione medica in una discesa amministrata: Giuseppe Corte entra quasi sano e viene progressivamente spostato verso il piano dei casi gravi. Ogni trasferimento ha una motivazione ragionevole; il risultato complessivo è assurdo. La burocrazia non appare caotica, ma troppo coerente.</p><p>In <em>Qualcosa era successo</em>, i passeggeri vedono dal treno una popolazione in fuga. Non conoscono la causa e non fermano la corsa. Velocità, frammenti e reticenza costruiscono un’apocalisse senza nome. Nel <em>Colombre</em>, Stefano Roi evita per tutta la vita la creatura che crede destinata a ucciderlo; scopre infine che portava una perla capace di offrire fortuna. La favola non invita ingenuamente ad affrontare ogni pericolo: mostra il costo di una vita organizzata attorno a un’interpretazione mai verificata.</p><p><em>Sessanta racconti</em> vince lo Strega nel 1958 e conferma la centralità della forma breve. I racconti attraversano industria, scienza, città, malattia, paura collettiva e animali fantastici. La varietà impedisce di ridurre Buzzati alla sola attesa militare.</p>
        <h2 id="m5-ritratto">Il grande ritratto: desiderio, macchina, persona</h2><p>Nel 1960 Buzzati pubblica un romanzo che interroga cibernetica e intelligenza artificiale prima che questi temi entrino nell’immaginario quotidiano. Una gigantesca macchina sembra ospitare la personalità di Laura, donna morta e desiderata dal suo creatore. La tecnologia non è presentata soltanto come minaccia esterna. Diventa il luogo in cui l’uomo proietta lutto, possesso e bisogno di cancellare la morte.</p><p>Il romanzo pone domande ancora vive: una mente ricostruita da tracce è la stessa persona? Il desiderio di conservare qualcuno rispetta la sua alterità o la trasforma in oggetto? L’Università di Padova sottolinea l’attualità di questa intuizione. Non occorre dichiarare Buzzati profeta dell’IA: la forza consiste nell’aver individuato il nucleo umano che accompagna la tecnica, cioè la speranza di riscattare solitudine e mortalità.</p>
        <h2 id="m5-poema">Poema a fumetti: Orfeo nella città delle immagini</h2><p>Nel 1969 <em>Poema a fumetti</em> riscrive il mito di Orfeo ed Euridice in una Milano contemporanea. Orfi, cantante, attraversa una porta verso l’aldilà per ritrovare Eura. Il mito classico incontra rock, erotismo, pubblicità, fumetto e pittura. Secondo il saggio di Elvira Ghirlanda, il “serissimo gioco” consiste nell’affidare a un medium considerato minore una domanda teorica sulla forza del mito nella società contemporanea.</p><p>La sequenza delle tavole produce un ritmo che non coincide né con il romanzo illustrato né con il fumetto d’avventura convenzionale. Il lettore deve leggere immagini, parole, citazioni e variazioni. L’aldilà assume forme urbane e domestiche: lo straordinario si colloca ancora una volta dietro una porta della normalità. Orfi non annulla la morte; porta con sé una traccia, insufficiente ma reale. Il racconto verbo-visivo non risolve la perdita: le dà una forma condivisibile.</p>
        <h2 id="m5-costellazione">Una costellazione, non quattro eccezioni</h2><p>Le quattro aree comunicano. La fortezza, il piano d’ospedale, la macchina e la porta sono dispositivi di confine. Ognuno promette accesso a un senso: gloria, diagnosi, sopravvivenza, ritorno dell’amata. Ognuno mostra anche il limite della promessa. Cambiano il genere e il medium, resta la domanda: quanto della vita consegniamo a una costruzione che dovrebbe salvarci dal tempo?</p><div class="interpretation"><strong>Scelta critica.</strong> <em>Un amore</em>, la narrativa per ragazzi, il teatro e <em>I miracoli di Val Morel</em> restano importanti. Qui non sono ignorati, ma esclusi dal primo piano per evitare un inventario e rendere leggibile la traiettoria.</div><div class="bridge"><strong>Ponte.</strong> Dopo le opere non resta una morale unica. Resta un’eredità: riconoscere i segnali senza diventarne prigionieri e usare il racconto per sottrarre il quotidiano all’automatismo.</div>`,
      summary:`<p>Quattro laboratori rendono visibile la traiettoria di Buzzati. <em>Il deserto dei Tartari</em> trasforma la fortezza in una macchina dell’attesa: Drogo affida il presente all’occasione futura e conquista solo alla fine uno spazio di scelta. I racconti comprimono un dispositivo fino alle conseguenze estreme: in <em>Sette piani</em> la procedura diventa destino, in <em>Qualcosa era successo</em> velocità e conformismo impediscono di capire, nel <em>Colombre</em> una lettura mai verificata consuma la vita. <em>Il grande ritratto</em> interroga tecnologia, lutto e identità senza essere ridotto a profezia dell’IA. <em>Poema a fumetti</em> riscrive Orfeo mediante parola, pittura, pubblicità e cultura pop. Fortezza, ospedale, macchina e porta sono dispositivi di confine: promettono un senso e ne mostrano il limite. La selezione rinuncia volutamente al catalogo completo. Il confronto evita una lettura monotematica dell’autore.</p>`,
      essentials:["Ricostruire il meccanismo dell’attesa nel Deserto dei Tartari.","Spiegare come la forma breve trasformi una regola normale in assurdo coerente.","Confrontare Sette piani, Qualcosa era successo e Il Colombre.","Formulare le domande su identità e tecnica poste dal Grande ritratto.","Descrivere Poema a fumetti come riscrittura intermediale di Orfeo.","Collegare fortezza, ospedale, macchina e porta come dispositivi di confine."],
      glossary:[{term:"Dispositivo",definition:"Insieme di spazio, regole e gesti che produce un comportamento narrativo."},{term:"Forma breve",definition:"Racconto concentrato che isola un meccanismo e ne accelera gli effetti."},{term:"Cibernetica",definition:"Studio dei sistemi di controllo e comunicazione in organismi e macchine."},{term:"Identità personale",definition:"Continuità per cui riconosciamo qualcuno come la stessa persona nel tempo."},{term:"Riscrittura",definition:"Trasformazione di un testo o mito precedente in un nuovo contesto e linguaggio."},{term:"Costellazione",definition:"Insieme di opere collegate da relazioni, senza ridurle a una serie lineare."}],
      map:{src:"./maps/05-opere.svg",alt:"Mappa: Il deserto dei Tartari usa la fortezza per l’attesa; i racconti usano dispositivi brevi; Il grande ritratto collega macchina e identità; Poema a fumetti unisce mito e immagini; tutti mettono alla prova le promesse contro il tempo.",caption:"Quattro laboratori, un problema comune: le costruzioni con cui cerchiamo di salvarci dal tempo."},
      quiz:[
        {q:"Che cosa trattiene Drogo alla Fortezza Bastiani?",options:["La certezza di una promozione immediata","La promessa di un evento capace di dare senso alla vita","Il divieto assoluto di presentare dimissioni"],answer:1,explanation:"L’attesa diventa dipendenza perché promette di riscattare il tempo investito.",recovery:R("Promessa dell’evento","Drogo resta soprattutto perché il futuro sembra poter giustificare ogni sacrificio.","Ogni indizio dei Tartari rinnova la speranza e rende più costoso partire.","Che cosa dovrebbe fare l’evento?","Riscattare gli anni trascorsi in attesa.")},
        {q:"Quale meccanismo domina Sette piani?",options:["Una procedura ragionevole in ogni passaggio produce un esito assurdo","Un medico commette un unico errore evidente","Il protagonista sceglie liberamente di aggravarsi"],answer:0,explanation:"La razionalità locale delle decisioni costruisce la discesa complessiva.",recovery:R("Assurdo amministrato","Ogni atto è giustificato, ma la sequenza sottrae al paziente controllo e identità.","Un trasferimento temporaneo ne prepara un altro finché la classificazione coincide col destino.","Dove sta l’assurdo?","Nel risultato della somma di procedure apparentemente sensate.")},
        {q:"Quale errore organizza la vita di Stefano Roi?",options:["Confondere il mare con la città","Non imparare a navigare","Accettare senza verifica che il Colombre sia una minaccia"],answer:2,explanation:"La paura ereditata diventa una lettura totale della realtà e impedisce l’incontro col dono.",recovery:R("Interpretazione non verificata","Una credenza può diventare destino se ogni scelta viene adattata ad essa.","Roi fugge per anni dalla creatura senza interrogarne davvero la funzione.","Che cosa manca alla sua lettura?","La verifica del significato attribuito al Colombre.")},
        {q:"Quale domanda centrale pone Il grande ritratto?",options:["Se una macchina possa sostituire il giornale","Se una mente ricostruita coincida con la persona perduta","Se le Dolomiti possano essere automatizzate"],answer:1,explanation:"Tecnica, lutto e desiderio convergono nel problema dell’identità personale.",recovery:R("Copia e persona","Riprodurre tracce, voce o comportamento non risolve automaticamente la continuità dell’identità.","La macchina-Laura porta il desiderio del creatore, ma resta aperta la domanda su chi essa sia.","Somiglianza equivale a identità?","No: è proprio il problema interrogato dal romanzo.")},
        {q:"Perché Poema a fumetti è più di un romanzo illustrato?",options:["Perché elimina del tutto la narrazione","Perché le immagini sono state aggiunte dopo","Perché parola e sequenza visiva costruiscono insieme ritmo e senso"],answer:2,explanation:"Il medium verbo-visivo è parte del progetto e della riscrittura del mito.",recovery:R("Opera verbo-visiva","Testo e immagini non sono separabili senza cambiare l’opera.","Il passaggio fra tavole dà durata e forma al viaggio di Orfi.","Che cosa produce la sequenza?","Un montaggio e una metrica visiva propri.")}
      ]
    },
    {
      id:"conclusione", title:"Conclusione", short:"Vivere prima del segnale", subtitle:"La traiettoria e l’eredità",
      question:"Che cosa resta di Buzzati quando smettiamo di chiamarlo soltanto “autore fantastico”?",
      lesson:`
        <p class="eyebrow">Tesi</p><p>Di Buzzati resta una domanda scomoda: quanta vita affidiamo all’evento che dovrebbe finalmente autorizzarci a vivere? Il suo fantastico non fornisce una fuga, ma rompe l’anestesia dell’abitudine. Una creatura, un rumore, una porta o un nemico lontano rendono percepibile ciò che era già in corso. La sua eredità non è una morale contro ogni attesa; è un esercizio di vigilanza sul rapporto fra desiderio, tempo e scelta.</p>
        <h2 id="m6-catena">Ricostruire i sei movimenti</h2><p>Il mondo precedente prometteva ordine: la borghesia delle professioni, la città moderna, il giornale e le istituzioni sembravano capaci di misurare la realtà. Le fratture hanno mostrato il limite della promessa. La perdita, la ripetizione del lavoro, la guerra e il crollo dei miti hanno trasformato l’ordine in domanda. Da qui emerge un’immagine del mondo instabile: la normalità contiene segnali, il tempo agisce senza rumore, gli spazi orientano le scelte e l’uomo interpreta attraverso paure e desideri.</p><p>Per dire questa realtà Buzzati costruisce una poetica della chiarezza inquieta. Il tono cronachistico non elimina il mistero: gli dà credibilità. La suspense fa vivere l’attesa; oggetti e luoghi rendono visibili processi astratti; allegoria e simbolo collegano vicenda individuale e condizione umana. Nella maturità parola e immagine confluiscono in forme intermediali. Le opere mettono alla prova il dispositivo: la fortezza trattiene, l’ospedale classifica, la macchina promette di vincere la morte, la porta conduce a un aldilà che non restituisce ciò che abbiamo perduto.</p>
        <h2 id="m6-nonmorale">Non una morale contro l’attesa</h2><p>Sarebbe troppo semplice concludere: “bisogna vivere il presente”. Una certa attesa è necessaria. Studiare, curare, educare e progettare significano investire tempo in ciò che non esiste ancora. Il problema nasce quando il futuro non orienta il presente ma lo svuota; quando l’occasione immaginata diventa l’unico criterio di valore; quando il costo già sostenuto ci impedisce di cambiare strada.</p><p>Buzzati mostra inoltre che anche la fuga dalla paura può diventare una forma di obbedienza. Stefano Roi crede di evitare il destino, ma organizza l’intera esistenza intorno al Colombre. Drogo crede di prepararsi all’azione, ma l’attesa gli impedisce di scegliere. I passeggeri credono di mantenere il contegno, ma il rispetto umano li trascina verso l’ignoto. La libertà non coincide automaticamente con partire o restare; comincia quando riconosciamo il meccanismo che sta decidendo al nostro posto.</p>
        <h2 id="m6-attualita">Perché ci riguarda ancora</h2><p>Le forme contemporanee dell’attesa non hanno bisogno di fortezze. Possono essere notifiche, graduatorie, metriche, procedure, promozioni, approvazioni o l’idea che la vita autentica inizierà dopo il prossimo risultato. Anche la tecnologia promette di ridurre l’incertezza e conservare ciò che perdiamo. <em>Il grande ritratto</em> parla al presente perché chiede se una simulazione capace di rispondere ai nostri desideri rappresenti davvero l’altro o soltanto il nostro bisogno di non perderlo.</p><p>L’attualità non va confusa con la profezia. Buzzati non “prevede” le nostre piattaforme o l’intelligenza artificiale odierna. Individua strutture umane durevoli: delegare il senso a un sistema, scambiare la ripetizione per sicurezza, desiderare che un dispositivo neutralizzi la morte. Sono strutture che ogni epoca riempie con tecnologie diverse.</p>
        <h2 id="m6-limiti">Anche i limiti fanno parte dell’eredità</h2><p>Un autore vivo non deve essere trasformato in monumento senza crepe. Alcuni personaggi appaiono schematici; alcune allegorie possono risultare troppo guidate; la ricerca della commozione può sfiorare il sentimentalismo; la rappresentazione del femminile e del desiderio in opere come <em>Un amore</em> richiede uno sguardo critico. Anche la posizione storica e politica di Buzzati non va resa più eroica di quanto documentino le fonti.</p><p>Questi limiti non cancellano l’opera. Impediscono piuttosto la devozione scolastica e obbligano a leggere. La limpidezza di Buzzati può produrre profondità oppure semplificazione; il compito del lettore è distinguere. La critica stessa diverge, e tale divergenza è una risorsa didattica: mostra che interpretare non significa ripetere un’etichetta.</p>
        <h2 id="m6-eredita">Il racconto come allarme</h2><p>L’eredità più forte è una funzione del racconto: interrompere l’automatismo. Nella vita ordinaria non percepiamo ogni giorno il passaggio del tempo, il peso delle procedure o il modo in cui una paura dirige le scelte. La narrazione concentra il processo in un’immagine. Dopo aver visto il sole scomparire dietro la finestra di <em>Sette piani</em>, una classificazione non è più soltanto neutra. Dopo Drogo, ogni promessa di “grande occasione” porta con sé il sospetto del rinvio.</p><p>La letteratura non salva automaticamente la vita. Può però rendere visibile il meccanismo un istante prima che diventi destino. Questo istante è lo spazio della scelta. Il segnale buzzatiano non ci dice che cosa fare; ci costringe ad accorgerci che stiamo già facendo qualcosa, anche quando crediamo soltanto di aspettare.</p><div class="interpretation"><strong>Domanda conclusiva.</strong> Una società può progettare il futuro senza trasformare il presente in una sala d’attesa? La risposta non è contenuta in una favola pronta: deve essere discussa, individualmente e politicamente.</div><div class="bridge"><strong>Catena finale.</strong> Ordine ricevuto → fratture → realtà sotto allarme → cronaca dell’impossibile → opere-dispositivo → vigilanza sul tempo. Questa è la traiettoria proposta, aperta al confronto.</div>`,
      summary:`<p>L’eredità di Buzzati non si riduce all’etichetta del fantastico. Il percorso parte dalla promessa moderna di ordine, attraversa perdita, giornalismo, guerra e crisi dei miti, e giunge a una realtà quotidiana attraversata da tempo e mistero. La poetica risponde con una lingua chiara, suspense, oggetti simbolici e intreccio fra parola e immagine. Le opere mostrano dispositivi che promettono senso e insieme trattengono. La conclusione non è una morale generica sul “vivere il presente”: progettare richiede attesa, ma il futuro diventa pericoloso quando svuota l’oggi o decide al nostro posto. Buzzati resta attuale non perché abbia previsto le tecnologie odierne, ma perché riconosce strutture durevoli del desiderio e della delega. Anche limiti, semplificazioni e ambiguità politiche vanno discussi. Il racconto funziona infine come allarme: rende visibile un meccanismo prima che diventi destino e apre uno spazio di scelta.</p>`,
      essentials:["Ricostruire la catena completa dei sei movimenti.","Distinguere attesa progettuale e rinvio che svuota il presente.","Spiegare perché la libertà richiede il riconoscimento dei meccanismi.","Argomentare l’attualità del Grande ritratto senza chiamarlo profezia.","Valutare anche limiti stilistici, ideologici e rappresentativi dell’autore.","Definire il racconto come interruzione dell’automatismo.","Discutere la domanda politica sulla società-sala d’attesa."],
      glossary:[{term:"Automatismo",definition:"Azione ripetuta senza più percepirne ragioni, costi e alternative."},{term:"Delega",definition:"Trasferimento a un’istituzione o dispositivo della responsabilità di attribuire senso."},{term:"Costo sommerso",definition:"Tendenza a continuare perché abbiamo già investito molto, anche quando cambiare sarebbe ragionevole."},{term:"Attualizzazione",definition:"Lettura che collega un’opera al presente senza fingere che lo avesse previsto."},{term:"Vigilanza",definition:"Attenzione critica ai processi che orientano le scelte prima che diventino irreversibili."},{term:"Eredità",definition:"Insieme di domande, forme e problemi che un’opera consegna ai lettori successivi."}],
      map:{src:"./maps/06-conclusione.svg",alt:"Mappa finale: l’ordine ricevuto viene incrinato dalle fratture, produce una realtà sotto allarme, richiede la cronaca dell’impossibile, si realizza nelle opere-dispositivo e lascia una vigilanza sul tempo e sulla scelta.",caption:"La catena interpretativa completa: dal mondo ricevuto allo spazio della scelta."},
      quiz:[
        {q:"Quale conclusione evita la PWA?",options:["L’attesa può diventare rinvio","Bisogna sempre e soltanto vivere il presente","Il racconto interrompe l’automatismo"],answer:1,explanation:"Una morale assoluta cancellerebbe il valore progettuale di molte attese necessarie.",recovery:R("Attesa e progetto","Non ogni orientamento al futuro svuota il presente; conta il rapporto che costruisce.","Studiare prepara il futuro ma può dare senso anche al lavoro di oggi.","Quale attesa è problematica?","Quella che rende l’oggi privo di valore e impedisce di scegliere.")},
        {q:"Perché Buzzati è ancora attuale secondo il percorso?",options:["Perché individua strutture umane che nuove tecnologie riattivano","Perché descrive esattamente i social network","Perché ogni sua opinione politica è valida oggi"],answer:0,explanation:"L’attualità riguarda delega, ripetizione, perdita e desiderio, non la previsione letterale del presente.",recovery:R("Attualità senza profezia","Un’opera può parlare al presente perché formula un problema durevole.","Il Grande ritratto interroga copia e persona, non anticipa tecnicamente i modelli odierni.","Che cosa resta stabile?","Il bisogno umano di vincere perdita e solitudine tramite un dispositivo.")},
        {q:"Come vanno trattati i limiti di Buzzati?",options:["Nascosti per proteggere il canone","Usati per annullare ogni valore","Inclusi nella valutazione critica dell’opera"],answer:2,explanation:"Leggere criticamente significa tenere insieme forza, limiti e divergenze interpretative.",recovery:R("Critica non devozionale","Un classico non ha bisogno di essere reso perfetto; ha bisogno di lettori precisi.","Allegoria efficace e rischio di moralismo possono coesistere.","Riconoscere un limite cancella l’opera?","No: rende il giudizio più responsabile.")},
        {q:"In che senso il racconto funziona come allarme?",options:["Predice con certezza gli eventi futuri","Rende visibile un processo prima che diventi destino","Impedisce materialmente ogni errore"],answer:1,explanation:"La letteratura apre consapevolezza e quindi possibilità di scelta, non offre garanzie.",recovery:R("Allarme narrativo","Un’immagine concentra ciò che la ripetizione quotidiana rende invisibile.","La discesa di Sette piani fa percepire il potere di una classificazione.","Che cosa apre la visibilità?","Uno spazio di giudizio e possibile scelta.")},
        {q:"Qual è la catena finale corretta?",options:["Opere → ordine → sonno → biografia","Ordine → fratture → realtà sotto allarme → poetica → opere → vigilanza","Fantastico → evasione → morale → oblio"],answer:1,explanation:"La catena ricompone i sei movimenti senza ridurli a un elenco.",recovery:R("Traiettoria","Ogni passaggio risponde al limite del precedente e prepara il successivo.","Le fratture rendono insufficiente l’ordine; la poetica risponde alla nuova immagine del mondo.","Che cosa collega le sezioni?","Un nesso causale prudente e interpretativo, non una semplice cronologia.")}
      ]
    }
  ];

  window.BUZZATI_FINAL_QUIZ = [
    {q:"Quale limite interno contiene il mondo ordinato ricevuto da Buzzati?",options:["La promessa del futuro può svuotare il presente","La montagna impedisce ogni racconto","La chiarezza elimina il mistero"],answer:0,explanation:"L’ordine prepara la frattura quando trasforma la vita in attesa dell’occasione.",recovery:R("Mondo precedente","La razionalità organizza, ma non garantisce senso né dominio sul tempo.","Una fortezza efficiente può consumare una vita.","Che cosa sfugge all’ordine?","Il senso del tempo vissuto.")},
    {q:"Quale formula rispetta il rapporto fra biografia e opera?",options:["Ogni perdita produce direttamente un libro","La biografia è sempre inutile","Le esperienze offrono contesti che la forma trasforma"],answer:2,explanation:"Il percorso evita sia il determinismo sia la separazione totale.",recovery:R("Fratture","Il nesso va documentato e formulato con prudenza.","La redazione rende intelligibile l’attesa istituzionale, ma non coincide con la fortezza.","Quale verbo è più corretto?","Offre un contesto, non causa automaticamente.")},
    {q:"Quale immagine del mondo emerge?",options:["Due realtà completamente separate","Una normalità attraversata da segnali e forze invisibili","Un universo sempre spiegabile senza residui"],answer:1,explanation:"Il fantastico rivela la profondità inquieta del quotidiano.",recovery:R("Realtà sotto allarme","L’anomalia non crea un altro universo: incrina quello riconoscibile.","La catastrofe appare dai finestrini di un normale treno.","Dove si apre il mistero?","Dentro gli spazi e i gesti quotidiani.")},
    {q:"Qual è il centro della poetica?",options:["Una lingua oscura per eventi oscuri","L’assenza di intreccio","Una cronaca chiara che rende credibile l’impossibile"],answer:2,explanation:"Precisione, suspense e continuità di tono costruiscono il dispositivo.",recovery:R("Cronaca dell’impossibile","La chiarezza è la condizione dell’inquietudine, non il suo contrario.","Il narratore descrive procedure normali mentre l’esito diventa assurdo.","Perché la lingua resta piana?","Per collocare l’anomalia nel nostro stesso mondo.")},
    {q:"Che cosa unisce le opere selezionate?",options:["L’identico genere letterario","Dispositivi che promettono senso e mostrano il proprio limite","La stessa ambientazione dolomitica"],answer:1,explanation:"Fortezza, ospedale, macchina e porta organizzano promesse contro il tempo.",recovery:R("Opere-dispositivo","Generi diversi possono condividere una struttura problematica.","La macchina promette sopravvivenza, la porta il ritorno dell’amata.","Che cosa fallisce?","La promessa di eliminare completamente perdita e limite.")},
    {q:"Quale eredità conclusiva propone la PWA?",options:["Rifiutare ogni progetto futuro","Vigilare sui meccanismi che decidono mentre crediamo di aspettare","Accettare ogni segnale come destino"],answer:1,explanation:"Il racconto apre consapevolezza e scelta senza consegnare una morale automatica.",recovery:R("Vigilanza","Accorgersi del meccanismo non garantisce la scelta giusta, ma la rende possibile.","Dopo Drogo possiamo interrogare le nostre grandi occasioni rinviate.","Che cosa precede la scelta?","Riconoscere ciò che orienta già il comportamento.")}
  ];

  window.BUZZATI_SECTIONS = [
    {
      id:"mondo-precedente", title:"Il mondo precedente", short:"Ordine moderno e crisi del reale", subtitle:"La realtà ricevuta",
      question:"Quale mondo riceve Buzzati, e quale sua promessa comincia a incrinarsi?",
      lesson:`
        <p class="eyebrow">Tesi</p><p>Buzzati nasce nel 1906 e diventa scrittore dentro un mondo che si vuole moderno, ordinato e leggibile. La scuola, la legge, il giornale, l’esercito e la città industriale sembrano capaci di classificare i fatti e governare il tempo. Ma il Novecento rende quella promessa sempre meno credibile. La sua narrativa nasce precisamente sulla soglia fra la superficie ordinata e ciò che essa non riesce a contenere. La frattura non distrugge l’ordine in un colpo solo: lo lascia funzionare mentre ne rivela lentamente l’insufficienza.</p>
        <h2 id="m1-borghesia">Una formazione borghese fra Milano e Belluno</h2><p>La famiglia appartiene all’alta borghesia colta. Il padre, Giulio Cesare, insegna diritto internazionale; la villa di San Pellegrino di Belluno possiede una vasta biblioteca. Durante l’anno la vita è milanese, regolata dallo studio e dalle professioni; nelle estati bellunesi si apre invece il paesaggio delle Dolomiti, con boschi, crode, silenzi e leggende. Non conviene trasformare meccanicamente questa duplicità in una formula biografica, ma essa offre un contesto utile: città e montagna diventano due modi di percepire il reale. La città è l’organizzazione moderna, la montagna è il luogo in cui l’ordine umano incontra qualcosa di più vasto e indecifrabile.</p><p>Il giovane Buzzati riceve anche una tradizione narrativa anteriore alle avanguardie. Ama la solidità del racconto, l’avventura, la fiaba, Poe, i grandi narratori ottocenteschi e il piacere di tenere il lettore dentro una storia. Questo dato lo separa da una parte della letteratura novecentesca, che mette in crisi il romanzo dall’interno, frantuma la voce narrante o rende opaca la lingua. Buzzati non rinuncia alla chiarezza. La sua innovazione consisterà piuttosto nel far passare l’inquietudine attraverso una forma leggibile.</p>
        <h2 id="m1-modernita">La modernità che misura tutto</h2><p>Fra le due guerre il mondo urbano accelera. Ferrovie, telefoni, giornali, burocrazie, ospedali, eserciti e grandi aziende coordinano persone e informazioni. Il quotidiano promette una conoscenza quasi immediata dei fatti. Anche il giornale, dove Buzzati entra nel 1928, vive di questa promessa: verificare, ordinare, titolare, raccontare con precisione. Eppure proprio gli apparati razionali generano nuovi labirinti. Un corridoio d’ospedale può diventare una macchina che sposta il malato verso il basso; una fortezza perfettamente regolata può consumare un’intera vita; un treno efficiente può correre senza permettere ai passeggeri di capire la catastrofe osservata dai finestrini.</p><p>Il mondo precedente non è dunque una semplice epoca storica. È un’idea di realtà: se ogni cosa ha un nome, un ufficio e una procedura, allora tutto dovrebbe risultare controllabile. Buzzati mette alla prova questa sicurezza. Nei suoi testi, il meccanismo continua spesso a funzionare proprio mentre il senso sfugge. L’orologio segna l’ora, il reparto compila la cartella, la sentinella obbedisce; ma nessuno sa davvero che cosa stia accadendo alla vita.</p>
        <h2 id="m1-letteratura">Fra avanguardie, realismo e fantastico</h2><p>Il primo Novecento italiano conosce futurismo, frammentismo, prosa d’arte e poi, nel dopoguerra, neorealismo. Buzzati non coincide pienamente con nessuna di queste direzioni. Il fantastico italiano possiede precedenti, ma non una tradizione compatta come in altri paesi europei. L’Università di Padova sottolinea il ruolo di Buzzati nell’aver dato al fantastico una forma personale e novecentesca: non castelli remoti e spettri convenzionali, bensì l’irruzione di un’anomalia in luoghi riconoscibili.</p><p>È decisivo distinguere fantastico da evasione. L’elemento impossibile non cancella i problemi del presente: li rende visibili spostandoli. Il mostro, il segnale, la malattia o il nemico atteso condensano paure che la normalità non sa nominare. Per questo il lettore accetta l’impossibile: tutto il resto assomiglia troppo al suo mondo.</p>
        <h2 id="m1-problema">La crepa dentro la promessa</h2><p>La civiltà moderna promette che il futuro ripagherà il presente: studio, carriera, disciplina e attesa dovrebbero condurre all’occasione decisiva. Ma se l’occasione non arriva? Se il futuro diventa un alibi che divora il presente? Qui si prepara il nucleo buzzatiano. La vita rischia di essere amministrata invece che vissuta. Il nemico più temibile non viene dall’esterno: è la seduzione del rinvio, la fiducia che il tempo importante debba ancora cominciare.</p><div class="interpretation"><strong>Interpretazione didattica.</strong> La catena proposta dalla PWA è questa: ordine moderno → fiducia nelle istituzioni → esperienza dell’attesa → scoperta che il tempo non obbedisce. È una lettura fondata sui testi e sulla critica, non una dichiarazione esplicita dell’autore.</div>
        <div class="bridge"><strong>Ponte.</strong> Per capire come questa tensione diventi scrittura, occorre osservare le esperienze che incrinano il mondo ricevuto: il giornale, la guerra, la crisi delle certezze e il confronto personale con il tempo.</div>`,
      summary:`<p>Buzzati riceve un mondo borghese e moderno che crede nell’ordine della legge, del giornale, dell’esercito e delle istituzioni. La sua formazione si svolge fra Milano, città della professione e dell’organizzazione, e le Dolomiti, spazio naturale che eccede le misure umane. Letterariamente preferisce il racconto solido, la fiaba e l’avventura alla dissoluzione sperimentale della forma. Tuttavia non resta estraneo alla crisi novecentesca: la introduce dentro una lingua chiara. Nei suoi testi, gli apparati continuano a funzionare mentre il senso sfugge. Il fantastico non rappresenta una fuga, ma un dispositivo che rende percepibili paura, tempo e desiderio nascosti nella normalità. La tensione fondamentale è fra la promessa moderna di un futuro controllabile e il sospetto che l’attesa dell’occasione decisiva consumi il presente. Da questa crepa nasceranno le fratture biografiche e storiche del percorso successivo.</p>`,
      essentials:["Spiegare perché Milano e Dolomiti sono due coordinate culturali, non due semplici scenari.","Descrivere la promessa di controllo propria delle istituzioni moderne.","Distinguere chiarezza narrativa e semplicità di pensiero.","Spiegare perché il fantastico buzzatiano non equivale a evasione.","Collegare organizzazione del tempo e rischio del rinvio.","Collocare Buzzati senza identificarlo rigidamente con avanguardie o neorealismo."],
      glossary:[{term:"Fantastico",definition:"Modo narrativo in cui un’anomalia incrina un mondo inizialmente riconoscibile."},{term:"Perturbante",definition:"Sensazione prodotta quando ciò che è familiare diventa improvvisamente estraneo o minaccioso."},{term:"Modernità",definition:"Sistema di vita fondato su città, istituzioni, tecnica, velocità e organizzazione razionale."},{term:"Borghesia",definition:"Classe sociale e orizzonte culturale di professioni, disciplina, proprietà e rispettabilità."},{term:"Koinè giornalistica",definition:"Lingua media, chiara e condivisa che mira alla comunicazione immediata."},{term:"Rinvio",definition:"Spostamento del valore della vita dal presente a un futuro atteso come decisivo."}],
      map:{src:"./maps/01-mondo.svg",alt:"Mappa: il mondo moderno ricevuto da Buzzati unisce borghesia, Milano, Dolomiti, giornale e istituzioni; la promessa di ordine produce attesa e mette in crisi il controllo del tempo.",caption:"Dal mondo ordinato alla crepa: quando la promessa del futuro comincia a consumare il presente."},
      quiz:[
        {q:"Qual è la tensione centrale del mondo ricevuto da Buzzati?",options:["Fra una promessa di ordine e un tempo che sfugge","Fra lingua italiana e dialetto bellunese","Fra poesia lirica e teatro classico"],answer:0,explanation:"La PWA individua nella promessa moderna di controllo e nella fuga del tempo la tensione preparatoria.",recovery:R("Ordine e tempo","Le istituzioni misurano il tempo, ma non possono garantire che la vita acquisti senso.","La fortezza può organizzare ogni turno senza impedire che l’attesa consumi Drogo.","Che cosa non garantisce l’efficienza?","Non garantisce il senso della vita.")},
        {q:"Perché il fantastico non è presentato come evasione?",options:["Perché ricostruisce fedelmente eventi storici","Perché rende visibili paure nascoste nel quotidiano","Perché elimina ogni elemento impossibile"],answer:1,explanation:"L’anomalia fantastica funziona come rivelatore dei conflitti che la normalità copre.",recovery:R("Fantastico come rivelazione","L’impossibile sposta e concentra problemi reali invece di cancellarli.","Un corridoio d’ospedale diventa immagine della perdita di controllo.","Che cosa rivela l’anomalia?","Un conflitto reale nascosto nella normalità.")},
        {q:"Che funzione ha la chiarezza linguistica di Buzzati?",options:["Impedisce qualunque inquietudine","Imita la poesia ermetica","Rende credibile l’irruzione dell’impossibile"],answer:2,explanation:"Il tono piano stabilizza il mondo e fa risaltare l’anomalia senza segnalarla enfaticamente.",recovery:R("Chiarezza e anomalia","Una lingua ordinaria costruisce fiducia; proprio per questo l’evento assurdo colpisce di più.","La cronaca sobria fa apparire plausibile anche una goccia che sale le scale.","Perché il tono non cambia?","Perché l’impossibile deve sembrare accadere nel nostro stesso mondo.")},
        {q:"Come vanno intesi Milano e le Dolomiti?",options:["Come coordinate culturali di due esperienze del reale","Come prova che ogni opera è autobiografica","Come luoghi tra loro privi di rapporto"],answer:0,explanation:"Città e montagna offrono due regimi percettivi, senza determinare automaticamente le opere.",recovery:R("Coordinate, non cause","Un contesto rende intelligibile una tensione, ma non causa meccanicamente un testo.","Milano suggerisce organizzazione; la montagna, una misura oltre l’uomo.","Il paesaggio determina da solo l’opera?","No: offre immagini e tensioni che la scrittura trasforma.")},
        {q:"Quale rischio contiene la promessa del futuro?",options:["Che il presente venga vissuto con maggiore intensità","Che l’attesa dell’occasione consumi la vita presente","Che il racconto perda ogni intreccio"],answer:1,explanation:"Il rinvio è il nucleo esistenziale che prepara Il deserto dei Tartari e molti racconti.",recovery:R("Il rinvio","Quando tutto il valore è affidato a domani, l’oggi diventa solo preparazione e si svuota.","Drogo resta perché la grande occasione sembra sempre sul punto di arrivare.","Dove si sposta il valore della vita?","In un futuro atteso che può non arrivare.")}
      ]
    },
    {
      id:"fratture", title:"Le fratture della vita", short:"Giornale, guerra e caduta dei miti", subtitle:"Esperienze che incrinano l’ordine",
      question:"Quali esperienze rendono insufficiente il mondo ordinato ricevuto da Buzzati?",
      lesson:`
        <p class="eyebrow">Tesi</p><p>Le fratture di Buzzati non formano un romanzo psicologico da cui dedurre automaticamente ogni opera. Alcune esperienze, però, rendono intelligibili le sue ossessioni: la morte precoce del padre, la lunga disciplina del giornale, la guerra osservata da vicino, il crollo dei miti collettivi e la percezione sempre più netta del tempo. Il punto decisivo non è cercare “la causa” di un testo, ma capire come la vita gli abbia fornito forme concrete dell’attesa, dell’ordine e della perdita.</p>
        <h2 id="m2-padre">La morte entra presto nell’orizzonte</h2><p>Nel 1920, quando Dino ha quattordici anni, muore il padre. È un dato biografico certo; sarebbe invece arbitrario spiegare con questo solo evento l’intera presenza della morte nei suoi libri. Possiamo dire con cautela che l’esperienza rende comprensibile la precocità di alcune paure affidate alle lettere giovanili e la familiarità con l’idea che una vita ordinata possa essere interrotta. La morte buzzatiana non è quasi mai puro spettacolo macabro. È una frontiera che retroagisce sul presente: sapere che il tempo è limitato modifica il valore dell’attesa.</p>
        <h2 id="m2-giornale">La redazione: disciplina e sospensione</h2><p>Buzzati entra al Corriere della Sera nel luglio 1928 e vi rimane, con diverse funzioni, quasi tutta la vita. La gavetta è lunga: cronaca nera, resoconti, titoli, notti in redazione. Marcello Carlino osserva che il mestiere gli offre temi, contatto con i lettori e una lingua media efficace. Lo stesso Buzzati riconoscerà l’affinità fra ottimo giornalismo e ottima letteratura. Il giornale educa alla concretezza: un ambiente, un dettaglio e un tempo devono essere comprensibili in poche righe.</p><p>Ma la redazione è anche ripetizione. Turni, chiusure e attesa della notizia possono dare la sensazione che la vera occasione sia sempre altrove. Secondo una testimonianza richiamata dalla critica, l’esperienza fornisce un contesto per la fortezza del Deserto: un’istituzione assorbe le giornate mentre promette l’evento eccezionale. Non bisogna però sostituire “fortezza uguale redazione” alla complessità del romanzo. La biografia accende il problema; la forma letteraria lo universalizza.</p>
        <h2 id="m2-guerra">La guerra e l’ambivalenza dell’ordine</h2><p>Fra 1939 e guerra mondiale Buzzati è inviato ad Addis Abeba e poi corrispondente sulle navi della Marina. Assiste a operazioni e battaglie. La guerra mostra nella maniera più radicale l’ambivalenza delle istituzioni: disciplina, solidarietà e coraggio convivono con distruzione, obbedienza e mito. La voce del Dizionario Biografico insiste severamente sulla sua attrazione per il cameratismo e per l’ordine militare. Questo giudizio va conosciuto, non addolcito. Buzzati non costruisce una precoce figura pubblica di oppositore politico; la sua posizione appare segnata da distanza e da limiti che la critica ha discusso.</p><p>Il 1943-45 costituisce una frattura collettiva. Fascismo, sconfitta e Resistenza fanno crollare l’immagine compatta dell’ordine nazionale e militare. La traiettoria non produce automaticamente una letteratura storica o neorealista. Anzi, Buzzati reagisce spesso spostando il conflitto nella favola e nell’allegoria. Anche questa scelta è ambigua: può essere letta come difesa dalla contingenza, ma pure come ricerca di una forma capace di andare oltre la cronaca immediata.</p>
        <h2 id="m2-successo">Il successo non elimina l’inquietudine</h2><p>Il deserto dei Tartari esce nel 1940; nel dopoguerra cresce la fortuna dei racconti; Sessanta racconti ottiene il Premio Strega nel 1958. Il riconoscimento non chiude il problema dell’attesa. La maturità allarga piuttosto i media e i temi: scienza, tecnologia, metropoli, eros, pittura e fumetto. Nel Grande ritratto una macchina tenta di ricostruire la persona perduta; in Un amore il desiderio trasforma Milano in ossessione; nel Poema a fumetti parola e immagine reinventano Orfeo.</p><p>La frattura diventa allora anche mediale. Scrivere soltanto non basta più. Buzzati dipinge, illustra, costruisce tavole, falsi ex voto e racconti visivi. La formula “scrittore che dipinge” gli sta stretta: per lui narrare può avvenire con parole e immagini. L’Università di Bologna e Ca’ Foscari mostrano come queste opere vadano lette come esperimenti consapevoli, non come appendici decorative.</p>
        <h2 id="m2-ultimo">La malattia e l’ultima soglia</h2><p>Buzzati muore a Milano nel gennaio 1972, dopo una malattia rapida. Sarebbe facile leggere retrospettivamente ogni racconto come presagio della fine; sarebbe un errore. La morte è presente molto prima e non coincide con la diagnosi. Nell’ultima produzione, però, il confine fra vita e aldilà acquista una nuova urgenza. I miracoli di Val Morel costruisce un archivio immaginario di ex voto: finge documenti, immagini devozionali e memorie locali. Anche davanti alla fine, il narratore non abbandona il gioco; lo usa per dare figura all’invisibile.</p><div class="interpretation"><strong>Cautela critica.</strong> “Frattura” non significa causa lineare. La morte del padre non “genera” il Deserto, la redazione non “è” la fortezza, la guerra non “spiega” ogni paura. Queste esperienze offrono un contesto verificabile per tensioni che le opere trasformano.</div>
        <div class="bridge"><strong>Ponte.</strong> Dopo queste fratture, il mondo non appare più come un meccanismo sicuro. Occorre ricostruire l’immagine della realtà che emerge: una normalità attraversata da segnali, attese e forze invisibili.</div>`,
      summary:`<p>Le fratture biografiche di Buzzati non vanno usate come spiegazioni automatiche delle opere. La morte del padre rende però comprensibile la precoce familiarità con il limite. Il lavoro al Corriere gli offre precisione, lingua chiara, repertorio urbano e una concreta esperienza di disciplina e ripetizione. La guerra, vissuta come corrispondente, mostra l’ambivalenza dell’ordine militare e il crollo dei miti collettivi; la critica ha discusso anche i limiti politici della sua posizione. Nel dopoguerra Buzzati non sceglie il neorealismo: trasforma il conflitto mediante favola e allegoria. Il successo dei racconti e del Deserto non chiude l’inquietudine, ma conduce a nuove forme: fantascienza, romanzo urbano, pittura e fumetto. Nell’ultima stagione parola e immagine diventano strumenti equivalenti del narrare. La biografia, quindi, non determina i testi: offre situazioni concrete che la scrittura porta a una dimensione esistenziale.</p>`,
      essentials:["Distinguere un contesto biografico da una causa automatica dell’opera.","Spiegare che cosa il giornalismo offre alla scrittura di Buzzati.","Riconoscere l’ambivalenza dell’esperienza militare e della disciplina.","Collocare la crisi del 1943-45 senza trasformare Buzzati in autore neorealista.","Spiegare perché il successo non dissolve i temi di tempo e attesa.","Descrivere la frattura mediale che conduce da parola a immagine."],
      glossary:[{term:"Cronaca nera",definition:"Racconto giornalistico di delitti, incidenti e fatti drammatici della vita quotidiana."},{term:"Corrispondente di guerra",definition:"Giornalista che documenta operazioni e vita militare nelle zone di conflitto."},{term:"Allegoria",definition:"Racconto concreto che rinvia in modo riconoscibile a un significato ulteriore."},{term:"Neorealismo",definition:"Orientamento del dopoguerra volto a rappresentare storia, conflitti sociali e vita concreta."},{term:"Intermedialità",definition:"Interazione fra linguaggi diversi, per esempio parola, pittura e fumetto."},{term:"Frattura",definition:"Esperienza che rende insufficiente una visione ricevuta e costringe a riorganizzarla."}],
      map:{src:"./maps/02-fratture.svg",alt:"Mappa: morte del padre, redazione, guerra, crollo dei miti, successo e sperimentazione mediale trasformano l’ordine ricevuto in coscienza del limite.",caption:"Le esperienze non causano meccanicamente i testi: forniscono forme concrete che la scrittura trasforma."},
      quiz:[
        {q:"Come usa la PWA la morte precoce del padre?",options:["Come causa unica di tutte le opere","Come dato irrilevante da ignorare","Come contesto che rende intelligibile la precoce coscienza del limite"],answer:2,explanation:"Il nesso viene formulato con cautela, senza psicologismo deterministico.",recovery:R("Contesto biografico","Un evento può illuminare una tensione senza produrre direttamente un’opera.","La perdita rende comprensibile la familiarità con il limite, non “spiega” ogni racconto.","Che differenza c’è fra contesto e causa?","Il contesto aiuta a comprendere; la causa determinerebbe automaticamente.")},
        {q:"Quale coppia di risorse il giornale offre a Buzzati?",options:["Oscurità sintattica e autobiografia","Concretezza e lingua comunicativa","Dialetto e metrica classica"],answer:1,explanation:"Cronaca e redazione allenano dettaglio, montaggio, chiarezza e rapporto emotivo con il lettore.",recovery:R("Scuola del giornale","Il mestiere impone selezione dei dettagli e comunicazione rapida.","Una scena impossibile acquista forza se è narrata con precisione da cronista.","Qual è l’effetto della concretezza?","Rende credibile e vicino anche il fantastico.")},
        {q:"Perché l’esperienza militare è definita ambivalente?",options:["Perché unisce disciplina e solidarietà a obbedienza e distruzione","Perché Buzzati non vide mai la guerra","Perché riguarda soltanto la montagna"],answer:0,explanation:"L’ordine militare attrae e insieme mostra il proprio potenziale distruttivo e mitico.",recovery:R("Ambivalenza dell’ordine","La stessa istituzione può offrire appartenenza e sospendere la responsabilità individuale.","La vita di reparto organizza e protegge, ma chiede obbedienza dentro la guerra.","Perché non basta dire “ordine positivo”?","Perché bisogna includere il costo umano e politico dell’obbedienza.")},
        {q:"Qual è la risposta prevalente di Buzzati alla crisi del dopoguerra?",options:["L’adesione piena al neorealismo","L’abbandono definitivo della narrativa","Lo spostamento del conflitto in favola e allegoria"],answer:2,explanation:"La crisi storica viene spesso trasfigurata invece che rappresentata direttamente.",recovery:R("Trasfigurazione","Spostare non significa necessariamente negare: significa cambiare il piano della rappresentazione.","Una paura collettiva può diventare minaccia anonima in un racconto.","Buzzati documenta sempre direttamente la storia?","No: spesso la trasforma in favola o allegoria.")},
        {q:"Che cosa indica la “frattura mediale”?",options:["La rinuncia a ogni immagine","Il passaggio a forme che intrecciano parola, pittura e fumetto","La distruzione dei manoscritti giovanili"],answer:1,explanation:"Nella maturità il racconto migra fra linguaggi e l’immagine assume funzione narrativa.",recovery:R("Intermedialità","Un’opera intermediale costruisce senso attraverso più linguaggi coordinati.","Poema a fumetti narra con successione di tavole, parole, ritmo visivo e mito.","L’immagine è solo decorazione?","No: partecipa alla struttura e al significato del racconto.")}
      ]
    },
    {
      id:"immagine-del-mondo", title:"L’immagine del mondo", short:"La normalità sotto allarme", subtitle:"Come appare la realtà",
      question:"Come appare il mondo quando il tempo, il desiderio e la morte agiscono sotto la sua superficie normale?",
      lesson:`
        <p class="eyebrow">Tesi</p><p>Per Buzzati la realtà non è divisa in due territori, uno vero e uno fantastico. È un’unica superficie instabile. La quotidianità resta riconoscibile, ma può aprirsi all’improvviso su una forza che era già presente: il tempo che consuma, il destino che chiama, la paura che inventa segnali, il desiderio che deforma. Il fantastico non aggiunge un secondo mondo; mostra la profondità inquieta di questo.</p>
        <h2 id="m3-segnali">Un mondo pieno di segnali</h2><p>I personaggi buzzatiani vedono tracce: un movimento nel deserto, una goccia sulle scale, notizie incomprensibili fuori dal finestrino, una creatura che segue una nave. Il segnale è ambiguo. Può annunciare l’occasione desiderata o la catastrofe temuta; spesso le due cose coincidono. Nel Deserto dei Tartari l’arrivo del nemico darebbe senso alla vita militare di Drogo, ma porterebbe anche la morte. Nel Colombre la creatura temuta per anni custodisce in realtà un dono. L’uomo interpreta tardi, e il ritardo costituisce la tragedia.</p><p>Questa struttura assegna al lettore un compito. Non basta domandare se l’evento sia “reale”. Occorre osservare che cosa produce nei personaggi: obbedienza, fuga, attesa, silenzio. Il fantastico misura una risposta umana. Quando tutti i passeggeri di Qualcosa era successo vedono segni di una catastrofe ma nessuno osa fermare il treno, la minaccia esterna rivela una prigione interna: conformismo, vergogna, incapacità di interrompere la corsa.</p>
        <h2 id="m3-tempo">Il tempo non è uno sfondo</h2><p>Il tempo buzzatiano agisce. All’inizio sembra abbondante; poi accelera senza rumore. La ripetizione rende invisibile il consumo: ogni giorno assomiglia al precedente, quindi nessun singolo giorno sembra decisivo. Solo retrospettivamente il personaggio scopre che la somma delle giornate era la vita. L’attesa funziona perché promette un avvenimento capace di riscattare il passato. Più tempo è stato investito, più diventa difficile andarsene: abbandonare l’attesa significherebbe ammettere che il sacrificio non sarà ripagato.</p><p>Questa non è soltanto una metafisica astratta. Assomiglia a strutture concrete della modernità: carriera, promozione, riconoscimento, procedura, abitudine. L’opera di Buzzati interroga il punto in cui la disciplina smette di sostenere un progetto e comincia a sostituirsi alla vita. Perciò il Deserto continua a parlarci: non descrive soltanto un ufficiale remoto, ma il meccanismo con cui una promessa futura trattiene il presente.</p>
        <h2 id="m3-spazio">Gli spazi diventano macchine morali</h2><p>Fortezze, ospedali, uffici, palazzi, treni e città non sono fondali neutrali. Organizzano i gesti e restringono le scelte. In Sette piani il movimento fisico del malato verso i reparti inferiori rende visibile una classificazione che diventa destino. Nel Deserto, mura e regolamenti proteggono dal vuoto ma impediscono di lasciarlo. La montagna ha una funzione diversa: può rappresentare prova, altezza e libertà, ma anche indifferenza e pericolo. Nessuno spazio è puramente positivo.</p><p>Buzzati costruisce così una geografia esistenziale. Alto e basso, centro e confine, città e deserto, superficie e sotterraneo trasformano concetti astratti in percorsi. Il lettore non riceve una teoria sul destino: vede un uomo cambiare piano, una sentinella scrutare l’orizzonte, un viaggiatore oltrepassare stazioni senza poter scendere.</p>
        <h2 id="m3-mistero">Mistero senza soluzione completa</h2><p>Il mistero di Buzzati non coincide con l’enigma poliziesco. Nel giallo, gli indizi dovrebbero condurre a una spiegazione. Qui la spiegazione può arrivare troppo tardi o restare insufficiente. Il mondo mantiene un’eccedenza rispetto alla ragione. Ciò non implica rifiuto della razionalità: la prosa è precisa e l’osservazione concreta. Significa che la ragione non possiede l’intero reale.</p><p>Su questo punto si incontra una tensione religiosa, ma non una dottrina sistematica. Molti testi interrogano giudizio, grazia, miracolo e aldilà; nello stesso tempo evitano una soluzione teologica univoca. La morte può diventare l’ultima prova di dignità, come per Drogo, oppure una porta negata, come nel Poema. È più corretto parlare di domanda metafisica che attribuire all’autore un catechismo narrativo.</p>
        <h2 id="m3-uomo">L’uomo: fragile interprete</h2><p>L’essere umano cerca segni e storie per orientarsi. Ma paura e desiderio deformano l’interpretazione. Stefano Roi fugge dal Colombre perché eredita una lettura sbagliata; Drogo interpreta ogni traccia come promessa dell’evento; i passeggeri del treno tacciono per non esporsi. L’errore non nasce solo da ignoranza: nasce dal bisogno che la realtà confermi un’idea già posseduta.</p><div class="interpretation"><strong>Interpretazione didattica.</strong> Il vero “mostro” buzzatiano è spesso una relazione difettosa con il tempo: attendere invece di scegliere, temere invece di verificare, obbedire invece di interrompere.</div><div class="bridge"><strong>Ponte.</strong> Se la realtà è normale e insieme insondabile, la scrittura deve ottenere un equilibrio difficile: precisione cronachistica, suspense, allegoria e anomalia. Questo equilibrio costituisce la poetica.</div>`,
      summary:`<p>Il mondo di Buzzati è una superficie quotidiana attraversata da forze invisibili. I segnali sono ambigui: possono annunciare insieme l’occasione e la catastrofe. Il tempo agisce attraverso la ripetizione; ogni giorno sembra insignificante, ma la loro somma consuma la vita. L’attesa trattiene perché promette di riscattare il tempo già investito. Anche gli spazi diventano dispositivi morali: fortezza, ospedale, treno e città organizzano comportamenti e restringono scelte. Il mistero non è un enigma destinato a una soluzione totale, bensì l’eccedenza del reale rispetto alle spiegazioni. La domanda religiosa rimane aperta e non si lascia ridurre a dottrina. L’uomo è un interprete fragile: paura e desiderio gli fanno leggere male i segni. Per questo il fantastico misura soprattutto le reazioni umane. La poetica dovrà rendere credibile tale instabilità senza rinunciare alla chiarezza.</p>`,
      essentials:["Spiegare perché reale e fantastico non sono due mondi separati.","Descrivere la doppia funzione del segnale: occasione e minaccia.","Mostrare come ripetizione e attesa consumino il tempo.","Analizzare gli spazi come dispositivi che orientano le scelte.","Distinguere mistero buzzatiano ed enigma poliziesco.","Spiegare perché paura e desiderio deformano l’interpretazione."],
      glossary:[{term:"Segnale",definition:"Traccia ambigua che il personaggio interpreta come promessa o minaccia."},{term:"Attesa",definition:"Investimento del presente in un evento futuro che dovrebbe riscattarlo."},{term:"Spazio simbolico",definition:"Luogo concreto la cui struttura rende visibile un conflitto esistenziale."},{term:"Eccedenza",definition:"Parte del reale che non si lascia esaurire da una spiegazione razionale."},{term:"Metafisico",definition:"Riferito alle domande ultime su destino, morte, senso e realtà."},{term:"Conformismo",definition:"Adeguamento al comportamento comune anche contro ciò che si percepisce."}],
      map:{src:"./maps/03-immagine.svg",alt:"Mappa: la normalità contiene segnali ambigui; l’attesa consuma il tempo, gli spazi limitano le scelte, paura e desiderio deformano l’interpretazione e aprono il mistero.",caption:"La realtà non si spezza in vero e fantastico: diventa una superficie sotto allarme."},
      quiz:[
        {q:"Quale funzione svolge il segnale nei racconti di Buzzati?",options:["Conferma sempre una verità già nota","Resta ambiguo fra promessa e minaccia","Serve soltanto a decorare l’ambiente"],answer:1,explanation:"Il segnale mobilita desiderio e paura, e mette alla prova l’interpretazione.",recovery:R("Ambiguità del segnale","La stessa traccia può offrire senso e annunciare pericolo.","I Tartari rappresentano l’occasione attesa e insieme la guerra.","Il segnale possiede un significato unico?","No: è interpretato fra promessa e minaccia.")},
        {q:"Come agisce il tempo buzzatiano?",options:["Attraverso ripetizione e accelerazione quasi impercettibile","Come semplice datazione storica","Restando immobile per tutti i personaggi"],answer:0,explanation:"La somiglianza dei giorni nasconde il consumo finché è troppo tardi.",recovery:R("Tempo attivo","Il tempo non fa da sfondo: modifica possibilità, corpo e scelta.","Alla fortezza nessun giorno sembra decisivo, ma gli anni passano.","Perché la ripetizione inganna?","Perché fa sembrare ogni giornata sostituibile e innocua.")},
        {q:"Che cosa rende la fortezza uno spazio simbolico?",options:["La sua descrizione geografica esatta","Il fatto che organizza l’attesa e restringe la scelta","La presenza di un narratore in prima persona"],answer:1,explanation:"L’architettura traduce in spazio la dipendenza dalla promessa futura.",recovery:R("Spazio che agisce","Uno spazio simbolico non significa soltanto qualcosa: orienta concretamente i comportamenti.","Regole e confine rendono difficile per Drogo lasciare il luogo.","Che cosa fa la fortezza?","Protegge e insieme trattiene dentro l’attesa.")},
        {q:"In che cosa il mistero differisce dall’enigma poliziesco?",options:["Non contiene mai indizi","Ha sempre un colpevole identificabile","Non si esaurisce necessariamente in una soluzione completa"],answer:2,explanation:"L’eccedenza metafisica resta anche dopo eventuali spiegazioni dei fatti.",recovery:R("Mistero ed enigma","L’enigma chiede chiusura; il mistero conserva una parte non dominabile.","Capire il percorso del Colombre non elimina la domanda sulla vita perduta.","Una spiegazione chiude tutto?","No: il significato esistenziale resta aperto.")},
        {q:"Qual è un limite dell’interprete umano?",options:["Paura e desiderio possono deformare i segni","La ragione offre sempre una conoscenza totale","I personaggi non formulano mai ipotesi"],answer:0,explanation:"Spesso il personaggio trova nella realtà ciò che teme o spera già.",recovery:R("Interpretazione deformata","Non leggiamo da una posizione neutrale: aspettative e paure selezionano i dati.","Stefano Roi eredita la paura del Colombre e organizza tutta la vita attorno ad essa.","Che cosa precede talvolta la lettura dei fatti?","Un’idea o una paura già posseduta.")}
      ]
    }
  ];
  // Le tre sezioni conclusive sono dichiarate nel primo blocco del file e qui
  // ricomposte nel percorso; l'array delle fonti resta così composto solo da fonti.
  window.BUZZATI_SECTIONS.push(...window.BUZZATI_SOURCES.splice(7));
})();
