window.NEOREALISMO_DATA = {
  sections: [
    {
      id:"mondo", short:"Il mondo precedente", kicker:"Prima dello sguardo", title:"Il mondo precedente", subtitle:"Un’Italia raccontata dall’alto, mentre dal basso cresce una fame di realtà", color:"#6b4038",
      question:"Quale realtà culturale e politica riceve il Neorealismo, e perché le sue forme diventano improvvisamente insufficienti?",
      lesson:`
        <h3 id="m1-regime">1. Una realtà amministrata</h3>
        <p>Il Neorealismo nasce da un paradosso: prima ancora che manchino le storie, manca la possibilità pubblica di guardarle senza filtri. Durante il fascismo la cultura italiana non è tutta riducibile alla propaganda; esistono dissensi, zone autonome, opere irregolari. Tuttavia il regime controlla giornali, editoria, radio e cinema, selezionando ciò che può diventare immagine condivisa del paese. L’Italia ufficiale deve apparire ordinata, concorde, energica. Povertà, conflitto sociale, persecuzione politica e violenza coloniale non scompaiono dalla vita: vengono espulsi dal quadro o ricodificati.</p>
        <p>Nel cinema degli anni Trenta le commedie dette dei “telefoni bianchi” offrono interni borghesi, equivoci sentimentali e oggetti di consumo. Sarebbe rozzo liquidarle tutte come propaganda: alcune sono prodotti industriali sofisticati e perfino attraversati da ironie. Ma la loro superficie elegante diventa, a posteriori, il simbolo di una distanza. Mentre il paese reale conosce lavoro precario, emigrazione e repressione, lo schermo privilegia ambienti sociali rarefatti. Cinecittà, fondata nel 1937, costruisce una moderna industria cinematografica; la modernità tecnica, però, non garantisce verità politica.</p>
        <h3 id="m1-letteratura">2. L’autonomia della letteratura e il suo limite</h3>
        <p>Anche la letteratura precedente non forma un blocco. L’Ermetismo difende la concentrazione della parola poetica, il valore assoluto del linguaggio, una ricerca interiore che può sottrarsi alla retorica pubblica. Proprio questa chiusura può funzionare come rifiuto del linguaggio fascista. Ma dopo la guerra molti giovani percepiranno l’isolamento della parola come insufficiente: non perché Ungaretti, Montale o gli ermetici non abbiano conosciuto la storia, bensì perché la catastrofe impone una comunicazione più larga e immediata.</p>
        <p>Esistono inoltre anticipazioni realistiche decisive. <em>Gli indifferenti</em> di Moravia (1929) mostra la decomposizione morale della borghesia; <em>Gente in Aspromonte</em> di Corrado Alvaro (1930) porta in primo piano il Mezzogiorno contadino; <em>Tre operai</em> di Carlo Bernari (1934) racconta lavoro e alienazione industriale. Nel cinema, <em>Quattro passi fra le nuvole</em> di Blasetti, <em>I bambini ci guardano</em> di De Sica e soprattutto <em>Ossessione</em> di Visconti, fra 1942 e 1944, incrinano l’immaginario precedente. Il nuovo non comincia dal nulla: raccoglie energie già presenti e le rende riconoscibili dopo la frattura storica.</p>
        <h3 id="m1-modelli">3. Verga, l’America e Gramsci: tre eredità non coincidenti</h3>
        <p>Il termine “nuovo realismo” richiama inevitabilmente il Realismo e il Verismo ottocenteschi. Verga aveva spezzato la gerarchia dei soggetti, mostrando che pescatori e contadini potevano sostenere la grande letteratura. Dal suo metodo giunge l’attenzione ai vinti, alle lingue locali, ai meccanismi economici. Il dopoguerra, però, modifica la prospettiva: le masse non appaiono soltanto travolte da forze impersonali; sono entrate nella storia attraverso scioperi, guerra e Resistenza. La possibilità del cambiamento convive con la sconfitta.</p>
        <p>Un secondo laboratorio è la letteratura statunitense tradotta e discussa da Pavese e Vittorini: Hemingway, Faulkner, Steinbeck, Caldwell offrono dialoghi tesi, paesaggi concreti, personaggi non aristocratici e un ritmo meno accademico. Non sono modelli da copiare, ma strumenti per sprovincializzare l’italiano letterario. Un terzo riferimento sarà Gramsci. La pubblicazione postbellica dei <em>Quaderni del carcere</em> alimenta il problema di una cultura “nazionale-popolare”, capace di colmare la separazione storica fra intellettuali e popolo. Anche qui bisogna evitare la formula facile: parlare del popolo non significa automaticamente parlare con il popolo.</p>
        <h3 id="m1-tensione">4. Il limite che prepara la frattura</h3>
        <p>Il mondo precedente consegna dunque quattro tensioni: una rappresentazione pubblica controllata; una letteratura spesso separata dalla comunicazione collettiva; tradizioni realistiche ancora vitali; nuovi modelli linguistici in cerca di occasione. La guerra renderà impossibile continuare come prima. Quando le città bombardate, i soldati sbandati, i deportati e i partigiani diventano esperienza comune, l’eleganza senza storia appare moralmente inadeguata.</p>
        <p>La parola decisiva non è ancora “realismo”, ma <em>insufficienza</em>. Un linguaggio può essere tecnicamente perfetto e non riuscire più a dire il presente. Il Neorealismo nascerà da questa crisi: non come semplice ritorno alla fotografia del vero, ma come ricerca di una relazione nuova fra chi racconta, ciò che è accaduto e una comunità che vuole riconoscersi.</p>
        <p>Questa ricostruzione evita anche un errore frequente: opporre meccanicamente “arte falsa” e “arte vera”. Nessuna opera possiede il reale senza mediazioni. La differenza riguarda piuttosto quali esperienze una forma rende pensabili e quali lascia ai margini. Il cinema elegante degli anni Trenta e la poesia concentrata sull’interiorità non vengono cancellati; diventano il termine di confronto contro cui una generazione misura la distanza fra la propria esperienza e i linguaggi disponibili. La guerra non inventa la fame di realtà: le dà un’urgenza collettiva e un pubblico nuovo.</p>`,
      bridge:"La tensione accumulata diventa rottura fra il 1943 e il 1945: la storia entra nelle biografie e trasforma testimoni, combattenti, deportati e spettatori in narratori potenziali.",
      summary:`<p>Il Neorealismo riceve un’Italia la cui immagine pubblica è stata selezionata dal fascismo, ma non un deserto culturale. L’Ermetismo ha difeso l’autonomia della parola; Moravia, Alvaro e Bernari hanno già aperto squarci realistici; Visconti, De Sica e Blasetti hanno incrinato il cinema precedente. Verga offre l’attenzione ai vinti, la narrativa americana tradotta da Pavese e Vittorini rinnova ritmo e linguaggio, Gramsci pone il problema di una cultura nazionale-popolare. Dopo la catastrofe bellica, tuttavia, queste eredità devono essere riorganizzate. Il problema non è che l’arte precedente fosse tutta falsa: è che molte sue forme non bastano più a creare una comunicazione responsabile con una società attraversata da guerra, povertà e conflitto. La frattura del 1943-45 trasformerà questa insufficienza in urgenza di testimoniare.</p>`,
      essentials:[
        "Spiegare perché la cultura sotto il fascismo non coincide interamente con la propaganda, pur essendo sottoposta a controllo e selezione.",
        "Distinguere il valore letterario dell’Ermetismo dalla percezione postbellica della sua insufficienza comunicativa.",
        "Indicare almeno tre anticipazioni realistiche degli anni Trenta e spiegare perché preparano il Neorealismo.",
        "Confrontare il pessimismo verghiano con la nuova presenza storica e politica delle masse nel dopoguerra.",
        "Spiegare il ruolo della narrativa americana e della riflessione gramsciana senza ridurle a ricette.",
        "Formulare la tensione di fondo: un linguaggio può essere raffinato e tuttavia non bastare più a dire il presente."
      ],
      vocabulary:[["Telefoni bianchi","Etichetta per commedie cinematografiche eleganti degli anni Trenta, divenute simbolo di un’Italia borghese e rarefatta."],["Ermetismo","Ricerca poetica concentrata sull’autonomia e densità della parola, non semplice fuga dalla storia."],["Anticipazione realistica","Opera precedente al 1945 che rende visibili conflitti, ambienti e soggetti rimossi dall’immagine ufficiale."],["Verismo","Realismo italiano ottocentesco che studia ambienti popolari e forze economiche, soprattutto attraverso Verga."],["Nazionale-popolare","Problema gramsciano di una cultura capace di creare relazione organica fra intellettuali e popolo."],["Mediazione","Insieme di scelte linguistiche e formali attraverso cui la realtà diventa racconto, mai copia neutra."]],
      map:{src:"assets/maps/01-mondo.svg",alt:"Mappa: l’immagine controllata del fascismo e l’autonomia ermetica entrano in crisi; anticipazioni realistiche, Verga, narrativa americana e Gramsci preparano una nuova comunicazione con il pubblico.",caption:"Dal controllo dell’immagine alla fame di realtà: le eredità che preparano la frattura."},
      questions:[
        {prompt:"Qual è il limite principale dell’immagine pubblica costruita durante il fascismo?",options:["Seleziona e rimuove conflitti decisivi della società","Rifiuta ogni forma di industria culturale moderna","Rappresenta soltanto il mondo contadino"],correct:0,explanation:"Il problema è la selezione politica del visibile, non l’assenza di modernità tecnica.",anchor:"m1-regime",recovery:{concept:"Realtà amministrata",clarification:"Il regime non elimina ogni arte valida; controlla ciò che può diventare immagine collettiva.",example:"Cinecittà modernizza il cinema mentre molte contraddizioni restano fuori quadro.",check:"Perché innovazione tecnica e verità politica non coincidono?"}},
        {prompt:"Perché non è corretto descrivere l’Ermetismo soltanto come fuga?",options:["Perché usa sempre temi sociali espliciti","Perché l’autonomia della parola può anche opporsi alla retorica pubblica","Perché nasce dopo la Resistenza"],correct:1,explanation:"La concentrazione linguistica può essere una forma di autonomia, anche se poi appare insufficiente alla nuova urgenza.",anchor:"m1-letteratura",recovery:{concept:"Autonomia e insufficienza",clarification:"Una poetica può avere valore oppositivo e diventare, in un altro contesto, poco adatta alla comunicazione collettiva.",example:"Dopo la guerra i giovani non negano tutta la poesia precedente: cercano un diverso rapporto col pubblico.",check:"Come può una forma essere valida e insieme non più sufficiente?"}},
        {prompt:"Che cosa distingue il nuovo sguardo sui “vinti” da quello verghiano?",options:["L’eliminazione di ogni sconfitta","Il rifiuto degli ambienti popolari","La possibilità storica del riscatto collettivo"],correct:2,explanation:"Nel dopoguerra le masse sono soggetti politici; la sconfitta non esclude più in assoluto il cambiamento.",anchor:"m1-modelli",recovery:{concept:"Dai vinti ai soggetti storici",clarification:"Il Neorealismo eredita Verga, ma vive dopo organizzazione politica, scioperi e Resistenza.",example:"Il popolo non è soltanto osservato: partecipa alla storia.",check:"Quale evento collettivo rende diversa la prospettiva?"}},
        {prompt:"Quale funzione svolge la narrativa americana per Pavese e Vittorini?",options:["Offre strumenti per rinnovare lingua, ritmo e soggetti","Impone un unico stile da imitare","Sostituisce completamente la tradizione italiana"],correct:0,explanation:"È un laboratorio di sprovincializzazione, non una ricetta uniforme.",anchor:"m1-modelli",recovery:{concept:"Modello come strumento",clarification:"Tradurre significa mettere alla prova l’italiano letterario con altre cadenze e altri mondi.",example:"Hemingway e Faulkner offrono soluzioni molto diverse, dunque nessuna formula unica.",check:"Perché parlare di laboratorio è più preciso che parlare di copia?"}},
        {prompt:"Quale parola sintetizza meglio il passaggio alla frattura?",options:["Eleganza","Insufficienza","Nostalgia"],correct:1,explanation:"La guerra rende molte forme ricevute insufficienti a dire un’esperienza comune e traumatica.",anchor:"m1-tensione",recovery:{concept:"Crisi dei linguaggi",clarification:"Il nuovo nasce quando il vecchio non riesce più a organizzare l’esperienza presente.",example:"Le città bombardate e la guerra civile chiedono un’altra relazione tra scrittore e pubblico.",check:"Che cosa diventa moralmente inadeguato dopo il 1943?"}}
      ]
    },
    {
      id:"fratture", short:"Le fratture", kicker:"Vite nella storia", title:"Le fratture della vita degli autori", subtitle:"Guerra, Resistenza, deportazione e dopoguerra rompono la distanza tra biografia e storia", color:"#7b2f2a",
      question:"Che cosa rende impossibile continuare a raccontare come prima senza trasformare ogni esperienza in una spiegazione automatica dell’opera?",
      lesson:`
        <h3 id="m2-1943">1. Il 1943: la storia perde il fondale</h3>
        <p>Il 25 luglio 1943 cade Mussolini; l’8 settembre l’armistizio spezza l’apparato statale; l’occupazione tedesca, la Repubblica sociale e la Resistenza dividono il paese. La storia non è più uno scenario esterno alla vita privata. Ogni scelta — nascondersi, combattere, collaborare, attendere, proteggere qualcuno — acquista peso politico. La guerra civile lacera famiglie e territori; le deportazioni e le stragi mostrano che l’ordine precedente non può essere restaurato moralmente.</p>
        <p>Questa esperienza non produce automaticamente “buona letteratura”. Produce però una pressione: raccontare diventa una forma di testimonianza e, insieme, un problema di responsabilità. Chi parla a nome di chi? Come evitare che il dolore altrui diventi materiale spettacolare? Come raccontare la Resistenza senza trasformarla in leggenda edificante? Le opere migliori nasceranno proprio dalla resistenza alla risposta facile.</p>
        <h3 id="m2-vite">2. Molte biografie, nessuna biografia esemplare</h3>
        <p>Gli autori attraversano la frattura in modi diversi. Italo Calvino combatte nelle formazioni partigiane liguri e poi sceglie, nel <em>Sentiero dei nidi di ragno</em>, lo sguardo laterale di un bambino. Beppe Fenoglio porta nella scrittura la conoscenza concreta delle Langhe e della guerriglia, ma rifiuta l’eroe senza contraddizioni. Elio Vittorini partecipa all’antifascismo e in <em>Uomini e no</em> interroga il confine morale dentro l’uomo, non soltanto fra due eserciti. Cesare Pavese non combatte nella Resistenza: proprio lo scarto fra storia collettiva e colpa individuale alimenta una diversa, tormentata posizione.</p>
        <p>Primo Levi vive la deportazione ad Auschwitz e costruisce <em>Se questo è un uomo</em> come testimonianza sorvegliata, analisi dei meccanismi di disumanizzazione e domanda rivolta al lettore. Carlo Levi, confinato in Lucania dal fascismo, in <em>Cristo si è fermato a Eboli</em> porta alla luce un’Italia contadina esclusa dallo Stato nazionale. Vasco Pratolini attraversa invece quartieri e comunità urbane fiorentine. Queste vite non confluiscono in una sola esperienza; aprono diversi punti d’accesso a un paese plurale.</p>
        <h3 id="m2-cinema">3. Le fratture materiali del cinema</h3>
        <p>Anche il cinema cambia attraverso condizioni concrete. Studi danneggiati, scarsità di pellicola e risorse, città ancora ferite spingono le troupe fuori dai teatri di posa. Ma sarebbe ingenuo trasformare la necessità economica in estetica spontanea. <em>Roma città aperta</em> viene girato nel 1945 con difficoltà reali e unisce attori celebri come Anna Magnani e Aldo Fabrizi a una forte impressione di cronaca; la sua verità è il risultato di una costruzione narrativa e visiva.</p>
        <p>Rossellini attraversa una biografia professionale contraddittoria: prima della caduta del fascismo realizza film di guerra legati alla produzione del regime, nei quali però matura attenzione documentaria; poi racconta occupazione, liberazione e macerie. Visconti proviene dall’aristocrazia e dall’esperienza internazionale con Jean Renoir; De Sica è già un attore popolare e trova con Cesare Zavattini un laboratorio capace di scoprire il dramma nel quotidiano. Non esiste il regista neorealista “puro”: esistono conversioni, continuità e scarti.</p>
        <h3 id="m2-dopoguerra">4. Dal “noi” ritrovato al conflitto sul futuro</h3>
        <p>Fra 1945 e 1948 l’urgenza di narrare sembra creare un “noi”. Calvino ricorderà un’immediatezza di comunicazione: le storie passano di bocca in bocca, le diverse Italie entrano nella lingua. Riviste, giornali, case editrici e cineclub discutono il compito dell’intellettuale. <em>Il Politecnico</em> di Vittorini chiede una cultura non consolatoria, capace di intervenire sulle cause della sofferenza.</p>
        <p>Quel “noi”, però, non resta unito. La guerra fredda, lo scontro politico del 1948, la ricostruzione economica e i rapporti fra intellettuali e partiti rendono visibili differenze profonde. L’impegno rischia di diventare disciplina ideologica; la rappresentazione del popolo può irrigidirsi in populismo. La frattura non è quindi soltanto fra fascismo e democrazia: passa anche dentro il dopoguerra, fra speranza di trasformazione e normalizzazione.</p>
        <h3 id="m2-nesso">5. Biografia come contesto, non come causa</h3>
        <p>Una didattica seria deve evitare il determinismo biografico. Essere partigiano non spiega da solo una struttura narrativa; essere deportato non trasforma automaticamente una testimonianza in letteratura. L’esperienza rende intelligibili domande, urgenze e scelte, ma l’opera nasce quando quelle pressioni vengono organizzate da voce, punto di vista, ritmo e forma.</p>
        <p>La vera conseguenza della frattura è dunque una nuova domanda di conoscenza: il reale è diventato comune e insieme opaco. Per comprenderlo occorre scegliere una posizione. Da qui nascerà l’immagine del mondo neorealista: non la realtà “così com’è”, ma una realtà vista dal basso, attraversata da responsabilità e conflitti. La pluralità delle biografie impedisce così alla memoria di chiudersi in un’unica versione ufficiale.</p>`,
      bridge:"Dalle biografie spezzate emerge una nuova immagine del mondo: la storia abita i gesti quotidiani, gli esclusi diventano soggetti e nessuno sguardo può dichiararsi innocente.",
      summary:`<p>Fra il 1943 e il dopoguerra la storia entra violentemente nelle vite: caduta del fascismo, occupazione, guerra civile, Resistenza, deportazione e povertà trasformano il racconto in responsabilità. Gli autori vivono esperienze differenti: Calvino e Fenoglio conoscono la lotta partigiana; Vittorini interroga l’antifascismo; Pavese sperimenta lo scarto e la colpa; Primo Levi testimonia Auschwitz; Carlo Levi porta alla luce l’esclusione meridionale. Anche i registi giungono al nuovo cinema da traiettorie non pure e da condizioni produttive difficili. Fra 1945 e 1948 sembra nascere un “noi” narrante, ma guerra fredda e conflitti ideologici lo dividono. La biografia non causa meccanicamente l’opera: offre il contesto delle domande, mentre la forma decide come renderle conoscenza. Proprio per questo il Neorealismo non è autobiografia collettiva spontanea, ma scelta responsabile di un punto di vista.</p>`,
      essentials:["Ricostruire perché il 1943 trasforma la storia da fondale a scelta individuale e collettiva.","Confrontare le diverse esperienze di Calvino, Fenoglio, Vittorini, Pavese, Primo Levi e Carlo Levi.","Spiegare perché le difficoltà produttive del cinema favoriscono ma non determinano l’estetica neorealista.","Riconoscere continuità e conversioni nelle biografie di Rossellini, Visconti e De Sica.","Descrivere il passaggio dall’unità antifascista ai conflitti politici e culturali del dopoguerra.","Usare con precisione il nesso biografia-opera: l’esperienza rende intelligibile una domanda, non causa automaticamente una forma."],
      vocabulary:[["Armistizio","L’8 settembre 1943 disgrega lo Stato italiano e apre occupazione tedesca, Resistenza e guerra civile."],["Testimonianza","Racconto fondato sull’esperienza che assume responsabilità verso fatti, vittime e lettori."],["Determinismo biografico","Errore che deduce direttamente stile e valore di un’opera dagli eventi vissuti dall’autore."],["Resistenza","Insieme plurale di lotte militari, civili e politiche contro nazifascismo tra 1943 e 1945."],["Impegno","Assunzione di responsabilità pubblica dell’intellettuale, distinta dall’obbedienza a una linea politica."],["Normalizzazione","Ritorno a equilibri sociali e culturali che riduce la spinta trasformativa nata dalla Liberazione."]],
      map:{src:"assets/maps/02-fratture.svg",alt:"Mappa: il 1943 produce occupazione, Resistenza e deportazione; diverse vite di scrittori e registi generano domande differenti; il noi del dopoguerra si divide e la biografia diventa contesto, non causa dell’opera.",caption:"Le fratture non producono una formula: moltiplicano le responsabilità del racconto."},
      questions:[
        {prompt:"Che cosa cambia radicalmente nel 1943?",options:["Ogni scelta privata acquista anche peso politico","La letteratura smette di usare la finzione","Tutti gli intellettuali scelgono lo stesso partito"],correct:0,explanation:"Il crollo dello Stato e l’occupazione fanno entrare la storia nelle decisioni quotidiane.",anchor:"m2-1943",recovery:{concept:"La storia nelle vite",clarification:"La frattura trasforma anche l’attesa e la protezione di altri in scelte rischiose.",example:"Nascondersi, combattere o collaborare non sono più gesti neutrali.",check:"Perché la storia non può più restare un fondale?"}},
        {prompt:"Perché Calvino usa lo sguardo di un bambino nel Sentiero?",options:["Per eliminare la guerra dal romanzo","Per raccontare la Resistenza da un’angolazione laterale e non celebrativa","Per scrivere un libro soltanto per l’infanzia"],correct:1,explanation:"Pin permette di evitare l’eroismo convenzionale e mostrare contraddizioni e spaesamento.",anchor:"m2-vite",recovery:{concept:"Punto di vista laterale",clarification:"L’esperienza partigiana non obbliga a un racconto autobiografico frontale.",example:"La guerra è filtrata dagli occhi di Pin, escluso anche dal mondo degli adulti.",check:"Che cosa rende visibile uno sguardo non ufficiale?"}},
        {prompt:"Quale affermazione sul cinema neorealista è più precisa?",options:["Nasce solo perché mancano gli studi","È privo di sceneggiatura e montaggio","Le difficoltà materiali favoriscono scelte poi trasformate in forma"],correct:2,explanation:"La necessità economica conta, ma la qualità dipende dalla trasformazione consapevole in linguaggio.",anchor:"m2-cinema",recovery:{concept:"Necessità e forma",clarification:"Uscire dagli studi può essere obbligato; decidere come filmare la strada è una scelta estetica.",example:"Roma città aperta unisce condizioni difficili e forte costruzione drammatica.",check:"Perché una mancanza tecnica non produce da sola un capolavoro?"}},
        {prompt:"Che cosa accade al “noi” del primo dopoguerra?",options:["Si divide sotto la pressione di guerra fredda e conflitti ideologici","Resta compatto fino agli anni Sessanta","Esclude fin dall’inizio ogni speranza comune"],correct:0,explanation:"L’unità morale della Liberazione lascia emergere rapidamente progetti politici incompatibili.",anchor:"m2-dopoguerra",recovery:{concept:"Dal noi al conflitto",clarification:"La comunicazione condivisa non cancella le differenze sul futuro del paese.",example:"Il rapporto fra cultura, PCI e autonomia intellettuale diventa terreno di scontro.",check:"Quali trasformazioni rompono l’unità iniziale?"}},
        {prompt:"Qual è il rapporto corretto fra esperienza e opera?",options:["L’esperienza garantisce il valore letterario","L’esperienza apre domande che la forma deve organizzare","La biografia è irrilevante in ogni caso"],correct:1,explanation:"La biografia offre contesto e urgenza, ma voce e struttura trasformano l’esperienza in conoscenza.",anchor:"m2-nesso",recovery:{concept:"Biografia non deterministica",clarification:"Vivere un evento e saperlo raccontare sono azioni diverse.",example:"La deportazione fonda la testimonianza di Primo Levi, ma rigore e struttura ne costruiscono la forza.",check:"Quale lavoro compie la forma sull’esperienza?"}}
      ]
    },
    {
      id:"immagine", short:"L’immagine del mondo", kicker:"Chi entra nel quadro", title:"L’immagine del mondo", subtitle:"La realtà è quotidiana, plurale e attraversata dalla storia; guardarla significa prendere posizione", color:"#31545e",
      question:"Come appare la realtà dopo la frattura, e perché non può essere considerata un dato neutro che basta registrare?",
      lesson:`
        <h3 id="m3-basso">1. Vedere dal basso non significa idealizzare il basso</h3>
        <p>Il gesto più riconoscibile del Neorealismo è lo spostamento dell’inquadratura. Operai, contadini, disoccupati, donne, bambini, partigiani, reduci, deportati e abitanti delle periferie cessano di essere sfondo. La loro vita quotidiana diventa luogo in cui la storia mostra i propri effetti. In <em>Ladri di biciclette</em> la perdita di un oggetto minimo decide il diritto al lavoro e la dignità di una famiglia; in <em>Roma città aperta</em> scale, strade e cortili fanno dell’occupazione un’esperienza collettiva.</p>
        <p>Questo spostamento è democratico, ma contiene un rischio. Se il popolo viene dipinto come naturalmente buono, compatto e moralmente puro, la riparazione dell’esclusione diventa un nuovo stereotipo. La critica successiva parlerà di populismo. Le opere più forti non cancellano contraddizioni: il padre di <em>Ladri di biciclette</em>, vittima del furto, tenta a sua volta di rubare; i partigiani di Calvino e Fenoglio sono divisi, imperfetti, talvolta grotteschi. La dignità nasce dal riconoscimento della complessità, non dalla santificazione.</p>
        <h3 id="m3-quotidiano">2. Il quotidiano come struttura storica</h3>
        <p>Il Neorealismo scopre che un gesto ordinario può contenere un sistema. Cercare lavoro significa incontrare burocrazia, disoccupazione, mercato nero e solidarietà. Procurare il pane rende visibili distribuzione, povertà e ruoli familiari. Muoversi in città espone la geografia delle classi. Il quotidiano non è il contrario della grande storia: è il punto in cui la grande storia prende corpo.</p>
        <p>Zavattini radicalizza questa intuizione immaginando un cinema capace di seguire una persona per novanta minuti senza imporle un’avventura eccezionale. È un orizzonte teorico più che una regola rispettata alla lettera. I film neorealisti possiedono trame, conflitti, simboli; proprio per questo producono un’impressione di immediatezza. Il loro realismo non elimina la costruzione, ma riduce la distanza gerarchica fra evento degno e vita comune.</p>
        <h3 id="m3-italie">3. Le diverse Italie e la pluralità delle lingue</h3>
        <p>Calvino definirà il Neorealismo una molteplice scoperta delle diverse Italie. Il plurale è essenziale. Le Langhe di Pavese e Fenoglio non coincidono con la Sicilia di Vittorini, con la Lucania di Carlo Levi, con la Firenze di Pratolini o con le periferie romane del cinema. Dialetti, italiani regionali, gerghi di mestiere e cadenze orali entrano nella lingua nazionale, non come folklore decorativo ma come depositi di esperienza.</p>
        <p>La lingua popolare sullo schermo è tuttavia mediata. Molto cinema italiano del periodo viene postsincronizzato: le voci sono registrate in studio dagli stessi interpreti o da doppiatori. Anche quando l’effetto è naturale, il suono può essere costruito. Questa apparente contraddizione insegna qualcosa: realismo non significa identità materiale fra realtà e opera; significa produrre una relazione credibile e critica con il mondo.</p>
        <h3 id="m3-morale">4. La realtà come campo morale, non come fotografia</h3>
        <p>Il mondo neorealista è ferito, ma non privo di possibilità. La solidarietà convive con la lotta per la sopravvivenza; il desiderio di giustizia con la sconfitta; la costruzione democratica con permanenze autoritarie. Questa struttura aperta distingue il Neorealismo dal determinismo naturalista: l’ambiente condiziona duramente, ma l’azione umana conserva un margine etico e politico.</p>
        <p>Da qui deriva l’idea di impegno. L’arte non deve limitarsi a consolare né illustrare una tesi già pronta; deve rendere visibili problemi che il pubblico possa riconoscere e discutere. Vittorini insiste sulla necessità di una cultura capace di agire sulle sofferenze, non solo di piangerle. Rossellini parla di un film realistico come di un film che pone problemi. La verità non è una risposta consegnata dall’autore: è una domanda resa inevitabile dalla forma.</p>
        <h3 id="m3-sguardo">5. Nessuna innocenza dello sguardo</h3>
        <p>Ogni inquadratura include ed esclude. Ogni narratore decide a chi concedere interiorità, quale durata assegnare a un gesto, dove interrompere una storia. Il Neorealismo migliore diventa consapevole di questa responsabilità. Primo Levi adotta precisione e misura perché il Lager non sia trasformato in spettacolo; Calvino filtra la Resistenza attraverso Pin; Visconti compone immagini di enorme rigore figurativo pur usando pescatori e luoghi reali.</p>
        <p>L’immagine del mondo può allora essere formulata così: la realtà esiste, resiste alle nostre fantasie, ma non parla da sola. Occorre costruire dispositivi che la facciano vedere senza pretendere neutralità. Questa esigenza rende necessaria una poetica: scelte di lingua, punto di vista, montaggio e genere capaci di trasformare vicinanza in conoscenza. Lo spettatore non viene invitato soltanto a commuoversi, ma a riconoscere relazioni fra destini individuali e strutture collettive, senza che l’una dimensione cancelli l’altra.</p>`,
      bridge:"Se il reale non parla da solo, la poetica deve organizzare lo sguardo: semplicità apparente, coralità, lingue concrete, luoghi autentici e montaggio diventano strumenti di conoscenza.",
      summary:`<p>Il Neorealismo sposta l’inquadratura verso soggetti prima marginali e mostra la storia nei gesti quotidiani. Questo sguardo è democratico, ma diventa retorico quando idealizza il popolo. Le opere più forti conservano ambivalenze e conflitti. L’Italia appare plurale: Langhe, Sicilia, Lucania, Firenze e Roma portano lingue, memorie e strutture sociali diverse. Anche l’apparente naturalezza è costruita: il cinema usa spesso postsincronizzazione, sceneggiatura e montaggio. Il realismo non è dunque fotografia neutra, ma relazione critica con un mondo che resiste e deve essere interpretato. L’impegno consiste nel rendere i problemi visibili, non nell’imporre una risposta. Poiché ogni voce e inquadratura include ed esclude, lo sguardo assume una responsabilità morale. Da questa consapevolezza nasce la necessità di una poetica capace di trasformare vicinanza ai fatti in conoscenza.</p>`,
      essentials:["Spiegare in che senso il Neorealismo sposta l’inquadratura verso soggetti prima marginali.","Distinguere la dignità riconosciuta al popolo dalla sua idealizzazione populistica.","Mostrare come un gesto quotidiano possa rendere visibile un sistema storico e sociale.","Descrivere la pluralità geografica e linguistica delle “diverse Italie”.","Spiegare perché postsincronizzazione e montaggio non annullano necessariamente il realismo.","Formulare l’impegno come costruzione di problemi condivisi, non come illustrazione di una tesi.","Argomentare perché nessuno sguardo narrativo o cinematografico è innocente."],
      vocabulary:[["Sguardo dal basso","Scelta di assumere come centro soggetti e ambienti esclusi dalle rappresentazioni dominanti."],["Populismo","Idealizzazione del popolo come unità spontaneamente buona, che cancella differenze e contraddizioni."],["Quotidiano","Luogo concreto in cui strutture economiche, politiche e morali diventano esperienza vissuta."],["Italiano regionale","Varietà intermedia fra lingua nazionale e dialetto, segnata da lessico e cadenze locali."],["Postsincronizzazione","Registrazione o sostituzione in studio delle voci dopo le riprese cinematografiche."],["Impegno","Responsabilità pubblica della forma nel rendere visibili e discutibili i problemi del presente."],["Punto di vista","Posizione percettiva e morale da cui il racconto seleziona e organizza il mondo."]],
      map:{src:"assets/maps/03-immagine.svg",alt:"Mappa: lo sguardo dal basso rende protagonisti gli esclusi; il quotidiano rivela la storia; le diverse Italie portano pluralità linguistica; il rischio populista e la mediazione formale mostrano che nessuno sguardo è neutro.",caption:"Il reale resiste, ma non parla da solo: la responsabilità dello sguardo."},
      questions:[
        {prompt:"Che cosa significa davvero “vedere dal basso”?",options:["Dare centralità agli esclusi senza cancellarne le contraddizioni","Considerare il popolo sempre moralmente puro","Rifiutare ogni personaggio borghese"],correct:0,explanation:"Lo spostamento è democratico solo se non sostituisce un’esclusione con un’idealizzazione.",anchor:"m3-basso",recovery:{concept:"Centralità senza santificazione",clarification:"Riconoscere dignità significa concedere complessità, anche morale.",example:"Il protagonista di Ladri di biciclette è vittima e poi tenta un furto.",check:"Perché una contraddizione può rendere un personaggio più degno, non meno?"}},
        {prompt:"Perché il quotidiano è centrale?",options:["Perché elimina la grande storia","Perché rende visibili nei gesti le strutture sociali e storiche","Perché garantisce storie senza conflitto"],correct:1,explanation:"L’ordinario è il punto in cui lavoro, povertà, istituzioni e dignità diventano esperienza.",anchor:"m3-quotidiano",recovery:{concept:"Il sistema nel gesto",clarification:"Un oggetto o un’azione minima possono dipendere da strutture molto ampie.",example:"La bicicletta collega lavoro, sopravvivenza e dignità familiare.",check:"Quale sistema diventa visibile nella ricerca della bicicletta?"}},
        {prompt:"Che cosa dimostra la postsincronizzazione?",options:["Che i film non sono realistici","Che il dialetto è assente","Che anche l’effetto di naturalezza può essere costruito"],correct:2,explanation:"Il realismo è una relazione prodotta da forme, non l’assenza materiale di mediazione.",anchor:"m3-italie",recovery:{concept:"Autenticità mediata",clarification:"Una voce registrata dopo può contribuire a un mondo credibile se coerente con corpi e ambiente.",example:"Il cinema italiano del periodo registra spesso le voci in studio.",check:"Perché costruzione e verità non sono opposti automatici?"}},
        {prompt:"Qual è la funzione più rigorosa dell’impegno?",options:["Rendere inevitabili problemi che il pubblico deve affrontare","Fornire sempre una morale politica univoca","Sostituire la letteratura con il giornalismo"],correct:0,explanation:"L’opera impegnata apre conoscenza e discussione; la propaganda chiude il significato.",anchor:"m3-morale",recovery:{concept:"Impegno non propaganda",clarification:"Porre un problema lascia al pubblico un lavoro interpretativo.",example:"Rossellini concepisce il film realistico come film che pone problemi.",check:"Che differenza c’è fra una domanda resa visibile e una risposta imposta?"}},
        {prompt:"Perché nessuno sguardo è innocente?",options:["Perché ogni autore mente","Perché ogni forma seleziona, include ed esclude","Perché la realtà non esiste"],correct:1,explanation:"Il mondo esiste, ma narrarlo richiede decisioni di voce, durata, ordine e inquadratura.",anchor:"m3-sguardo",recovery:{concept:"Responsabilità della selezione",clarification:"Non possiamo mostrare tutto; dobbiamo rispondere di ciò che rendiamo centrale o marginale.",example:"Calvino sceglie Pin invece di un comandante esemplare.",check:"Quale effetto produce la scelta di un narratore bambino?"}}
      ]
    },
    {
      id:"poetica", short:"La poetica", kicker:"Costruire il vero", title:"La poetica", subtitle:"Lingua, punto di vista e montaggio producono un’impressione di verità senza cancellare l’autore", color:"#364f46",
      question:"Come si scrive e si filma una realtà comune senza trasformarla né in retorica né in documento inerte?",
      lesson:`
        <h3 id="m4-costellazione">1. Una poetica plurale, non un manifesto</h3>
        <p>Il Neorealismo non possiede un manifesto fondativo, un gruppo con regole d’ammissione o uno stile obbligatorio. È una costellazione riconosciuta a posteriori. Calvino parlerà di un insieme di voci e di una scoperta delle diverse Italie. Questa definizione impedisce di cercare un codice unico: la prosa simbolica di Vittorini, il paesaggio mitico di Pavese, l’esattezza testimoniale di Primo Levi, l’epica antieroica di Fenoglio e la leggerezza fiabesca del primo Calvino non si lasciano ridurre a una stessa superficie.</p>
        <p>Ciò che li avvicina è una tensione: diminuire la distanza fra letteratura e vita contemporanea, allargare il campo dei soggetti, restituire responsabilità pubblica alla forma. “Semplice” non significa ingenuo. Molti testi sembrano diretti perché hanno lavorato duramente per nascondere l’apparato, scegliere un lessico concreto e organizzare il ritmo.</p>
        <h3 id="m4-prosa">2. La prosa: oralità, montaggio e punto di vista</h3>
        <p>La narrativa neorealista privilegia spesso periodi meno solenni, dialoghi rapidi, lessico materiale, contaminazioni con dialetti e gerghi. L’oralità non viene trascritta fotograficamente: è selezionata e trasformata in ritmo letterario. Pratolini costruisce voci corali di quartiere; Fenoglio mescola italiano, parole piemontesi e una sintassi nutrita di inglese; Vittorini alterna dialoghi essenziali, ripetizioni e accensioni simboliche. Perfino entro la comune ricerca di realtà agiscono forme molto diverse.</p>
        <p>Il punto di vista diventa decisivo. <em>Il sentiero dei nidi di ragno</em> affida la guerra a Pin, che non comprende pienamente gli adulti e proprio per questo ne rivela le incoerenze. In <em>Se questo è un uomo</em> il testimone non pretende onniscienza: distingue ciò che ha visto, ciò che ricostruisce e ciò che non può sapere. Il montaggio di episodi, memorie e scene sostituisce spesso il grande romanzo totalizzante. La realtà appare frammentaria perché è stata vissuta come frattura.</p>
        <h3 id="m4-cinema">3. Il cinema: luoghi, corpi e durata</h3>
        <p>Nel cinema alcuni tratti diventano emblematici: riprese prevalenti in ambienti reali, attenzione alla strada, mescolanza di attori professionisti e non professionisti, luce capace di conservare l’asprezza dei luoghi, storie centrate su persone comuni. Tuttavia non sono comandamenti. <em>Roma città aperta</em> usa star popolari; <em>Ladri di biciclette</em> è sorretto da una sceneggiatura accuratissima; <em>La terra trema</em> combina pescatori di Aci Trezza, dialetto e composizioni visive di grande controllo.</p>
        <p>La macchina da presa tende a rispettare la continuità degli spazi e la durata delle azioni, lasciando che lo spettatore esplori l’immagine. Ma il montaggio resta interpretazione. La Roma di De Sica non è una mappa neutra: il percorso di Antonio e Bruno collega uffici, mercati, chiese, ristoranti e periferie, facendo della città un sistema sociale. Anche il suono, spesso postsincronizzato, costruisce un parlato credibile. L’effetto documentario è un risultato estetico, non una rinuncia all’estetica.</p>
        <h3 id="m4-generi">4. Contaminare cronaca, memoria, romanzo e fiaba</h3>
        <p>Il confine fra generi si fa mobile. Memorialistica e letteratura si incontrano in Primo Levi; saggio antropologico, autobiografia e romanzo convivono in Carlo Levi; cronaca resistenziale e invenzione si intrecciano in Fenoglio e Calvino. Nel cinema, Rossellini costruisce <em>Paisà</em> come sei episodi lungo la risalita alleata dell’Italia, unendo finzione e impressione documentaria; De Sica e Zavattini inseriscono perfino il miracolo e la fiaba in <em>Miracolo a Milano</em>.</p>
        <p>Questa contaminazione smentisce l’idea di un Neorealismo ostile all’immaginazione. La finzione non è evasione per natura: può diventare una lente che rende il reale più leggibile. Il bambino di Calvino, il montaggio episodico di Rossellini, il simbolismo di Vittorini non allontanano necessariamente dai fatti; impediscono che i fatti siano scambiati per una spiegazione già compiuta.</p>
        <h3 id="m4-limiti">5. Quando la poetica diventa formula</h3>
        <p>Ogni innovazione rischia di trasformarsi in repertorio: bambino povero, strada dissestata, dialetto, finale amaro. Se questi segni vengono ripetuti senza necessità, il realismo diventa maniera. Anche l’impegno può irrigidirsi: personaggi ridotti a tipi positivi o negativi, tesi politica che precede l’esperienza, popolo idealizzato. La crisi del Neorealismo comincia quando i suoi mezzi sono riconoscibili prima ancora del problema che dovrebbero esplorare.</p>
        <p>La poetica più feconda non consiste quindi in “fare come” Rossellini o De Sica, ma in una domanda metodologica: quale forma permette oggi di vedere ciò che le immagini dominanti escludono? Le opere decisive sono quelle che mettono alla prova il metodo e ne mostrano anche le contraddizioni. Per questo la verifica non può fermarsi all’elenco dei tratti: deve osservare come ciascuna opera li combina, li deforma o perfino li rifiuta per restare fedele al proprio problema.</p>`,
      bridge:"La pluralità delle forme va verificata nelle opere: ciascun testo o film riuscito trasforma il realismo in una soluzione singolare, non nell’applicazione di una ricetta.",
      summary:`<p>Il Neorealismo è una costellazione senza manifesto. Lo uniscono riduzione della distanza fra arte e vita, centralità di soggetti comuni e responsabilità pubblica; lo dividono le soluzioni formali. La prosa usa oralità costruita, dialetti, montaggio episodico e punti di vista limitati. Il cinema privilegia luoghi reali, corpi non divistici e continuità spaziale, ma conserva sceneggiatura, montaggio e frequente postsincronizzazione. Cronaca, memoria, romanzo, saggio e fiaba si contaminano: la finzione può aumentare, non diminuire, la comprensione del reale. Il pericolo nasce quando strada, povertà e dialetto diventano segni automatici di autenticità o quando l’impegno si riduce a tesi. La poetica neorealista resta viva non come repertorio stilistico, ma come domanda: quale forma rende visibile oggi ciò che il racconto dominante lascia fuori?</p>`,
      essentials:["Spiegare perché il Neorealismo è una costellazione e non una scuola dotata di manifesto.","Descrivere come l’oralità venga costruita letterariamente invece di essere trascritta in modo neutro.","Analizzare la funzione del punto di vista limitato in Calvino e della testimonianza sorvegliata in Primo Levi.","Distinguere i tratti ricorrenti del cinema neorealista da regole rigide.","Spiegare come sceneggiatura, montaggio e postsincronizzazione possano produrre un effetto realistico.","Riconoscere la contaminazione fra cronaca, memoria, romanzo, saggio e fiaba.","Individuare il passaggio dalla poetica alla maniera quando i segni del realismo diventano automatici."],
      vocabulary:[["Costellazione","Insieme di autori e opere vicini per tensioni, ma privi di un’unica dottrina o forma."],["Oralità costruita","Effetto di parlato ottenuto tramite selezione lessicale, ritmo e sintassi, non trascrizione meccanica."],["Coralità","Organizzazione narrativa che distribuisce il racconto fra molte voci e destini."],["Montaggio","Scelta dell’ordine e della durata di scene o episodi, capace di produrre interpretazione."],["Attore non professionista","Interprete scelto anche per corpo, volto e relazione con un ambiente, non garanzia automatica di autenticità."],["Ibridazione","Contaminazione di generi, registri e codici differenti."],["Maniera","Ripetizione esteriore di segni stilistici separati dalla necessità conoscitiva che li aveva generati."]],
      map:{src:"assets/maps/04-poetica.svg",alt:"Mappa: una costellazione senza manifesto si traduce in oralità costruita, punti di vista limitati, luoghi reali, montaggio e ibridazione dei generi; quando questi strumenti diventano automatici producono maniera.",caption:"La semplicità è un effetto: gli strumenti con cui il vero viene costruito."},
      questions:[
        {prompt:"Perché il Neorealismo non è una scuola in senso stretto?",options:["Non possiede manifesto e stile obbligatorio","Non ha autori riconoscibili","Rifiuta ogni confronto critico"],correct:0,explanation:"È un insieme di voci legate da tensioni morali, ma formalmente molto diverse.",anchor:"m4-costellazione",recovery:{concept:"Costellazione",clarification:"La vicinanza non richiede uniformità.",example:"Vittorini simbolico e Primo Levi analitico condividono responsabilità verso il reale senza scrivere allo stesso modo.",check:"Quale elemento comune può esistere senza uno stile unico?"}},
        {prompt:"Che cosa rende efficace il punto di vista di Pin?",options:["La piena comprensione politica degli eventi","La visione limitata che smonta l’eroismo convenzionale","L’assenza di immaginazione"],correct:1,explanation:"Il limite percettivo del bambino rivela spaesamento e contraddizioni degli adulti.",anchor:"m4-prosa",recovery:{concept:"Punto di vista limitato",clarification:"Sapere meno può far vedere ciò che la voce ufficiale nasconde.",example:"Pin osserva i partigiani senza riconoscerli come figure monumentali.",check:"Che cosa perde e che cosa guadagna il racconto?"}},
        {prompt:"Quale coppia descrive meglio La terra trema?",options:["Studio artificiale e lingua aulica","Improvvisazione totale e assenza di composizione","Pescatori e luoghi reali dentro immagini fortemente controllate"],correct:2,explanation:"Visconti unisce materiali autentici e rigore figurativo, mostrando che realismo e stile convivono.",anchor:"m4-cinema",recovery:{concept:"Materiale reale, forma autoriale",clarification:"L’autenticità dei corpi non elimina l’organizzazione dell’immagine.",example:"I pescatori di Aci Trezza sono inscritti in composizioni visive elaborate.",check:"Perché il controllo formale non annulla il legame col luogo?"}},
        {prompt:"Che cosa dimostra la presenza della fiaba?",options:["Che l’immaginazione può rendere leggibile il reale","Che il Neorealismo abbandona sempre la storia","Che cronaca e finzione sono incompatibili"],correct:0,explanation:"La finzione può impedire che il fatto venga scambiato per una spiegazione autosufficiente.",anchor:"m4-generi",recovery:{concept:"Finzione conoscitiva",clarification:"Inventare non equivale a fuggire; può isolare un conflitto reale.",example:"Miracolo a Milano usa il fantastico dentro la povertà urbana.",check:"Quale realtà viene resa più visibile grazie all’invenzione?"}},
        {prompt:"Quando una poetica diventa maniera?",options:["Quando cambia nel tempo","Quando ripete segni riconoscibili senza necessità conoscitiva","Quando utilizza attori professionisti"],correct:1,explanation:"La formula nasce quando strada, povertà o dialetto precedono il problema invece di servirlo.",anchor:"m4-limiti",recovery:{concept:"Dal metodo alla formula",clarification:"Uno strumento è vivo se risponde a una domanda precisa.",example:"Un bambino povero inserito solo per sembrare autentici è un cliché.",check:"Quale domanda dovrebbe venire prima della scelta stilistica?"}}
      ]
    },
    {
      id:"opere", short:"Le opere", kicker:"Il banco di prova", title:"Le opere più significative", subtitle:"Sei opere per vedere come una tensione comune diventa ogni volta una forma diversa", color:"#4f4840",
      question:"Dove la poetica neorealista diventa forma concreta, e quali contraddizioni emergono quando la osserviamo nelle singole opere?",
      lesson:`
        <h3 id="m5-roma">1. Roma città aperta: la comunità sotto occupazione</h3>
        <p>Girato da Roberto Rossellini nel 1945, quando la guerra continua nel Nord, <em>Roma città aperta</em> trasforma la capitale in personaggio collettivo. La vicenda intreccia resistenti, popolani, bambini e sacerdote; Anna Magnani e Aldo Fabrizi portano nel film corpi e voci già popolari. La celebre morte di Pina spezza bruscamente l’attesa narrativa: la violenza irrompe nella strada e rende lo spettatore parte di una comunità ferita.</p>
        <p>Il film non è documento grezzo. Condensa figure reali, costruisce un conflitto melodrammatico e usa attori professionisti. Proprio questa mescolanza gli consente di dare all’occupazione la forza della cronaca e della tragedia. La verità non coincide con la precisione di ogni dettaglio, ma con la capacità di rendere percepibile una condizione storica.</p>
        <h3 id="m5-ladri">2. Ladri di biciclette: il sistema dentro un oggetto</h3>
        <p>Nel film di Vittorio De Sica e Cesare Zavattini (1948), Antonio ottiene un lavoro che richiede una bicicletta; quando gli viene rubata, attraversa Roma con il figlio Bruno per ritrovarla. La trama sembra minima, ma l’oggetto lega lavoro, reddito, autorità paterna e dignità. La città appare come una rete di istituzioni insufficienti e di poveri messi in concorrenza fra loro.</p>
        <p>Il finale evita sia il lieto fine sia la condanna astratta. Antonio tenta di rubare una bicicletta; viene fermato e umiliato davanti a Bruno. Padre e figlio si perdono nella folla tenendosi per mano. La vittima è diventata colpevole senza cessare di essere vittima. Questa ambivalenza è una delle confutazioni più forti del populismo: la povertà non nobilita automaticamente, ma mette alla prova i legami.</p>
        <h3 id="m5-calvino">3. Il sentiero dei nidi di ragno: la Resistenza di scorcio</h3>
        <p>Il primo romanzo di Italo Calvino, pubblicato nel 1947, racconta la guerra partigiana attraverso Pin, bambino marginale che ruba una pistola a un soldato tedesco e cerca un luogo di appartenenza. La prospettiva infantile trasforma armi, boschi e adulti in un mondo insieme concreto e fiabesco. Calvino non sceglie i partigiani più esemplari, ma un distaccamento sgangherato: vuole sottrarre la Resistenza alla retorica senza negarne il valore storico.</p>
        <p>Nella prefazione del 1964 l’autore leggerà quel libro come prodotto di una tensione collettiva e definirà il Neorealismo non una scuola, ma una pluralità di voci. La distanza temporale gli permette di riconoscere entusiasmo e limiti. Il romanzo mostra già che il realismo può aver bisogno della fiaba e che la verità politica non richiede personaggi perfetti.</p>
        <h3 id="m5-levi">4. Se questo è un uomo: testimoniare senza appropriarsi</h3>
        <p>Pubblicato nel 1947 da una piccola casa editrice e accolto inizialmente con attenzione limitata, il libro di Primo Levi racconta la deportazione e Auschwitz attraverso una prosa precisa, controllata, capace di analizzare la distruzione sistematica dell’umano. Non offre il Lager come caos indicibile né come spettacolo dell’orrore: osserva gerarchie, fame, lingua, lavoro, memoria e degradazione.</p>
        <p>La misura è una scelta etica. Levi distingue episodi, sospende giudizi facili, interroga la “zona grigia” prima ancora di nominarla così nelle opere successive. L’apertura rivolta al lettore trasforma la memoria in responsabilità presente. Inserirlo nel quadro neorealista è utile se non lo si riduce a un’etichetta: la sua testimonianza possiede un rigore e una traiettoria specifici.</p>
        <h3 id="m5-pavese">5. La luna e i falò: il ritorno impossibile</h3>
        <p>Nel romanzo di Cesare Pavese (1950), Anguilla torna dall’America nelle Langhe per cercare le proprie origini. Il paesaggio non è semplice documento rurale: è memoria, mito e misura del tempo. Le trasformazioni storiche, il fascismo e la Resistenza emergono attraverso racconti, assenze e violenze che hanno segnato la comunità. Tornare non ricompone l’identità.</p>
        <p>Quest’opera mette in crisi il confine dell’etichetta neorealista. Il mondo contadino è concreto, ma attraversato da simboli; la storia è presente, ma non assorbe la solitudine esistenziale. Proprio questa eccedenza mostra che gli autori più importanti non coincidono con una corrente: usano una tensione comune per costruire mondi irriducibili.</p>
        <h3 id="m5-fenoglio">6. Una questione privata: l’epica senza monumento</h3>
        <p>Pubblicato postumo nel 1963, il romanzo breve di Beppe Fenoglio segue il partigiano Milton, ossessionato dal dubbio su Fulvia e Giorgio, mentre attraversa le Langhe in guerra. La missione privata si intreccia con la Resistenza senza subordinarsi a un messaggio edificante. Pioggia, fango, corsa e inseguimento danno alla storia una tensione quasi cavalleresca.</p>
        <p>Calvino lo considerò il romanzo sulla Resistenza che la sua generazione aveva cercato: un’opera capace di conservare verità storica e necessità narrativa. La pubblicazione tarda indica anche che il Neorealismo non si chiude in una data: alcune sue domande maturano oltre la stagione propriamente detta. Il lascito non è una galleria di titoli, ma la scoperta che la realtà diventa universale quando una forma singolare ne assume le contraddizioni.</p>`,
      bridge:"Dalle opere resta un metodo critico, ma anche la prova dei suoi limiti: il Neorealismo finisce come stagione quando il repertorio non basta più a interpretare la modernizzazione italiana.",
      summary:`<p>Le opere mostrano che non esiste una formula neorealista. <em>Roma città aperta</em> unisce cronaca, tragedia e attori popolari; <em>Ladri di biciclette</em> concentra un sistema sociale in un oggetto e rifiuta la purezza morale della vittima; <em>Il sentiero dei nidi di ragno</em> guarda la Resistenza attraverso un bambino e la contamina con la fiaba; <em>Se questo è un uomo</em> trasforma la testimonianza in analisi etica sorvegliata; <em>La luna e i falò</em> intreccia storia, memoria e mito; <em>Una questione privata</em> costruisce un’epica partigiana attraversata da un’ossessione personale. In ciascun caso il reale è mediato da una soluzione formale irripetibile. Le etichette aiutano a vedere relazioni storiche, ma diventano false quando assorbono l’autonomia delle opere e riducono la differenza a semplice esempio scolastico.</p>`,
      essentials:["Analizzare come Roma città aperta trasformi una città e una comunità in soggetto storico.","Spiegare la funzione narrativa e sociale della bicicletta nel film di De Sica.","Mostrare come il punto di vista di Pin combatta la retorica senza negare la Resistenza.","Descrivere il rapporto fra precisione, testimonianza ed etica in Primo Levi.","Spiegare perché paesaggio e mito rendono La luna e i falò eccedente rispetto al realismo documentario.","Analizzare l’intreccio fra questione privata ed epica resistenziale in Fenoglio.","Argomentare perché le opere verificano e insieme mettono in crisi l’etichetta Neorealismo."],
      vocabulary:[["Opera-mondo","Testo o film che organizza una realtà storica attraverso un sistema formale autonomo."],["Ambivalenza","Coesistenza di significati morali o emotivi opposti che impedisce giudizi semplicistici."],["Testimonianza sorvegliata","Racconto dell’esperienza fondato su precisione, distinzione dei piani e responsabilità verso il lettore."],["Fiabesco","Trasformazione percettiva che convive con il reale e ne rende visibili strutture nascoste."],["Paesaggio mitico","Luogo concreto caricato di memoria, ripetizione e significato simbolico."],["Antieroico","Modo di rappresentare il conflitto attraverso figure imperfette, senza cancellarne il valore storico."],["Eccedenza","Ciò che in un’opera supera l’etichetta critica usata per classificarla."]],
      map:{src:"assets/maps/05-opere.svg",alt:"Mappa: Roma città aperta costruisce la comunità; Ladri di biciclette concentra il sistema in un oggetto; Calvino usa lo sguardo infantile; Primo Levi la precisione; Pavese il mito; Fenoglio l’epica privata; tutte le opere superano la formula.",caption:"Sei opere, sei forme: il reale diventa conoscenza solo quando trova una soluzione singolare."},
      questions:[
        {prompt:"Che cosa rende Roma città aperta più di un documento grezzo?",options:["La costruzione che unisce cronaca, tragedia e comunità","L’assenza completa di attori professionisti","La fedeltà letterale a un unico episodio reale"],correct:0,explanation:"Rossellini condensa e organizza materiali storici per rendere percepibile una condizione collettiva.",anchor:"m5-roma",recovery:{concept:"Cronaca costruita",clarification:"L’impressione di immediatezza nasce da una forma drammatica.",example:"Pina è personaggio di finzione e figura collettiva della Roma occupata.",check:"Quale verità produce la condensazione narrativa?"}},
        {prompt:"Che cosa rivela il tentato furto finale di Antonio?",options:["Che Antonio era colpevole dall’inizio","Che vittima e colpevole possono coincidere sotto la pressione sociale","Che Bruno approva il gesto"],correct:1,explanation:"Il finale conserva responsabilità individuale e condizionamento sociale senza semplificarli.",anchor:"m5-ladri",recovery:{concept:"Ambivalenza morale",clarification:"La povertà spiega la pressione, ma non cancella la ferita del gesto.",example:"Antonio subisce un furto e poi tenta di ripeterlo davanti al figlio.",check:"Perché il film non assolve né condanna astrattamente?"}},
        {prompt:"Perché Pin è decisivo nel romanzo di Calvino?",options:["È il capo politico del distaccamento","Conosce la verità completa degli adulti","Fa vedere la Resistenza di scorcio, fra realtà e fiaba"],correct:2,explanation:"Il suo sguardo marginale impedisce la monumentalizzazione e conserva lo spaesamento.",anchor:"m5-calvino",recovery:{concept:"Resistenza di scorcio",clarification:"La prospettiva infantile non nega la storia; la sottrae alla posa ufficiale.",example:"Il distaccamento appare umano, imperfetto e lontano dall’iconografia eroica.",check:"Che cosa guadagna il racconto rinunciando all’eroe esemplare?"}},
        {prompt:"Qual è la funzione della precisione in Se questo è un uomo?",options:["Evitare spettacolarizzazione e analizzare la disumanizzazione","Dimostrare che tutto può essere spiegato facilmente","Eliminare il coinvolgimento del lettore"],correct:0,explanation:"La misura è una scelta etica che trasforma la memoria in conoscenza e responsabilità.",anchor:"m5-levi",recovery:{concept:"Precisione etica",clarification:"Descrivere con rigore protegge i fatti dall’enfasi e dall’appropriazione.",example:"Levi analizza fame, gerarchie e lingua invece di accumulare immagini d’orrore.",check:"Perché la sobrietà può essere più potente dell’enfasi?"}},
        {prompt:"Che cosa accomuna Pavese e Fenoglio in queste opere?",options:["L’uso dello stesso narratore","Il superamento della cronaca mediante una forma personale","L’eliminazione della Resistenza"],correct:1,explanation:"Pavese usa memoria e mito; Fenoglio un’epica privata. Entrambi eccedono il documentario.",anchor:"m5-pavese",recovery:{concept:"Oltre l’etichetta",clarification:"Un tema storico non determina la forma con cui viene conosciuto.",example:"Le Langhe sono paesaggio mitico in Pavese e spazio d’inseguimento cavalleresco in Fenoglio.",check:"Quale diversa funzione assume lo stesso territorio?"}}
      ]
    },
    {
      id:"conclusione", short:"Conclusione", kicker:"Dopo il Neorealismo", title:"Conclusione", subtitle:"La stagione finisce; la responsabilità dello sguardo resta", color:"#5b342c",
      question:"Che cosa resta vivo del Neorealismo quando il suo repertorio storico non basta più a leggere l’Italia del boom?",
      lesson:`
        <h3 id="m6-fine">1. Una fine senza data unica</h3>
        <p>Il Neorealismo non termina in un giorno. Nel cinema la sua fase propulsiva si concentra fra <em>Roma città aperta</em> (1945) e i primi anni Cinquanta; in letteratura temi e forme resistono più a lungo e producono opere decisive anche fuori dal decennio. Le date 1953 o 1956 sono soglie utili, non cancelli. Indicano il mutamento del contesto: ricostruzione avanzata, guerra fredda, nuove industrie culturali, avvio del boom economico.</p>
        <p>Il paese delle macerie diventa il paese dei consumi, delle migrazioni interne, della televisione e dell’urbanizzazione. Per raccontarlo non basta ripetere partigiani, borgate e bambini poveri. Antonioni studia incomunicabilità e borghesia; Fellini trasforma memoria e spettacolo; Pasolini osserva la mutazione antropologica; Calvino usa fiaba, allegoria e poi strutture combinatorie. Non tradiscono necessariamente il reale: cercano forme adeguate a un reale mutato.</p>
        <h3 id="m6-crisi">2. Le ragioni interne della crisi</h3>
        <p>La crisi non dipende soltanto dalla società. Il Neorealismo porta in sé tensioni insolute. Vuole dare voce al popolo, ma rischia di parlare al suo posto. Cerca immediatezza, ma vive di costruzioni complesse. Rivendica impegno, ma può scivolare nella propaganda. Celebra la comunicazione fra scrittore e pubblico, ma le diverse Italie non formano una coscienza unica.</p>
        <p>La critica di populismo, formulata con durezza da Alberto Asor Rosa negli anni Sessanta, colpisce l’idealizzazione degli umili e la funzione conciliatoria di molta letteratura. La critica è utile, purché non cancelli le differenze fra opere. <em>Ladri di biciclette</em>, Fenoglio e Primo Levi, per esempio, complicano proprio l’immagine di un popolo innocente. Una corrente va giudicata attraverso i suoi capolavori e i suoi fallimenti, non come blocco uniforme.</p>
        <h3 id="m6-eredita">3. L’eredità estetica</h3>
        <p>Il cinema mondiale eredita la libertà di portare la macchina da presa nei luoghi reali, lavorare con attori non professionisti, costruire drammi su eventi quotidiani e mescolare documentario e finzione. Le nuove onde europee, diversi cinema postcoloniali e molte forme contemporanee di cinema sociale riconoscono nel Neorealismo un precedente. Non copiano soltanto l’immagine povera: assumono il diritto di produrre cinema fuori dai codici industriali dominanti.</p>
        <p>La letteratura eredita una lingua più porosa verso parlate, mestieri e territori, insieme alla legittimità di memorialistica, testimonianza e racconto civile. Ma l’eredità più profonda è forse negativa: dopo il Neorealismo diventa difficile credere che alcuni soggetti siano indegni di arte alta. La gerarchia fra vita eccezionale e vita comune è stata spezzata.</p>
        <h3 id="m6-etica">4. L’eredità etica e il suo pericolo</h3>
        <p>Resta l’idea che scegliere un soggetto, una voce e un’inquadratura sia un atto pubblico. L’artista non è obbligato a illustrare un programma politico, ma non può fingere che le forme siano innocenti. Chi viene mostrato? Chi resta senza parola? Quale sofferenza diventa spettacolo? Quale conflitto viene addolcito? Sono domande neorealiste ancora attuali.</p>
        <p>Proprio l’attualità contiene un pericolo: chiamare “neorealista” ogni opera su povertà, periferie o criminalità. L’etichetta diventa marketing morale se l’immagine dei marginali serve a rassicurare chi guarda. La fedeltà al Neorealismo non consiste nel ripetere i suoi soggetti, ma nel conservare la sua inquietudine critica verso le rappresentazioni dominanti.</p>
        <h3 id="m6-oggi">5. La domanda che resta</h3>
        <p>Oggi viviamo immersi in immagini prodotte e selezionate da piattaforme, pubblicità, informazione continua e algoritmi. La quantità del visibile è enorme, ma visibilità non significa conoscenza. Anche noi possediamo “telefoni bianchi” aggiornati: superfici levigate che organizzano desideri, successo, dolore e paura. Il problema neorealista ritorna in forma nuova: come bucare l’immagine amministrata?</p>
        <p>La traiettoria può essere ricomposta. Il mondo precedente controlla o separa la rappresentazione; guerra e Resistenza rendono quei linguaggi insufficienti; nasce un’immagine plurale e quotidiana della realtà; una poetica di lingue concrete, luoghi e punti di vista la costruisce; le opere migliori trasformano la tensione in forme singolari; la crisi dimostra che nessuna forma resta vera per decreto.</p>
        <blockquote>Domanda conclusiva: un’opera è realista perché assomiglia al mondo, o perché modifica ciò che siamo capaci di vedere nel mondo?</blockquote>
        <p>La seconda risposta è più esigente. Assomigliare può ridursi a imitazione; modificare lo sguardo richiede scelta, rischio e responsabilità. È questo, a mio giudizio, il lascito non consumato del Neorealismo. Non una nostalgia del bianco e nero, ma un esercizio permanente di sospetto verso ciò che una società presenta come naturale, inevitabile o indegno di attenzione. E anche una disciplina: verificare sempre se la nostra compassione produce comprensione oppure soltanto una breve soddisfazione morale.</p>`,
      bridge:"Il percorso torna all’inizio: ogni epoca produce immagini dominanti e ogni realismo vivo deve nuovamente scoprire ciò che esse lasciano fuori.",
      summary:`<p>Il Neorealismo termina gradualmente quando l’Italia delle macerie lascia posto a boom, televisione, urbanizzazione e nuovi conflitti. La crisi è anche interna: dare voce può diventare parlare al posto degli altri; l’impegno propaganda; l’autenticità formula. Tuttavia l’eredità è enorme. Cinema e letteratura acquisiscono luoghi reali, attori non professionisti, lingue porose, ibridazione tra documento e finzione, dignità artistica della vita comune. Resta soprattutto una responsabilità: ogni forma seleziona il visibile. Ripetere oggi povertà e periferie non basta; può diventare marketing morale. Essere fedeli alla domanda neorealista significa interrogare le immagini dominanti del proprio tempo, anche quelle prodotte dalle piattaforme. Il realismo più vivo non è quello che somiglia superficialmente al mondo, ma quello che modifica ciò che siamo capaci di vedere e discutere.</p>`,
      essentials:["Spiegare perché la fine del Neorealismo è una transizione e non una data assoluta.","Collegare la crisi della corrente alla trasformazione economica e mediatica dell’Italia.","Individuare le contraddizioni interne fra voce e appropriazione, immediatezza e costruzione, impegno e propaganda.","Descrivere almeno tre eredità estetiche nel cinema e nella letteratura.","Formulare l’eredità etica come responsabilità di ciò che la forma include ed esclude.","Distinguere la ripetizione dei soggetti neorealisti dalla fedeltà al suo metodo critico.","Ricostruire l’intera catena dai linguaggi ricevuti alla domanda contemporanea sul visibile."],
      vocabulary:[["Boom economico","Rapida trasformazione industriale e dei consumi fra anni Cinquanta e Sessanta, che modifica i problemi da rappresentare."],["Populismo letterario","Rappresentazione idealizzante del popolo che può cancellarne conflitti e autonomia."],["Eredità estetica","Insieme di possibilità formali rese disponibili alle opere successive."],["Eredità etica","Responsabilità verso soggetti, pubblico e conseguenze della rappresentazione."],["Cinema sociale","Cinema che interroga conflitti e condizioni collettive; non è neorealista automaticamente."],["Immagine dominante","Rappresentazione resa normale da poteri politici, economici o mediali."],["Realismo critico","Forma che non si limita a somigliare al mondo, ma rende leggibili relazioni nascoste e contraddizioni."]],
      map:{src:"assets/maps/06-conclusione.svg",alt:"Mappa: boom e nuovi media mettono in crisi il repertorio neorealista; i limiti sono populismo e propaganda; le eredità sono luoghi reali, lingue plurali e responsabilità dello sguardo; oggi il metodo interroga le immagini dominanti.",caption:"La stagione finisce, il problema ricomincia: rendere visibile ciò che ogni epoca lascia fuori."},
      questions:[
        {prompt:"Perché non esiste una data assoluta di fine?",options:["Cinema, letteratura e singoli autori cambiano con tempi diversi","Il Neorealismo è ancora identico oggi","Non esistono trasformazioni negli anni Cinquanta"],correct:0,explanation:"Le soglie cronologiche indicano mutamenti, ma temi e forme hanno durate non coincidenti.",anchor:"m6-fine",recovery:{concept:"Fine come transizione",clarification:"Una corrente perde centralità gradualmente e in modo diseguale.",example:"Il cinema cambia nei primi Cinquanta, mentre Fenoglio pubblica opere decisive più tardi.",check:"Perché una soglia è utile senza essere un cancello?"}},
        {prompt:"Quale contraddizione è interna al Neorealismo?",options:["Rifiuta sempre la realtà","Dare voce può trasformarsi nel parlare al posto degli altri","Non usa mai forme complesse"],correct:1,explanation:"L’intenzione democratica non garantisce che i soggetti rappresentati conservino autonomia.",anchor:"m6-crisi",recovery:{concept:"Voce e appropriazione",clarification:"Rappresentare qualcuno significa assumere potere sulla sua immagine.",example:"Il popolo idealizzato può diventare figura costruita dall’intellettuale.",check:"Come si evita che la solidarietà cancelli le differenze?"}},
        {prompt:"Qual è un’eredità estetica decisiva?",options:["L’obbligo del bianco e nero","Il divieto di usare attori professionisti","La dignità narrativa della vita comune e dei luoghi reali"],correct:2,explanation:"Il Neorealismo amplia ciò che può sostenere un’opera e libera il cinema da gerarchie di soggetti e ambienti.",anchor:"m6-eredita",recovery:{concept:"Ampliamento del narrabile",clarification:"La vita ordinaria non è più materia minore.",example:"Una ricerca di bicicletta può diventare tragedia moderna.",check:"Quale gerarchia artistica viene spezzata?"}},
        {prompt:"Che cosa significa fedeltà contemporanea al Neorealismo?",options:["Interrogare le rappresentazioni dominanti del proprio tempo","Girare sempre in periferia","Ripetere trame resistenziali"],correct:0,explanation:"Il metodo critico conta più del repertorio storico dei soggetti.",anchor:"m6-etica",recovery:{concept:"Metodo, non costume",clarification:"Copiare i segni esterni può trasformare il realismo in marketing.",example:"Mostrare marginalità senza interrogarne la rappresentazione può rassicurare il pubblico.",check:"Quale domanda dovrebbe guidare la scelta del soggetto?"}},
        {prompt:"Quale definizione conclusiva di realismo è più esigente?",options:["Perfetta somiglianza visiva","Modificazione di ciò che sappiamo vedere nel mondo","Assenza totale di invenzione"],correct:1,explanation:"Il realismo critico rende visibili relazioni prima escluse o naturalizzate.",anchor:"m6-oggi",recovery:{concept:"Realismo come conoscenza",clarification:"Somigliare può restare superficiale; vedere diversamente modifica il giudizio.",example:"La bicicletta di De Sica diventa una struttura sociale, non soltanto un oggetto fedele.",check:"Che cosa aggiunge un’opera alla semplice registrazione?"}}
      ]
    }
  ],
  final:{
    color:"#7b2f2a",
    map:{src:"assets/maps/07-sintesi.svg"},
    questions:[
      {prompt:"Quale limite del mondo precedente prepara il Neorealismo?",options:["L’insufficienza di molte forme nel dire la catastrofe presente","L’assenza completa di tradizioni realistiche","La scomparsa dell’industria culturale"],correct:0,explanation:"Il nuovo nasce dalla crisi di forme ricevute, non da un vuoto assoluto.",anchor:"m1-tensione",recovery:{concept:"Dal mondo alla frattura",clarification:"Anticipazioni e tradizioni esistono, ma devono essere riorganizzate dopo il 1943.",example:"Verga e la narrativa americana forniscono strumenti, non la risposta già pronta.",check:"Quale esperienza rende urgente il cambiamento?"}},
      {prompt:"Che cosa produce la frattura biografica e storica?",options:["Uno stile identico per tutti","Domande comuni organizzate da forme differenti","La garanzia automatica del valore artistico"],correct:1,explanation:"Guerra e Resistenza aprono urgenze; ogni autore le trasforma diversamente.",anchor:"m2-nesso",recovery:{concept:"Esperienza e forma",clarification:"La vita fonda la domanda, non determina la soluzione.",example:"Calvino e Primo Levi rispondono con punti di vista e generi differenti.",check:"Quale passaggio separa il vissuto dall’opera?"}},
      {prompt:"Qual è il centro dell’immagine del mondo neorealista?",options:["Una realtà inesistente","Una realtà già perfettamente parlante","Una realtà quotidiana e plurale che richiede un punto di vista responsabile"],correct:2,explanation:"Il mondo resiste, ma diventa conoscenza soltanto attraverso selezione e forma.",anchor:"m3-sguardo",recovery:{concept:"Reale e mediazione",clarification:"Riconoscere la costruzione non equivale a negare la realtà.",example:"La postsincronizzazione può convivere con un mondo cinematografico credibile.",check:"Perché la neutralità è impossibile?"}},
      {prompt:"Quale principio definisce meglio la poetica?",options:["La semplicità è un effetto prodotto da scelte complesse","Ogni artificio deve scomparire materialmente","Il dialetto garantisce sempre autenticità"],correct:0,explanation:"Oralità, montaggio e punto di vista sono strumenti deliberati.",anchor:"m4-prosa",recovery:{concept:"Costruire la semplicità",clarification:"L’immediatezza può richiedere un lavoro formale rigoroso.",example:"La voce di Pin appare spontanea ma dipende da una precisa focalizzazione.",check:"Quali scelte producono l’effetto di parlato?"}},
      {prompt:"Che cosa insegnano le opere più riuscite?",options:["Che l’etichetta sostituisce l’analisi","Che ogni tensione comune richiede una soluzione formale singolare","Che il documento è sempre superiore alla finzione"],correct:1,explanation:"I capolavori appartengono alla stagione proprio perché ne superano la formula.",anchor:"m5-fenoglio",recovery:{concept:"Opera contro formula",clarification:"Una corrente è feconda quando genera differenze, non copie.",example:"Pavese usa il mito; Fenoglio l’epica privata; Levi la testimonianza analitica.",check:"Perché la diversità conferma anziché smentire la costellazione?"}},
      {prompt:"Quale eredità resta più attuale?",options:["Il bianco e nero","La responsabilità di interrogare ciò che le immagini dominanti escludono","L’obbligo di ambientare ogni storia nel dopoguerra"],correct:1,explanation:"Il metodo dello sguardo può sopravvivere ai soggetti e alle tecniche della stagione storica.",anchor:"m6-oggi",recovery:{concept:"Eredità critica",clarification:"Essere fedeli non significa ripetere il costume del 1945.",example:"Oggi la domanda riguarda anche immagini selezionate da piattaforme e algoritmi.",check:"Quale invisibilità del presente merita una nuova forma?"}}
    ]
  }
};
