(() => {
  const q = (question, options, answer, explanation, concept, clarification, example, check, checkAnswer) => ({
    q: question, options, answer, explanation,
    recovery: {concept, clarification, example, check, checkAnswer}
  });

  const s1 = {
    title: 'Il mondo precedente', short: 'Il mondo precedente', navHint: 'Ordine e avanguardie',
    card: 'La crisi del linguaggio poetico fra tradizione italiana, simbolismo francese e avanguardie.',
    question: 'Quale lingua poetica riceve Ungaretti, e perché non gli basta più?',
    lesson: `
      <h2>Una poesia troppo piena davanti a un mondo che si spezza</h2>
      <p>Quando Giuseppe Ungaretti comincia a scrivere, la poesia italiana possiede ancora una voce pubblica, sonora, riconoscibile. Carducci, Pascoli e D’Annunzio hanno mostrato possibilità molto diverse della tradizione: la costruzione civile e classicheggiante, la scoperta delle piccole cose e delle zone oscure dell’io, la musicalità sontuosa della parola. Questo patrimonio non è morto; anzi, continua a offrire forme, ritmi e immagini. Ma all’inizio del Novecento appare anche come un’eredità problematica. La lingua alta rischia di trasformare l’esperienza in eloquenza, proprio mentre la società europea entra nell’epoca delle masse, delle metropoli, della tecnica e della guerra industriale. La domanda che prepara Ungaretti non è dunque: come distruggere la tradizione? È più difficile: quale parola può restare vera quando le forme ricevute sembrano dire troppo?</p>
      <h3>L’Italia: crisi dell’io e ribellione alla voce solenne</h3>
      <p>Negli anni in cui Ungaretti si forma, varie esperienze italiane incrinano il modello del poeta-vate. I crepuscolari abbassano il tono, frequentano oggetti quotidiani e identità marginali; i vociani cercano una scrittura morale e autobiografica; i futuristi aggrediscono sintassi, punteggiatura e ordine tipografico. Questi gruppi non compongono una scuola unitaria e Ungaretti non coincide con nessuno di essi. Tuttavia rendono disponibile un gesto comune: la poesia può rinunciare all’apparato tradizionale e cercare la propria necessità in una forma nuova. Dal Futurismo Ungaretti ricava soprattutto una libertà tecnica, non il culto permanente della velocità e della guerra. Dalla cultura della «Voce» incontra invece l’idea che scrivere coinvolga l’intera persona e non sia un semplice esercizio ornamentale.</p>
      <h3>Alessandria: una periferia che è già il mondo</h3>
      <p>Il suo punto di partenza non è però soltanto italiano. Ungaretti nasce nel 1888 ad Alessandria d’Egitto da genitori lucchesi emigrati. La città è un crocevia mediterraneo di lingue, religioni e provenienze; il deserto le sta accanto come una presenza fisica e simbolica. L’infanzia africana gli consegna due esperienze destinate a durare: l’appartenenza plurale e la mancanza di un’unica patria immediata. Il Nilo, il porto sommerso di cui sente raccontare, la tenda, il miraggio, il nomade diventeranno nuclei di memoria. Non sono cartoline esotiche: sono immagini attraverso cui il poeta penserà l’identità come ricerca, emersione e perdita.</p>
      <p>La formazione francofona dell’École Suisse Jacot e la lettura di riviste europee lo avvicinano presto a Baudelaire e soprattutto ai simbolisti. Qui trova un’altra idea di poesia: il reale non si lascia esaurire dalla descrizione; la parola non deve catalogare le cose, ma aprire rapporti imprevisti fra di esse. L’analogia, la suggestione sonora e il valore del silenzio contano più della spiegazione completa. Questa lezione prepara la concentrazione ungarettiana, anche se il poeta la trasformerà con un’esperienza storica che i suoi maestri non potevano prevedere.</p>
      <h3>Parigi: il laboratorio europeo</h3>
      <p>Nel 1912 Ungaretti raggiunge Parigi. Frequenta corsi alla Sorbona e al Collège de France, ascolta Henri Bergson e incontra scrittori e artisti delle avanguardie, fra i quali Apollinaire. La capitale francese gli mostra che poesia, pittura e filosofia stanno affrontando lo stesso problema: l’unità stabile dell’oggetto e del soggetto non può più essere data per scontata. Il cubismo scompone e ricompone i punti di vista; Apollinaire sperimenta il verso e lo spazio tipografico; Bergson distingue il tempo misurato dagli orologi dalla durata vissuta dalla coscienza. Ungaretti non applica meccanicamente queste teorie. Impara però a vedere l’identità come un flusso che la memoria ricompone e la forma artistica rende percepibile.</p>
      <h3>La tensione che prepara la frattura</h3>
      <p>Il mondo precedente offre dunque a Ungaretti tre risorse e tre limiti. La tradizione italiana gli dà profondità storica, ma rischia la retorica; il simbolismo gli insegna che la parola allude a un mistero, ma può allontanarsi dall’urgenza concreta; l’avanguardia libera il verso, ma può fare della rottura una posa. La sua poesia nascerà dal tentativo di non scegliere superficialmente uno dei tre campi. Vorrà una parola antica e nuova, misteriosa e concreta, libera ma responsabile.</p>
      <p>Prima della guerra questa esigenza è già visibile, ma non ha ancora trovato la sua necessità estrema. Servirà una frattura storica e personale perché la sottrazione diventi non soltanto un’opzione estetica, bensì una forma di verità. Nella trincea, davanti a corpi, fango e attese, la parola enfatica non sarà semplicemente fuori moda: diventerà moralmente falsa. Il mondo ricevuto contiene quindi la domanda; la guerra costringerà Ungaretti a rispondere.</p>`,
    bridge: 'Le possibilità della tradizione, del simbolismo e dell’avanguardia non bastano ancora: la guerra trasforma una ricerca di stile in una necessità umana.',
    summary: 'Ungaretti eredita una poesia italiana ancora segnata dalle grandi voci di Carducci, Pascoli e D’Annunzio, ma attraversata dalla ribellione dei crepuscolari, dei vociani e dei futuristi. Alessandria d’Egitto gli offre un’identità mediterranea e plurale; Parigi lo mette a contatto con simbolismo, avanguardie e riflessione bergsoniana sul tempo vissuto. Da questi mondi riceve tradizione, analogia e libertà formale, ma ne avverte anche i limiti: la retorica può falsificare l’esperienza, la suggestione può diventare evasione, la rottura può ridursi a posa. Prima del 1915 la sua domanda poetica è già pronta: trovare una parola insieme essenziale, concreta e capace di mistero. Sarà la guerra a rendere questa ricerca urgente e non più soltanto estetica.',
    essentials: [
      'Saper spiegare perché la tradizione italiana è per Ungaretti una risorsa e insieme un limite.',
      'Distinguere la libertà formale delle avanguardie dal successivo uso ungarettiano della frammentazione.',
      'Collegare Alessandria d’Egitto alla pluralità delle origini e al tema del nomadismo.',
      'Spiegare che cosa Ungaretti apprende dal simbolismo: la parola come rivelazione, non come semplice descrizione.',
      'Riconoscere nel soggiorno parigino un crocevia di poesia, pittura e filosofia.',
      'Formulare la tensione iniziale: dire il vero senza ricadere nella retorica.'
    ],
    glossary: [
      {term:'Poeta-vate',definition:'Figura pubblica che pretende di interpretare e guidare la nazione; è il modello che il primo Novecento mette in crisi.'},
      {term:'Simbolismo',definition:'Poetica che cerca corrispondenze e significati non immediatamente visibili attraverso suono, immagine e analogia.'},
      {term:'Avanguardia',definition:'Movimento che rompe deliberatamente convenzioni artistiche e linguistiche per produrre forme nuove.'},
      {term:'Durata',definition:'In Bergson, tempo qualitativo vissuto dalla coscienza, diverso dalla successione misurabile dell’orologio.'},
      {term:'Analogia',definition:'Rapporto rapido fra realtà lontane, capace di suggerire un significato senza sviluppare una spiegazione logica completa.'},
      {term:'Déraciné',definition:'Letteralmente “sradicato”: condizione di chi non possiede un’appartenenza unica e immediata.'}
    ],
    map:'maps/01-mondo.svg',
    mapAlt:'La tradizione italiana offre forme ma rischia la retorica; simbolismo e Parigi aprono analogia e mistero; le avanguardie liberano verso e pagina; Alessandria produce un’identità plurale. Queste linee confluiscono nella domanda di una parola vera, che la guerra renderà urgente.',
    questions: [
      q('Qual è la tensione fondamentale del mondo poetico ricevuto da Ungaretti?',['Scegliere fra poesia italiana e lingua francese','Conservare la profondità della tradizione evitando la retorica','Eliminare ogni rapporto con il passato'],1,'La sua ricerca non cancella la tradizione: vuole renderla nuovamente vera sottraendola all’enfasi.','Tradizione e verità','Ungaretti non tratta il passato come un deposito da demolire, ma come una lingua da sottoporre a prova.','Recupererà più avanti metri e autori antichi senza rinunciare alla propria modernità.','La tradizione viene cancellata o trasformata?','Viene trasformata e rimessa alla prova.'),
      q('Che cosa rappresenta soprattutto Alessandria d’Egitto nella formazione del poeta?',['Un’identità plurale e mediterranea','Una parentesi senza conseguenze poetiche','Il luogo della sua formazione universitaria'],0,'Alessandria è il crocevia delle origini, delle lingue e delle immagini di deserto, fiume e porto.','Origini plurali','La città natale rende impossibile pensare l’identità come appartenenza semplice.','Ne I fiumi il Nilo sarà una delle acque che compongono la sua storia.','Perché il Nilo può diventare memoria personale?','Perché appartiene al paesaggio della nascita e dell’infanzia.'),
      q('Quale lezione essenziale proviene dal simbolismo francese?',['La poesia deve descrivere ogni dettaglio con precisione documentaria','La parola può evocare rapporti invisibili senza spiegare tutto','Il verso deve rispettare sempre una misura regolare'],1,'Il simbolismo insegna il potere evocativo, analogico e musicale della parola.','Parola simbolica','La parola poetica non coincide con una definizione: apre una relazione e lascia attivo il lettore.','Un’immagine può collegare realtà lontane senza una lunga catena logica.','L’analogia spiega completamente o suggerisce?','Suggerisce una relazione di senso.'),
      q('Quale distinzione bergsoniana interessa la futura poesia ungarettiana?',['Fra tempo dell’orologio e durata vissuta','Fra prosa italiana e poesia francese','Fra guerra offensiva e guerra difensiva'],0,'La durata permette di pensare memoria e identità come esperienza interiore, non come semplice cronologia.','Tempo vissuto','La coscienza non sperimenta il tempo come una fila di unità identiche.','Un ricordo remoto può entrare nel presente e trasformarlo.','La durata è quantitativa o qualitativa?','È qualitativa e interiore.'),
      q('Perché la libertà futurista non basta a definire la poetica di Ungaretti?',['Perché Ungaretti rifiuta ogni innovazione grafica','Perché la rottura formale dovrà diventare responsabilità verso l’esperienza','Perché il Futurismo usa soltanto forme classiche'],1,'Ungaretti assume alcune libertà tecniche, ma la trincea darà alla sottrazione una necessità etica diversa dal gesto provocatorio.','Avanguardia e necessità','Una forma nuova conta quando risponde a un’esperienza, non quando è soltanto spettacolo della novità.','Il verso breve ungarettiano pesa il silenzio e la precarietà.','Che cosa trasforma la tecnica in poetica?','Il nesso necessario fra forma ed esperienza.')
    ]
  };

  const s2 = {
    title: 'Le fratture della vita', short: 'Le fratture', navHint: 'Esilio, guerra, lutto',
    card: 'Sradicamento, trincea, conversione e lutto: esperienze che mettono alla prova ogni certezza.',
    question: 'Che cosa rende insufficiente il mondo ricevuto e obbliga Ungaretti a cambiare sguardo?',
    lesson: `
      <h2>Non una biografia che “spiega” i versi</h2>
      <p>La vita di Ungaretti è segnata da spostamenti, guerre, scelte politiche e lutti. Sarebbe facile trasformare ogni evento in una causa automatica di una poesia. È però un metodo debole: riduce l’opera a documento psicologico e cancella il lavoro consapevole della forma. Le fratture biografiche servono invece a comprendere quali problemi diventano urgenti per il poeta e perché certe soluzioni linguistiche acquistano significato. L’esperienza non detta il verso; lo mette alla prova.</p>
      <h3>Lo sradicamento prima della guerra</h3>
      <p>Ungaretti nasce italiano in Egitto, studia in francese, vive poi a Parigi e arriva in Italia da adulto. Questa mobilità produce libertà, ma anche una domanda dolorosa sull’appartenenza. L’amico Moammed Sceab, conosciuto ad Alessandria e ritrovato a Parigi, diventa il caso estremo di uno sradicamento senza ricomposizione: cambia nome, non riesce a diventare francese, non sa più tornare alla cultura d’origine e si suicida nel 1913. La poesia In memoria non va letta come una semplice cronaca del lutto. Interroga la possibilità stessa di trasformare l’abbandono in canto. Ungaretti riconosce nell’amico una condizione che gli è vicina, ma indica nella poesia una differenza decisiva: dare forma al proprio esilio può impedire che esso resti muto.</p>
      <h3>La guerra: dall’interventismo alla fraternità precaria</h3>
      <p>Nel 1914-15 Ungaretti sostiene l’intervento italiano e si arruola volontario. Questo dato non va nascosto con una leggenda edificante: il poeta entra nella guerra anche per scelta, dentro il clima politico e culturale del tempo. L’esperienza del Carso smentisce però ogni immagine astratta del conflitto. Il soldato incontra attese interminabili, fango, cadaveri, paura e casualità della morte. Le liriche nate al fronte conservano spesso luogo e data, come pagine di un diario, ma non celebrano la battaglia. Registrano ciò che resta dell’uomo quando le identità pubbliche cedono.</p>
      <p>In Veglia la vicinanza fisica del compagno ucciso non produce un discorso patriottico: scatena un attaccamento quasi scandaloso alla vita. In Fratelli una parola pronunciata nella notte diventa una fragile rivolta contro la riduzione degli uomini a reparti contrapposti. In Soldati la condizione militare si allarga a figura della precarietà universale. La guerra non “crea” magicamente il verso breve, già preparato dalle letture e dalle avanguardie; rende però necessaria una lingua che non copra il trauma con la retorica. Luogo, giorno e parola isolata sono il minimo documento lasciato contro l’anonimato della morte industriale.</p>
      <h3>Roma, fascismo e conversione: una zona da non addomesticare</h3>
      <p>Nel dopoguerra Ungaretti vive fra Parigi e Roma, lavora nel giornalismo e cerca una sistemazione. Aderisce al fascismo e nel 1925 firma il Manifesto degli intellettuali fascisti; Mussolini scrive una prefazione per l’edizione del Porto sepolto del 1923. È una responsabilità storica, non un dettaglio da espellere perché disturba il profilo del poeta. Non significa però che ogni poesia successiva sia propaganda. La lettura seria deve mantenere insieme il giudizio sulla scelta politica e l’autonomia relativa dell’opera, evitando sia l’assoluzione agiografica sia la cancellazione semplicistica.</p>
      <p>Negli stessi anni matura il riavvicinamento alla fede cattolica, espresso apertamente alla fine degli anni Venti. Anche questo passaggio non è una pacificazione definitiva. In Sentimento del tempo la religione convive con il senso del peccato, della caducità e della distanza fra creatura ed eterno. La forma si fa più ampia e recupera la tradizione perché il problema non è più soltanto sopravvivere all’istante, ma misurare l’uomo con il tempo, la colpa e l’assoluto.</p>
      <h3>Brasile, morte del figlio e guerra mondiale</h3>
      <p>Dal 1936 Ungaretti insegna letteratura italiana all’Università di San Paolo. Nel 1939 muore a nove anni il figlio Antonietto. Tornato in Italia nel 1942, il poeta attraversa inoltre l’occupazione di Roma e la violenza della seconda guerra mondiale. Il Dolore, pubblicato nel 1947, accosta la perdita privata e la tragedia collettiva senza dichiararle equivalenti. Il lutto del padre non diventa una formula capace di spiegare il dolore storico; piuttosto, le due ferite si interrogano reciprocamente. La parola, che nella prima guerra cercava un lampo di vita dentro il naufragio, ora deve sopportare l’assenza di una persona insostituibile.</p>
      <p>Le fratture non conducono quindi lungo una linea di progresso tranquillo. Ungaretti resta attraversato da contraddizioni: nomade e cercatore di patria, interventista e poeta della fraternità, innovatore e restauratore di forme, uomo di fede e voce dell’angoscia. La sua immagine del mondo nascerà proprio dall’impossibilità di sciogliere queste tensioni in una dottrina semplice.</p>`,
    bridge: 'Le fratture non consegnano una soluzione, ma una visione: l’uomo è fragile, temporaneo e tuttavia capace di fraternità, memoria e ricerca dell’assoluto.',
    summary: 'Le fratture della vita di Ungaretti non spiegano meccanicamente le poesie, ma rendono intelligibili i problemi cui la forma risponde. Lo sradicamento fra Egitto, Francia e Italia trova un’immagine estrema nel suicidio di Moammed Sceab. La guerra, scelta inizialmente dall’interventista Ungaretti, distrugge ogni rappresentazione astratta del conflitto e rende necessaria una parola che non copra il trauma. Nel dopoguerra l’adesione al fascismo costituisce una responsabilità storica da non occultare, mentre il ritorno alla fede apre una ricerca tutt’altro che pacificata sul tempo e sulla colpa. In Brasile la morte del figlio Antonietto, poi la seconda guerra mondiale e Roma occupata, portano Il Dolore a confrontare perdita privata e tragedia collettiva. Da queste tensioni nasce una visione dell’uomo fragile ma ancora capace di relazione e ricerca.',
    essentials: [
      'Spiegare perché il rapporto fra vita e poesia non è una causalità automatica.',
      'Collegare In memoria al problema dello sradicamento e della possibilità del canto.',
      'Ricostruire senza rimozioni il passaggio dall’interventismo alla poesia di trincea.',
      'Riconoscere la funzione di luoghi e date come tracce concrete contro l’anonimato.',
      'Conoscere l’adesione di Ungaretti al fascismo e distinguerne il giudizio storico dall’analisi dei testi.',
      'Collegare conversione, recupero della tradizione e nuova meditazione sul tempo.',
      'Distinguere nel Dolore la perdita del figlio dalla sofferenza collettiva, senza separarle.'
    ],
    glossary: [
      {term:'Frattura',definition:'Esperienza che rende insufficiente l’ordine precedente e costringe a riformulare visione e linguaggio.'},
      {term:'Interventismo',definition:'Posizione favorevole all’ingresso dell’Italia nella Prima guerra mondiale, sostenuta inizialmente anche da Ungaretti.'},
      {term:'Poesia-diario',definition:'Scrittura che conserva coordinate concrete di luogo e data, trasformandole però in interrogazione universale.'},
      {term:'Fraternità',definition:'Riconoscimento fragile dell’umanità comune che la guerra divide e, paradossalmente, rende più urgente.'},
      {term:'Conversione',definition:'Riavvicinamento alla fede cattolica, che in Ungaretti apre domande su colpa, tempo ed eterno più che certezze facili.'},
      {term:'Lutto',definition:'Esperienza di una perdita irreversibile; nel Dolore riguarda il figlio e dialoga con la tragedia storica.'}
    ],
    map:'maps/02-fratture.svg',
    mapAlt:'Lo sradicamento conduce al problema dell’identità e alla poesia In memoria; la trincea mette in crisi la retorica e produce parola essenziale e fraternità; fascismo e conversione mostrano responsabilità e ricerca d’ordine; la morte del figlio e la seconda guerra confluiscono nel Dolore. Le fratture trasformano la visione dell’uomo.',
    questions: [
      q('Qual è il modo corretto di collegare biografia e poesia?',['Ogni evento produce direttamente una forma poetica','La biografia è irrilevante per qualsiasi interpretazione','L’esperienza rende urgenti problemi ai quali la forma risponde'],2,'Il nesso va documentato e formulato con cautela: l’opera è elaborazione, non riflesso automatico.','Biografia e forma','Una frattura offre un contesto e mette alla prova il linguaggio, ma non detta da sola il testo.','La guerra rende necessaria una tecnica preparata anche da letture precedenti.','La vita detta il verso o gli pone un problema?','Gli pone un problema che il lavoro poetico elabora.'),
      q('Che cosa rende Moammed Sceab decisivo nel percorso?',['Incarna uno sradicamento che non riesce a diventare canto','Introduce Ungaretti al Futurismo italiano','Pubblica Il Porto Sepolto al fronte'],0,'In memoria confronta la perdita di patria e lingua con la possibilità, propria del poeta, di dare forma all’abbandono.','Sradicamento e canto','Sceab è vicino a Ungaretti per condizione, ma non riesce a trasformare il proprio esilio in parola.','La poesia conserva il nome dell’amico contro la sparizione.','Quale possibilità distingue il poeta dall’amico?','Dare una forma condivisibile al proprio abbandono.'),
      q('Perché luoghi e date compaiono nelle poesie di guerra?',['Per simulare un rapporto militare completo','Per ancorare la parola a un’esperienza concreta e irripetibile','Per rispettare una regola del Simbolismo'],1,'Le coordinate fanno della lirica una traccia personale e resistono all’anonimato della morte di massa.','Coordinate del diario','Data e luogo non chiudono il significato: attestano da dove nasce la voce.','Una poesia datata sul Carso parte da un istante e raggiunge la precarietà universale.','Le coordinate limitano o radicano la poesia?','La radicano, senza impedirle di diventare universale.'),
      q('Come va trattata l’adesione di Ungaretti al fascismo?',['Va omessa perché non entra nelle liriche','Va riconosciuta come responsabilità storica senza ridurre a essa ogni testo','Dimostra che le poesie di guerra sono propaganda fascista'],1,'Una lettura critica evita sia l’assoluzione sia la riduzione totale dell’opera alla scelta politica.','Responsabilità storica','L’autonomia dell’arte è relativa, non una scusa per cancellare le decisioni dell’autore.','Firma del Manifesto fascista e complessità della produzione poetica vanno tenute entrambe presenti.','Giudicare una scelta significa cancellare l’opera?','No: significa leggerla senza rimuovere il contesto.'),
      q('Nel Dolore, come si rapportano lutto privato e tragedia collettiva?',['Si interrogano senza diventare equivalenti','Il lutto del figlio sostituisce completamente la storia','La guerra mondiale è soltanto una metafora familiare'],0,'La raccolta accosta ferite diverse e impedisce che una diventi spiegazione facile dell’altra.','Dolore privato e pubblico','Antonietto è insostituibile; Roma occupata appartiene a un’altra scala. La poesia crea risonanza, non equivalenza.','La voce del padre incontra la storia senza appropriarsene.','Accostare due dolori significa identificarli?','No: significa farli dialogare preservandone la differenza.')
    ]
  };

  const s3 = {
    title: 'L’immagine del mondo', short: 'L’immagine del mondo', navHint: 'Fragilità e mistero',
    card: 'L’uomo come creatura temporanea: disperso nella storia, ma capace di riconoscersi nell’universo.',
    question: 'Come appare la realtà dopo che guerra, esilio e lutto hanno dissolto le certezze?',
    lesson: `
      <h2>La creatura fra il nulla e l’immenso</h2>
      <p>L’immagine del mondo di Ungaretti non è una filosofia ordinata in proposizioni. Emerge da tensioni ricorrenti: precarietà e slancio vitale, sradicamento e desiderio di patria, memoria e innocenza, tempo umano ed eterno. Il poeta non risolve queste opposizioni; le rende percepibili. Per questo una lirica brevissima può aprire una dimensione vastissima: non perché nasconda un codice segreto, ma perché concentra in un’immagine il punto in cui l’esperienza individuale tocca una condizione comune.</p>
      <h3>Precarietà: non solo la condizione del soldato</h3>
      <p>La guerra rivela che la vita può essere interrotta in ogni momento. In Soldati la similitudine stagionale non descrive una battaglia: espone corpi umani a una caduta possibile e imminente. La forza del testo nasce dal passaggio dal titolo collettivo all’immagine naturale. Il soldato non è presentato come eroe né come vittima eccezionale; diventa figura dell’uomo, sospeso a condizioni che non controlla. Tuttavia la precarietà non conduce a una poesia del puro nulla. Proprio perché la vita è fragile, ogni attimo può acquistare un’intensità assoluta. In Veglia, accanto alla morte, nasce un attaccamento estremo all’esistenza; in Mattina l’io sperimenta un’apertura improvvisa che non elimina il limite, ma lo oltrepassa per un istante.</p>
      <p>Questa dialettica spiega l’«allegria» dentro il «naufragio». Non si tratta di ottimismo. Il naufragio resta reale; l’allegria è la capacità intermittente di ricominciare, riconoscere una presenza, dire una parola. La positività ungarettiana è tanto più intensa quanto meno è garantita. È una luce esposta, non una consolazione sistematica.</p>
      <h3>Fraternità: la parola che ricrea l’uomo</h3>
      <p>La guerra organizza gli individui per uniformi, eserciti e nazioni. La poesia cerca invece il momento in cui quelle categorie si incrinano. Fratelli nasce da una domanda fra soldati incontrati nella notte: l’appartenenza militare è incerta, ma la parola pronunciata fa affiorare un’appartenenza più profonda. Chiamare l’altro “fratello” non cancella il conflitto né istituisce una pace reale. È una protesta fragile, simile a una foglia appena nata nell’aria sconvolta. La fraternità è dunque relazione da rifare, non essenza posseduta una volta per tutte.</p>
      <h3>Identità come confluenza</h3>
      <p>Ne I fiumi l’identità non viene trovata scegliendo una sola origine. L’Isonzo del presente di guerra richiama il Serchio degli antenati, il Nilo dell’infanzia e la Senna della formazione. La memoria non allinea semplicemente quattro luoghi su una carta: li fa confluire in un istante vissuto. Il soggetto si riconosce come parte dell’universo quando smette di pensarsi come unità isolata. L’acqua leviga, collega, attraversa; all’opposto, la pietra può indicare aridità e peso. Il mondo naturale non è uno sfondo decorativo, ma il lessico attraverso cui l’io comprende la propria posizione.</p>
      <p>Qui la lezione di Bergson è utile: il passato sopravvive nel presente e lo modifica. Ma non basta a definire l’intera riflessione ungarettiana. Nella maturità la memoria assume anche un volto tragico: rende presente ciò che è perduto, misura la distanza dall’innocenza, accumula il tempo e quindi la morte. La poesia cerca allora, dentro la memoria, una parola capace di risalire verso un’origine non ancora corrotta dall’abitudine.</p>
      <h3>Innocenza, memoria e assoluto</h3>
      <p>Ungaretti usa spesso “innocenza” non nel senso ingenuo di assenza di colpa personale, ma come desiderio di una relazione originaria fra parola e realtà. La memoria è necessaria perché costituisce l’identità; nello stesso tempo, può coprire l’origine con strati di cultura, abitudine e dolore. Il poeta vive questa contraddizione: vuole una parola primigenia, ma sa che può cercarla soltanto attraverso la storia della lingua e la propria esperienza.</p>
      <p>Con il ritorno alla fede cristiana, la precarietà viene inscritta nella distanza fra creatura e Dio. Il tempo umano appare consumazione, mentre l’eterno è cercato come misura irraggiungibile. Non ne deriva una sicurezza uniforme. La preghiera ungarettiana conserva il vuoto, la colpa e l’attesa; Il Dolore porta la fede davanti allo scandalo della morte del figlio. L’assoluto è una domanda che approfondisce la ferita, non un cerotto teologico.</p>
      <h3>Il mondo come mistero da attraversare</h3>
      <p>Questa visione rende insufficiente sia il discorso retorico sia la spiegazione analitica completa. Se l’uomo è frammento temporaneo ma aperto all’immenso, la poesia deve rispettare entrambe le dimensioni: la precisione dell’istante e l’eccedenza del significato. Deve poter nominare un luogo e, nello stesso tempo, lasciar risuonare ciò che quel luogo non contiene. La poetica della parola isolata, dell’analogia e del silenzio nascerà come risposta formale a questa immagine del mondo.</p>`,
    bridge: 'Una realtà fatta di precarietà, memoria e mistero richiede una forma capace di essere esatta senza pretendere di esaurire il senso: nasce la parola scavata.',
    summary: 'La visione ungarettiana tiene insieme precarietà e slancio vitale. La guerra rende evidente la fragilità del soldato, ma questa condizione diventa figura dell’uomo; proprio il limite può far esplodere l’intensità dell’istante. La fraternità non è una certezza politica già realizzata, bensì una parola fragile che restituisce umanità dentro le classificazioni della guerra. Ne I fiumi l’identità appare come confluenza di tempi e luoghi, secondo una memoria dinamica vicina alla durata bergsoniana. La memoria però conserva e insieme misura la perdita; l’innocenza indica il desiderio di un rapporto originario fra parola e realtà. Con il ritorno alla fede, il tempo umano si confronta con l’eterno senza trovare una consolazione facile. Questa realtà, concreta e misteriosa, esige una parola precisa ma non esaustiva.',
    essentials: [
      'Spiegare perché la precarietà dei soldati diventa immagine della condizione umana.',
      'Distinguere l’allegria ungarettiana dall’ottimismo: è un ricominciare dentro il naufragio.',
      'Interpretare la fraternità come relazione fragile che resiste alle categorie della guerra.',
      'Leggere I fiumi come ricomposizione dinamica dell’identità, non come elenco geografico.',
      'Comprendere la doppia funzione della memoria: costituisce l’io e rende presente la perdita.',
      'Definire l’innocenza come ricerca di un’origine della parola, non come ingenuità.',
      'Riconoscere nella fede una domanda sull’assoluto, non una soluzione priva di conflitto.'
    ],
    glossary: [
      {term:'Precarietà',definition:'Esposizione della vita alla perdita e alla casualità; dal soldato si estende all’intera condizione umana.'},
      {term:'Naufragio',definition:'Figura della crisi e della dispersione da cui può emergere un nuovo, momentaneo slancio vitale.'},
      {term:'Confluenza',definition:'Modello dell’identità in cui luoghi e tempi diversi restano attivi nel presente.'},
      {term:'Innocenza',definition:'Desiderio di una relazione originaria e non consumata fra uomo, parola e mondo.'},
      {term:'Memoria',definition:'Forza che compone la durata personale ma porta anche la coscienza della perdita.'},
      {term:'Assoluto',definition:'Orizzonte di totalità ed eterno cercato dalla creatura, senza che il limite umano venga annullato.'}
    ],
    map:'maps/03-immagine.svg',
    mapAlt:'La precarietà produce un attaccamento intermittente alla vita; la guerra mette in crisi le identità e rende necessaria la fraternità; i fiumi fanno confluire origini e memoria; la memoria crea identità ma misura la perdita; il desiderio d’innocenza e la fede aprono la ricerca dell’assoluto. Ne deriva un mondo concreto e misterioso.',
    questions: [
      q('Che cosa significa “allegria” nel naufragio?',['Una smentita della sofferenza','La possibilità intermittente di ricominciare dentro la crisi','La certezza che la storia migliori sempre'],1,'L’allegria non elimina il naufragio: è una luce fragile e non garantita.','Allegria tragica','La vitalità ungarettiana nasce proprio dalla prossimità della perdita.','In Veglia l’orrore rende più intenso l’attaccamento alla vita.','L’allegria cancella il naufragio?','No, vi resiste per un istante.'),
      q('In Fratelli, quale funzione ha la parola del titolo?',['Ricostruisce precariamente un’umanità comune','Identifica con certezza il reparto militare','Celebra l’obbedienza dei soldati'],0,'La parola incrina le classificazioni belliche e riconosce nell’altro una creatura esposta.','Fraternità fragile','“Fratello” non descrive una pace già raggiunta: compie un gesto di riconoscimento.','Una parola umana emerge nella notte della guerra.','La fraternità è possesso o atto?','È un atto da rinnovare.'),
      q('Come costruisce l’identità la poesia I fiumi?',['Scegliendo il Nilo come unica patria autentica','Cancellando il passato europeo','Facendo confluire origini e tempi diversi nel presente'],2,'Serchio, Nilo, Senna e Isonzo restano differenti ma partecipano allo stesso riconoscimento dell’io.','Identità come confluenza','La memoria non seleziona una sola radice: compone una pluralità.','L’Isonzo presente riattiva i fiumi delle altre stagioni di vita.','Identità unica o plurale?','Plurale, ricomposta nell’esperienza presente.'),
      q('Qual è l’ambivalenza della memoria?',['Conserva l’identità e insieme rende percepibile la perdita','È sempre un ostacolo che il poeta elimina','Coincide con la cronologia esterna'],0,'Il passato vive nel presente, ma porta con sé ciò che non può tornare.','Memoria ambivalente','Ricordare costituisce l’io e contemporaneamente misura una distanza.','Il ricordo del figlio mantiene una presenza proprio attraverso l’assenza.','La memoria cura soltanto?','No, conserva e ferisce.'),
      q('Come va intesa la fede nella poesia matura?',['Come prova che ogni dolore è stato risolto','Come ricerca dell’assoluto attraversata da colpa, assenza e attesa','Come rifiuto definitivo della storia'],1,'La dimensione religiosa approfondisce la domanda e non annulla lo scandalo della perdita.','Fede problematica','La preghiera può contenere vuoto e protesta, non soltanto certezza.','Nel Dolore la fede è portata davanti alla morte del figlio.','La fede elimina la ferita?','No, offre un orizzonte in cui interrogarla.')
    ]
  };

  const s4 = {
    title: 'La poetica', short: 'La poetica', navHint: 'Parola, silenzio, ritmo',
    card: 'Scavare la parola, far parlare lo spazio bianco, poi misurarsi nuovamente con la tradizione.',
    question: 'Come deve scrivere Ungaretti per dire una realtà insieme concreta e misteriosa?',
    lesson: `
      <h2>La parola non è breve: è concentrata</h2>
      <p>Ridurre la poetica di Ungaretti alla brevità sarebbe come descrivere un’architettura contando i mattoni. Il centro non è il numero delle parole, ma la pressione esercitata su ciascuna di esse. Nelle liriche della guerra il poeta elimina nessi esplicativi, punteggiatura e misure regolari perché vuole sottrarre la lingua all’automatismo. La parola comune, isolata fra pause e spazi bianchi, deve tornare a essere percepita nel suono, nel significato e nella sua relazione con il silenzio. “Scavare” non significa cercare un vocabolo raro: significa attraversare la propria esperienza finché il vocabolo necessario non appaia insostituibile.</p>
      <h3>Versicolo e spazio bianco</h3>
      <p>Il verso ungarettiano può coincidere con poche sillabe o con una sola parola. I manuali parlano spesso di “versicolo”, termine utile se non diventa un giudizio diminutivo. La frantumazione interrompe la sintassi abituale, costringe l’occhio a sostare e moltiplica gli accenti. Lo spazio bianco non è un vuoto decorativo: rappresenta pausa, esitazione, distanza, silenzio della morte e campo di risonanza. Il lettore non riceve una frase già organizzata; deve ricomporre il rapporto fra i frammenti, sperimentando una precarietà simile a quella espressa dal testo.</p>
      <p>L’assenza di punteggiatura nelle prime raccolte non produce libertà arbitraria. Sono gli a capo, le ripetizioni e la disposizione strofica a guidare il respiro. La lettura ad alta voce rivela che il ritmo resta rigoroso, anche quando non obbedisce a uno schema metrico fisso. La pagina diventa una partitura: il bianco indica il tempo non meno delle parole.</p>
      <h3>Analogia: il salto controllato</h3>
      <p>La sintassi ridotta favorisce l’analogia, cioè l’accostamento di realtà lontane senza una lunga spiegazione. L’immagine non è un indovinello da decifrare con una chiave unica. È un salto che mette in contatto esperienza sensibile e condizione interiore. L’albero “mutilato”, l’uomo levigato come un sasso, la vita esposta come una foglia: ciascun rapporto resta concreto e nello stesso tempo apre un campo di significati. L’analogia è dunque controllata dall’esattezza dell’esperienza; se diventasse associazione gratuita, perderebbe la sua necessità.</p>
      <h3>Dal diario alla riscrittura continua</h3>
      <p>I testi di guerra mostrano date e luoghi e sembrano nati nell’immediatezza. Ma Ungaretti li riscrive per decenni, spostandoli, correggendoli, modificando titoli e raccolte. Il Porto Sepolto del 1916 confluisce nell’Allegria di naufragi del 1919 e poi, attraverso varie edizioni, nell’Allegria. La filologia delle varianti smentisce il mito di un poeta che annota l’emozione pura una volta per tutte. L’istante è sottoposto a un laboratorio severo: togliere, ripristinare, cambiare un a capo significa ridefinire la relazione fra voce, storia e memoria.</p>
      <p>Anche il titolo complessivo Vita d’un uomo, dato all’opera poetica, non autorizza a confondere vita e spontaneità. Indica piuttosto che scrivere è il modo con cui una vita viene continuamente riletta. L’opera non segue passivamente l’esistenza; la monta, la corregge e la trasforma in una forma condivisibile.</p>
      <h3>Il secondo tempo: ritorno alla forma</h3>
      <p>Con Sentimento del tempo, negli anni Venti e Trenta, la poesia cambia. Tornano punteggiatura, sintassi più complessa, versi della tradizione — in particolare endecasillabi e settenari — e un lessico più alto. Non è una resa né un ritorno al punto di partenza. Dopo aver liberato la parola, Ungaretti affronta la durata storica della lingua italiana e dialoga con Petrarca, Leopardi e il Barocco romano. Il paesaggio del Lazio, il mito, le stagioni e la meditazione religiosa chiedono un respiro diverso dall’annotazione di trincea.</p>
      <p>Esiste quindi una continuità sotto la differenza. Nell’Allegria il poeta cerca l’assoluto nell’istante e nella parola nuda; nel Sentimento del tempo lo cerca nel rapporto fra caducità e tradizione. In entrambi i casi la forma nasce dall’immagine del mondo. Prima il soggetto frammentario richiede un ritmo spezzato; poi la creatura davanti al tempo e all’eterno richiede architetture più ampie.</p>
      <h3>Ungaretti ed Ermetismo: una precisazione necessaria</h3>
      <p>È frequente chiamare Ungaretti “fondatore dell’Ermetismo”. L’etichetta è comoda ma imprecisa. L’Ermetismo in senso storico si sviluppa soprattutto negli anni Trenta attorno ad autori e critici più giovani; Ungaretti, insieme a esperienze come quella di Montale, offre un precedente decisivo per la concentrazione lirica e il valore assoluto della parola. È dunque un maestro e un antecedente, non il capo di una scuola con un programma unitario. Questa distinzione impedisce di interpretare l’essenzialità come oscurità deliberata. La sua poesia non vuole chiudere il significato: vuole sottrarlo alle formule consumate e riaprirlo.</p>`,
    bridge: 'La poetica va verificata nei testi e nelle raccolte: solo le opere mostrano se parola, silenzio, analogia e ritorno alla tradizione reggono il confronto con guerra, tempo e dolore.',
    summary: 'La poetica ungarettiana concentra il massimo peso nella parola necessaria. Il verso breve, lo spazio bianco e l’assenza di punteggiatura interrompono l’automatismo e affidano il ritmo ad a capo, pause e ripetizioni. L’analogia collega realtà lontane, ma resta controllata dall’esattezza dell’esperienza. Le coordinate diaristiche non equivalgono a spontaneità: Ungaretti riscrive a lungo le poesie e trasforma ogni edizione in una nuova organizzazione della memoria. Con Sentimento del tempo recupera punteggiatura, sintassi e metri tradizionali; non rinnega la prima stagione, ma cerca l’assoluto entro la durata storica della lingua. Anche il rapporto con l’Ermetismo va precisato: Ungaretti è un antecedente e un maestro decisivo, non semplicemente il fondatore di una scuola. La sua essenzialità vuole riaprire il senso, non renderlo oscuramente inaccessibile.',
    essentials: [
      'Spiegare che l’essenzialità è concentrazione semantica, non semplice brevità.',
      'Descrivere la funzione ritmica e significativa dello spazio bianco.',
      'Definire l’analogia come salto fra realtà lontane controllato dall’esperienza.',
      'Riconoscere negli a capo una forma di punteggiatura e di partitura del respiro.',
      'Smentire il mito della spontaneità attraverso il lavoro delle varianti.',
      'Interpretare il ritorno ai metri tradizionali come nuova fase della ricerca.',
      'Precisare che Ungaretti anticipa e influenza l’Ermetismo senza fondarlo come scuola.'
    ],
    glossary: [
      {term:'Parola scavata',definition:'Vocabolo reso necessario da un lavoro di sottrazione e dal suo rapporto profondo con l’esperienza.'},
      {term:'Versicolo',definition:'Verso molto breve, talvolta di una sola parola, che concentra accento e pausa.'},
      {term:'Spazio bianco',definition:'Elemento attivo della pagina che indica silenzio, distanza e durata del respiro.'},
      {term:'Paratassi',definition:'Accostamento di frasi o immagini coordinate, con pochi nessi subordinanti espliciti.'},
      {term:'Variante',definition:'Forma alternativa di un testo prodotta durante la riscrittura e conservata nelle diverse redazioni.'},
      {term:'Ermetismo',definition:'Tendenza lirica degli anni Trenta fondata su concentrazione e autonomia della parola; Ungaretti ne è un antecedente decisivo.'}
    ],
    map:'maps/04-poetica.svg',
    mapAlt:'La realtà fragile richiede sottrazione; la sottrazione concentra la parola e frantuma il verso; spazio bianco e a capo producono ritmo e silenzio; l’analogia collega concreto e mistero; le varianti mostrano un laboratorio continuo; Sentimento del tempo recupera la tradizione. Questa poetica influenza l’Ermetismo senza coincidere con esso.',
    questions: [
      q('Qual è il senso dell’essenzialità ungarettiana?',['Usare sempre il minor numero matematico di parole','Concentrare esperienza, suono e significato nella parola necessaria','Evitare ogni termine della lingua comune'],1,'La brevità è un possibile effetto del lavoro di concentrazione, non il suo scopo autonomo.','Essenzialità','Una parola è essenziale quando non può essere sostituita senza cambiare l’intero equilibrio del testo.','Il vocabolo comune, isolato, torna percepibile.','Essenziale significa soltanto corto?','No, significa necessario e concentrato.'),
      q('Che funzione svolge lo spazio bianco?',['È un elemento attivo di pausa, silenzio e risonanza','Serve soltanto a rendere il libro più lungo','Sostituisce il titolo delle poesie'],0,'Il bianco entra nella partitura del testo e condiziona lettura, respiro e senso.','Bianco attivo','La pagina non è un contenitore neutro: organizza il tempo della voce.','Una parola isolata riceve più peso e una pausa più lunga.','Il bianco è assenza o forma?','È un’assenza trasformata in forma.'),
      q('Che cosa dimostra lo studio delle varianti?',['Che i testi furono trascritti senza correzioni','Che l’apparente immediatezza nasce anche da una lunga riscrittura','Che tutte le edizioni sono identiche'],1,'Le diverse redazioni mostrano un laboratorio durato decenni.','Laboratorio testuale','Data e luogo documentano l’origine, ma non cancellano il lavoro successivo.','Un a capo tolto o ripristinato cambia ritmo e relazione fra immagini.','Il diario esclude la revisione?','No: l’istante viene continuamente rielaborato.'),
      q('Come va interpretato il recupero di metri tradizionali?',['Come abbandono definitivo dell’innovazione','Come imitazione passiva di D’Annunzio','Come nuova risposta al problema del tempo e della tradizione'],2,'Sentimento del tempo amplia la forma per misurarsi con storia della lingua, mito ed eterno.','Seconda stagione','La forma cambia perché cambia il problema dominante, non perché il poeta torna indietro.','Endecasillabi e settenari vengono attraversati dalla sensibilità moderna.','Recuperare significa restaurare?','No, significa trasformare una forma ereditata.'),
      q('Qual è la formulazione più precisa sul rapporto con l’Ermetismo?',['Ungaretti è un antecedente e maestro, non il fondatore programmatico di una scuola','Ungaretti non ha alcun rapporto con la lirica ermetica','L’Ermetismo nasce nelle trincee del 1915'],0,'La sua concentrazione lirica influenza gli ermetici, ma movimento, generazione e contesto non coincidono.','Etichette storico-letterarie','Un’etichetta è utile solo se non cancella differenze cronologiche e poetiche.','Poeti degli anni Trenta ricevono la lezione della parola concentrata.','Influenza equivale a identità?','No: si può preparare una tendenza senza coincidere con essa.')
    ]
  };

  const s5 = {
    title: 'Le opere più significative', short: 'Le opere', navHint: 'Dalla trincea al mito',
    card: 'Cinque cantieri, non un catalogo: ogni raccolta mette alla prova una diversa forma della parola.',
    question: 'In quali opere la poetica diventa forma concreta e conflitto ancora aperto?',
    lesson: `
      <h2>Un’opera che cambia mentre cerca la propria unità</h2>
      <p>Ungaretti raccoglie la propria produzione sotto il titolo Vita d’un uomo. L’espressione suggerisce un percorso unitario, ma non una linea senza svolte. Le raccolte sono cantieri: cambiano titolo, ordine, testi e varianti. Leggerle significa osservare come la stessa domanda — trovare una parola capace di attraversare la perdita — assuma forme diverse davanti alla guerra, al tempo, al lutto e al mito. Cinque nuclei permettono di seguire questa trasformazione senza ridurre l’opera a un inventario.</p>
      <h3>Il Porto Sepolto: scendere per riportare una traccia</h3>
      <p>Il piccolo libro stampato a Udine nel 1916, grazie all’intervento di Ettore Serra, nasce sul fronte ma possiede un titolo legato ad Alessandria d’Egitto. Il porto sommerso allude a qualcosa che esiste e non è immediatamente visibile. La funzione del poeta è immergersi, toccare il segreto e tornare con un frammento, non con una spiegazione totale. Commiato formula questa poetica attraverso l’immagine della parola scavata nella vita. Il testo è dedicato a Serra e chiude la raccolta collegando mondo, umanità, esperienza personale e linguaggio.</p>
      <p>In memoria apre invece il libro con Moammed Sceab: la poesia nasce dal nome di chi rischia di scomparire e dal problema di un canto impossibile. I fiumi ricompone le diverse appartenenze nell’acqua dell’Isonzo. Veglia porta il desiderio di vita alla massima vicinanza con il corpo morto. San Martino del Carso sovrappone il paese distrutto e il cuore che conserva le presenze degli amici. Non sono “temi di guerra” illustrati da versi; sono modi diversi di misurare ciò che la parola può salvare senza riparare.</p>
      <h3>Dall’Allegria di naufragi all’Allegria</h3>
      <p>Nel 1919 Allegria di naufragi amplia e riorganizza il primo libro. Il titolo ossimorico tiene insieme rovina e impulso a ricominciare. Nelle edizioni successive, fino alla forma dell’Allegria stabilizzata negli anni Trenta e poi ancora rivista, il poeta modifica il corpus. Questo lavoro rende la raccolta più di un diario della Grande Guerra: comprende l’infanzia egiziana, Parigi, il nomadismo, il ritorno e la memoria.</p>
      <p>Le liriche più brevi mostrano l’efficacia della concentrazione. In Mattina due sole parole semanticamente decisive trasformano un’esperienza luminosa in apertura smisurata; non raccontano, compiono un’espansione. Soldati costruisce invece una sospensione: titolo e similitudine si completano soltanto attraversando gli a capo. Fratelli trasforma una parola comune in gesto etico. La brevità non uniforma questi testi: ognuno dispone voce e silenzio in modo diverso.</p>
      <h3>Sentimento del tempo: il moderno dentro la tradizione</h3>
      <p>Pubblicato nel 1933 e poi ampliato, Sentimento del tempo sposta il centro dall’istante di guerra alla percezione della durata, delle stagioni e della distanza dall’eterno. Il paesaggio romano e laziale appare carico di stratificazioni: rovine, Barocco, mito e natura fanno percepire simultaneamente grandezza e caducità. La sintassi si distende, il lessico diventa più alto, ritornano punteggiatura e metri riconoscibili.</p>
      <p>La madre, composta dopo la morte della madre, unisce immaginazione religiosa e attesa personale: il ricongiungimento è pensato dentro il giudizio e il perdono, non come memoria sentimentale. In altri testi l’estate romana, la metamorfosi e il paesaggio diventano figure del tempo che consuma. La raccolta mette alla prova una domanda nuova: la parola liberata nell’Allegria può entrare nella storia della lingua senza perdere intensità? Ungaretti risponde recuperando la tradizione come tensione viva, non come repertorio.</p>
      <h3>Il Dolore: l’io davanti all’irreparabile</h3>
      <p>Il Dolore del 1947 raccoglie poesie nate fra la morte del fratello, quella del figlio Antonietto e gli anni della seconda guerra mondiale. Il tono è più apertamente elegiaco; la frase può spezzarsi nel grido o distendersi nella memoria. Giorno per giorno affronta l’assenza del figlio senza trasformarla in simbolo sostituibile: dettagli, voce e gesti ricordati attestano l’unicità di chi non c’è più. La sezione su Roma occupata porta la parola dentro una sofferenza collettiva diversa.</p>
      <p>Qui la poesia incontra il proprio limite. Non restituisce il morto, non giustifica la storia e non chiude il lutto. Può però rifiutare l’anonimato, conservare un appello e trasformare l’isolamento in forma comunicabile. La maturità di Ungaretti consiste anche nell’ammettere che la parola “scavata” non è onnipotente.</p>
      <h3>La Terra Promessa: frammento, mito, vecchiaia</h3>
      <p>La Terra Promessa, pubblicata nel 1950, nasce da un progetto più ampio e incompiuto ispirato al viaggio di Enea e alla figura di Didone. Del poema restano frammenti e cori. Il mito non offre evasione dal presente: consente di pensare desiderio, abbandono, destino e fine delle stagioni su una scala che unisce storia individuale e lunga durata culturale. L’incompiutezza stessa diventa significativa. La terra promessa resta meta desiderata, mai pienamente posseduta.</p>
      <p>Le raccolte tarde continuano il confronto con vecchiaia, paesaggio, eros e memoria. L’intera Vita d’un uomo appare così non come monumento immobile, ma come montaggio di ritorni. Il porto sommerso dell’inizio e la terra promessa della maturità descrivono lo stesso gesto da due lati: cercare un’origine nascosta e dirigersi verso una totalità che arretra. Fra i due estremi resta la poesia, capace non di possedere il senso, ma di riportarne frammenti necessari.</p>`,
    bridge: 'Dalle opere resta una lezione: la parola può custodire e mettere in relazione, ma non ripara magicamente la storia. La conclusione dovrà misurare questa eredità e le sue contraddizioni.',
    summary: 'Le raccolte ungarettiane sono cantieri in trasformazione. Il Porto Sepolto nasce nel 1916 sul fronte e affida al poeta il compito di riportare una traccia da una profondità non interamente spiegabile. Allegria di naufragi e poi L’Allegria riorganizzano l’esperienza di guerra entro un percorso più ampio di origini, nomadismo e memoria; Mattina, Soldati e Fratelli mostrano usi diversi della concentrazione. Sentimento del tempo recupera sintassi, metrica e tradizione per affrontare durata, mito, fede e caducità. Il Dolore porta la parola davanti alla morte del figlio e alla tragedia storica, riconoscendo che la poesia conserva ma non ripara. La Terra Promessa usa il mito di Enea e Didone in forma frammentaria: l’approdo resta desiderato e incompiuto. Vita d’un uomo è quindi unità mobile, costruita attraverso riscritture e ritorni.',
    essentials: [
      'Spiegare il porto sepolto come figura di una profondità da cui il poeta riporta frammenti.',
      'Riconoscere nell’Allegria una raccolta riscritta, più ampia di un semplice diario di guerra.',
      'Confrontare la funzione della brevità in Mattina, Soldati e Fratelli.',
      'Descrivere il nuovo classicismo di Sentimento del tempo come trasformazione della tradizione.',
      'Comprendere che Il Dolore preserva l’unicità del figlio e distingue sofferenza privata e pubblica.',
      'Interpretare l’incompiutezza della Terra Promessa come parte del suo significato.',
      'Definire Vita d’un uomo come progetto unitario ma non immobile.'
    ],
    glossary: [
      {term:'Silloge',definition:'Raccolta organizzata di testi poetici; in Ungaretti l’ordine cambia fra le edizioni e produce nuovi significati.'},
      {term:'Ossimoro',definition:'Unione di termini apparentemente contrari; “allegria” e “naufragi” esprimono una tensione, non un gioco decorativo.'},
      {term:'Elegia',definition:'Forma del lamento e della meditazione sulla perdita, centrale nel Dolore.'},
      {term:'Nuovo classicismo',definition:'Recupero moderno di metri, sintassi e tradizione, evidente in Sentimento del tempo.'},
      {term:'Macrotesto',definition:'Insieme di testi organizzati in modo da costruire un significato complessivo oltre le singole poesie.'},
      {term:'Frammento',definition:'Parte che dichiara la totalità assente; nella Terra Promessa è forma strutturale e tema dell’approdo incompiuto.'}
    ],
    map:'maps/05-opere.svg',
    mapAlt:'Il Porto Sepolto scava e riporta frammenti; L’Allegria riorganizza guerra, origini e vitalità; Sentimento del tempo recupera tradizione e durata; Il Dolore confronta lutto privato e storia; La Terra Promessa usa mito e frammento per un approdo incompiuto. Tutte le raccolte confluiscono nel progetto mobile Vita d’un uomo.',
    questions: [
      q('Che cosa simboleggia il “porto sepolto”?',['Una verità profonda da cui si riportano frammenti, non una spiegazione totale','Il luogo esatto in cui furono combattute le battaglie del Carso','La decisione di abbandonare Alessandria'],0,'Il poeta si immerge nel segreto dell’esperienza e torna con una parola limitata ma necessaria.','Porto e scavo','L’immagine unisce memoria alessandrina e funzione della poesia.','Commiato lega la parola scavata alla vita.','Il poeta possiede interamente il segreto?','No, ne porta alla luce un frammento.'),
      q('Perché L’Allegria non è soltanto un diario di guerra?',['Perché elimina tutte le poesie del fronte','Perché integra origini, Parigi, nomadismo e riscritture successive','Perché è stata composta interamente dopo il 1945'],1,'La raccolta conserva la guerra ma la colloca dentro l’intero itinerario dell’identità.','Macrotesto dell’Allegria','L’ordine e le varianti ampliano il significato dei testi datati.','I fiumi fa entrare Serchio, Nilo e Senna nel presente dell’Isonzo.','Una raccolta coincide con la somma cronologica?','No, l’organizzazione costruisce un percorso.'),
      q('Qual è il problema centrale di Sentimento del tempo?',['Come recuperare tradizione e durata senza perdere la modernità','Come descrivere tecnicamente le battaglie','Come fondare un partito letterario'],0,'La seconda stagione misura la parola con storia della lingua, caducità ed eterno.','Nuovo classicismo','Il ritorno metrico è una trasformazione moderna del passato.','Il paesaggio romano unisce stagioni, rovine e Barocco.','Quale tempo domina: solo l’istante o la durata?','La durata storica ed esistenziale.'),
      q('Quale limite della poesia emerge nel Dolore?',['La poesia non può essere letta ad alta voce','La poesia conserva e comunica, ma non restituisce il morto né giustifica la storia','La poesia deve rinunciare alla memoria'],1,'La parola resiste all’anonimato senza pretendere di riparare l’irreparabile.','Potere limitato della parola','La maturità riconosce insieme necessità e insufficienza del canto.','Il nome e i gesti del figlio restano, ma l’assenza non viene annullata.','Custodire equivale a risuscitare?','No: custodire riconosce anche il limite.'),
      q('Perché il frammento è adatto alla Terra Promessa?',['Perché il manoscritto fu distrutto integralmente','Perché rappresenta un approdo desiderato ma mai pienamente posseduto','Perché Ungaretti rifiutava ormai il mito'],1,'L’incompiutezza formale corrisponde alla tensione verso una totalità che arretra.','Frammento e meta','Il mito permette di pensare il destino senza chiuderlo in un racconto risolto.','Enea e Didone aprono desiderio, abbandono e fine delle stagioni.','La terra promessa è possesso o ricerca?','È ricerca di un approdo non definitivo.')
    ]
  };

  const s6 = {
    title: 'Conclusione: ciò che resta', short: 'Conclusione', navHint: 'Eredità e domanda',
    card: 'Una traiettoria ancora viva: sottrarre retorica, custodire i nomi, lasciare aperto il mistero.',
    question: 'Che cosa resta vivo e discutibile della lezione di Ungaretti?',
    lesson: `
      <h2>Una vita non diventa poesia da sola</h2>
      <p>Il percorso può essere ricomposto in una catena, purché non la si trasformi in destino inevitabile. Ungaretti riceve una grande tradizione poetica, la libertà delle avanguardie e la lezione simbolista; vive da sradicato fra culture diverse; la guerra rende intollerabile la lingua enfatica; da questa crisi emerge un’immagine dell’uomo precario e relazionale; la poetica concentra la parola e attiva il silenzio; le opere riscrivono nel tempo quella prima scoperta, fino al dolore e al mito. Nessun passaggio produce automaticamente il successivo. Ogni ponte è un atto di elaborazione e responsabilità.</p>
      <h3>La prima eredità: diffidare della parola già pronta</h3>
      <p>Ungaretti insegna che la retorica non coincide con uno stile ricco. È retorica ogni parola usata senza essere nuovamente verificata nell’esperienza. Anche un verso breve può diventare maniera, e infatti l’enorme fortuna della lirica concentrata ha generato imitazioni meccaniche. La sua lezione autentica non è “scrivere poco”, ma impedire che la lingua parli al posto nostro. L’essenzialità richiede ascolto, selezione, ritmo e coraggio del silenzio.</p>
      <p>Questa idea conserva un valore speciale nel presente, sommerso da messaggi, immagini e formule istantanee. Sarebbe però ingenuo trasformare Ungaretti nel profeta dei social network: la somiglianza quantitativa fra una lirica breve e un post non garantisce alcuna parentela. La differenza sta nel lavoro. Il frammento digitale tende spesso alla rapida sostituzione; il frammento poetico ungarettiano rallenta, obbliga a sostare e porta con sé le varianti di decenni.</p>
      <h3>La seconda eredità: custodire senza fingere di riparare</h3>
      <p>Da In memoria al Dolore, la poesia salva nomi, luoghi, date e gesti dalla cancellazione. Non “vince” la morte. Rifiuta però che l’individuo diventi una cifra anonima. In questo senso la parola poetica possiede una funzione etica: crea uno spazio in cui l’altro può essere chiamato e ricordato. La fraternità non è un sentimento generico; comincia dal riconoscere la vulnerabilità che condividiamo e la singolarità che non possiamo sostituire.</p>
      <p>Il limite è parte di questa etica. Quando la poesia pretende di spiegare il dolore altrui o di trasformarlo subito in consolazione, rischia di appropriarsene. Ungaretti è più forte quando lascia visibile la frattura. La parola necessaria non chiude la ferita: le dà una forma che può essere attraversata insieme.</p>
      <h3>Le contraddizioni come oggetto di giudizio</h3>
      <p>Un autore canonico non deve essere santificato. L’interventismo e l’adesione al fascismo obbligano a distinguere fra la profondità di alcune opere e la fallibilità delle scelte storiche. La poesia della fraternità non cancella tali responsabilità; semmai rende la contraddizione più esigente. Come può chi riconosce l’uomo esposto nella trincea affidarsi a un regime che trasforma la comunità in disciplina e violenza? Non esiste una risposta che assolva tutto. Esiste il dovere di non mutilare il profilo per ottenere un maestro senza ombre.</p>
      <p>Questa lettura non “annulla” Ungaretti. Al contrario, prende sul serio la sua idea di Vita d’un uomo: una vita contiene errori, svolte, revisioni e zone non conciliabili. Il giudizio critico è più rispettoso dell’agiografia perché non usa l’opera per fabbricare un monumento innocuo.</p>
      <h3>Fra innovazione e tradizione</h3>
      <p>L’altra eredità decisiva è la dimostrazione che moderno e antico non sono avversari fissi. La prima stagione spezza il verso; la seconda recupera metri e memorie letterarie. Entrambe combattono contro l’automatismo. La tradizione è viva quando torna problema, l’innovazione è viva quando non si riduce a marchio. Per questo Ungaretti influenza la poesia ermetica e molta lirica successiva senza poter essere chiuso in un’unica etichetta.</p>
      <p>La filologia delle varianti aggiunge una lezione didattica preziosa: scrivere è riscrivere. L’apparente semplicità può essere il risultato di un lavoro lungo, e la versione finale non cancella il processo che l’ha prodotta. Vedere i testi cambiare libera gli studenti dal mito romantico dell’ispirazione immediata e mostra la creazione come scelta verificabile.</p>
      <h3>Il porto e la promessa</h3>
      <p>Due immagini possono racchiudere l’intero itinerario. Il porto sepolto è un’origine nascosta verso cui si scende; la terra promessa è una meta verso cui si procede. Una sta sotto il passato, l’altra davanti al futuro. Nessuna viene posseduta interamente. Nel mezzo, l’uomo attraversa guerre, paesaggi, memoria, fede e lutto, raccogliendo frammenti di senso. La poesia non consegna la mappa definitiva: rende il viaggio abitabile.</p>
      <p>Resta allora una domanda aperta, non un esercizio con risposta corretta: una parola può davvero opporsi alla violenza della storia, oppure può soltanto testimoniare che qualcuno non ha accettato il silenzio imposto? Ungaretti non permette di scegliere comodamente. La sua opera mostra insieme la debolezza materiale della poesia e la sua ostinata necessità. Proprio questa tensione, più di qualsiasi formula sull’Ermetismo, continua a renderlo contemporaneo.</p>`,
    bridge: 'Il percorso torna al principio: dal mondo ricevuto alle fratture, dalla visione alla forma, dalle opere alla responsabilità di chi legge. Ora i sei nessi possono essere verificati insieme.',
    summary: 'La traiettoria di Ungaretti collega mondo ricevuto, fratture, visione, poetica e opere senza trasformare la vita in destino. La prima eredità è la diffidenza verso la parola già pronta: essenzialità significa verifica e lavoro, non brevità automatica. La seconda è la capacità di custodire nomi e presenze senza fingere che la poesia ripari la morte. Le contraddizioni politiche — interventismo e fascismo — devono restare visibili accanto alla forza dei testi. Ungaretti mostra inoltre che innovazione e tradizione possono servire la stessa lotta contro l’automatismo, e le varianti rivelano la scrittura come processo. Fra il porto sepolto, origine nascosta, e la terra promessa, meta mai posseduta, la poesia rende abitabile una ricerca incompiuta. Resta aperta la domanda sul potere reale della parola davanti alla violenza della storia.',
    essentials: [
      'Ricostruire l’intera catena causale senza presentarla come destino necessario.',
      'Distinguere l’essenzialità dalla semplice brevità, anche nel confronto con la comunicazione digitale.',
      'Spiegare la funzione etica della poesia come custodia di nomi e singolarità.',
      'Riconoscere che testimoniare il dolore non equivale a ripararlo o spiegarlo.',
      'Formulare un giudizio critico sulle scelte politiche senza cancellare né assolvere l’opera.',
      'Collegare innovazione e tradizione come due forme di lotta contro l’automatismo.',
      'Interpretare porto sepolto e terra promessa come origine e meta entrambe non possedute.'
    ],
    glossary: [
      {term:'Retorica',definition:'Uso di una lingua non più verificata nell’esperienza; può nascondersi anche dietro forme apparentemente semplici.'},
      {term:'Testimonianza',definition:'Atto di lasciare una traccia responsabile senza pretendere di esaurire o riparare l’evento.'},
      {term:'Canone',definition:'Insieme di opere riconosciute come centrali; va interrogato criticamente, non venerato.'},
      {term:'Agiografia',definition:'Racconto che trasforma una figura in modello senza ombre, cancellandone responsabilità e contraddizioni.'},
      {term:'Ricezione',definition:'Modo in cui un’opera viene letta, imitata e trasformata dalle generazioni successive.'},
      {term:'Riscrittura',definition:'Processo con cui un testo viene riconsiderato nel tempo; è parte della creazione, non semplice correzione.'}
    ],
    map:'maps/06-conclusione.svg',
    mapAlt:'Il mondo ricevuto prepara la domanda; le fratture modificano la visione; la fragilità e il mistero esigono una parola essenziale; la poetica diventa opera e riscrittura; le opere custodiscono senza riparare; l’eredità unisce responsabilità, giudizio critico e ricerca. Porto sepolto e terra promessa tengono aperto il viaggio.',
    questions: [
      q('Qual è l’eredità più precisa dell’essenzialità ungarettiana?',['Pubblicare testi il più brevi possibile','Verificare ogni parola contro esperienza, ritmo e silenzio','Rinunciare alla revisione'],1,'La lezione riguarda la necessità della forma, non la quantità dei caratteri.','Essenzialità oggi','La somiglianza esterna fra frammenti non dimostra la stessa qualità del lavoro.','Un testo di due righe può essere retorico; una poesia lunga può essere essenziale.','Che cosa decide l’essenzialità?','La necessità di ogni scelta nel testo.'),
      q('Quale funzione etica può avere la poesia?',['Custodire nomi e singolarità senza promettere una riparazione impossibile','Giustificare retroattivamente ogni tragedia','Sostituire la memoria storica con l’emozione'],0,'La parola contrasta l’anonimato ma riconosce il proprio limite materiale.','Custodia','Testimoniare significa lasciare spazio all’altro, non appropriarsi del suo dolore.','In memoria mantiene il nome di Sceab dentro una forma condivisa.','Custodire significa spiegare tutto?','No, significa preservare una presenza e una domanda.'),
      q('Come va esercitato il giudizio sulle contraddizioni politiche?',['Separando totalmente autore e storia','Tenendo insieme responsabilità delle scelte e analisi autonoma dei testi','Assolvendo l’autore grazie alla fama poetica'],1,'La lettura critica rifiuta sia la santificazione sia la cancellazione.','Giudizio critico','Un’opera importante non rende innocente ogni scelta del suo autore.','La poesia della fraternità rende ancora più visibile la contraddizione con il fascismo.','Criticare significa annullare?','No, significa leggere l’intero profilo.'),
      q('Che cosa unisce rottura metrica e recupero della tradizione?',['La lotta contro l’automatismo della lingua','Il rifiuto di ogni forma moderna','L’obbedienza allo stesso programma di scuola'],0,'Le due stagioni cambiano mezzi ma chiedono entrambe che la forma torni necessaria.','Moderno e antico','Innovare e recuperare possono essere gesti equivalenti se riaprono il senso.','Il verso spezzato e l’endecasillabo trasformato rispondono a problemi diversi.','Tradizione e innovazione sono sempre opposte?','No, possono collaborare contro la forma consumata.'),
      q('Che rapporto unisce porto sepolto e terra promessa?',['Sono due luoghi visitati nello stesso anno','Rappresentano origine nascosta e meta desiderata, entrambe non possedute','Indicano il rifiuto del viaggio'],1,'Le due immagini incorniciano una ricerca di senso che resta incompiuta.','Origine e meta','La poesia porta frammenti dal profondo e procede verso una totalità che arretra.','Fra discesa e cammino si colloca Vita d’un uomo.','Il senso viene posseduto definitivamente?','No, viene cercato e testimoniato per frammenti.')
    ]
  };

  const finalTest = [
    q('Quale limite del mondo precedente prepara la poesia di guerra?',['La tradizione non possiede alcun ritmo','La lingua alta rischia di coprire l’esperienza con la retorica','Il simbolismo proibisce le immagini'],1,'La trincea rende moralmente insufficiente una parola automatica o enfatica.','Dal mondo alla frattura','La prima sezione prepara il problema che la guerra rende urgente.','Tradizione, simbolismo e avanguardia offrono risorse ma nessuna soluzione pronta.','Qual è la domanda iniziale?','Come dire il vero senza retorica.'),
    q('Quale frattura trasforma più direttamente la ricerca formale in necessità etica?',['L’esperienza della trincea','Il trasferimento a Roma','Il successo editoriale'],0,'La guerra mette la lingua davanti alla morte industriale e all’anonimato.','Dalla frattura alla visione','L’esperienza estrema verifica le tecniche già preparate dalla formazione.','Il verso breve non nasce dal nulla, ma acquista nel Carso una necessità nuova.','La guerra inventa o rende necessario?','Rende necessaria una ricerca già avviata.'),
    q('Quale immagine dell’uomo emerge dalle fratture?',['Creatura fragile ma capace di relazione e apertura','Eroe autosufficiente che domina la storia','Individuo privo di memoria'],0,'Precarietà, fraternità e confluenza della memoria definiscono l’uomo ungarettiano.','Dalla visione alla poetica','La forma deve rispettare limite concreto ed eccedenza del significato.','Soldati universalizza una precarietà nata al fronte.','Fragilità esclude relazione?','No, la rende più urgente.'),
    q('Quale scelta formale risponde meglio a questa visione?',['Una lingua esplicativa che chiuda ogni significato','Parola concentrata, analogia e silenzio attivo','Una metrica identica in tutte le raccolte'],1,'La poetica unisce esattezza dell’istante e apertura del mistero.','Dalla visione alla forma','La pagina rende percepibile la precarietà attraverso frammento e pausa.','Lo spazio bianco obbliga il lettore a sostare e ricomporre.','La poesia esaurisce il mistero?','No, gli dà una forma attraversabile.'),
    q('Quale opera mostra con maggiore evidenza il recupero moderno della tradizione?',['Sentimento del tempo','Il Porto Sepolto del 1916','In memoria considerata isolatamente'],0,'La raccolta recupera metri, sintassi, mito e paesaggio storico senza tornare semplicemente al passato.','Poetica nelle opere','Il nuovo classicismo è il secondo tempo della stessa ricerca.','Endecasillabi e memoria barocca affrontano durata e caducità.','Recupero significa restaurazione?','No, significa trasformazione moderna.'),
    q('Quale eredità ricompone l’intero percorso?',['La poesia risolve definitivamente il dolore','La parola necessaria custodisce e interroga, riconoscendo il proprio limite','La brevità è superiore a ogni altra forma'],1,'La forza della poesia sta nella testimonianza responsabile, non nell’onnipotenza.','Dalle opere all’eredità','Porto sepolto e terra promessa indicano una ricerca non conclusa.','La parola conserva un nome ma non restituisce il morto.','Qual è il potere realistico della poesia?','Creare memoria e relazione senza fingere di riparare tutto.')
  ];

  window.UNGARETTI_DATA = {
    methodNote: 'Il Google Doc fornito è stato usato come base e controllato criticamente. Le affermazioni sono state verificate con fonti istituzionali e universitarie; i siti scolastici, blog e aggregatori presenti nella bibliografia originaria non sono stati usati come prova. Le interpretazioni biografiche sono formulate come nessi plausibili, non come causalità automatiche.',
    sources: [
      {label:'Materiale di base fornito dal docente (Google Doc)',url:'https://docs.google.com/document/d/1nP0o1408CrgLy8P9_Kd2R1iHKef_6Yi0AEB0eUz_YLE/edit',use:'struttura iniziale, opere e selezione dei testi; sottoposto a controllo'},
      {label:'S. Colangelo, “Giuseppe Ungaretti”, Dizionario Biografico degli Italiani, Treccani',url:'https://www.treccani.it/enciclopedia/giuseppe-ungaretti_%28Dizionario-Biografico%29/',use:'cronologia, formazione, guerra, scelte politiche e carriera'},
      {label:'D. Baroncini, Ungaretti, scheda IRIS Università di Bologna',url:'https://cris.unibo.it/handle/11585/93708',use:'profilo delle stagioni poetiche e nuovo classicismo'},
      {label:'M. Benussi, Un’analisi semantica del Porto Sepolto, Università di Padova',url:'https://thesis.unipd.it/handle/20.500.12608/44146',use:'percorsi semantici, carteggi e maturazione del primo libro'},
      {label:'A. D’Ambrosio, “In principio era il verso”, Università di Firenze',url:'https://flore.unifi.it/handle/2158/1321931',use:'varianti, alleggerimento retorico e frantumazione metrica'},
      {label:'Letteratura italiana moderna e contemporanea, Università di Bari',url:'https://www.uniba.it/it/docenti/tuccini-giona/attivita-didattica/prof-tuccini-testi-lett-ita-mod-cont-1.pdf',use:'riscontro testuale e contesto delle liriche'},
      {label:'M. Migliorati, Memoria e innocenza, Università Cattolica',url:'https://publicatt.unicatt.it/retrieve/440b941c-5cb4-4ab6-9a43-f5fff4fa57e9/tesiphd_completa_Migliorati.pdf',use:'poetica critica, memoria e innocenza'}
    ],
    sections:[s1,s2,s3,s4,s5,s6], finalTest
  };
})();
