/* Contenuti originali elaborati dalla dispensa fornita dal docente. */
const Q = (prompt, options, answer, explanation, concept, clarification, example, check, checkAnswer) => ({prompt, options, answer, explanation, recovery:{concept, clarification, example, check:[...check, checkAnswer]}});

window.PASOLINI_COURSE = [
{
  id:'mondo', number:'01', title:'Il mondo precedente', short:'Un’Italia di culture plurali',
  question:'Che cosa esisteva prima che la società dei consumi trasformasse gli italiani in consumatori somiglianti?',
  hook:'Prima del nuovo potere non c’era un paradiso: c’era però una pluralità di mondi che non parlavano ancora con una voce sola.',
  lesson:[
`Per capire Pasolini bisogna cominciare da ciò che il suo sguardo vede scomparire. L’Italia nella quale nasce, nel 1922, non è ancora una società industriale unificata dai consumi e dalla televisione. È un paese politicamente unitario ma antropologicamente plurale: città e campagne, Nord e Sud, italiano e dialetti, cultura borghese e culture popolari convivono senza fondersi. Le disuguaglianze sono profonde e la povertà non va idealizzata; tuttavia contadini, artigiani e sottoproletari possiedono linguaggi, riti e criteri di valore non interamente prodotti dal mercato. Questo è il “mondo precedente” che Pasolini eredita: non un’età dell’oro, ma una realtà ancora resistente all’omologazione.`,
`La prima forza che tenta di rendere uniforme questo paese è il fascismo. Il regime non vuole soltanto il consenso politico: costruisce un italiano modello, disciplina i corpi, impone simboli, retoriche e una lingua nazionale, diffida dei dialetti perché custodiscono appartenenze locali difficili da controllare. Il giovane Pasolini si forma dentro questa pressione uniformante, ma la sua risposta poetica nasce ai margini. Quando nel 1942 pubblica Poesie a Casarsa in friulano, sceglie una lingua minoritaria che il potere considera inferiore. Quel gesto non è ancora realismo sociale: è la ricerca di una lingua assoluta, musicale e separata dalla retorica ufficiale. Proprio perché quasi privata, quella lingua diventa una forma di opposizione.`,
`Il Friuli materno offre a Pasolini il primo laboratorio di questa alterità. Casarsa è il luogo stabile di un’infanzia segnata dagli spostamenti dovuti alla carriera militare del padre. Nella memoria del poeta il paese si trasfigura: campi, rogge, ragazzi e parlata locale compongono un paesaggio insieme concreto e mitico. “Mitico” non significa falso; significa sottratto al tempo lineare del progresso e percepito come origine. Pasolini vede nel mondo contadino una vicinanza alla terra, al corpo, alla morte e al sacro che la modernità borghese tende a rimuovere. È uno sguardo partecipe ma anche esterno: egli appartiene alla piccola borghesia colta e sa che quell’innocenza è, almeno in parte, una costruzione poetica.`,
`Dopo la guerra, un’altra immagine del futuro sembra possibile. La Resistenza, la nascita della Repubblica, il movimento operaio e il Partito comunista promettono emancipazione collettiva. Il marxismo offre a Pasolini categorie per leggere lo sfruttamento e per non trasformare la povertà in folclore. Ma egli non accetta mai che la storia cancelli ciò che non rientra nello schema del progresso. Da Gramsci ricava l’attenzione per la cultura nazionale-popolare e per il conflitto tra egemonia e subalternità; nello stesso tempo conserva una religiosità senza Chiesa, una nostalgia del sacro e un legame sensuale con le forme premoderne. La sua posizione nascerà proprio dall’attrito tra ragione storica e fedeltà alle origini.`,
`Roma, dove arriva nel 1950, gli mostra un secondo mondo precedente: le borgate. Non sono villaggi incontaminati, ma periferie prodotte dall’espulsione sociale, abitate da immigrati, disoccupati e giovani che vivono di espedienti. Pasolini vi riconosce tuttavia una cultura autonoma, con un proprio gergo, gesti, codici d’onore e forme di vitalità. La borgata sostituisce il Friuli come luogo in cui la storia ufficiale non è ancora riuscita a integrare tutti. Nei ragazzi romani egli non vede “buoni selvaggi”: vede corpi esposti alla fame e alla violenza, ma non ancora educati a desiderare le stesse merci e lo stesso stile di vita della borghesia.`,
`Intorno a questi mondi agisce la tradizione culturale italiana. Pascoli gli insegna che le realtà umili possono entrare nella poesia senza perdere densità simbolica; Roberto Longhi gli insegna a leggere la realtà come una composizione figurativa, mettendo in relazione volti popolari e pittura sacra. Il neorealismo porta nel romanzo e nel cinema l’Italia esclusa dalla rappresentazione ufficiale. Pasolini attraversa queste eredità senza coincidere con esse: dal neorealismo prende l’urgenza del reale, ma rifiuta l’illusione di uno sguardo puramente documentario; dalla poesia novecentesca prende la concentrazione linguistica, ma la contamina con dialetti, gerghi e discorso politico.`,
`Poi arriva il boom economico. Tra la fine degli anni Cinquanta e gli anni Sessanta industria, migrazioni interne, elettrodomestici, automobile, scuola di massa e televisione modificano il paese con una velocità mai conosciuta. Milioni di persone migliorano concretamente le proprie condizioni materiali: sarebbe falso negarlo. Pasolini, però, distingue lo sviluppo economico dal progresso umano. Si chiede quale prezzo culturale venga pagato quando l’emancipazione coincide con l’adozione obbligata dei modelli borghesi. Il suo bersaglio non è il benessere in sé, ma un benessere che pretende di cancellare ogni differenza e di trasformare bisogni storicamente prodotti in desideri naturali.`,
`Il problema iniziale può allora essere formulato con precisione. Pasolini non difende semplicemente il passato contro il presente. Usa il passato come termine di confronto per rendere visibile un mutamento che i contemporanei chiamano soltanto modernizzazione. Dove altri vedono più merci e più libertà privata, egli vede anche perdita di lingue, gesti e forme comunitarie. Dove altri considerano la televisione un mezzo neutrale, egli scorge una scuola senza contraddittorio. Il “mondo precedente” è dunque la misura critica del nuovo: una pluralità imperfetta ma reale, la cui scomparsa permette a Pasolini di riconoscere il volto culturale del potere consumistico.`
  ],
  summary:`Pasolini nasce in un’Italia politicamente unita ma culturalmente plurale, attraversata da dialetti, culture contadine, differenze regionali e profonde disuguaglianze. Il fascismo tenta una prima uniformazione autoritaria; Pasolini reagisce scegliendo il friulano come lingua poetica. Nel dopoguerra il marxismo e Gramsci gli offrono gli strumenti per leggere lo sfruttamento, senza cancellare la sua attrazione per il sacro e per i mondi premoderni. A Roma scopre nelle borgate un’altra cultura marginale, violenta e vitale, non ancora assorbita dai modelli borghesi. Pascoli, Longhi e il neorealismo contribuiscono alla sua educazione letteraria e visuale. Il boom economico migliora molte condizioni materiali, ma produce anche una rapida uniformazione dei desideri e dei comportamenti. Per Pasolini il passato non è un paradiso da restaurare: è il termine di confronto che rende visibile la trasformazione del popolo in massa di consumatori. Da qui nasce la distinzione decisiva fra sviluppo economico e progresso umano.`,
  essentials:[
    ['Pluralità italiana','Spiegare perché l’Italia preindustriale fosse composta da culture locali autonome e non da una massa uniforme.'],
    ['Dialetto come opposizione','Mostrare perché il friulano di Poesie a Casarsa contrasti l’unificazione linguistica fascista.'],
    ['Friuli e borgate','Confrontare i due mondi marginali senza trasformarli in paradisi innocenti.'],
    ['Gramsci e sacro','Spiegare la compresenza di analisi marxista e nostalgia religiosa.'],
    ['Sviluppo e progresso','Distinguere la crescita economica dal miglioramento umano e culturale.'],
    ['Funzione del passato','Comprendere il passato come misura critica del presente, non come programma di restaurazione.']
  ],
  vocab:[
    ['Omologazione','Riduzione delle differenze culturali a modelli uniformi di comportamento e desiderio.'],
    ['Subalterno','Gruppo sociale privo di potere egemonico e di pieno accesso alla rappresentazione.'],
    ['Nazionale-popolare','In Gramsci, cultura capace di legare intellettuali e popolo in una storia comune.'],
    ['Arcaico','Ciò che appartiene a forme di vita anteriori alla modernizzazione industriale.'],
    ['Sacro','Dimensione della realtà non riducibile a utilità, mercato o spiegazione razionale.'],
    ['Sviluppo','Crescita produttiva e materiale, distinta da un autentico progresso civile.']
  ],
  map:'maps/01-mondo.svg',
  mapAlt:'Mappa: l’Italia plurale viene prima uniformata dal fascismo e poi trasformata dal boom; Friuli e borgate custodiscono culture autonome; Gramsci e il sacro confluiscono nello sguardo critico di Pasolini; la distinzione tra sviluppo e progresso apre la critica al consumismo.',
  questions:[
    Q('Perché il “mondo precedente” non va interpretato come un paradiso perduto?',['Perché era già industriale e uniforme','Perché conservava pluralità culturali ma anche povertà e violenza','Perché Pasolini non conobbe direttamente Friuli e borgate'],1,'Era un mondo plurale e autonomo, non innocente né privo di conflitti.','Passato critico','Idealizzare il passato cancellerebbe le disuguaglianze che Pasolini conosceva. La sua funzione è comparativa.','Le borgate sono insieme vitali e segnate da fame, esclusione e violenza.',['Il passato serve soprattutto a…','misurare ciò che il presente cancella','negare ogni miglioramento materiale'],0),
    Q('Quale significato assume inizialmente la scelta del friulano?',['Un gesto poetico contro l’uniformazione linguistica','Una trascrizione realistica del parlato familiare','Un modo per raggiungere il pubblico nazionale'],0,'Il friulano è una lingua poetica minoritaria opposta alla retorica nazionale del fascismo.','Lingua minoritaria','Pasolini non sceglie il friulano per comunicare con più persone, ma per creare una lingua separata e musicale.','Poesie a Casarsa trasforma una parlata locale in lingua di poesia.',['La scelta del dialetto produce…','maggiore uniformità','una differenza resistente'],1),
    Q('Che cosa distingue, per Pasolini, sviluppo e progresso?',['Lo sviluppo riguarda solo le campagne, il progresso solo le città','Sono due parole equivalenti','Lo sviluppo è crescita economica; il progresso implica qualità umana e civile'],2,'La crescita dei consumi non garantisce automaticamente libertà, cultura o giustizia.','Sviluppo/progresso','Una società può produrre più beni senza diventare più autonoma o giusta.','Il boom porta elettrodomestici e mobilità, ma anche perdita di culture locali.',['Più merci significano necessariamente più progresso?','Sì, sempre','No, è un nesso da verificare'],1),
    Q('Perché le borgate diventano un secondo laboratorio per Pasolini?',['Perché vi trova una cultura marginale non ancora pienamente borghese','Perché rappresentano la Roma monumentale','Perché sono comunità rurali rimaste intatte'],0,'Nelle borgate Pasolini incontra codici, gerghi e corpi esclusi dalla cultura dominante.','Borgata','La borgata è periferia moderna e povera, non villaggio rurale. Possiede però una cultura non ancora assimilata.','Ragazzi di vita nasce dall’immersione nel gergo e nella vita delle periferie romane.',['La borgata è soprattutto…','una periferia sociale autonoma','un museo del mondo contadino'],0),
    Q('Quale funzione svolge Gramsci nella formazione pasoliniana?',['Giustifica il rifiuto di ogni politica','Offre categorie per leggere egemonia, popolo e subalternità','Elimina la dimensione religiosa della sua poetica'],1,'Gramsci permette a Pasolini di leggere storicamente le culture popolari senza risolvere le sue contraddizioni.','Eredità gramsciana','Il marxismo fornisce strumenti critici; non cancella la nostalgia del sacro.','Nelle Ceneri di Gramsci Pasolini si dichiara insieme vicino e lontano dal pensatore comunista.',['Gramsci aiuta Pasolini a…','analizzare i rapporti culturali di potere','scegliere una fede dogmatica'],0)
  ]
},
{
  id:'fratture', number:'02', title:'Le fratture della vita', short:'Origini, esclusioni, passaggi',
  question:'Quando una biografia diventa forma e pensiero, senza ridursi a spiegazione psicologica dell’opera?',
  hook:'Pasolini non scrive “a causa” delle sue ferite: le trasforma in domande sulla lingua, sul potere e sull’appartenenza.',
  lesson:[
`La vita di Pasolini entra continuamente nell’opera, ma il rapporto non è meccanico. Un lutto non “produce” automaticamente una poesia, né un’esclusione sociale spiega da sola una poetica. Le esperienze diventano letteratura quando sono rielaborate in forme, immagini e conflitti intellettuali. Per questo conviene parlare di fratture: momenti in cui un’appartenenza si spezza e costringe l’autore a ridefinire il proprio sguardo. La mobilità infantile, il legame con la madre, la guerra, la morte del fratello, l’espulsione dal Partito comunista, l’esilio romano e i processi non sono curiosità biografiche. Sono soglie attraverso cui Pasolini comprende di essere, ogni volta, dentro e fuori il mondo che descrive.`,
`La prima frattura è già familiare e geografica. Il padre Carlo Alberto, ufficiale, incarna autorità, disciplina e instabilità; la madre Susanna lega Pasolini a Casarsa e alla lingua friulana. Sarebbe riduttivo trasformare questa opposizione in una diagnosi. Letterariamente essa organizza però una polarità durevole: da una parte la norma, l’istituzione, la lingua del potere; dall’altra l’origine materna, il corpo, il dialetto, il sacro. Il Friuli diventa patria scelta proprio perché la vita familiare non possiede un luogo stabile. In seguito Pasolini riprenderà questa materia in poesia e nel cinema, fino a Edipo re, ma sempre deformandola e universalizzandola. L’autobiografia è una materia, non la chiave che apre ogni opera.`,
`La guerra spezza il paesaggio friulano. Nel febbraio 1945 il fratello Guido, partigiano della Osoppo, viene ucciso a Porzûs da partigiani comunisti. Il fatto imprime una contraddizione profonda nel rapporto di Pasolini con il comunismo. Egli si iscrive comunque al PCI nel 1947, perché riconosce nella lotta di classe una possibilità di giustizia; non dimentica però che una disciplina ideologica può trasformarsi in violenza contro chi non coincide con la linea dominante. Da questa ferita non nasce un anticomunismo: nasce un marxismo eretico, affettivamente legato agli oppressi e diffidente verso ogni apparato che pretenda di possedere tutta la verità.`,
`La frattura decisiva avviene nel 1949. Dopo una denuncia legata a fatti sessuali, Pasolini perde l’incarico di insegnante ed è espulso dalla federazione comunista di Pordenone per “indegnità morale e politica”. Nel clima dell’epoca, l’omosessualità viene usata per squalificarlo pubblicamente. È essenziale distinguere due piani: gli atti specifici appartengono alla vicenda giudiziaria; la reazione sociale e politica rivela un sistema che trasforma la diversità in colpa totale. Pasolini sperimenta sulla propria persona la violenza del conformismo. Da allora la parola “diverso” non indicherà soltanto una condizione privata: diventerà un punto di osservazione sul modo in cui una società costruisce e punisce la norma.`,
`Nel gennaio 1950 la fuga a Roma con la madre è un vero esilio. Pasolini lascia il Friuli, il lavoro, il partito e una reputazione distrutta. I primi mesi romani sono segnati dalla povertà, ma proprio il declassamento gli impedisce di osservare le periferie dall’alto. Entra in contatto con i ragazzi delle borgate, ne studia il gergo, ne segue i percorsi. Non diventa uno di loro e non finge di esserlo: la distanza resta. Tuttavia quella distanza è attraversata dal desiderio, dalla solidarietà e dalla ricerca linguistica. I romanzi romani nasceranno da questa posizione scomoda, partecipe e insieme esterna, che evita tanto la neutralità sociologica quanto la piena identificazione.`,
`Il successo non ricompone la frattura. Con Ragazzi di vita, Una vita violenta e poi con il cinema, Pasolini diventa una figura centrale della cultura italiana, ma anche un bersaglio continuo. Processi per oscenità, sequestri, aggressioni giornalistiche e accuse politiche accompagnano la sua produzione. Il caso della Ricotta, per il quale viene condannato per vilipendio alla religione di Stato, mostra il paradosso: un autore ossessionato dal sacro viene perseguito come nemico della religione. Pasolini trasforma lo scandalo in metodo pubblico. Non cerca semplicemente di scioccare; forza la società a mostrare ciò che considera dicibile, rappresentabile e accettabile.`,
`Negli anni Sessanta un’altra frattura investe il suo stesso oggetto d’amore. Il sottoproletariato romano, che aveva immaginato come esterno alla borghesia, entra nella società dei consumi. Cambiano corpi, linguaggio, desideri. Pasolini vive questa trasformazione come perdita e quasi come tradimento, ma comprende che non è una scelta individuale dei ragazzi: è l’effetto di un potere capace di penetrare la vita quotidiana. Da qui il passaggio dalla fiducia nella rappresentazione popolare alla diagnosi apocalittica degli Scritti corsari e di Salò. Anche l’abiura dalla Trilogia della vita nasce da una frattura: le immagini di corpi liberi possono essere recuperate dal mercato pornografico e rovesciate nel loro contrario.`,
`La morte violenta all’Idroscalo di Ostia, nella notte tra il primo e il 2 novembre 1975, è l’ultima frattura, ma non va trasformata in una conclusione già scritta. Pino Pelosi fu condannato; successive ritrattazioni, incongruenze e ipotesi di complicità hanno lasciato aperte domande che la ricostruzione giudiziaria non ha definitivamente chiuso. È legittimo studiare il valore simbolico assunto dall’omicidio; non è legittimo presentarlo come prova automatica di una profezia o di un complotto. Pasolini aveva rappresentato spesso sacrificio e persecuzione, ma la sua opera non conduce necessariamente alla morte. La responsabilità critica consiste nel resistere sia all’agiografia sia alla denigrazione e nel tornare ai testi.`
  ],
  summary:`Le fratture biografiche di Pasolini diventano significative quando vengono trasformate in forme e problemi, non quando sono usate come spiegazioni psicologiche automatiche. L’instabilità familiare e il legame materno fanno del Friuli una patria poetica; la morte del fratello Guido a Porzûs rende contraddittorio il rapporto con il comunismo. Nel 1949 la denuncia, la perdita del lavoro e l’espulsione dal PCI mostrano la violenza sociale esercitata contro l’omosessualità. La fuga a Roma nel 1950 è un esilio che conduce Pasolini alle borgate e a una nuova lingua narrativa. Successo, processi e polemiche consolidano la sua posizione di intellettuale insieme interno ed esterno alla cultura nazionale. Negli anni Sessanta la trasformazione consumistica del sottoproletariato spezza anche il suo oggetto poetico. L’omicidio del 1975 rimane segnato da questioni controverse, ma non deve essere letto come destino inevitabile né usato per sostituire l’analisi delle opere. Il nesso costante è l’esperienza della diversità come punto di osservazione sulla norma.`,
  essentials:[
    ['Biografia non deterministica','Spiegare come un’esperienza diventi opera solo attraverso una rielaborazione formale.'],
    ['Porzûs','Collegare la morte di Guido al marxismo eretico, non a un semplice anticomunismo.'],
    ['1949','Comprendere denuncia, perdita del lavoro ed espulsione come frattura sociale e politica.'],
    ['Esilio romano','Mostrare come il declassamento apra l’incontro con le borgate.'],
    ['Scandalo pubblico','Interpretare processi e polemiche come rivelatori dei confini sociali del dicibile.'],
    ['Morte e metodo','Distinguere fatti accertati, ipotesi giudiziarie e letture simboliche.']
  ],
  vocab:[
    ['Frattura','Svolta che spezza un’appartenenza e costringe a ridefinire il proprio sguardo.'],
    ['Diversità','Condizione trasformata da Pasolini da stigma privato a posizione critica.'],
    ['Esilio','Allontanamento materiale e simbolico dal luogo e dalla comunità d’origine.'],
    ['Marxismo eretico','Adesione alla giustizia sociale unita al rifiuto del dogmatismo di partito.'],
    ['Agiografia','Racconto celebrativo che trasforma una persona complessa in santo o martire.'],
    ['Controverso','Non definitivamente chiarito dalle prove disponibili; non equivale a falso o a provato.']
  ],
  map:'maps/02-fratture.svg',
  mapAlt:'Mappa: famiglia e nomadismo conducono al Friuli materno; Porzûs mette in crisi l’appartenenza comunista; il 1949 produce esclusione; l’esilio apre Roma e le borgate; processi e mutazione del sottoproletariato alimentano la voce corsara; la morte richiede distinzione tra fatti e interpretazioni.',
  questions:[
    Q('Che cosa significa evitare il determinismo biografico?',['Negare che la vita entri nelle opere','Considerare ogni opera come cronaca fedele','Studiare come l’esperienza venga trasformata da linguaggio e forma'],2,'La biografia è materia dell’opera, non una causa sufficiente che la spiega automaticamente.','Biografia e forma','Tra evento e testo interviene un lavoro di selezione, deformazione e costruzione.','Edipo re usa materiali familiari ma li trasforma in mito e allegoria.',['Un lutto produce da solo una poesia?','No, serve una rielaborazione formale','Sì, in modo automatico'],0),
    Q('Quale effetto ha Porzûs sul rapporto di Pasolini con il comunismo?',['Lo rende un marxista critico degli apparati e del dogmatismo','Lo conduce subito alla destra politica','Non ha alcun effetto sulla sua posizione'],0,'La morte di Guido apre una contraddizione: giustizia sociale sì, disciplina cieca no.','Porzûs','Pasolini non abbandona l’ideale comunista, ma diffida di chi identifica il partito con la verità.','Si iscrive al PCI dopo la morte del fratello, mantenendo una ferita irrisolta.',['La contraddizione genera…','obbedienza assoluta','un marxismo eretico'],1),
    Q('Perché il 1949 è una frattura decisiva?',['Perché esordisce nel cinema','Perché viene eletto in Parlamento','Perché perde lavoro e appartenenza politica dopo lo scandalo'],2,'La vicenda trasforma una condizione privata in esclusione pubblica e costringe Pasolini a lasciare il Friuli.','Esclusione','La società non giudica solo un fatto: usa l’omosessualità per definire l’intera persona come indegna.','L’espulsione dal PCI e la perdita dell’insegnamento precedono la fuga a Roma.',['Dopo il 1949 Pasolini…','resta integrato a Casarsa','vive un esilio materiale e simbolico'],1),
    Q('Qual è la posizione di Pasolini rispetto ai ragazzi delle borgate?',['È un osservatore partecipe ma non identico a loro','È un sociologo completamente neutrale','Finge di appartenere alla stessa classe sociale'],0,'La forza dei romanzi nasce dalla tensione tra immersione, desiderio e distanza.','Partecipazione e distanza','Pasolini studia il gergo e condivide la vita periferica, ma resta un intellettuale piccolo-borghese.','Ragazzi di vita usa la lingua delle borgate senza cancellare la regia dell’autore.',['La distanza dell’autore viene…','negata','attraversata ma mantenuta'],1),
    Q('Come va trattata criticamente la morte di Pasolini?',['Come prova certa di un complotto politico','Come destino inevitabile annunciato dalle opere','Distinguendo sentenza, dubbi successivi e interpretazioni simboliche'],2,'Il metodo storico non trasforma una questione aperta in certezza e non fa dell’opera una profezia giudiziaria.','Fatto e interpretazione','Valore simbolico e ricostruzione penale sono piani diversi.','La condanna di Pelosi è un fatto; le ipotesi di mandanti restano oggetto di discussione.',['Una lettura simbolica è una prova penale?','Sì','No'],1)
  ]
},
{
  id:'immagine', number:'03', title:'L’immagine del mondo', short:'Mutazione, potere, sacro',
  question:'Che forma assume il potere quando non vieta, ma persuade tutti a volere la stessa vita?',
  hook:'Il nuovo fascismo non marcia in uniforme: entra nelle case, parla dalla televisione e promette felicità in cambio della differenza.',
  lesson:[
`Pasolini non costruisce un sistema filosofico ordinato. Il suo pensiero procede per immagini, polemiche, revisioni e contraddizioni. Questa mobilità non autorizza però a ridurlo a una raccolta di profezie. Al centro resta una domanda coerente: che cosa accade alla realtà umana quando il potere economico riesce a trasformare cultura, corpi e desideri? Negli anni Sessanta e Settanta Pasolini osserva che il capitalismo italiano non si limita più a sfruttare il lavoro. Produce modelli di vita, impone un’idea di felicità e rende desiderabile l’integrazione. Il potere diventa antropologico: non chiede soltanto obbedienza esterna, ma modifica dall’interno coloro che lo subiscono.`,
`Per descrivere questa novità Pasolini usa l’espressione provocatoria “nuovo fascismo”. Il fascismo storico aveva tentato di uniformare gli italiani attraverso Stato, scuola, censura e violenza, senza cancellare davvero le culture profonde del paese. La società dei consumi, secondo lui, ottiene un risultato più radicale per mezzo della seduzione. Pubblicità, merci e televisione definiscono ciò che è moderno, bello e desiderabile; chi non aderisce prova vergogna della propria lingua, del proprio corpo e della propria origine. Il paragone non identifica due regimi sul piano giuridico. Indica una continuità nella volontà di uniformare e una differenza decisiva nei mezzi: dalla repressione alla persuasione quotidiana.`,
`La “mutazione antropologica” è il nome dato agli effetti di questo processo. Non cambia la biologia degli italiani: cambiano comportamenti, linguaggi, aspirazioni, rapporti fra generazioni. Il giovane borgataro che negli anni Cinquanta possedeva codici diversi dal figlio borghese, negli anni Settanta imita gli stessi vestiti, gli stessi consumi e gli stessi gesti. Per Pasolini non si tratta di una libera convergenza. Il modello borghese viene presentato come l’unico futuro possibile. L’emancipazione coincide così con l’abbandono di sé. Questa diagnosi contiene un rischio paternalistico, perché può negare ai subalterni il diritto di desiderare benessere; resta però potente quando mostra che anche i desideri hanno una storia e possono essere fabbricati.`,
`La metafora più celebre è la “scomparsa delle lucciole”. Le lucciole reali rimandano all’inquinamento e alla trasformazione del paesaggio; quelle simboliche rappresentano culture, gesti e forme di vita divenuti invisibili. La metafora permette a Pasolini di unire ecologia, antropologia e politica. Non è soltanto scomparso un insetto: è mutata la capacità di vedere il buio e di abitarlo senza riempirlo di luce artificiale. Nel celebre articolo il “vuoto del potere” indica anche l’incapacità della classe dirigente democristiana di comprendere la trasformazione che essa stessa ha favorito. Le istituzioni continuano a parlare il linguaggio antico mentre il vero potere si è spostato nei consumi e nei media.`,
`La televisione occupa un ruolo centrale perché unifica la lingua e offre modelli senza possibilità di replica. Pasolini la considera autoritaria non perché ogni programma sia propaganda esplicita, ma perché il mezzo stabilisce silenziosamente chi è visibile, come si parla e quale vita merita imitazione. La scuola può ancora contenere conflitto e dialogo; la televisione entra invece nella casa come evidenza naturale. Questa critica va storicizzata: il sistema mediale contemporaneo è più frammentato e interattivo. Tuttavia gli algoritmi, gli influencer e la pubblicità personalizzata rendono ancora attuale la domanda pasoliniana: chi educa i nostri desideri mentre crediamo di scegliere liberamente?`,
`Contro l’universo ridotto a merce, Pasolini cerca il sacro. La sua è una fede senza adesione ecclesiastica, nutrita dal cristianesimo, dal mito, dalla fisicità e dal sentimento della morte. Il sacro è ciò che resiste alla completa utilizzazione: il volto di un ragazzo, il corpo povero, un paesaggio, la nascita, la sofferenza. Nel Vangelo secondo Matteo Cristo appare insieme rivoluzionario e arcaico, incarnato in volti contadini e paesaggi meridionali. Pasolini non offre una riconciliazione religiosa; mette la trascendenza dentro la materia. Proprio questa compresenza di materialismo e sacro rende il suo mondo irriducibile sia al cattolicesimo istituzionale sia all’ateismo dogmatico.`,
`La contraddizione è quindi un metodo di conoscenza. Nelle Ceneri di Gramsci Pasolini può essere attratto dalla chiarezza razionale della storia e insieme dalla vitalità preistorica del popolo. Può difendere la libertà sessuale e poi denunciare la liberalizzazione dei costumi quando essa diventa mercato. Può celebrare i corpi nella Trilogia della vita e successivamente abiurare quei film. Non sono tutte contraddizioni equivalenti, né ogni ripensamento è automaticamente profondo. Ma Pasolini rifiuta l’idea che una posizione intellettuale debba diventare identità stabile. Quando la realtà cambia, anche il giudizio deve esporsi al rischio di cambiare, senza nascondere la ferita del passaggio.`,
`La sua immagine del mondo è infine tragica, non semplicemente pessimista. Il tragico nasce quando due esigenze giuste entrano in conflitto: emancipare i poveri dalla miseria e salvare la loro autonomia culturale; allargare la libertà e impedire che sia comprata dal mercato; partecipare alla storia e custodire ciò che la storia distrugge. Pasolini non possiede la soluzione. La sua forza consiste nel non cancellare uno dei due termini per ottenere una risposta rassicurante. Da qui deriva l’inattualità della sua voce: ci costringe a chiedere se una società sia davvero più libera quando offre infinite possibilità di acquisto ma rende sempre più difficile immaginare una forma di vita differente.`
  ],
  summary:`Al centro dell’immagine del mondo pasoliniana c’è il potere consumistico, capace non soltanto di imporre regole ma di produrre desideri e modelli di vita. Pasolini lo definisce provocatoriamente “nuovo fascismo”: non perché sia identico al regime storico, ma perché realizza un’omologazione più profonda attraverso la seduzione delle merci e della televisione. La “mutazione antropologica” indica il cambiamento culturale di linguaggi, comportamenti e aspirazioni, non una trasformazione biologica. La “scomparsa delle lucciole” unisce distruzione ambientale e perdita delle culture popolari. Contro la mercificazione totale, Pasolini cerca una dimensione del sacro incarnata nei corpi, nel mito e nella materia, senza aderire alla Chiesa. Le sue contraddizioni — marxismo e sacro, emancipazione e nostalgia, libertà sessuale e critica del mercato — non si risolvono in un sistema. Formano uno sguardo tragico: progresso materiale e autonomia culturale possono entrare in conflitto. L’attualità della diagnosi sta nella domanda su chi costruisca i desideri che percepiamo come liberi.`,
  essentials:[
    ['Potere antropologico','Spiegare come il consumismo modifichi desideri e identità, non solo comportamenti esterni.'],
    ['Nuovo fascismo','Distinguere il paragone culturale dalla falsa equivalenza fra regimi politici.'],
    ['Mutazione antropologica','Definirla come trasformazione storica di linguaggi, corpi e aspirazioni.'],
    ['Lucciole','Interpretare insieme il livello ecologico, culturale e politico della metafora.'],
    ['Sacro materiale','Comprendere il sacro come resistenza alla completa mercificazione.'],
    ['Pensiero tragico','Riconoscere il conflitto tra esigenze entrambe legittime.']
  ],
  vocab:[
    ['Neocapitalismo','Capitalismo dei consumi di massa che estende il mercato agli stili di vita.'],
    ['Mutazione antropologica','Trasformazione culturale profonda dell’essere umano sociale.'],
    ['Persuasione','Potere che ottiene adesione rendendo desiderabile un modello.'],
    ['Mercificazione','Trasformazione di corpi, relazioni e valori in beni scambiabili.'],
    ['Dopostoria','Condizione in cui le differenze storiche sembrano assorbite da un unico sistema.'],
    ['Tragico','Conflitto senza soluzione semplice tra valori ugualmente necessari.']
  ],
  map:'maps/03-immagine.svg',
  mapAlt:'Mappa: il neocapitalismo usa merci e televisione, produce omologazione e mutazione antropologica; la scomparsa delle lucciole rende visibile la perdita; il sacro e la contraddizione resistono alla mercificazione; ne deriva una visione tragica della modernità.',
  questions:[
    Q('In che senso il consumismo è un potere “antropologico”?',['Perché cambia geneticamente le persone','Perché forma desideri, linguaggi e modelli di vita','Perché agisce soltanto sulle leggi dello Stato'],1,'Il nuovo potere entra nella costruzione dell’identità e di ciò che appare desiderabile.','Potere antropologico','Non basta osservare i divieti: bisogna chiedere chi costruisce bisogni e aspirazioni.','La televisione propone un modello di italiano prima ancora di formulare un ordine.',['Il potere antropologico agisce…','solo dall’esterno','anche dall’interno dei desideri'],1),
    Q('Che cosa significa “nuovo fascismo” in Pasolini?',['Una perfetta identità giuridica col fascismo storico','Il ritorno delle sole camicie nere','Una nuova uniformazione ottenuta soprattutto attraverso seduzione e consumo'],2,'Il paragone riguarda l’esito omologante, mentre distingue i mezzi repressivi da quelli persuasivi.','Confronto storico','Usare la parola fascismo non elimina le differenze tra dittatura e democrazia dei consumi.','Il regime vietava i dialetti; il mercato rende desiderabile abbandonarli.',['I due fascismi sono identici?','No, il paragone segnala continuità e differenze','Sì, in ogni aspetto'],0),
    Q('La “mutazione antropologica” indica…',['Una trasformazione culturale di comportamenti e aspirazioni','Un cambiamento biologico della specie','Soltanto l’aumento del reddito'],0,'Pasolini descrive una trasformazione storica dell’uomo sociale.','Mutazione','“Antropologico” riguarda qui forme di vita, non genetica.','Il borgataro e il borghese iniziano a condividere gesti, vestiti e desideri.',['La mutazione riguarda…','la cultura vissuta','il DNA'],0),
    Q('Perché le lucciole sono una metafora complessa?',['Perché alludono solo a un ricordo d’infanzia','Perché uniscono ambiente, culture popolari e crisi politica','Perché rappresentano la vittoria della tecnologia'],1,'La loro scomparsa materiale diventa il segno visibile di una perdita antropologica.','Lucciole','La metafora parte dall’ambiente ma non si ferma all’ecologia.','La luce artificiale cancella il buio come il consumo cancella differenze e memorie.',['Le lucciole collegano…','natura e società','solo zoologia'],0),
    Q('Quale funzione ha il sacro nel pensiero di Pasolini?',['Garantire obbedienza alla Chiesa','Negare il corpo e la materia','Indicare ciò che resiste alla completa riduzione a merce'],2,'Il sacro pasoliniano è incarnato e non coincide con l’ortodossia religiosa.','Sacro materiale','Corpo, morte e paesaggio possono avere valore non utilizzabile né vendibile.','Nel Vangelo secondo Matteo la trascendenza appare in volti e terre concreti.',['Il sacro pasoliniano è…','separato dalla materia','incarnato nella materia'],1)
  ]
},
{
  id:'poetica', number:'04', title:'La poetica', short:'Contaminare per vedere',
  question:'Perché un autore cambia lingua, genere e mezzo invece di perfezionare una sola forma?',
  hook:'Quando un linguaggio viene assorbito dal potere, Pasolini ne cerca un altro: la coerenza non è nella forma, ma nell’urgenza di raggiungere la realtà.',
  lesson:[
`La poetica di Pasolini nasce da un paradosso: possiede una fiducia quasi religiosa nella realtà e, nello stesso tempo, sa che nessun linguaggio la restituisce in modo neutrale. Per avvicinarla bisogna cambiare forma, contaminare codici, esporre la presenza dell’autore. Da qui il carattere polimorfo dell’opera: poesia in friulano e in italiano, romanzi, critica, teatro, giornalismo, cinema. Non si tratta di virtuosismo enciclopedico. Ogni passaggio risponde alla crisi del mezzo precedente. Quando la parola letteraria sembra chiusa in un pubblico ristretto, Pasolini cerca il cinema; quando anche le immagini rischiano di diventare merce, le rende più dure, allegoriche e sgradevoli. La fedeltà alla realtà esige infedeltà alle forme stabilite.`,
`Il primo gesto è linguistico. Il friulano di Poesie a Casarsa è scelto come lingua pura e musicale, non come riproduzione spontanea del parlato. Pasolini lo studia e in parte lo inventa, trasformando una lingua locale in codice poetico. A Roma il procedimento cambia: nei romanzi delle borgate il romanesco e il gergo cercano una “regressione” nel mondo rappresentato. Anche qui non c’è registrazione passiva. Il narratore alterna lingua letteraria e voce popolare, costruendo una tensione tra pietà, distanza e violenza. Il plurilinguismo non è ornamento: mostra che la società contiene punti di vista inconciliabili e che l’italiano standard non basta a raccontarli.`,
`La poesia italiana degli anni Cinquanta aggiunge una dimensione civile. Le ceneri di Gramsci recupera il poemetto, una forma ampia capace di intrecciare autobiografia, paesaggio, ragionamento politico e canto. Pasolini rifiuta sia la poesia chiusa nella pura interiorità sia la propaganda che riduce i versi a messaggio. La sua voce espone la contraddizione: ama la vitalità popolare che la coscienza marxista giudica storicamente destinata a sparire; desidera la storia e rimpiange ciò che il progresso distrugge. Lo stile può essere alto e prosastico, musicale e argomentativo. Questa impurezza permette alla poesia di pensare senza diventare trattato e di confessarsi senza diventare diario.`,
`La nozione decisiva è contaminazione. Pasolini mette insieme registri che la cultura separa: sublime e osceno, Cristo e borgata, Bach e corpi sottoproletari, pittura del Quattrocento e paesaggio periferico, mito greco e autobiografia. Il contrasto non serve a produrre sorpresa superficiale. Attribuisce dignità figurativa a chi ne è escluso e, nello stesso tempo, impedisce allo spettatore di consumare la povertà come semplice documento. In Accattone la musica sacra e le inquadrature frontali trasformano un ladro di periferia in figura tragica senza cancellarne la miseria. La forma alta non abbellisce: rende visibile una sacralità che l’ordine sociale non riconosce.`,
`Il passaggio al cinema nasce dal desiderio di scrivere con la realtà stessa. Corpi, paesaggi, gesti e oggetti non sono descritti da parole: lasciano una traccia luminosa sull’immagine. Pasolini parla perciò del cinema come “lingua scritta della realtà”. Ma la cinepresa non è innocente. Inquadrare significa scegliere, montare significa produrre nessi, associare una musica a un volto significa interpretarlo. Il suo cinema conserva spesso una frontalità pittorica, attori non professionisti, montaggi bruschi e una recitazione non naturalistica. La povertà tecnica apparente è una scelta di stile: contro il cinema trasparente, Pasolini vuole che si percepisca lo sguardo che organizza l’immagine.`,
`Nel saggio sul “cinema di poesia” Pasolini distingue una narrazione che tende a far dimenticare la macchina da presa da un cinema in cui lo stile diventa percepibile. Attraverso la “soggettiva libera indiretta”, il film può avvicinarsi allo sguardo alterato di un personaggio senza coincidere completamente con esso. È l’equivalente cinematografico del discorso indiretto libero, ma non una traduzione meccanica. Movimenti, zoom, colori e montaggio fanno sentire insieme la visione del personaggio e la coscienza stilistica dell’autore. Il cinema di poesia non significa film in versi o immagini semplicemente belle: significa linguaggio che mette in primo piano il proprio modo di vedere.`,
`Questa poetica è anche intermediale. Le lezioni di Roberto Longhi restano visibili nella composizione delle scene; la letteratura fornisce miti e strutture; la musica crea collisioni emotive; il teatro accentua la parola e il rito. Il Vangelo secondo Matteo usa volti non divistici, paesaggi italiani e musiche provenienti da tradizioni diverse per produrre un Cristo non addomesticato. Edipo re mescola autobiografia, tragedia greca e paesaggi arcaici. Teorema riduce la vicenda a una geometria allegorica. Pasolini non adatta semplicemente un testo a un altro mezzo: costruisce un sistema in cui ogni arte corregge i limiti delle altre.`,
`Negli ultimi anni lo stile si fa più esplicitamente saggistico e allegorico. Gli articoli corsari adottano una voce diretta, apodittica, pronta a esporsi all’errore pur di spezzare il consenso. Petrolio abbandona l’idea del romanzo finito e si presenta come un insieme di “appunti”, mescolando dossier, visione, politica e sessualità. Salò costruisce invece uno spazio freddo, rituale e geometrico nel quale i corpi sono completamente amministrati dal potere. Dalla musicalità friulana alla macchina infernale di Salò cambia tutto in superficie. Resta la stessa esigenza: trovare una forma non pacificata, capace di impedire che lo spettatore scambi l’abitudine per realtà.`
  ],
  summary:`La poetica di Pasolini è polimorfa perché ogni linguaggio viene scelto, contaminato e infine messo in crisi in rapporto alla realtà. Il friulano di Poesie a Casarsa è una lingua poetica costruita; il gergo dei romanzi romani nasce da un lavoro di regressione e plurilinguismo. Con Le ceneri di Gramsci il poemetto unisce canto, autobiografia e ragionamento civile senza diventare propaganda. La contaminazione accosta sublime e osceno, musica sacra e borgata, pittura antica e corpi marginali, attribuendo loro una dignità tragica. Il cinema è pensato come “lingua scritta della realtà”, pur nella consapevolezza che inquadratura e montaggio interpretano. Il “cinema di poesia” rende percepibile lo stile e, mediante la soggettiva libera indiretta, avvicina lo sguardo del personaggio senza annullare quello dell’autore. Letteratura, pittura, musica e teatro formano un sistema integrato. Negli ultimi lavori la forma diventa più frammentaria o allegorica. La coerenza profonda non sta in un genere, ma nella ricerca di un linguaggio che resista all’assimilazione e renda di nuovo visibile il reale.`,
  essentials:[
    ['Polimorfismo','Spiegare perché il passaggio fra generi risponda a crisi conoscitive, non a puro virtuosismo.'],
    ['Plurilinguismo','Mostrare la funzione critica di dialetto, gergo e lingua letteraria.'],
    ['Poemetto civile','Comprendere l’unione di canto, autobiografia e argomentazione.'],
    ['Contaminazione','Analizzare l’accostamento di alto e basso come produzione di senso.'],
    ['Lingua della realtà','Spiegare la fiducia nel cinema senza attribuire neutralità alla cinepresa.'],
    ['Cinema di poesia','Definirlo come visibilità dello stile, non come semplice bellezza visiva.']
  ],
  vocab:[
    ['Regressione','Avvicinamento controllato dell’autore alla lingua e al punto di vista dei personaggi.'],
    ['Plurilinguismo','Coesistenza conflittuale di più lingue e registri nella stessa opera.'],
    ['Contaminazione','Accostamento intenzionale di codici, livelli e arti tradizionalmente separati.'],
    ['Poemetto','Componimento poetico ampio, narrativo e argomentativo.'],
    ['Soggettiva libera indiretta','Procedimento filmico che intreccia sguardo del personaggio e stile dell’autore.'],
    ['Intermedialità','Dialogo strutturale fra letteratura, cinema, pittura, musica e teatro.']
  ],
  map:'maps/04-poetica.svg',
  mapAlt:'Mappa: la passione per la realtà genera sperimentalismo; dal friulano si passa al plurilinguismo e al poemetto civile; la contaminazione unisce alto e basso; il cinema scrive con corpi e paesaggi; il cinema di poesia rende visibile lo stile; le arti confluiscono in un sistema intermediale.',
  questions:[
    Q('Perché Pasolini attraversa tanti generi e linguaggi?',['Per mostrare una competenza enciclopedica','Perché ogni mezzo viene messo alla prova dalla ricerca del reale','Per evitare qualsiasi coerenza tra le opere'],1,'Il polimorfismo risponde alla crisi dei mezzi e mantiene una coerenza di ricerca.','Polimorfismo','Cambiare forma non significa cambiare casualmente tema: significa cercare un nuovo accesso alla stessa urgenza.','Dalla poesia al cinema Pasolini cerca una maggiore presenza di corpi e paesaggi.',['La coerenza sta soprattutto…','in un unico genere','nell’urgenza conoscitiva'],1),
    Q('Che funzione ha il plurilinguismo nei romanzi romani?',['Mostra punti di vista sociali diversi e mette in crisi l’italiano standard','Riproduce senza intervento una registrazione sonora','Rende tutti i personaggi linguisticamente uguali'],0,'Lingua letteraria e gergo convivono in una costruzione artistica conflittuale.','Plurilinguismo','La lingua popolare non è copiata: è selezionata e montata dall’autore.','Ragazzi di vita alterna voce narrante e parlato borgataro.',['Il plurilinguismo è…','una tecnica critica','una trascrizione automatica'],0),
    Q('Che cosa produce la contaminazione tra Bach e la borgata in Accattone?',['Una parodia della musica religiosa','Una semplice decorazione elegante','Una dignità tragica che rende visibile il sacro nel profano'],2,'L’accostamento alto/basso interpreta i corpi esclusi senza cancellarne la realtà.','Contaminazione','Due codici lontani generano un significato che nessuno avrebbe da solo.','La musica sacra non rende ricca la borgata: rende tragica la sua esclusione.',['La forma alta serve a…','nascondere la povertà','far emergere una sacralità negata'],1),
    Q('Perché il cinema non è una copia neutrale della realtà?',['Perché inquadratura e montaggio selezionano e costruiscono nessi','Perché non usa corpi e oggetti reali','Perché ogni film è necessariamente fantastico'],0,'Anche quando registra il reale, il cinema lo organizza da un punto di vista.','Sguardo filmico','La traccia fotografica non elimina la scelta dell’autore.','Associare Bach al volto di Accattone è già un’interpretazione.',['Montare significa…','lasciare tutto invariato','costruire una relazione'],1),
    Q('Che cosa definisce il “cinema di poesia”?',['La presenza obbligatoria di versi recitati','La visibilità dello stile e dello sguardo cinematografico','L’uso esclusivo di immagini armoniose'],1,'Il cinema di poesia fa percepire il modo in cui la realtà viene vista.','Cinema di poesia','“Poesia” indica l’autocoscienza stilistica, non la bellezza decorativa.','La soggettiva libera indiretta intreccia visione del personaggio e forma dell’autore.',['Un’immagine bella è sempre cinema di poesia?','Sì','No'],1)
  ]
},
{
  id:'opere', number:'05', title:'Le opere decisive', short:'Un solo progetto, molte forme',
  question:'Come cambia la stessa domanda passando dalla poesia al romanzo, dal saggio al cinema?',
  hook:'Le opere non sono scaffali separati: ciascuna riprende il conflitto tra realtà, sacro e potere con strumenti diversi.',
  lesson:[
`Il canone pasoliniano è vasto e inquieto. Elencarlo per generi rischia di nascondere i nessi; ridurlo a due o tre titoli celebri produce l’effetto opposto, perché cancella la continuità della ricerca. Conviene scegliere opere-soglia: testi e film nei quali cambia il modo di porre la stessa domanda. Il filo è il rapporto fra una realtà amata nella sua concretezza e le forze che la trasformano. Poesia, romanzo, saggio e cinema non illustrano una teoria già pronta. Ogni forma scopre qualcosa che le altre non potevano vedere: la contraddizione interiore, la lingua di una comunità, la diagnosi pubblica, la presenza fisica dei corpi, l’allegoria del potere.`,
`Poesie a Casarsa, pubblicato nel 1942, è il punto d’origine. Il friulano viene elevato a lingua assoluta e insieme legato a un mondo locale minacciato dalla storia. In seguito La meglio gioventù raccoglie e riorganizza quella stagione, mentre La nuova gioventù la riscrive negli anni Settanta mostrando che il ritorno non è più possibile: la stessa lingua registra ormai la perdita. Tra le due raccolte non c’è semplice nostalgia. C’è la misura di una trasformazione storica. La riscrittura diventa un esperimento crudele: confrontare il mito dell’origine con un presente che ha alterato perfino la possibilità di ricordarlo.`,
`Le ceneri di Gramsci, del 1957, porta la contraddizione al centro della poesia civile. Davanti alla tomba di Gramsci, l’io poetico dichiara di essere attratto dalla razionalità rivoluzionaria e nello stesso tempo legato a una vita popolare anteriore alla coscienza di classe. La forma del poemetto consente di attraversare paesaggio romano, confessione e storia nazionale. Non offre una sintesi: rende abitabile il conflitto. Il titolo stesso mette in relazione un’eredità politica e ciò che resta dopo una morte. Questa raccolta mostra perché l’aggettivo “civile” non significhi didascalico. La politica entra nella struttura della voce, non si aggiunge come messaggio esterno.`,
`Ragazzi di vita (1955) e Una vita violenta (1959) sono il laboratorio narrativo delle borgate. Il primo procede per episodi e segue una comunità giovanile senza costruire una maturazione edificante. Il secondo concentra maggiormente il percorso di Tommaso, includendo un avvicinamento alla coscienza politica che non salva il protagonista. In entrambi il gergo romanesco incrina la lingua letteraria e costringe il lettore a una prossimità scomoda. Le opere furono accusate di oscenità proprio perché portavano al centro della letteratura corpi, parole e comportamenti esclusi. Il valore non consiste nel documentare un ambiente, ma nel farne emergere insieme vitalità, violenza e abbandono storico.`,
`Il cinema riprende e trasforma questa materia. Accattone (1961) conserva il sottoproletariato romano ma lo sottopone a una stilizzazione sacrale: Bach, frontalità e richiami pittorici conferiscono statura tragica a un personaggio incapace di uscire dal proprio mondo. Il Vangelo secondo Matteo (1964) usa attori non professionisti e paesaggi meridionali per restituire un Cristo duro, umano e rivoluzionario, lontano dall’oleografia. Uccellacci e uccellini (1966) mette in scena, con la favola di Totò e Ninetto, la crisi del marxismo e la fine delle vecchie spiegazioni. Questi film non sono illustrazioni dei saggi: pensano attraverso volti, spazi, ritmi e collisioni sonore.`,
`Teorema (romanzo e film, 1968) sposta lo sguardo sulla borghesia. Un ospite misterioso entra in una famiglia industriale, stabilisce con ciascun membro un rapporto erotico e, partendo, ne rivela il vuoto. Il sacro non salva: disorganizza identità fondate sul possesso. La geometria della vicenda sostituisce il realismo delle borgate. Petrolio, rimasto incompiuto e pubblicato postumo, radicalizza la forma aperta: il protagonista Carlo si sdoppia, sessualità, potere economico e politica si mescolano in “appunti” che rifiutano il romanzo organico. L’incompiutezza non autorizza a trattare ogni lacuna come mistero risolto; rende però visibile un progetto che voleva anatomizzare il potere dall’interno.`,
`Scritti corsari (1975) e Lettere luterane (1976, postumo) raccolgono l’intervento giornalistico. Qui troviamo il nuovo fascismo, la mutazione antropologica, la scomparsa delle lucciole, la critica della televisione e della classe politica. Lo stile è assertivo, provocatorio, spesso costruito per opposizioni nette. Va letto come gesto militante, non come sociologia infallibile. La forza degli articoli sta nell’individuare un potere culturale mentre altri osservano soprattutto istituzioni e partiti; il limite possibile sta nella generalizzazione e nella nostalgia. Nel progetto pedagogico di Gennariello, Pasolini tenta anche una controeducazione: insegnare a leggere il linguaggio delle cose e a diffidare delle evidenze fabbricate.`,
`La Trilogia della vita — Decameron, I racconti di Canterbury, Il fiore delle Mille e una notte — celebra corpi, sessualità e narrazione popolare come realtà non ancora separata dal piacere. L’abiura successiva dichiara che il mercato ha assorbito perfino quella libertà, riducendola a consumo. Salò o le 120 giornate di Sodoma (1975) rovescia allora la festa in macchina di dominio: nella Repubblica di Salò quattro signori amministrano corpi ridotti a oggetti, entro uno spazio rituale e chiuso. Il film non rappresenta il fascismo soltanto come evento storico; costruisce un’allegoria del potere consumistico che usa la libertà apparente per disporre integralmente della vita. È il punto più estremo e non una chiave unica per tutto Pasolini.`,
`Queste opere formano un percorso, non una marcia lineare verso la disperazione. Il friulano, la borgata, Cristo, la borghesia, il giornalismo corsaro e Salò sono stazioni in cui la relazione fra realtà e rappresentazione viene nuovamente verificata. Alcune diagnosi possono essere contestate; alcune immagini restano disturbanti; alcune posizioni sono segnate dal proprio tempo. Ma il canone conserva unità perché non smette di chiedere chi abbia il diritto di dare forma ai corpi e alle parole. Leggere Pasolini significa perciò spostarsi tra i media, confrontare le opere e osservare i ripensamenti, invece di estrarre una frase profetica e usarla come risposta universale.`
  ],
  summary:`Le opere decisive di Pasolini vanno lette come soglie di un unico progetto. Poesie a Casarsa crea il mito linguistico del Friuli; La nuova gioventù ne registra la perdita. Le ceneri di Gramsci porta nella poesia civile il conflitto fra razionalità marxista e amore per la vita popolare. Ragazzi di vita e Una vita violenta trasformano la lingua e i corpi delle borgate in materia narrativa non pacificata. Accattone sacralizza il sottoproletariato; Il Vangelo secondo Matteo incarna un Cristo rivoluzionario; Uccellacci e uccellini mette in scena la crisi ideologica. Teorema rivela il vuoto della borghesia, mentre Petrolio tenta una forma frammentaria per anatomizzare potere e sessualità. Scritti corsari e Lettere luterane formulano la diagnosi della mutazione antropologica. La Trilogia della vita celebra i corpi, poi viene abiurata quando Pasolini ritiene che il mercato li abbia assorbiti. Salò rovescia la festa in amministrazione totale del corpo. Nessuna opera esaurisce l’autore: il senso emerge dai passaggi e dalle revisioni.`,
  essentials:[
    ['Opere-soglia','Spiegare perché la selezione segue mutamenti del problema e non un catalogo di titoli.'],
    ['Ceneri di Gramsci','Analizzare la contraddizione fra storia rivoluzionaria e vitalità popolare.'],
    ['Romanzi romani','Collegare plurilinguismo, esclusione e assenza di riscatto edificante.'],
    ['Cinema per cicli','Distinguere fase delle borgate, crisi ideologica, Trilogia e allegoria finale.'],
    ['Scritti corsari','Valutare insieme potenza diagnostica e rischio di generalizzazione.'],
    ['Abiura e Salò','Comprendere il passaggio dalla liberazione dei corpi alla loro amministrazione totale.']
  ],
  vocab:[
    ['Canone','Selezione ragionata di opere considerate decisive per comprendere un autore.'],
    ['Opera-soglia','Opera che modifica forma o direzione di una ricerca.'],
    ['Abiura','Rifiuto pubblico di una fase precedente della propria opera.'],
    ['Allegoria','Rappresentazione concreta che organizza un significato storico o concettuale ulteriore.'],
    ['Incompiuto','Testo non portato dall’autore a una forma definitiva.'],
    ['Militante','Intervento culturale che prende posizione nel conflitto del presente.']
  ],
  map:'maps/05-opere.svg',
  mapAlt:'Mappa: Poesie a Casarsa fonda l’origine; Le ceneri di Gramsci espone la contraddizione; i romanzi romani danno lingua alle borgate; il cinema rende presenti i corpi; gli Scritti corsari diagnosticano la mutazione; la Trilogia viene abiurata; Salò allegorizza il potere totale.',
  questions:[
    Q('Perché la lezione seleziona “opere-soglia”?',['Per evitare di leggere generi diversi','Per seguire i momenti in cui cambia la forma della stessa ricerca','Per stabilire una classifica estetica definitiva'],1,'Le opere-soglia mostrano trasformazioni e nessi meglio di un catalogo completo.','Opera-soglia','La scelta non dice che gli altri titoli non valgono; rende visibile il percorso.','Accattone trasferisce la materia delle borgate dalla pagina all’immagine sacrale.',['Un’opera-soglia…','apre o modifica una fase','è sempre l’opera più venduta'],0),
    Q('Quale conflitto struttura Le ceneri di Gramsci?',['Razionalità marxista e amore per la vitalità popolare','Cinema e teatro','Cultura italiana e cultura francese'],0,'Il poemetto mantiene insieme due appartenenze che non si conciliano.','Contraddizione poetica','La poesia civile non offre uno slogan, ma espone il dissidio dell’io nella storia.','La tomba di Gramsci diventa il luogo di un dialogo con un’eredità amata e non pienamente accettata.',['Il conflitto viene…','cancellato','reso forma poetica'],1),
    Q('Che cosa distingue Accattone da un semplice documento sulle borgate?',['L’assenza di personaggi popolari','La stilizzazione sacrale prodotta da musica e immagini','L’ambientazione in un’epoca antica'],1,'Il film interpreta la periferia attraverso Bach, pittura e costruzione tragica.','Realismo sacrale','La presenza del reale convive con una forma alta che ne cambia la percezione.','Il volto di Accattone acquista una gravità che la società gli nega.',['Accattone combina…','documento e sacralizzazione','favola e musical'],0),
    Q('Come vanno letti gli Scritti corsari?',['Come previsioni infallibili','Come narrativa fantastica','Come interventi militanti potenti ma discutibili'],2,'La loro forza critica non elimina generalizzazioni, errori possibili o necessità di contestualizzare.','Saggistica militante','Un articolo polemico interviene nel presente e usa spesso tesi nette; non è una legge scientifica.','La diagnosi della televisione illumina il potere culturale, ma va confrontata con la storia dei media.',['Criticare un testo corsaro significa…','tradirlo','prenderne sul serio argomenti e limiti'],1),
    Q('Quale passaggio collega l’abiura dalla Trilogia della vita a Salò?',['Dalla celebrazione dei corpi alla denuncia della loro mercificazione','Dal cinema alla poesia friulana','Dalla politica all’evasione fiabesca'],0,'Pasolini ritiene che il mercato abbia recuperato la libertà sessuale e la rovescia nell’immagine del corpo amministrato.','Abiura','L’abiura non dice che i film non esistono più: registra il fallimento storico attribuito alla loro utopia.','In Salò i corpi non celebrano piacere autonomo, ma sono posseduti e regolati dai signori.',['Il corpo in Salò è…','autonomo','ridotto a oggetto del potere'],1)
  ]
},
{
  id:'conclusione', number:'06', title:'Conclusione', short:'L’eredità dell’inattuale',
  question:'Pasolini ci aiuta ancora a vedere il presente, oppure il presente lo ha trasformato in una citazione innocua?',
  hook:'Ereditare Pasolini non significa dargli sempre ragione: significa conservare la sua capacità di rendere discutibile ciò che appare naturale.',
  lesson:[
`Alla fine del percorso, Pasolini non si lascia chiudere in una formula. “Profeta”, “corsaro”, “eretico”, “martire”: ogni parola coglie un tratto e rischia di trasformarlo in posa. La sua eredità più esigente non è un elenco di giudizi da applicare al presente, ma un metodo di attenzione. Pasolini osserva i cambiamenti là dove la politica tradizionale spesso non guarda: nella lingua, nei corpi, nei vestiti, nei desideri, nei paesaggi, nel modo in cui i giovani immaginano il futuro. Ci insegna che il potere diventa più profondo quando sembra coincidere con la normalità e che una trasformazione economica è sempre anche una trasformazione dell’uomo.`,
`La catena dei sei movimenti può ora essere ricomposta. L’Italia plurale e preindustriale offre il termine di confronto. Le fratture biografiche collocano Pasolini dentro e fuori diverse comunità. Da questa posizione nasce l’immagine di un mondo minacciato dall’omologazione consumistica. La poetica risponde cambiando lingua e mezzo, perché nessuna forma rimane innocente. Le opere verificano la diagnosi su materiali differenti, dal Friuli alle borgate, da Cristo alla borghesia, dalla festa dei corpi alla loro amministrazione. La conclusione non è che il passato fosse buono e il presente cattivo. È che ogni progresso deve essere interrogato anche per ciò che rende impossibile vedere, dire e desiderare.`,
`Molte intuizioni pasoliniane risultano ancora fertili. La distinzione fra sviluppo e progresso impedisce di misurare una società soltanto con produzione e consumo. La mutazione antropologica invita a osservare gli effetti culturali della tecnologia. La critica televisiva può essere trasferita, con cautela, alle piattaforme digitali: oggi non riceviamo tutti lo stesso programma, ma algoritmi diversi organizzano visibilità, attenzione e desiderio. L’omologazione non produce necessariamente uniformità esteriore; può funzionare anche attraverso nicchie personalizzate che condividono la stessa economia dell’attenzione. Questa è un’estensione contemporanea, non una tesi formulata da Pasolini, e va dichiarata come tale.`,
`Altre posizioni richiedono invece resistenza critica. Pasolini tende talvolta a rappresentare il popolo scomparso come più innocente di quanto fosse e a leggere l’accesso ai consumi soprattutto come degradazione. Chi viveva povertà, esclusione o repressione sessuale poteva legittimamente desiderare beni, istruzione e libertà. Il rischio è che l’intellettuale difenda l’autenticità dei subalterni al prezzo di congelarli nella condizione che lui ama osservare. Anche la contrapposizione tra prima e dopo può diventare troppo netta. Riconoscere questi limiti non riduce Pasolini; lo sottrae alla devozione e rende il dialogo più adulto. Un autore critico merita lettori capaci di criticarlo.`,
`La sua riflessione sul sacro conserva una forza particolare in una cultura che traduce quasi ogni valore in prestazione o prezzo. Il sacro pasoliniano non obbliga ad accettare una fede. Domanda se esistano aspetti della vita che non debbano essere interamente disponibili: il corpo, il lutto, l’infanzia, il paesaggio, la relazione con l’altro. Questa indisponibilità può diventare un criterio etico ed ecologico. Se tutto è risorsa, anche la persona diventa materiale da ottimizzare. Pasolini ricorda che la realtà non coincide con la sua utilità e che vedere un volto significa incontrare qualcosa che eccede la funzione assegnata dal sistema.`,
`Anche la figura dell’intellettuale cambia alla luce del suo esempio. Pasolini interveniva sui grandi giornali, nel cinema, in poesia e in televisione; accettava la contraddizione di usare i mezzi del potere per criticarli. Non parlava da un esterno puro. Questa posizione è più utile dell’immagine romantica del solitario incontaminato. Oggi un docente, un artista o un creatore digitale agisce dentro piattaforme commerciali e istituzioni. La domanda non è come restarne magicamente fuori, ma come usare quelle forme senza lasciare che definiscano interamente ciò che può essere pensato. La coerenza assoluta può diventare alibi per il silenzio; la contraddizione dichiarata può invece aprire uno spazio di responsabilità.`,
`Il metodo pasoliniano richiede infine attenzione alle perdite invisibili. Le statistiche misurano reddito, accessi, velocità e produttività; più raramente misurano la scomparsa di una parola dialettale, di un sapere manuale, di una specie, di una forma di tempo non monetizzata. Non ogni perdita deve essere evitata e non ogni tradizione merita di sopravvivere. Ma ciò che non viene contato rischia di essere distrutto senza decisione pubblica. La metafora delle lucciole resta potente proprio perché trasforma un’assenza quasi impercettibile in evento politico. Educare lo sguardo significa imparare ad accorgersi prima che il buio sembri naturalmente vuoto.`,
`Che cosa significa allora “restare umani”? Non difendere una presunta natura immobile, né rifiutare la tecnica. Significa mantenere la capacità di distinguere desiderio e comando, libertà e adattamento, sviluppo e progresso; riconoscere la dignità di lingue, corpi e vite che il centro considera marginali; accettare che una contraddizione possa essere più vera di una risposta ideologica perfetta. In questa prospettiva Pasolini è davvero inattuale: non perché appartenga al passato, ma perché interrompe l’automatismo del presente. La domanda finale resta aperta e deve diventare discussione: quali nostre libertà sono conquiste reali, e quali sono soltanto la forma più efficace assunta oggi dall’obbedienza?`
  ],
  summary:`L’eredità di Pasolini non consiste in profezie da ripetere, ma in un metodo che osserva il potere nei linguaggi, nei corpi e nei desideri. I sei movimenti mostrano una catena: pluralità del mondo precedente, fratture biografiche, diagnosi dell’omologazione, sperimentazione dei linguaggi, opere come verifiche successive e domanda critica sul presente. La distinzione tra sviluppo e progresso e l’idea di mutazione antropologica possono illuminare anche le piattaforme digitali, purché questa applicazione contemporanea venga dichiarata come nostra. Pasolini va però discusso: la nostalgia rischia di idealizzare il popolo e di sottovalutare il legittimo desiderio di benessere e libertà. Il sacro conserva valore come nome di ciò che non deve essere interamente trasformato in merce. L’intellettuale pasoliniano non parla da un’esternità pura, ma usa in modo contraddittorio i mezzi che critica. Restare umani significa distinguere desiderio e comando, progresso e semplice sviluppo, e rendere visibili le perdite che le misure dominanti non registrano.`,
  essentials:[
    ['Metodo, non oracolo','Spiegare perché l’eredità critica valga più della raccolta di citazioni profetiche.'],
    ['Catena dei sei movimenti','Ricostruire il nesso dal mondo precedente alle forme artistiche e all’eredità.'],
    ['Attualizzazione dichiarata','Distinguere ciò che Pasolini ha scritto dalle applicazioni contemporanee.'],
    ['Critica della nostalgia','Valutare il rischio di idealizzare i subalterni e negarne i desideri.'],
    ['Indisponibilità','Collegare il sacro a ciò che non deve essere ridotto interamente a merce.'],
    ['Perdite invisibili','Riconoscere il valore politico di ciò che gli indicatori non misurano.']
  ],
  vocab:[
    ['Inattuale','Capace di opporsi alle evidenze del proprio tempo per comprenderlo meglio.'],
    ['Economia dell’attenzione','Sistema che trasforma il tempo e l’interesse degli utenti in valore economico.'],
    ['Attualizzazione','Applicazione argomentata di un concetto storico a un problema presente.'],
    ['Indisponibile','Ciò che non può essere usato, comprato o amministrato senza limite.'],
    ['Indicatore','Misura scelta per rappresentare un fenomeno, che rende visibili alcuni aspetti e ne oscura altri.'],
    ['Pensiero critico','Capacità di esaminare presupposti, prove, limiti e conseguenze di un giudizio.']
  ],
  map:'maps/06-conclusione.svg',
  mapAlt:'Mappa finale: il mondo precedente entra in frattura; la diversità produce uno sguardo sul nuovo potere; l’immagine del mondo esige nuovi linguaggi; la poetica confluisce nelle opere; le opere rendono visibile la mutazione; l’eredità riapre la domanda su libertà e obbedienza.',
  questions:[
    Q('Qual è l’eredità più rigorosa di Pasolini?',['Un elenco di profezie sempre vere','Un metodo per osservare potere e mutamenti nella vita quotidiana','Il rifiuto completo di ogni tecnologia'],1,'Ereditare criticamente significa usare domande e distinzioni, non trasformare l’autore in oracolo.','Metodo critico','Una citazione può colpire; un metodo obbliga a verificare il presente.','La distinzione sviluppo/progresso va applicata a dati e conseguenze concrete.',['Leggere Pasolini criticamente significa…','verificare e discutere','ripetere e venerare'],0),
    Q('Come si può collegare Pasolini agli algoritmi contemporanei?',['Dichiarando che è un’attualizzazione della sua critica dei desideri','Attribuendogli previsioni precise sui social network','Sostenendo che televisione e algoritmi siano identici'],0,'L’estensione è plausibile ma appartiene alla nostra interpretazione, non alle parole storiche dell’autore.','Attualizzazione','Applicare un concetto richiede analogie e differenze esplicite.','Televisione e feed personalizzati organizzano entrambi la visibilità, ma in modi diversi.',['Un’attualizzazione corretta…','cancella le differenze storiche','dichiara il proprio passaggio interpretativo'],1),
    Q('Qual è un limite possibile della nostalgia pasoliniana?',['Ignorare del tutto il mondo popolare','Congelare i subalterni nell’autenticità e svalutare il loro desiderio di benessere','Accettare senza critica la società dei consumi'],1,'Amare una cultura marginale non autorizza a negare a chi la vive il diritto di cambiarla.','Paternalismo','L’intellettuale rischia di preferire l’autenticità della povertà che non deve sopportare.','I giovani delle borgate possono desiderare istruzione e comfort senza essere semplicemente traditori.',['Criticare la nostalgia serve a…','rendere il dialogo più adulto','eliminare ogni valore del passato'],0),
    Q('Che cosa può significare oggi il sacro pasoliniano?',['Obbedienza obbligatoria a un’istituzione religiosa','Rifiuto del corpo','Limite alla totale disponibilità commerciale della vita'],2,'Il sacro indica un’eccedenza della realtà rispetto a prezzo, funzione e consumo.','Indisponibilità','Non tutto ciò che può essere sfruttato deve esserlo.','Un paesaggio possiede valore oltre il profitto ricavabile dalla sua trasformazione.',['Indisponibile significa…','senza valore','non riducibile a uso illimitato'],1),
    Q('Quale domanda ricompone l’intero percorso?',['Come ripristinare esattamente l’Italia contadina?','Quale genere letterario è superiore?','Quali libertà sono conquiste e quali forme interiorizzate di obbedienza?'],2,'La domanda distingue emancipazione reale e desiderio prodotto senza negare in blocco la modernità.','Libertà e obbedienza','Il potere più efficace può presentarsi come scelta spontanea.','Una piattaforma offre molte opzioni, ma decide anche quali diventano visibili.',['La libertà richiede anche…','esaminare chi forma le scelte','avere il maggior numero di merci'],0)
  ]
}
];
