const Q = (q, options, correct, explanation, anchor, recovery) => ({ q, options, correct, explanation, anchor, recovery });

window.LESSON_DATA = [
  {
    id: "mondo",
    number: "01",
    title: "Il mondo precedente",
    subtitle: "La promessa dell’ordine e le prime crepe",
    question: "Quale realtà riceve Gadda, e perché la sua promessa di ordine diventa presto insufficiente?",
    color: "#405b66",
    lesson: `
      <h3 id="mondo-promessa">Una civiltà che crede nell’ordine</h3>
      <p>Carlo Emilio Gadda nasce a Milano nel 1893 dentro un mondo che possiede una grande fiducia in se stesso. La borghesia lombarda di fine Ottocento associa il progresso alla scienza, alla tecnica, al lavoro e all’efficienza. La città industriale sembra dimostrare che la realtà possa essere conosciuta, organizzata e migliorata. Il giovane Gadda riceve questo sistema di valori non come una teoria astratta, ma come una disciplina quotidiana: studia al liceo Parini, poi sceglie ingegneria al Politecnico. La precisione del calcolo e la responsabilità dell’opera ben costruita resteranno per lui esigenze morali, anche quando scoprirà che né la famiglia né la società funzionano come macchine ordinate.</p>
      <p>Questa fiducia ha una radice ottocentesca. Il positivismo considera i fatti osservabili, le leggi scientifiche e il metodo sperimentale strumenti privilegiati di conoscenza. In letteratura, realismo, naturalismo e verismo cercano di descrivere ambienti e rapporti sociali con rigore. Ma l’idea di un narratore capace di dominare dall’alto la materia raccontata comincia a incrinarsi. La modernità moltiplica città, professioni, linguaggi specialistici e conflitti: quanto più il mondo diventa analizzabile, tanto meno appare riducibile a una sola spiegazione.</p>
      <h3 id="mondo-lingua">Una lingua nazionale ancora incompleta</h3>
      <p>L’Italia unita ha inoltre una lingua letteraria prestigiosa, ma non una voce quotidiana davvero comune. Dialetti, italiani regionali, latino scolastico, francese borghese e lessici tecnici convivono senza fondersi. Per molti scrittori questa pluralità è un ostacolo da disciplinare; per Gadda diventerà un dato di realtà. Se ogni gruppo sociale nomina le cose a modo proprio, scegliere una lingua perfettamente uniforme significherebbe cancellare differenze, interessi e responsabilità.</p>
      <p>Il precedente decisivo è Alessandro Manzoni. Gadda ne ammira la capacità di collegare lingua, storia, morale e istituzioni. Nei <em>Promessi sposi</em> il male non nasce soltanto dalla cattiveria individuale: passa attraverso carestia, guerra, amministrazione, paura collettiva e abuso del potere. Tuttavia Manzoni conserva una prospettiva ordinatrice e una fiducia provvidenziale che il Novecento renderà problematica. Accanto a lui agisce la linea lombarda più irregolare di Carlo Dossi e degli scapigliati: deformazione, ironia, impasto linguistico, insofferenza verso la rispettabilità borghese. Gadda eredita entrambi i poli, la tensione morale di Manzoni e l’espressionismo linguistico lombardo.</p>
      <h3 id="mondo-modernita">La modernità come moltiplicazione dei sistemi</h3>
      <p>Fra Ottocento e Novecento la vita europea viene attraversata da reti ferroviarie, elettricità, burocrazie, giornali, produzione industriale e nuovi saperi. L’ingegnere impara che nessun dispositivo funziona isolatamente: un guasto locale può dipendere dall’interazione fra parti lontane. Questa forma mentale sarà importante nella scrittura gaddiana, ma non bisogna trasformarla in una formula semplice — “scrive così perché è ingegnere”. La tecnica gli offre piuttosto un vocabolario della relazione, del sistema e dell’errore. La letteratura gli mostrerà ciò che il progetto tecnico non può chiudere: desideri contraddittori, colpe distribuite, deformazioni della conoscenza.</p>
      <p>Anche l’idea di patria appartiene al mondo ricevuto. Educato nel culto del Risorgimento e del dovere civile, Gadda vede inizialmente nella guerra una prova di responsabilità e appartenenza. Il nazionalismo promette unità, mentre la società reale è percorsa da divisioni. Questa tensione prepara una frattura radicale: la Prima guerra mondiale trasformerà il linguaggio dell’eroismo in esperienza della disorganizzazione, della prigionia e della perdita.</p>
      <p>Alla promessa di ordine partecipa anche il romanzo poliziesco classico: un enigma turba la società, l’investigatore ricostruisce una catena causale e la soluzione ristabilisce l’equilibrio. Gadda conserverà l’impulso dell’indagine, ma ne rovescerà la chiusura. Il delitto non sarà un corpo estraneo espulso dalla comunità: rivelerà connessioni che attraversano la comunità stessa.</p>
      <h3 id="mondo-limite">Il limite interno alla promessa</h3>
      <p>Il mondo precedente non è dunque soltanto uno sfondo. Contiene già il problema che Gadda tenterà di affrontare: come conservare il bisogno di esattezza senza fingere che il reale sia semplice? La borghesia proclama efficienza, ma può produrre spreco e vanità; la famiglia si presenta come rifugio, ma può diventare luogo di debiti e risentimenti; la lingua nazionale promette unità, ma nasconde una società plurale; la patria chiede sacrificio, ma la guerra rivela incompetenza e caos.</p>
      <p>Gadda non abbandonerà mai del tutto la richiesta di ordine. Proprio per questo soffrirà la distanza fra i modelli e i fatti. La sua opera nascerà da una fedeltà diventata critica: non rifiutare la ragione, ma impedirle di mentire attraverso spiegazioni troppo comode. La frattura biografica non creerà meccanicamente la poetica; renderà però impossibile credere ancora nell’ordine come dato già posseduto.</p>`,
    summary: "Gadda riceve dalla borghesia lombarda una fiducia positivistica nella scienza, nella tecnica, nel lavoro e nell’efficienza. La letteratura realista cerca nello stesso periodo di dominare i fatti, ma la modernità moltiplica sistemi, linguaggi e conflitti. L’Italia possiede una lingua letteraria ma vive nella pluralità di dialetti, italiani regionali e lessici specialistici. Manzoni offre a Gadda un modello morale e storico; la linea lombarda espressionistica gli consegna deformazione e ironia. La formazione ingegneristica gli insegna a vedere relazioni e guasti senza determinare automaticamente il suo stile. Anche patria, famiglia e classe borghese promettono unità ma contengono contraddizioni. Il problema iniziale è quindi preciso: come mantenere il bisogno di esattezza senza ridurre la realtà a una spiegazione semplice? La guerra renderà esplosivo questo limite.",
    essentials: [
      "Spiegare la fiducia della borghesia lombarda in scienza, tecnica, lavoro ed efficienza.",
      "Collegare il positivismo alla ricerca di fatti e leggi senza identificarlo con tutta la modernità.",
      "Mostrare perché il plurilinguismo sociale dell’Italia precede la scelta stilistica di Gadda.",
      "Distinguere l’eredità morale di Manzoni dalla linea espressionistica lombarda.",
      "Intendere l’ingegneria come forma mentale della relazione, non come causa automatica dello stile.",
      "Formulare il limite del mondo ricevuto: l’ordine promesso non coincide con i fatti."
    ],
    vocabulary: [
      ["Positivismo", "Fiducia ottocentesca nei fatti osservabili, nelle scienze e nella ricerca di leggi."],
      ["Borghesia lombarda", "Ceto urbano legato a impresa, professioni, istruzione e ideali di efficienza civile."],
      ["Plurilinguismo", "Coesistenza e uso di più lingue, dialetti, registri e lessici specialistici."],
      ["Linea lombarda", "Tradizione che unisce tensione civile, concretezza, ironia e sperimentazione espressiva."],
      ["Sistema", "Insieme di elementi il cui comportamento dipende dalle relazioni reciproche."],
      ["Espressionismo", "Deformazione intensa della lingua e delle immagini per rendere una realtà conflittuale."]
    ],
    map: "assets/maps/01-mondo.svg",
    mapAlt: "La borghesia lombarda promette ordine attraverso scienza, tecnica e lavoro; positivismo e realismo cercano leggi e fatti; la pluralità linguistica e la modernità moltiplicano i sistemi; Manzoni e la linea lombarda offrono due eredità; le contraddizioni di famiglia, patria e classe mettono in crisi l’ordine e preparano le fratture.",
    questions: [
      Q("Quale valore domina il mondo borghese ricevuto da Gadda?", ["L’efficienza fondata su scienza, tecnica e lavoro", "Il rifiuto di ogni conoscenza scientifica", "La fuga programmatica dalla vita civile"], 0, "La borghesia lombarda propone il progresso tecnico e produttivo come modello anche morale.", "mondo-promessa", ["La promessa dell’efficienza", "Il mondo di partenza crede che conoscere e organizzare significhi migliorare.", "Milano industriale appare come prova concreta del progresso."]),
      Q("Perché la pluralità linguistica è un dato storico prima che una tecnica?", ["Perché Gadda inventa tutti i dialetti italiani", "Perché l’Italia vive già fra dialetti, registri e lessici differenti", "Perché nel Novecento scompare l’italiano letterario"], 1, "Gadda trasforma in forma letteraria una pluralità già presente nella società italiana.", "mondo-lingua", ["Prima la società, poi lo stile", "La scelta formale nasce da lingue e gruppi reali, non dal puro virtuosismo.", "Il tecnico, il borghese e il popolano nominano diversamente lo stesso fatto."]),
      Q("Che cosa eredita soprattutto da Manzoni?", ["Il rifiuto della storia", "Una prosa esclusivamente dialettale", "Il nesso fra lingua, storia, istituzioni e giudizio morale"], 2, "Manzoni mostra che le colpe individuali agiscono dentro sistemi storici e sociali.", "mondo-lingua", ["L’eredità manzoniana", "La narrazione può collegare responsabilità personali e strutture collettive.", "La carestia non dipende da una sola persona ma non elimina le colpe."]),
      Q("Come va interpretata la formazione ingegneristica?", ["Come prova che ogni frase di Gadda deriva da una formula", "Come vocabolario di sistemi, relazioni e guasti", "Come elemento irrilevante per il suo pensiero"], 1, "L’ingegneria offre una disciplina del nesso, ma non determina meccanicamente la letteratura.", "mondo-modernita", ["Una forma mentale, non una causa unica", "La biografia rende intelligibili alcune scelte senza produrle automaticamente.", "Un circuito aiuta a pensare dipendenze lontane, non scrive un romanzo."]),
      Q("Quale problema prepara il passaggio alle fratture?", ["Conservare l’esattezza senza fingere che il reale sia semplice", "Sostituire la ragione con l’irrazionalità", "Dimostrare che la famiglia è sempre un rifugio"], 0, "Il nucleo è la distanza fra il bisogno di ordine e una realtà che smentisce i modelli.", "mondo-limite", ["Ordine e verità", "Gadda non rinuncia alla ragione: rifiuta la ragione che semplifica per comodità.", "Un progetto elegante fallisce se ignora le relazioni effettive."])
    ]
  },
  {
    id: "opere",
    number: "05",
    title: "Le opere più significative",
    subtitle: "Cinque laboratori del groviglio",
    question: "In quali forme Gadda mette alla prova la sua idea di una realtà pluricausale e linguisticamente stratificata?",
    color: "#42634f",
    lesson: `
      <h3 id="opere-giornale">Giornale di guerra e di prigionia: l’ideale davanti ai fatti</h3>
      <p>Il <em>Giornale di guerra e di prigionia</em>, composto fra il 1915 e il 1919 e pubblicato molto più tardi, registra il passaggio dalla guerra immaginata alla guerra vissuta. Gadda parte volontario con un forte senso del dovere nazionale. Al fronte osserva impreparazione, spreco, fame, ordini inadeguati e irresponsabilità. Dopo Caporetto, la prigionia porta l’umiliazione e l’impotenza. Il diario non è ancora il grande pastiche dei romanzi maturi, ma ne contiene il laboratorio morale: confrontare senza tregua parole e fatti.</p>
      <p>La testimonianza personale si apre così a una domanda collettiva. Chi risponde di una catastrofe prodotta da tanti errori? La colpa non coincide con un solo comando, ma non si dissolve nel destino. Il dolore per la morte di Enrico, appresa al ritorno, rende la sconfitta storica inseparabile dalla perdita privata. La guerra appare già come sistema, non come scena di eroismi individuali.</p>
      <h3 id="opere-meditazione">Meditazione milanese: il cantiere filosofico</h3>
      <p>Scritta nel 1928 e pubblicata postuma, la <em>Meditazione milanese</em> è l’opera teorica decisiva. Gadda pensa la realtà come molteplicità di sistemi, la sostanza come provvisorio equilibrio e la conoscenza come deformazione. Il titolo “milanese” conserva insieme modestia ironica e radice concreta: non un sistema filosofico chiuso, ma un esercizio che nasce fra ingegneria, Leibniz, Kant e osservazione del mondo moderno.</p>
      <p>La <em>Meditazione</em> non è un manuale da applicare ai romanzi come una formula. Mostra piuttosto che la narrativa e la filosofia lavorano sullo stesso problema con strumenti differenti. Il concetto di concausa diventa nel racconto intreccio; il sistema diventa città, famiglia o indagine; la deformazione conoscitiva diventa voce narrante che corregge continuamente se stessa.</p>
      <h3 id="opere-cognizione">La cognizione del dolore: casa, famiglia, società</h3>
      <p>Composta soprattutto fra il 1938 e il 1941, pubblicata a puntate e poi in volume nel 1963, <em>La cognizione del dolore</em> trasforma la Brianza nel Maradagàl sudamericano. Gonzalo Pirobutirro vive con la madre in una villa carica di debiti, memorie e conflitti. Intorno agiscono vicini, servitori, questuanti e un ambiguo istituto di vigilanza. La materia biografica è evidente, ma la trasfigurazione impedisce l’identificazione diretta fra Gonzalo e Gadda o fra la madre del personaggio e Adele.</p>
      <p>Il romanzo familiare diventa analisi di un intero mondo. La casa è proprietà, prestigio, affetto, spreco e spazio vulnerabile. Il dolore di Gonzalo non lo rende automaticamente innocente: la sua intelligenza convive con rabbia, disprezzo e incapacità di relazione. L’aggressione finale alla madre resta senza soluzione dichiarata. Nominare un solo colpevole non basterebbe a spiegare il sistema di incuria, sospetto e violenza che prepara l’evento.</p>
      <h3 id="opere-pasticciaccio">Quer pasticciaccio: il giallo delle concause</h3>
      <p><em>Quer pasticciaccio brutto de via Merulana</em> esce prima a puntate nel 1946-47 e poi in volume nel 1957, portando a Gadda un successo tardivo. A Roma, durante il fascismo, un furto e l’omicidio di Liliana Balducci attivano l’indagine del commissario Ingravallo. Il modello poliziesco promette la scoperta di causa e colpevole; Gadda lo usa per mostrare che ogni pista apre una rete ulteriore.</p>
      <p>Roma entra nel romanzo attraverso romanesco, molisano, napoletano, italiano burocratico, lessici tecnici e voce colta del narratore. La pluralità non è folclore: collega quartieri, classi, desideri, amministrazione e propaganda. Il fascismo proclama ordine mentre la città rivela miseria, sessualità nascosta, avidità e violenza. Il finale non dichiara l’assassino né produce un arresto, ma gli indizi convergono: l’apertura non equivale a vuoto totale. Il giallo è “letterariamente concluso” perché il centro non è il nome finale, bensì l’impossibilità di ridurre il fatto a una sola causalità.</p>
      <h3 id="opere-eros">Eros e Priapo: anatomia e limiti dell’invettiva</h3>
      <p>Scritto a partire dal 1944 e pubblicato in volume nel 1967, <em>Eros e Priapo</em> demolisce Mussolini e interroga il consenso di massa. Il fascismo appare come dispositivo di narcisismo, eccitazione collettiva, obbedienza e retorica. Il linguaggio stesso del regime diventa oggetto di deformazione: titoli, pose e parole solenni vengono restituiti come sintomi di una regressione.</p>
      <p>Il testo è importante anche perché obbliga a conservare la contraddizione biografica: la critica posteriore non cancella l’iscrizione al partito e gli scritti precedenti favorevoli al regime. Inoltre la lettura psicosessuale del fascismo ricorre a stereotipi misogini e immagini oggi inaccettabili. Lo studente deve saper distinguere la forza dell’analisi del consenso dai limiti del suo vocabolario.</p>
      <h3 id="opere-rete">Una costellazione, non cinque caselle</h3>
      <p>Altre opere — <em>Il castello di Udine</em>, <em>L’Adalgisa</em>, <em>La meccanica</em>, <em>I viaggi la morte</em>, <em>Accoppiamenti giudiziosi</em> — ampliano la costellazione. Le cinque scelte, però, rendono visibile il percorso: il diario misura l’ideale sui fatti; la filosofia costruisce i concetti; il romanzo familiare concentra il dolore; il giallo indaga le concause; il pamphlet attacca il potere e mostra anche i rischi dell’invettiva. Nessuna opera illustra passivamente una teoria: ciascuna la modifica attraverso la propria forma.</p>`,
    summary: "Cinque opere mostrano la poetica gaddiana in azione. Il Giornale di guerra e di prigionia confronta l’ideale patriottico con disorganizzazione, prigionia e lutto. La Meditazione milanese elabora sistemi, deformazione e concause senza diventare un manuale dei romanzi. La cognizione del dolore trasforma la materia familiare in un sistema economico, sociale e affettivo; Gonzalo non coincide semplicemente con Gadda. Il Pasticciaccio usa il giallo per indagare concause e fa della pluralità linguistica di Roma una struttura conoscitiva; il finale aperto non equivale a mancanza assoluta di indizi. Eros e Priapo smonta Mussolini e il consenso, ma va letto criticamente anche nei suoi stereotipi e alla luce delle precedenti compromissioni dell’autore. Le opere non applicano una teoria: la sviluppano in forme diverse.",
    essentials: [
      "Leggere il Giornale come verifica dei discorsi patriottici attraverso i fatti.",
      "Usare la Meditazione per comprendere sistemi e concausalità senza ridurre i romanzi a esempi.",
      "Distinguere trasfigurazione autobiografica e identificazione diretta nella Cognizione.",
      "Spiegare come il modello del giallo renda narrabile l’indagine sulle concause.",
      "Interpretare il plurilinguismo del Pasticciaccio come mappa sociale di Roma.",
      "Valutare Eros e Priapo nella forza antifascista e nei suoi limiti.",
      "Ricostruire la costellazione delle opere come sviluppo, non catalogo."
    ],
    vocabulary: [
      ["Diario di guerra", "Scrittura testimoniale legata alla prossimità degli eventi e alla loro verifica morale."],
      ["Trattato", "Testo argomentativo che elabora concetti e relazioni teoriche."],
      ["Trasfigurazione", "Trasformazione della materia vissuta in un sistema letterario autonomo."],
      ["Giallo conoscitivo", "Romanzo investigativo che usa il delitto per interrogare cause e limiti del sapere."],
      ["Pamphlet", "Testo polemico e satirico diretto contro un potere, una persona o un’ideologia."],
      ["Polifonia", "Compresenza di voci portatrici di prospettive non riducibili a una sola."],
      ["Finale aperto", "Chiusura che non risolve in modo univoco tutti i conflitti e gli indizi."]
    ],
    map: "assets/maps/05-opere.svg",
    mapAlt: "Il Giornale verifica l’ideale sui fatti; la Meditazione elabora sistemi e concause; la Cognizione trasforma casa e famiglia in rete; il Pasticciaccio usa il giallo e la polifonia per indagare Roma; Eros e Priapo attacca fascismo e consenso mostrando anche i limiti dell’invettiva; le forme confluiscono in una costellazione del groviglio.",
    questions: [
      Q("Che cosa viene sottoposto alla prova nel Giornale?", ["La teoria del giallo", "L’ideale patriottico ed eroico della guerra", "La tecnica radiofonica"], 1, "La realtà materiale del fronte misura e smentisce la retorica bellica.", "opere-giornale", ["Parole davanti ai fatti", "Il diario confronta aspettativa morale e organizzazione reale.", "Dovere e patria urtano contro fame, ordini inadeguati e prigionia."]),
      Q("Quale opera elabora più direttamente sistemi e deformazione?", ["Eros e Priapo", "L’Adalgisa", "Meditazione milanese"], 2, "La Meditazione è il cantiere filosofico della concezione relazionale.", "opere-meditazione", ["Il laboratorio teorico", "Filosofia e narrativa affrontano lo stesso problema con strumenti diversi.", "Il concetto di concausa diventerà intreccio nel Pasticciaccio."]),
      Q("Perché la Cognizione non è una semplice autobiografia?", ["Perché trasforma la materia familiare in un sistema sociale e immaginario", "Perché non contiene alcun elemento biografico", "Perché è ambientata fedelmente a Milano"], 0, "Maradagàl, Gonzalo e la casa ricreano la vita in una struttura autonoma.", "opere-cognizione", ["Dalla vita alla forma", "Trasfigurare significa conservare materiali e cambiarne funzione e relazioni.", "La Brianza diventa Sudamerica immaginario e la famiglia entra in una rete politica."]),
      Q("Perché il Pasticciaccio usa la forma del giallo?", ["Per eliminare la critica sociale", "Per promettere e problematizzare la ricerca delle cause", "Per offrire una soluzione immediata"], 1, "L’indagine poliziesca rende visibile la proliferazione delle piste causali.", "opere-pasticciaccio", ["Il giallo come epistemologia", "Cercare il colpevole diventa cercare relazioni, ambienti e moventi.", "Ogni interrogatorio apre legami che superano il singolo sospettato."]),
      Q("Come va letto Eros e Priapo?", ["Solo come prova di un antifascismo sempre coerente", "Come testo da escludere per i suoi limiti", "Come critica del consenso da confrontare con compromissioni e stereotipi"], 2, "Una lettura rigorosa conserva insieme potenza critica, storia dell’autore e limiti del linguaggio.", "opere-eros", ["Una critica senza agiografia", "Il valore di un’analisi non cancella contraddizioni e immagini ingiuste.", "L’invettiva contro Mussolini segue una precedente fase di adesione."])
    ]
  },
  {
    id: "conclusione",
    number: "06",
    title: "Conclusione",
    subtitle: "La complessità come responsabilità",
    question: "Che cosa resta vivo di Gadda quando usciamo dal suo laboratorio linguistico e torniamo al presente?",
    color: "#39464b",
    lesson: `
      <h3 id="conclusione-catena">Ricomporre i sei movimenti</h3>
      <p>Il percorso può essere ricostruito come una trasformazione. Il mondo precedente promette ordine attraverso borghesia, scienza, tecnica, famiglia, patria e lingua nazionale. Le fratture mostrano che questi sistemi possono produrre dissesto, guerra, lutto, retorica e consenso. Da questa smentita nasce un’immagine del reale come rete di relazioni e concause: il fatto è un nodo, l’io è un sistema aperto, la conoscenza è un’operazione che deforma.</p>
      <p>Una realtà simile rende necessaria una poetica plurale. Pastiche, dialetti, tecnicismi, digressioni, accumuli e grottesco non sono decorazioni: seguono i fili del mondo e smontano le lingue che fingono neutralità. Le opere verificano la poetica in forme differenti, dal diario al pamphlet. Il risultato non è un elogio del caos, ma una ragione resa più esigente dalla coscienza dei propri limiti.</p>
      <h3 id="conclusione-ragione">Contro la semplificazione, non contro la ragione</h3>
      <p>La distinzione è decisiva. Gadda non sostiene che la verità sia impossibile o che ogni interpretazione valga quanto un’altra. L’investigatore continua a cercare, lo scrittore documenta luoghi e parole, l’ingegnere controlla i nessi. Ciò che viene rifiutato è la soluzione che chiude troppo presto: una causa principe che assolve tutte le concause, un colpevole trasformato in mostro estraneo, una lingua ufficiale che cancella i parlanti reali.</p>
      <p>La verità gaddiana è parziale nel senso più rigoroso: fondata, discutibile, capace di correggersi e consapevole di non coincidere col tutto. Questa posizione è più scomoda sia della certezza dogmatica sia del relativismo. Obbliga a cercare prove senza promettere una vista assoluta.</p>
      <h3 id="conclusione-etica">Un’etica dei nessi</h3>
      <p>La causalità complessa possiede una conseguenza politica. I poteri preferiscono racconti lineari: identificano un nemico, semplificano una crisi, trasformano la ripetizione in evidenza. Ricostruire i sistemi significa chiedere quali istituzioni, interessi, omissioni e linguaggi abbiano cooperato. Non serve a distribuire la colpa in modo così largo da renderla innocua; serve a graduare responsabilità e a impedire che la società si assolva sacrificando un solo colpevole.</p>
      <p>Il rapporto contraddittorio di Gadda col fascismo rende questa lezione meno comoda e più vera. Egli fu sensibile alla promessa di ordine del regime e solo dopo ne produsse una demolizione radicale. La sua opera ci insegna anche involontariamente che l’intelligenza non immunizza dal consenso. Per comprendere un’ideologia bisogna studiare non soltanto le menzogne del capo, ma i bisogni e i linguaggi attraverso cui una collettività le rende credibili.</p>
      <h3 id="conclusione-leggere">Come leggere una pagina difficile</h3>
      <p>La difficoltà di Gadda non va né eliminata né venerata. Una strategia efficace procede per strati. Prima si individua il fatto narrato; poi si riconoscono le voci e i registri; quindi si osservano le deviazioni e si domanda quale relazione aggiungano; infine si valuta il giudizio prodotto dal montaggio. Non occorre decifrare ogni parola al primo passaggio. Occorre capire perché una parola tecnica, dialettale o arcaica sia collocata proprio lì.</p>
      <p>Rendere Gadda accessibile non significa tradurlo in una prosa piatta. Significa offrire al lettore strumenti per attraversare il groviglio. È la funzione di questa PWA: lezioni e mappe costruiscono orientamento; i quiz non premiano la memoria di etichette ma verificano nessi; il recupero torna sul punto preciso in cui il filo si è spezzato.</p>
      <h3 id="conclusione-presente">Gadda nel presente delle spiegazioni rapide</h3>
      <p>Il nostro tempo produce immense quantità di linguaggio e premia la sintesi immediata. Titoli, post, slogan politici e sistemi automatici tendono a scegliere una causa dominante perché è più facile da comunicare. La lezione gaddiana non impone di rendere ogni discorso interminabile. Chiede di sapere che cosa si perde quando si accorcia: quali soggetti spariscono, quali condizioni vengono naturalizzate, quale interesse presenta la propria versione come semplice buon senso.</p>
      <p>Anche davanti a una risposta generata da un’intelligenza artificiale, la domanda gaddiana è utile: quali fonti, scelte linguistiche e omissioni hanno prodotto questa apparente chiarezza? La complessità non è il contrario della comprensione; è ciò che la comprensione deve imparare a non tradire.</p>
      <h3 id="conclusione-domanda">La domanda che resta</h3>
      <p>Resta infine una tensione discutibile: quanta complessità può accogliere una lingua senza perdere la capacità di agire? Semplificare è inevitabile; altrimenti nessuna decisione sarebbe possibile. Ma una semplificazione può dichiarare i propri limiti oppure mascherarli. Gadda ci lascia un criterio: diffidare dell’ordine che sembra naturale, verificare i nessi, ascoltare le lingue escluse, riaprire una spiegazione quando pretende di aver detto tutto.</p>
      <p>La sua eredità non è una formula stilistica da imitare. È una disciplina dell’attenzione. Il groviglio non chiede al lettore di arrendersi: gli chiede di seguire più di un filo e di assumersi la responsabilità di non scambiare la comodità per la verità.</p>`,
    summary: "Il percorso conduce dalla promessa borghese di ordine alle fratture di famiglia, guerra e fascismo; da queste nasce una visione del reale come rete di concause e una poetica plurilingue. Gadda critica la semplificazione, non la ragione: cerca verità fondate ma parziali, aperte alla correzione. La causalità complessa diventa un’etica dei nessi perché impedisce a istituzioni e comunità di assolversi attraverso un solo capro espiatorio. La contraddizione politica dell’autore dimostra che l’intelligenza non immunizza dal consenso. Leggere Gadda richiede distinguere fatto, voci, digressioni e giudizio, senza appiattire né venerare la difficoltà. Nel presente delle spiegazioni rapide, la sua disciplina domanda quali fonti, soggetti e condizioni siano stati esclusi. Resta un problema: semplificare è necessario per agire, ma una semplificazione responsabile deve dichiarare i propri limiti.",
    essentials: [
      "Ricostruire la catena completa da ordine ricevuto a poetica plurilingue.",
      "Distinguere critica della semplificazione e rifiuto della ragione.",
      "Definire la verità parziale come fondata, correggibile e non totalizzante.",
      "Applicare l’etica dei nessi a propaganda, consenso e capri espiatori.",
      "Usare le contraddizioni politiche di Gadda come problema storico, non incidente da cancellare.",
      "Leggere una pagina difficile per strati: fatto, voci, deviazioni, giudizio.",
      "Valutare i costi di ogni semplificazione nel presente."
    ],
    vocabulary: [
      ["Razionalità semplificatrice", "Ragione che elimina relazioni per ottenere un ordine più comodo che vero."],
      ["Verità parziale", "Conoscenza fondata ma non esaustiva, capace di revisione."],
      ["Etica dei nessi", "Responsabilità di ricostruire relazioni e graduare le colpe senza capri espiatori."],
      ["Propaganda", "Comunicazione orientata a produrre consenso attraverso selezione e ripetizione."],
      ["Lettura stratificata", "Metodo che distingue evento, voci, tecniche e giudizio di un testo."],
      ["Semplificazione responsabile", "Riduzione necessaria che dichiara criteri, limiti e aspetti esclusi."],
      ["Disciplina dell’attenzione", "Abitudine a verificare nessi e differenze prima di chiudere una spiegazione."]
    ],
    map: "assets/maps/06-conclusione.svg",
    mapAlt: "Il mondo ordinato viene smentito dalle fratture; le fratture generano una visione pluricausale; la visione richiede una poetica plurilingue; le opere verificano le forme; l’eredità è una ragione critica e un’etica dei nessi; questa disciplina interroga le semplificazioni del presente e apre la domanda su come agire senza tradire la complessità.",
    questions: [
      Q("Gadda rifiuta la ragione?", ["Sì, sostituisce ogni causa con il caos", "No, cerca una ragione più adeguata alla complessità", "Sì, perché considera inutili le prove"], 1, "La ricerca resta razionale, documentaria e investigativa, ma rifiuta le chiusure premature.", "conclusione-ragione", ["Una ragione più esigente", "Criticare la semplificazione non significa rinunciare alla conoscenza.", "Ingravallo continua a indagare anche senza promettere una causa unica."]),
      Q("Che cosa rende rigorosa una verità parziale?", ["L’essere fondata, discutibile e correggibile", "Il coincidere con una semplice opinione", "Il rifiutare qualunque prova contraria"], 0, "Parziale non significa arbitraria: indica un sapere che non finge di essere totale.", "conclusione-ragione", ["Fondata senza essere totale", "Una spiegazione vale per prove e capacità di rispondere alle obiezioni.", "Una mappa è utile se dichiara la scala e non pretende di essere il territorio."]),
      Q("Quale rischio politico produce la causa unica?", ["Rende visibili tutte le istituzioni", "Aumenta automaticamente il pluralismo", "Favorisce capri espiatori e assoluzioni collettive"], 2, "Isolare un colpevole può nascondere strutture e complicità che hanno reso possibile l’evento.", "conclusione-etica", ["L’etica dei nessi", "Ricostruire più responsabilità impedisce alla società di dichiararsi estranea.", "La propaganda attribuisce una crisi a un nemico e cancella decisioni istituzionali."]),
      Q("Come si affronta una pagina difficile di Gadda?", ["Cercando subito ogni parola e ignorando il fatto", "Per strati: evento, voci, deviazioni e giudizio", "Riducendola a una parafrasi uniforme"], 1, "Il metodo conserva la complessità ma offre un ordine di attraversamento.", "conclusione-leggere", ["Leggere per strati", "Prima orientarsi, poi riconoscere che cosa aggiunge ogni scelta linguistica.", "Il romanesco situa una voce; il tecnicismo introduce un sapere; la digressione apre un nesso."]),
      Q("Qual è la domanda finale sulla semplificazione?", ["Come eliminarla per sempre", "Come renderla più veloce", "Come agire semplificando senza mascherare ciò che viene escluso"], 2, "Ogni decisione riduce la complessità; la responsabilità sta nel dichiarare limiti e costi.", "conclusione-domanda", ["Semplificare senza mentire", "Una sintesi è legittima quando rende visibili criteri e omissioni.", "Un titolo può indicare la causa principale e segnalare che non è l’unica."])
    ]
  },
  {
    id: "immagine",
    number: "03",
    title: "L’immagine del mondo",
    subtitle: "Lo gnommero delle concause",
    question: "Come appare la realtà quando nessuna causa e nessun osservatore possono stare davvero isolati?",
    color: "#5a526f",
    lesson: `
      <h3 id="immagine-nodo">Dal fatto isolato al nodo di relazioni</h3>
      <p>L’immagine più celebre del pensiero gaddiano è il gomitolo: in romanesco, lo <em>gnommero</em> o <em>gliuommero</em>. Un fatto appare come un punto, ma appena lo si interroga si scopre che è l’incrocio di molti fili. Un delitto dipende da desideri, denaro, spazi urbani, rapporti familiari, istituzioni, casualità apparenti e decisioni precedenti. Un fallimento economico rinvia a prestigio sociale, investimenti, affetti e paure. La realtà non è una collezione di oggetti autonomi: è una rete mobile di sistemi.</p>
      <p>Questo non significa che “tutto dipende da tutto” in modo vago. Una concausa è una condizione specifica che coopera con altre alla produzione di un evento. Alcune relazioni possono essere documentate, altre restano ipotesi. La complessità richiede quindi più rigore, non meno: occorre distinguere i fili reali dalle associazioni arbitrarie. Nel <em>Pasticciaccio</em>, il commissario Ingravallo pensa il delitto come una convergenza di causalità. L’indagine non viene abolita; perde soltanto l’illusione che una spiegazione unica possa esaurire il fatto.</p>
      <h3 id="immagine-filosofia">Leibniz, sistemi e deformazione</h3>
      <p>Negli anni Venti Gadda frequenta corsi di filosofia e progetta una tesi su Leibniz. La <em>Meditazione milanese</em>, scritta nel 1928 e pubblicata postuma, è il laboratorio più esplicito della sua concezione. Da Leibniz conserva l’attenzione alla molteplicità delle percezioni e alle relazioni; ne rifiuta però una lettura pacificata. L’individuo non è una sostanza perfettamente chiusa e armonica. È attraversato da eredità biologiche, famiglia, lingua, storia e materia.</p>
      <p>Anche conoscere è un processo. Non esiste uno sguardo collocato fuori dall’universo, capace di fotografarlo senza conseguenze. Chi osserva seleziona, nomina, collega; quindi “deforma” l’oggetto, mentre ciò che incontra modifica a sua volta le sue categorie. Deformazione non significa falsificazione volontaria: indica il carattere operativo della conoscenza. Una carta geografica deforma il territorio per renderne leggibili alcuni rapporti; diventa ingannevole solo se si presenta come il territorio intero.</p>
      <h3 id="immagine-io">L’io come sistema aperto</h3>
      <p>La stessa critica vale per l’identità. L’io non è un nucleo sovrano che decide da una posizione pura. È un nodo di memorie, desideri, abitudini, parole altrui e situazioni sociali. Questo decentramento non cancella la responsabilità. Al contrario, impedisce di assolvere una persona invocando un carattere immutabile o di condannarla senza ricostruire il sistema nel quale agisce. La responsabilità diventa relazionale: una decisione appartiene a chi la prende, ma le sue condizioni e i suoi effetti superano il singolo.</p>
      <p>Qui si comprende anche la difficoltà della colpa in Gadda. Il male può concentrarsi in un gesto, ma spesso è preparato da incuria, vanità, linguaggi pubblici e piccoli vantaggi accettati da molti. La ricerca del “mostro” isolato protegge il resto della società dall’esame di sé. Tuttavia Gadda non trasforma la pluralità in alibi. Dire che esistono concause non equivale a dire che tutte le responsabilità siano uguali.</p>
      <h3 id="immagine-barocco">“Barocco è il mondo”</h3>
      <p>Definire Gadda “barocco” può essere utile solo se non si riduce la parola a ornamento. Per lui la deformazione è già nelle cose: corpi, oggetti, istituzioni e frasi sociali sono stratificati, eccedenti, spesso caricaturali. La prosa accentua queste tensioni per renderle visibili. Il barocco non è un velo appoggiato sopra un mondo semplice; è il modo in cui un mondo contraddittorio appare quando viene osservato senza levigature.</p>
      <p>Perciò il comico e il tragico convivono. Una descrizione grottesca può far ridere e subito dopo mostrare dolore o violenza. Il riso non risolve il disordine; rompe la facciata rispettabile che lo copre. Nella <em>Cognizione</em>, la casa familiare è insieme memoria, farsa sociale, campo di battaglia affettivo e possibile scena del delitto.</p>
      <h3 id="immagine-verita">Una ragione tormentata, non la rinuncia alla verità</h3>
      <p>Il groviglio non autorizza il relativismo secondo cui ogni versione vale quanto un’altra. Alcune spiegazioni sono più documentate, comprendono più dati, rendono conto delle obiezioni; altre sono slogan. Gadda resta fedele a una ragione investigativa, ma sa che ogni risultato è provvisorio. La verità può essere fondata senza essere totale.</p>
      <p>Questa posizione ha una conseguenza etica. La causa unica può diventare un’arma: costruisce capri espiatori, assolve le istituzioni, trasforma la propaganda in evidenza. Ricostruire le concause significa restituire visibilità a ciò che l’ordine ufficiale elimina. Ma se il mondo è fatto di tante relazioni, nasce un problema espressivo: quale lingua può mostrarle senza ridurle a un discorso uniforme? L’immagine del mondo rende necessaria la poetica.</p>`,
    summary: "Per Gadda ogni fatto è un nodo di relazioni, non un oggetto isolato. Lo gnommero rappresenta una pluralità di concause specifiche e verificabili, non un caos nel quale tutto vale. La Meditazione milanese traduce la formazione filosofica in una concezione sistemica: anche l’osservatore appartiene al mondo osservato e conoscere significa selezionare, collegare e quindi deformare. L’io stesso è un sistema aperto di memoria, corpo, lingua e storia. La responsabilità non scompare, ma deve essere distribuita senza considerare equivalenti tutte le colpe. “Barocco” indica prima di tutto la deformazione già presente nelle cose; la prosa la rende visibile unendo comico e tragico. Gadda conserva una ragione investigativa: la verità può essere fondata senza diventare totale. Questa immagine richiede una lingua capace di rappresentare la molteplicità.",
    essentials: [
      "Definire lo gnommero come rete di concause e non come assenza di spiegazione.",
      "Distinguere una concausa documentabile da un’associazione arbitraria.",
      "Spiegare perché l’osservatore appartiene al sistema che studia.",
      "Descrivere l’io come nodo aperto senza cancellare la responsabilità personale.",
      "Comprendere il barocco come qualità del mondo prima che ornamento stilistico.",
      "Distinguere verità parziale, relativismo e spiegazione totalizzante.",
      "Collegare la causalità complessa alla critica dei capri espiatori."
    ],
    vocabulary: [
      ["Gnommero", "Gomitolo: immagine di un fatto composto da fili causali molteplici e intrecciati."],
      ["Concausa", "Condizione specifica che coopera con altre alla produzione di un evento."],
      ["Epistemologia", "Riflessione sui metodi, le possibilità e i limiti della conoscenza."],
      ["Deformazione", "Trasformazione inevitabile compiuta da ogni percezione o modello conoscitivo."],
      ["Sistema aperto", "Insieme che scambia effetti e informazioni con altri sistemi."],
      ["Relativismo", "Posizione che considera impossibile stabilire criteri fra interpretazioni differenti."],
      ["Capro espiatorio", "Soggetto isolato sul quale una comunità scarica colpe più ampie e distribuite."]
    ],
    map: "assets/maps/03-immagine.svg",
    mapAlt: "Il fatto è un nodo di concause; la Meditazione milanese lo interpreta come sistema; conoscere produce deformazione perché l’osservatore è coinvolto; anche l’io è aperto; responsabilità e male sono relazionali; il barocco appartiene al mondo; la ragione investigativa ricerca verità fondate ma parziali e rende necessaria una lingua plurale.",
    questions: [
      Q("Che cosa rappresenta lo gnommero?", ["L’assenza completa di legami", "Una rete intricata di cause, fatti e responsabilità", "Un errore occasionale dell’investigatore"], 1, "Il gomitolo conserva i fili: la complessità non annulla le connessioni.", "immagine-nodo", ["Il gomitolo causale", "Un evento nasce dall’interazione di condizioni differenti ma ricostruibili.", "Un delitto coinvolge moventi, luoghi, denaro, istituzioni e decisioni precedenti."]),
      Q("Che cosa distingue una concausa da un’associazione arbitraria?", ["La concausa deve avere un rapporto argomentato o documentato con l’evento", "La concausa è sempre la prima informazione trovata", "Non esiste alcuna differenza"], 0, "La complessità aumenta l’obbligo di provare i nessi.", "immagine-nodo", ["Più fili, più rigore", "Non basta nominare due fatti: bisogna mostrare come cooperano.", "Il costo della villa incide sul dissesto; il colore del cielo, senza altri dati, no."]),
      Q("Perché conoscere comporta deformazione?", ["Perché ogni studioso mente", "Perché i fatti non esistono", "Perché selezionare, nominare e modellizzare trasforma ciò che appare"], 2, "Una rappresentazione rende leggibili alcuni rapporti e ne lascia altri sullo sfondo.", "immagine-filosofia", ["Conoscere è operare", "Ogni modello sceglie una scala e un punto di vista.", "Una carta stradale deforma le distanze per mostrare percorsi."]),
      Q("La pluralità delle cause elimina la responsabilità?", ["Sì, perché nessuno può essere giudicato", "No: distribuisce le responsabilità senza renderle tutte uguali", "Sì, perché ogni gesto dipende soltanto dall’ambiente"], 1, "Gadda amplia l’indagine della colpa, ma non trasforma le concause in alibi.", "immagine-io", ["Responsabilità relazionale", "Il contesto spiega condizioni e complicità senza cancellare la scelta.", "Un ordine illegittimo coinvolge chi lo emette e, in misura diversa, chi lo esegue."]),
      Q("Che cosa significa affermare che il barocco è nel mondo?", ["Che la prosa aggiunge ornamenti inutili", "Che ogni realtà è bella", "Che deformazione e stratificazione precedono la loro resa stilistica"], 2, "La lingua gaddiana accentua una complessità che appartiene già alle cose.", "immagine-barocco", ["Non decorazione, ma diagnosi", "Lo stile diventa intenso perché vuole mostrare tensioni reali.", "La casa è insieme oggetto economico, memoria, prestigio e conflitto."])
    ]
  },
  {
    id: "poetica",
    number: "04",
    title: "La poetica",
    subtitle: "Una lingua capace di conoscere",
    question: "Come deve scrivere Gadda per non semplificare una realtà fatta di sistemi, voci e deformazioni?",
    color: "#7a5b2e",
    lesson: `
      <h3 id="poetica-necessita">La complessità della lingua è una necessità</h3>
      <p>La frase centrale di questo percorso è semplice: la lingua di Gadda non complica una realtà semplice; rende percepibile una realtà che è già complessa. Se il mondo è attraversato da classi, mestieri, luoghi, saperi e desideri differenti, una voce narrativa perfettamente uniforme produrrebbe un ordine falso. Il plurilinguismo è allora una scelta conoscitiva: italiano letterario, dialetti, tecnicismi, burocratese, latino, parole straniere, arcaismi e neologismi portano nel testo prospettive diverse.</p>
      <p>Ogni registro contiene informazioni. Un gergo professionale mostra ciò che un mestiere sa vedere e ciò che tende a ignorare; un dialetto colloca il parlante in una geografia e in una relazione sociale; una formula burocratica può nascondere la responsabilità dietro l’impersonalità. Gadda non usa le lingue come etichette immobili: le contamina, le deforma e le fa reagire. La voce del narratore può scivolare dentro quella di un personaggio e poi prenderne le distanze, creando un giudizio instabile ma non neutrale.</p>
      <h3 id="poetica-pastiche">Pastiche e maccheronea</h3>
      <p>Il termine <em>pastiche</em> indica l’impasto consapevole di stili eterogenei. La tradizione maccheronica, da Folengo a Rabelais, offre un precedente di mescolanza fra lingue alte e basse, corpi, eccesso e parodia. Nel modernismo europeo anche Joyce o Céline affrontano la crisi del realismo uniforme attraverso una lingua plurale. Gadda appartiene a questa costellazione senza perdere la propria radice lombarda e manzoniana.</p>
      <p>Il pastiche svolge almeno quattro funzioni. È mimetico, perché riproduce l’eterogeneità sociale; conoscitivo, perché mette in relazione saperi differenti; satirico, perché smonta la voce ufficiale facendola urtare contro i fatti; etico, perché impedisce a un solo linguaggio di presentarsi come naturale e assoluto. Non è quindi un ornamento che si possa togliere lasciando intatto il contenuto: la forma produce il modo stesso in cui il reale viene compreso.</p>
      <p>La precisione e la deformazione non sono nemiche. Un termine scientifico può circoscrivere un fenomeno con rigore e, collocato in un contesto inatteso, smascherare comicamente una pretesa. Gadda cerca una precisione capace di includere l’attrito fra linguaggi, non la superficie levigata di una lingua neutra.</p>
      <h3 id="poetica-digressione">Digressione, accumulo, catalogo</h3>
      <p>La trama gaddiana avanza deviando. Un oggetto apre la sua storia, una parola richiama un ambiente, un personaggio conduce a una rete di rapporti. La digressione non è una distrazione casuale: segue i fili che il racconto lineare taglierebbe. Accumuli ed enumerazioni fanno percepire quantità, pressione e proliferazione; metafore tecniche o biologiche collegano domini lontani. Il periodo può espandersi con incisi e correzioni, come se il pensiero rifiutasse di chiudersi prima di aver registrato le proprie obiezioni.</p>
      <p>Questo procedimento domanda al lettore un lavoro attivo. Non si può consumare la frase cercando soltanto “che cosa succede”; bisogna osservare chi parla, con quale lessico, contro quale versione dei fatti. La difficoltà non va celebrata come valore in sé. Una pagina è riuscita quando la complessità formale fa vedere relazioni che una prosa più piana nasconderebbe.</p>
      <h3 id="poetica-grottesco">Grottesco, comicità e dolore</h3>
      <p>Il grottesco deforma corpi, gesti e discorsi fino a rivelarne le pretese. La rispettabilità borghese può apparire come posa fisica; il linguaggio del potere come gonfiore narcisistico; la burocrazia come macchina che moltiplica l’irresponsabilità. Ma il riso gaddiano è spesso attraversato dal dolore. Il comico non consola: mostra la sproporzione fra le maschere e il danno reale.</p>
      <p>La satira possiede perciò un rischio. In <em>Eros e Priapo</em> l’energia verbale che smonta Mussolini e il consenso fascista ricorre anche a schemi sessuali, immagini misogine e generalizzazioni che vanno giudicate criticamente. La potenza di una forma non rende innocenti tutti i suoi strumenti. Leggere Gadda significa esercitare su di lui la stessa attenzione che egli rivolge ai linguaggi del potere.</p>
      <h3 id="poetica-nonfinito">Il non finito senza mitologia</h3>
      <p><em>La cognizione del dolore</em> e <em>Quer pasticciaccio brutto de via Merulana</em> non offrono una chiusura tradizionale. È sensato collegare questa apertura alla causalità complessa: un colpevole nominato non esaurirebbe il sistema del male. Sarebbe però scorretto trasformare ogni incompiutezza in un programma perfettamente intenzionale. Revisioni continue, autocritica, condizioni editoriali e difficoltà personali contribuiscono alla storia dei testi.</p>
      <p>Nel <em>Pasticciaccio</em> gli indizi possono convergere senza produrre un arresto e una soluzione dichiarata; Gadda stesso parlò di conclusione letteraria. Il non finito non è assenza di forma, ma una forma che sposta l’attenzione dal responso al processo conoscitivo. Le opere metteranno ora alla prova questi strumenti: diario, trattato, romanzo familiare, giallo e pamphlet saranno cinque diversi accessi al groviglio.</p>`,
    summary: "Il plurilinguismo gaddiano nasce dalla necessità di rappresentare una realtà socialmente e conoscitivamente plurale. Dialetti, tecnicismi, burocratese, italiano letterario, arcaismi e neologismi portano nel testo punti di vista differenti. Il pastiche ha funzione mimetica, conoscitiva, satirica ed etica; non è un ornamento separabile dalla conoscenza. Digressione, accumulo e catalogo seguono relazioni che la trama lineare taglierebbe e chiedono al lettore di riconoscere voci e interessi. Grottesco e comicità smascherano rispettabilità e potere, ma restano attraversati dal dolore. Eros e Priapo mostra anche i rischi di una satira fondata su immagini misogine e schemi riduttivi, da valutare criticamente. Il non finito è coerente con la causalità complessa, ma dipende anche da revisioni e vicende editoriali: non va trasformato in una mitologia dell’incompiutezza.",
    essentials: [
      "Spiegare il plurilinguismo come strumento conoscitivo, non esibizione di difficoltà.",
      "Attribuire a ogni registro una prospettiva sociale, geografica o professionale.",
      "Distinguere le funzioni mimetica, conoscitiva, satirica ed etica del pastiche.",
      "Comprendere la digressione come esplorazione dei nessi laterali.",
      "Collegare grottesco e dolore senza ridurre Gadda a scrittore comico.",
      "Valutare criticamente i limiti della satira in Eros e Priapo.",
      "Leggere il non finito come forma e storia editoriale, non dogma unico."
    ],
    vocabulary: [
      ["Pastiche", "Impasto consapevole di lingue, registri e stili eterogenei."],
      ["Maccheronea", "Tradizione comica e corporea fondata sulla mescolanza di lingue alte e basse."],
      ["Tecniscismo", "Parola o costruzione propria di un sapere o di una professione specialistica."],
      ["Digressione", "Deviazione dalla linea principale che esplora connessioni laterali."],
      ["Accumulo", "Successione fitta di elementi che rende percepibile quantità e pressione."],
      ["Grottesco", "Deformazione che unisce comico e inquietante per smascherare una realtà."],
      ["Non finito", "Forma priva di una chiusura univoca, dovuta a ragioni poetiche e materiali."]
    ],
    map: "assets/maps/04-poetica.svg",
    mapAlt: "La realtà plurale rende necessario il plurilinguismo; i registri confluiscono nel pastiche con funzioni mimetica, conoscitiva, satirica ed etica; digressione e accumulo seguono i nessi; grottesco e comicità smascherano il potere ma vanno letti criticamente; il non finito mantiene aperta l’indagine e conduce alle opere.",
    questions: [
      Q("Perché Gadda mescola dialetti e linguaggi tecnici?", ["Per impedire ogni comprensione", "Per rappresentare strati e prospettive differenti del reale", "Per dimostrare che l’italiano deve scomparire"], 1, "Ogni varietà linguistica reca informazioni su luogo, classe, sapere e interesse.", "poetica-necessita", ["Le lingue sono punti di vista", "La variazione linguistica appartiene alla struttura sociale rappresentata.", "Un tecnicismo mostra la competenza di chi parla; il dialetto la sua posizione e relazione."]),
      Q("Quale funzione non appartiene al pastiche gaddiano?", ["Rendere uniforme ogni voce", "Mettere in relazione saperi diversi", "Smascherare la lingua ufficiale"], 0, "Il pastiche moltiplica e mette in conflitto le voci; non le uniforma.", "poetica-pastiche", ["Quattro funzioni", "Il pastiche è mimetico, conoscitivo, satirico ed etico.", "Il burocratese urta contro il dialetto e perde la pretesa di neutralità."]),
      Q("Qual è la funzione della digressione?", ["Riassumere rapidamente la trama", "Eliminare ogni nesso", "Seguire relazioni che il racconto lineare lascerebbe fuori"], 2, "La deviazione amplia il campo causale e semantico.", "poetica-digressione", ["Deviare per conoscere", "La linea principale non basta quando un oggetto contiene più storie.", "Un gioiello conduce a proprietari, desideri, commercio e furto."]),
      Q("Come va valutata la satira di Eros e Priapo?", ["Come innocente perché antifascista", "Nella sua forza critica e anche nei suoi stereotipi e limiti", "Come testo privo di rapporto con la politica"], 1, "La critica del potere non assolve automaticamente il linguaggio usato per compierla.", "poetica-grottesco", ["Criticare anche il critico", "Una forma potente può riprodurre immagini ingiuste.", "La demolizione di Mussolini convive con generalizzazioni misogine."]),
      Q("Perché il non finito non va spiegato con una sola causa?", ["Perché unisce coerenza poetica, revisioni e storia editoriale", "Perché Gadda non rileggeva mai i testi", "Perché tutti i romanzi moderni restano incompiuti"], 0, "Anche l’incompiutezza ha una storia pluricausale.", "poetica-nonfinito", ["Il non finito come problema", "La forma aperta può essere significativa senza cancellare le condizioni materiali.", "Il Pasticciaccio problematizza la soluzione, ma subisce anche pressioni e riscritture."])
    ]
  },
  {
    id: "fratture",
    number: "02",
    title: "Le fratture della vita",
    subtitle: "Guerra, famiglia e ideali rovesciati",
    question: "Che cosa rende insufficiente il mondo ricevuto e modifica il modo di guardare la realtà?",
    color: "#71433d",
    lesson: `
      <h3 id="fratture-famiglia">La famiglia contro la propria immagine</h3>
      <p>La prima crepa precede la guerra. La famiglia Gadda appartiene alla borghesia milanese, ma le scelte economiche del padre — soprattutto la costosa villa di Longone in Brianza — consumano le risorse familiari. Dopo la morte del padre nel 1909, il peso economico ricade sulla madre Adele Lehr, insegnante e dirigente scolastica. La casa, che dovrebbe rappresentare stabilità e prestigio, diventa per Carlo Emilio il segno di una rispettabilità pagata con sacrifici, rinunce e risentimenti.</p>
      <p>Non bisogna usare questa vicenda come chiave totale della scrittura. Tuttavia offre un contesto fondato per comprendere la tensione fra il culto borghese dell’ordine e l’esperienza concreta dello spreco. La famiglia non è un semplice rifugio né un semplice inferno: è una rete di affetti, obblighi, colpe attribuite e punti di vista incompatibili. Questa ambivalenza troverà una forma potente nella casa della <em>Cognizione del dolore</em>.</p>
      <h3 id="fratture-guerra">La guerra smentisce l’eroismo</h3>
      <p>Nel 1915 Gadda interrompe gli studi e parte volontario. Porta con sé il patriottismo risorgimentale, il desiderio di dovere e l’aspirazione a una prova capace di dare unità alla vita. L’esperienza reale è opposta: disorganizzazione, ordini inadeguati, fango, paura, impotenza. Dopo Caporetto viene fatto prigioniero e internato a Celle, in Germania. Nel <em>Giornale di guerra e di prigionia</em> l’ideale non scompare in un colpo: viene sottoposto alla pressione dei fatti, fino a mostrare l’abisso fra retorica pubblica e corpi esposti.</p>
      <p>Al ritorno, nel 1919, Gadda apprende che il fratello Enrico, aviatore, è morto negli ultimi mesi del conflitto. La perdita si unisce al senso di colpa del sopravvissuto e al confronto con un fratello percepito come più forte, amato e riuscito. Le fonti permettono di riconoscere la persistenza di questo trauma nell’opera; non autorizzano a spiegare ogni pagina come sintomo privato. Più rigorosamente, la morte di Enrico rende intelligibile l’insistenza gaddiana su vite interrotte, colpa, memoria e impossibilità di ricomporre il danno.</p>
      <h3 id="fratture-doppiaformazione">Ingegnere, filosofo, scrittore</h3>
      <p>Gadda riprende ingegneria e si laurea nel 1920. Lavora in Italia e in Argentina, dove resta fra il 1922 e il 1924. L’esperienza professionale gli mostra la realtà dei cantieri, delle imprese e dei linguaggi tecnici. Tornato a Milano, studia filosofia e prepara senza concluderla una tesi sui <em>Nuovi saggi sull’intelletto umano</em> di Leibniz. Anche qui il gesto decisivo non è scegliere fra scienza e letteratura, ma rifiutare la separazione: il reale è materia, relazione, percezione, errore e giudizio.</p>
      <p>Le difficoltà economiche lo costringono più volte a tornare alla professione tecnica. La scrittura si sviluppa quindi dentro lavori, spostamenti, articoli e progetti incompiuti. Questa condizione aiuta a capire il carattere di “cantiere” di molte opere, ma non basta a spiegare l’incompiutezza. In Gadda la materia narrativa tende ad allargarsi perché ogni fatto apre nuove connessioni; la biografia e la poetica si incontrano senza coincidere.</p>
      <h3 id="fratture-madre">La morte della madre e la casa che ritorna</h3>
      <p>Nel 1936 muore Adele. Poco dopo Gadda comincia la <em>Cognizione del dolore</em>. Il rapporto cronologico è documentato; il rapporto artistico va formulato con cautela. Il lutto non “produce” il romanzo come una causa lineare, ma riapre la materia della casa, del figlio, della madre, del debito affettivo e della rabbia. Il paese sudamericano immaginario del Maradagà deforma la Brianza e impedisce alla narrazione di ridursi a confessione diretta.</p>
      <h3 id="fratture-fascismo">La frattura politica senza agiografia</h3>
      <p>Anche il rapporto con il fascismo è contraddittorio. Il giovane patriottismo, il culto dell’ordine e la ricerca di un’efficienza nazionale rendono possibile una fase di adesione e testi favorevoli al regime e all’autarchia. Sarebbe falso presentare Gadda come antifascista da sempre. Con il tempo, però, la retorica dell’ordine si rivela maschera di narcisismo, violenza e irresponsabilità collettiva. Nel <em>Pasticciaccio</em> e soprattutto in <em>Eros e Priapo</em>, Mussolini e il consenso fascista vengono sottoposti a una demolizione satirica feroce.</p>
      <p>Questa evoluzione conta davvero perché impedisce una morale comoda. Gadda non osserva il male soltanto negli altri: mostra come bisogno di appartenenza, desiderio di ordine e seduzione della parola pubblica possano partecipare alla colpa. La crisi modifica la visione: nessun fatto ha una causa sola, nessun io è completamente trasparente a se stesso, nessuna istituzione è innocente per definizione. Da qui nasce il problema della sezione successiva: che immagine del mondo può reggere dopo il crollo delle spiegazioni lineari?</p>`,
    summary: "Le fratture di Gadda rovesciano dall’interno i valori ricevuti. La villa di Longone trasforma il prestigio familiare in costo, sacrificio e risentimento. La Prima guerra mondiale smentisce la retorica eroica con disorganizzazione e prigionia; la morte del fratello Enrico rende persistenti i temi della perdita e della colpa del sopravvissuto. Dopo la laurea, lavoro tecnico, Argentina e studi filosofici costruiscono una formazione doppia, senza separare scienza e letteratura. La morte della madre nel 1936 riapre la materia familiare della Cognizione, ma non ne è una causa meccanica. Anche il rapporto con il fascismo è contraddittorio: adesione iniziale e scritti favorevoli precedono la critica feroce del regime e del consenso. La nuova visione rifiuta cause uniche, io trasparenti e istituzioni innocenti per definizione.",
    essentials: [
      "Collegare la villa di Longone alla contraddizione fra prestigio borghese e dissesto economico.",
      "Spiegare come guerra, Caporetto e prigionia smentiscano la retorica dell’eroismo.",
      "Usare con cautela il trauma per illuminare temi senza ridurre le opere a sintomi.",
      "Descrivere la doppia formazione di ingegnere e filosofo-scrittore.",
      "Collegare la morte della madre alla Cognizione senza affermare una causalità automatica.",
      "Riconoscere l’evoluzione politica dall’adesione al fascismo alla sua demolizione critica."
    ],
    vocabulary: [
      ["Frattura", "Evento o conflitto che rende insufficiente un ordine precedente e apre nuove domande."],
      ["Caporetto", "Disfatta italiana dell’ottobre 1917 dopo la quale Gadda fu fatto prigioniero."],
      ["Colpa del sopravvissuto", "Dolore di chi vive e percepisce la propria sopravvivenza come debito o ingiustizia."],
      ["Autobiografismo", "Trasformazione di esperienze personali in materia letteraria, non loro semplice trascrizione."],
      ["Cantiere", "Opera aperta a revisioni, innesti e percorsi non ricomposti in una forma definitiva."],
      ["Autarchia", "Politica fascista orientata all’autosufficienza economica nazionale."],
      ["Consenso", "Partecipazione attiva o passiva che rende possibile la durata di un potere."]
    ],
    map: "assets/maps/02-fratture.svg",
    mapAlt: "La villa di Longone mette in crisi l’ordine familiare; guerra, Caporetto e prigionia rovesciano l’eroismo; la morte di Enrico alimenta perdita e colpa; ingegneria, Argentina e filosofia costruiscono una formazione plurale; la morte della madre riapre la casa; l’adesione e poi la critica del fascismo conducono a una visione senza cause uniche.",
    questions: [
      Q("Che cosa rappresenta la villa di Longone?", ["Solo un luogo sereno dell’infanzia", "La contraddizione fra prestigio familiare, costo e risentimento", "La prova della ricchezza stabile dei Gadda"], 1, "La casa concentra l’ideale borghese e il dissesto che quell’ideale tenta di nascondere.", "fratture-famiglia", ["Una casa ambivalente", "Lo stesso oggetto può essere simbolo di rango e fonte di privazione.", "La villa conserva il prestigio mentre consuma le risorse della famiglia."]),
      Q("In che modo la guerra agisce come frattura?", ["Conferma integralmente la retorica eroica", "Elimina ogni senso del dovere", "Oppone disorganizzazione e impotenza alla promessa di unità eroica"], 2, "Gadda non perde subito ogni ideale, ma ne vede la smentita nei fatti.", "fratture-guerra", ["Ideale contro esperienza", "Una frattura nasce quando il mondo vissuto contraddice il modello ricevuto.", "Gli ordini inadeguati di Caporetto incrinano la retorica pubblica."]),
      Q("Come va collegata la morte di Enrico all’opera?", ["Come contesto fondato per temi di perdita e colpa, non come spiegazione totale", "Come prova che ogni personaggio rappresenta Enrico", "Come fatto privo di conseguenze nella scrittura"], 0, "Il trauma è persistente, ma non autorizza una lettura psicologica unica di tutti i testi.", "fratture-guerra", ["Cautela biografica", "Un’esperienza orienta domande e immagini senza determinare ogni scelta formale.", "La perdita rende intelligibile la memoria del danno nella Cognizione."]),
      Q("Quale rapporto unisce tecnica e filosofia?", ["Si escludono e Gadda abbandona ogni scienza", "Concorrono a pensare realtà, relazione, percezione ed errore", "Servono soltanto a garantirgli un lavoro"], 1, "La doppia formazione rende insufficiente la separazione fra materia e conoscenza.", "fratture-doppiaformazione", ["Una formazione plurale", "Saperi diversi possono interrogare aspetti diversi dello stesso reale.", "Il circuito descrive relazioni materiali; Leibniz interroga relazioni e percezione."]),
      Q("Qual è la ricostruzione storicamente corretta del rapporto col fascismo?", ["Fu sempre antifascista senza contraddizioni", "Rimase sostenitore del regime fino alla fine", "Passò da adesioni e testi favorevoli a una critica satirica radicale"], 2, "La contraddizione va conservata per capire sia la seduzione dell’ordine sia la responsabilità del consenso.", "fratture-fascismo", ["Una storia non agiografica", "Capire un autore significa anche riconoscere le sue compromissioni e trasformazioni.", "Eros e Priapo è più significativo se non si cancella l’adesione precedente."])
    ]
  }
];

const SECTION_ORDER = ["mondo", "fratture", "immagine", "poetica", "opere", "conclusione"];
window.LESSON_DATA.sort((a, b) => SECTION_ORDER.indexOf(a.id) - SECTION_ORDER.indexOf(b.id));

window.FINAL_QUIZ = {
  title: "Verifica finale — I sei nessi",
  questions: [
    Q("Quale limite del mondo precedente avvia il percorso?", ["L’ordine promesso non coincide con la complessità dei fatti", "La completa assenza di scienza", "L’impossibilità di usare i dialetti"], 0, "La tensione fra modello ordinato e realtà effettiva prepara le fratture.", "mondo-limite", ["Dalla promessa alla crepa", "Una frattura acquista senso rispetto all’ordine che smentisce.", "La borghesia proclama efficienza, mentre la villa concentra spreco e dissesto."]),
    Q("Che cosa insegnano insieme guerra, famiglia e fascismo?", ["Che ogni male è soltanto privato", "Che istituzioni e gruppi possono produrre disordine dietro una facciata d’ordine", "Che la tecnica risolve ogni conflitto"], 1, "Le fratture mostrano responsabilità personali dentro sistemi collettivi.", "fratture-fascismo", ["Dalla frattura alla visione", "Il fallimento non appartiene solo al singolo: attraversa organizzazioni e linguaggi.", "Caporetto unisce errori di comando, logistica, retorica e corpi."]),
    Q("Che cos’è una concausa?", ["Una spiegazione inventata", "L’unica causa davvero importante", "Una condizione che coopera con altre alla produzione di un evento"], 2, "Il groviglio conserva cause specifiche e non va confuso col caos.", "immagine-nodo", ["I fili del gomitolo", "Più condizioni possono essere necessarie senza che una esaurisca il fatto.", "Il delitto coinvolge movente, occasione, spazio e storia delle relazioni."]),
    Q("Perché il pastiche è conoscitivo?", ["Perché mette in relazione lingue e saperi che mostrano aspetti diversi del mondo", "Perché nasconde ogni significato", "Perché sostituisce la trama con decorazioni"], 0, "La forma linguistica rende percepibile la pluralità sociale e causale.", "poetica-pastiche", ["La forma produce conoscenza", "Ogni registro fa entrare nel testo una prospettiva e un interesse.", "Il burocratese e il dialetto raccontano diversamente lo stesso potere."]),
    Q("Quale opera trasforma il giallo in indagine sulle concause?", ["Il castello di Udine", "Quer pasticciaccio brutto de via Merulana", "Eros e Priapo"], 1, "Il commissario Ingravallo segue piste che allargano la rete causale.", "opere-pasticciaccio", ["Il giallo del groviglio", "La ricerca del colpevole diventa ricerca di ambienti, desideri e sistemi.", "Roma fascista entra nell’indagine insieme al delitto."]),
    Q("Quale eredità conclude il percorso?", ["La rinuncia alla verità", "L’obbligo di scrivere sempre in modo oscuro", "Una disciplina dell’attenzione che verifica nessi e limiti delle semplificazioni"], 2, "Gadda chiede più rigore davanti alla complessità, non resa o oscurità gratuita.", "conclusione-domanda", ["Seguire più fili", "Comprendere significa ridurre senza cancellare ciò che conta.", "Una sintesi responsabile dichiara criteri e omissioni."])
  ]
};
