const SOURCES=[
  {label:'Dizionario Biografico degli Italiani · Salvatore Quasimodo',url:'https://www.treccani.it/enciclopedia/salvatore-quasimodo_%28Dizionario-Biografico%29/',use:'cronologia verificata, formazione, opere, ricezione critica e passaggio alla poesia civile'},
  {label:'Nobel Prize · Premio per la letteratura 1959',url:'https://www.nobelprize.org/prizes/literature/1959/summary/',use:'motivazione ufficiale del premio e riconoscimento internazionale'},
  {label:'Università degli Studi di Milano · Meccanismi figurali in Quasimodo',url:'https://air.unimi.it/retrieve/dfa8b991-b82a-748b-e053-3a05fe0a3a96/Meccanismi%20figurali%20Quasimodo.pdf',use:'costruzione delle immagini, cromatismo e continuità della funzione veritativa della poesia'},
  {label:'Università di Messina · Il Virgilio di Quasimodo',url:'https://iris.unime.it/handle/11570/3231903',use:'rapporti fra traduzione, metrica e poesia originale'},
  {label:'Università di Bologna · Quasimodo, Dallapiccola e i lirici greci',url:'https://cris.unibo.it/handle/11585/104431',use:'ricezione dei Lirici greci e traduzione-ricreazione in chiave ermetica'},
  {label:'Università di Messina · Geografie letterarie di Quasimodo',url:'https://iris.unime.it/handle/11570/3351449',use:'viaggio, esilio, polarità Sicilia-Lombardia e bilancio dell’ultima stagione'},
  {label:'Treccani · Ancora sulla poetica della parola',url:'https://www.treccani.it/magazine/lingua_italiana/articoli/percorsi/percorsi_332.html',use:'radici, apolidia e stratificazione interna della poetica'}
];

const rec=(anchor,concept,clarification,example,q,options,answer)=>({anchor,concept,clarification,example,q,options,answer});

const LESSONS=[
{
  short:'Mondo',title:'Il mondo precedente',card:'Una civiltà perde le proprie certezze e la poesia cerca una lingua nuova tra tradizione, avanguardie e dittatura.',
  question:'Quale mondo riceve Quasimodo, e perché le sue lingue poetiche tradizionali non sembrano più sufficienti?',
  lesson:`
    <h2 id="s1-crisi">1. Una modernità senza centro</h2>
    <p>Salvatore Quasimodo nasce nel 1901: abbastanza tardi da non appartenere alla generazione che aveva costruito l’Italia liberale, abbastanza presto da vedere quel mondo entrare in crisi. All’inizio del Novecento il positivismo, con la sua fiducia nel progresso scientifico e nella spiegazione razionale della realtà, non scompare, ma perde l’autorità di una visione totale. Industrializzazione, emigrazione, conflitti sociali e nazionalismi mostrano che lo sviluppo tecnico non coincide automaticamente con un miglioramento umano. La Prima guerra mondiale rende la contraddizione brutale: la stessa razionalità capace di organizzare produzione e comunicazioni sa organizzare anche la distruzione di massa.</p>
    <p>Per la letteratura ciò significa che le parole ricevute rischiano di suonare false. Il poeta-vate di matrice dannunziana, che parla dall’alto a una comunità immaginata come compatta, non basta più. Neppure l’intimismo può fingere che l’io sia una casa trasparente. Simbolismo e decadentismo avevano già incrinato la fiducia nella descrizione oggettiva: dietro le cose sembrava agire una rete di corrispondenze che il linguaggio ordinario non afferrava. Le avanguardie, in particolare il Futurismo, reagiscono distruggendo sintassi, tradizione e contemplazione; celebrano velocità e tecnica, ma il loro entusiasmo non è l’unico esito possibile della frattura moderna.</p>
    <h2 id="s1-poesia">2. Da Pascoli e D’Annunzio alla parola novecentesca</h2>
    <p>Quasimodo eredita dunque più linee, non una scuola già pronta. Da Pascoli proviene la possibilità di caricare oggetti, suoni e paesaggi di risonanze interiori; da D’Annunzio, un lessico prezioso e una sensibilità musicale che il Novecento dovrà però ridimensionare. Le esperienze dei crepuscolari abbassano il tono e mettono in dubbio il prestigio del poeta; i vociani cercano una scrittura concentrata, morale, frammentaria. Ungaretti, durante la guerra, dimostra che il verso può ridursi a poche parole separate dal silenzio senza diventare povero: la concentrazione crea peso. Montale, poco dopo, fa degli oggetti concreti il luogo di una conoscenza negativa, mai trasformata in formula rassicurante.</p>
    <p>Quasimodo non copia semplicemente questi autori. Entra in un campo di possibilità: la poesia può frantumare il discorso, creare analogie, trasformare un paesaggio in emblema, far sentire il silenzio fra le parole. La sua specificità si formerà quando queste tecniche incontreranno una memoria siciliana costruita come lontananza. È importante non chiamare già tutto “Ermetismo”: negli anni Venti e nei primi Trenta la categoria si definisce attraverso riviste, polemiche e giudizi critici, e non coincide né con Ungaretti né con Montale. Il Dizionario Biografico Treccani distingue infatti un ermetismo forte, nel quale colloca Quasimodo, da altre esperienze novecentesche solo superficialmente simili.</p>
    <h2 id="s1-storia">3. Fascismo, lingua pubblica e spazi letterari</h2>
    <p>Dopo il 1922 il fascismo occupa progressivamente la sfera pubblica. Discorsi, rituali, giornali e scuola devono costruire consenso; la parola politica tende a presentarsi come certa, compatta, collettiva. Non si deve però trasformare automaticamente ogni poesia difficile in resistenza antifascista: sarebbe un nesso troppo comodo e storicamente indimostrato. È più corretto dire che la ricerca di una parola autonoma si sviluppa in un ambiente in cui il linguaggio ufficiale è fortemente controllato. L’oscurità ermetica non costituisce di per sé un programma politico, ma sottrae la poesia alla comunicazione immediata e utilitaria.</p>
    <p>Riviste come <em>Solaria</em>, pubblicata a Firenze dal 1926 al 1936, aprono finestre sulla letteratura europea e creano reti fra scrittori. È attraverso questo ambiente che Quasimodo, invitato a Firenze da Elio Vittorini, passa dalla formazione provinciale alla scena nazionale. La rivista non gli fornisce una dottrina: gli offre interlocutori, lettori e un luogo editoriale. <em>Acque e terre</em> esce nel 1930 nelle Edizioni di <em>Solaria</em>. La poesia nasce quindi dentro una modernizzazione del sistema culturale fatta di riviste, premi, case editrici, recensioni e polemiche.</p>
    <h2 id="s1-sicilia">4. La Sicilia: periferia reale, centro immaginario</h2>
    <p>Il mondo precedente non è soltanto europeo o letterario. È anche la Sicilia dei primi decenni del secolo, attraversata dalle ferrovie, dagli spostamenti di lavoro, dall’emigrazione e da disuguaglianze profonde. Il padre di Quasimodo è capostazione; la famiglia segue le linee ferroviarie e vive in più luoghi. Qui appare una contraddizione decisiva: la ferrovia collega, ma fa sperimentare l’instabilità; promette mobilità, ma rende difficile fissare una patria quotidiana. La Sicilia che entrerà nei versi non sarà una fotografia sociologica. Diventerà un’isola della memoria: luce, acque, vento, miti greci, infanzia e distanza.</p>
    <p>Questa trasformazione non va scambiata per nostalgia ingenua. Il poeta riceve una terra concreta, ma la ricostruisce quando ne è lontano. Il Mediterraneo diventa una grammatica dell’origine: non “com’era davvero” la Sicilia, bensì come la coscienza dell’esule la rende necessaria. Sullo sfondo stanno il terremoto di Messina del 1908 e le sue rovine, esperienza collettiva che Quasimodo bambino conobbe attraverso il trasferimento del padre e la temporanea vita della famiglia in un carro merci. Prima ancora della guerra mondiale, la modernità gli mostra dunque che la casa può crollare.</p>
    <h2 id="s1-problema">5. Il problema consegnato al poeta</h2>
    <p>Il mondo ricevuto lascia a Quasimodo quattro tensioni: progresso tecnico e vulnerabilità umana; lingua pubblica enfatica e bisogno di autenticità; Sicilia concreta e isola mitica; tradizione lirica e necessità di concentrazione. La sua poesia nascerà dal tentativo di tenerle insieme. Non parlerà subito della storia in modo diretto: comincerà comprimendo il mondo in immagini e parole assolute. Ma proprio questa concentrazione prepara una domanda destinata a riaprirsi durante la guerra: se la parola custodisce una verità, può restare soltanto privata?</p>`,
  bridge:'Il mondo ricevuto offre strumenti e tensioni; le fratture biografiche trasformano quelle tensioni in esperienza di esilio, precarietà e responsabilità.',
  summary:'Quasimodo nasce dentro la crisi della modernità europea: il progresso tecnico non garantisce un progresso umano e la Prima guerra mondiale rende evidente la potenza distruttiva dell’organizzazione razionale. La poesia italiana abbandona gradualmente la voce sicura del vate e sperimenta frammento, analogia, concentrazione e oggetti carichi di senso. Pascoli, D’Annunzio, i vociani, Ungaretti e Montale costituiscono possibilità diverse, non un’unica genealogia. Nel fascismo la lingua pubblica tende alla certezza e al consenso; la poesia autonoma non è automaticamente resistenza, ma rifiuta l’uso puramente strumentale della parola. La Sicilia ricevuta da Quasimodo è attraversata da ferrovie, mobilità e catastrofi; lontano dall’isola, essa diventerà memoria e mito. Restano quattro tensioni: tecnica e fragilità, retorica e autenticità, terra reale e origine immaginata, tradizione e forma nuova. Le fratture della vita renderanno queste tensioni personali.',
  essentials:['Spiegare perché la crisi del positivismo modifica anche la fiducia nel linguaggio.','Distinguere il poeta-vate dalla nuova figura novecentesca del poeta.','Riconoscere analogia, concentrazione e frammento come risposte diverse alla crisi della rappresentazione.','Evitare l’equazione automatica “poesia oscura = antifascismo”.','Spiegare il ruolo delle riviste, in particolare <em>Solaria</em>, nella formazione del campo letterario.','Descrivere la Sicilia quasimodiana come costruzione della memoria, non come semplice paesaggio realistico.'],
  glossary:[['Positivismo','Fiducia ottocentesca nella conoscenza scientifica e nel progresso, messa in crisi dalla storia novecentesca.'],['Poeta-vate','Poeta che pretende di guidare la comunità con una parola pubblica e autorevole.'],['Simbolismo','Concezione per cui le cose visibili rinviano a significati ulteriori attraverso corrispondenze.'],['Analogia','Accostamento che crea un rapporto di senso senza esplicitarne tutti i passaggi logici.'],['Campo letterario','Rete di riviste, editori, premi, critici e autori che rende possibile la vita pubblica delle opere.'],['Ermetismo forte','Categoria critica riferita a una poesia altamente analogica, nominale e semanticamente indeterminata.'],['Mitizzazione','Trasformazione di un luogo o evento reale in figura simbolica dell’origine.'],['Lingua pubblica','Linguaggio della politica e delle istituzioni, nel fascismo orientato alla propaganda e al consenso.']],
  map:'./maps/01-mondo.svg',mapAlt:'La crisi del progresso mette in dubbio la lingua ricevuta; simbolismo, avanguardie e nuova lirica cercano forme alternative; fascismo e riviste definiscono il campo pubblico; la Sicilia mobile e ferita confluisce nel problema di una parola autentica.',
  quiz:[
    {q:'Qual è la contraddizione centrale della modernità ricevuta da Quasimodo?',options:['La tecnica scompare mentre cresce la religione','Il progresso tecnico convive con una vulnerabilità umana crescente','La poesia sostituisce completamente la politica'],answer:1,explain:'Il Novecento mostra che organizzazione razionale e tecnica possono produrre sia sviluppo sia distruzione.',recovery:rec('Una modernità senza centro','Tecnica e progresso non coincidono','La crisi non nasce dal rifiuto della scienza, ma dalla scoperta che l’efficienza non garantisce fini umani.','La guerra industriale usa competenze moderne per distruggere su scala nuova.','Quale frase ricostruisce il nesso?',['Ogni tecnica è moralmente positiva','La tecnica è neutra rispetto a ogni uso','La capacità tecnica non decide da sola il valore dei fini'],2)},
    {q:'Che cosa rappresenta <em>Solaria</em> nel percorso di Quasimodo?',options:['Una rete editoriale e intellettuale che lo introduce nella scena nazionale','Un partito clandestino con un preciso programma poetico','La rivista ufficiale del Futurismo'],answer:0,explain:'<em>Solaria</em> offre relazioni, pubblicazione e confronto europeo; non impone una dottrina unica.',recovery:rec('Fascismo, lingua pubblica e spazi letterari','La rivista come ambiente, non come formula','Le riviste organizzano incontri e circolazione delle opere; non trasformano automaticamente gli autori in aderenti a una scuola.','<em>Acque e terre</em> esce nel 1930 nelle Edizioni di <em>Solaria</em>.','Qual è la funzione più precisa di una rivista letteraria?',['Creare un campo di confronto e pubblicazione','Garantire un’identica poetica a tutti','Sostituire il lavoro individuale'],0)},
    {q:'Perché non è corretto identificare automaticamente oscurità ermetica e antifascismo?',options:['Perché Quasimodo scrive soltanto dopo il 1945','Perché il fascismo favoriva ogni sperimentazione','Perché la forma difficile non prova da sola un’intenzione politica'],answer:2,explain:'L’autonomia della parola può sottrarsi alla lingua ufficiale, ma ciò non equivale senza prove a un programma di opposizione.',recovery:rec('Fascismo, lingua pubblica e spazi letterari','Forma e intenzione politica vanno distinte','Una conseguenza politica possibile non basta a dimostrare l’intenzione dell’autore. Servono documenti e contesto.','La PWA parla di autonomia della ricerca poetica, non di resistenza automatica.','Quale inferenza è lecita?',['Ogni testo ambiguo è clandestino','La poesia autonoma può non coincidere con la propaganda','Ogni poeta difficile è apolitico'],1)},
    {q:'Come entra la Sicilia nella prima poesia quasimodiana?',options:['Come inventario folklorico immutabile','Come origine ricostruita dalla memoria e dalla distanza','Come semplice documento geografico'],answer:1,explain:'La Sicilia reale viene trasformata in isola della memoria, della luce, dell’infanzia e del mito.',recovery:rec('La Sicilia: periferia reale, centro immaginario','Il paesaggio è una costruzione della coscienza','La poesia seleziona e trasforma luoghi concreti in figure dell’origine; non produce una cartolina.','Ferrovie, Stretto, luce e vento diventano elementi di una geografia interiore.','Che cosa fa la distanza?',['Cancella ogni luogo','Rende la Sicilia una prova statistica','Trasforma il luogo vissuto in figura dell’origine'],2)},
    {q:'Quale problema prepara il passaggio alle fratture biografiche?',options:['Come trovare una parola autentica fra retorica pubblica, perdita e memoria','Come restaurare integralmente la lirica ottocentesca','Come eliminare la storia dalla poesia'],answer:0,explain:'Le tensioni del mondo precedente diventano decisive quando sono attraversate da esilio, precarietà e catastrofe.',recovery:rec('Il problema consegnato al poeta','Le tensioni richiedono un’esperienza che le renda personali','Il contesto non produce meccanicamente un’opera; offre problemi che le vicende dell’autore rendono urgenti.','La vulnerabilità moderna si fa concreta nel terremoto, negli spostamenti e poi nella guerra.','Qual è il ponte corretto?',['Contesto → destino inevitabile','Contesto + esperienza → problema poetico','Biografia → spiegazione totale'],1)}
  ]
},
{
  short:'Fratture',title:'Le fratture della vita',card:'Spostamenti, terremoto, esilio, lavoro tecnico, guerra e riconoscimento pubblico modificano il rapporto fra io e mondo.',
  question:'Quali esperienze rendono insufficiente il mondo ricevuto e costringono Quasimodo a ridefinire la funzione della poesia?',
  lesson:`
    <h2 id="s2-infanzia">1. Un’infanzia senza un solo centro</h2>
    <p>Quasimodo nasce a Modica il 20 agosto 1901 in una famiglia legata alle ferrovie. Il lavoro del padre Gaetano, capostazione, comporta spostamenti lungo le linee siciliane. Non bisogna immaginare una fanciullezza interamente raccolta in un unico paese destinato a diventare patria perduta. La mobilità viene prima della nostalgia: proprio perché l’origine è distribuita fra luoghi diversi, la poesia potrà condensarla in un’isola assoluta. Messina conta in modo particolare per la formazione. Dopo il terremoto del 28 dicembre 1908 il padre viene trasferito nella città distrutta e la famiglia vive per un periodo in un carro merci. Il bambino incontra rovine, provvisorietà e dolore collettivo.</p>
    <p>È prudente non dedurre ogni immagine poetica da quell’evento. Il terremoto, però, rende intelligibile una struttura che tornerà: la casa desiderata è anche la casa che può essere perduta; la terra natale non coincide con la stabilità. Le prime prove poetiche, legate a un apprendistato simbolista, nascono insieme a interessi tecnici e a una rete di amicizie messinesi. Quasimodo non è il letterato puro che ignora il mondo materiale: frequenta un istituto tecnico e consegue la licenza fisico-matematica.</p>
    <h2 id="s2-partenza">2. Partire: Roma, il lavoro, il continente</h2>
    <p>Nel 1919 si trasferisce a Roma. La ricostruzione documentaria del Dizionario Biografico corregge la mitobiografia diffusa dallo stesso poeta: si iscrive ad agraria, non a ingegneria, e abbandona presto gli studi per difficoltà economiche. Lavora come disegnatore tecnico, commesso e impiegato. Studia greco e latino privatamente. Questo doppio apprendistato — necessità materiale e cultura classica conquistata fuori dai percorsi regolari — è più importante di una comoda leggenda del genio spontaneo. Il poeta futuro impara a misurare e disegnare, ma anche a trasferire una lingua antica nel presente.</p>
    <p>Nel 1926 entra nel Genio civile come geometra e viene assegnato a Reggio Calabria. Il lavoro lo porta poi a Imperia, in Sardegna, a Milano e a Sondrio. La penisola diventa una geografia di incarichi più che una patria sostitutiva. Attraversare lo Stretto per incontrare gli amici e guardare Tindari da lontano offre il contesto a una delle sue figure decisive: l’esilio non è espulsione politica, ma distanza fra il soggetto e un luogo che, proprio perché lontano, diventa più intenso. Il continente non cancella l’isola; la rende interiore.</p>
    <h2 id="s2-letteratura">3. Firenze e Milano: entrare nella letteratura</h2>
    <p>Nel 1929 Elio Vittorini, che aveva sposato la sorella Rosina, lo invita a Firenze e lo introduce nell’ambiente di <em>Solaria</em>. Nel 1930 esce <em>Acque e terre</em>; nel 1932 <em>Òboe sommerso</em>. La svolta non è una conversione istantanea, ma l’ingresso in un sistema che sottopone i testi al giudizio pubblico. Montale, De Robertis e altri critici discutono qualità e limiti di quella lingua. Quasimodo sperimenta così una seconda forma di esposizione: non più soltanto il soggetto che ha perso un luogo, ma l’autore la cui parola viene classificata, contestata, chiamata “ermetica”.</p>
    <p>A Milano, dove giunge a metà degli anni Trenta, abbandona nel 1938 il Genio civile e lavora nell’editoria. Nel 1941 ottiene per chiara fama l’insegnamento di letteratura italiana al Conservatorio Giuseppe Verdi, che manterrà fino alla morte. Nello stesso periodo lavora intensamente alle traduzioni. I <em>Lirici greci</em> del 1940 non sono un esercizio laterale: la frammentarietà dei testi antichi, la loro distanza e la libertà ricreativa consentono a Quasimodo di incontrare una voce insieme arcaica e contemporanea. Gli studi delle Università di Bologna e Messina mostrano gli scambi di lessico, immagini e forme fra traduzione e poesia originale.</p>
    <h2 id="s2-guerra">4. La guerra rompe l’isolamento lirico</h2>
    <p>La frattura storica decisiva è la Seconda guerra mondiale vissuta a Milano. Bombardamenti, occupazione tedesca, guerra civile e persecuzioni rendono insufficiente una poesia che custodisca la verità solo nell’io. Quasimodo è antifascista, ma non partecipa alla Resistenza: precisarlo evita l’eroicizzazione retrospettiva. Nel 1942 subisce un’aggressione squadrista e nel 1944 viene denunciato da una spia fascista; nel 1945 aderisce per breve tempo al Partito comunista. La poesia civile nasce da questo nodo, ma non coincide con una tessera politica.</p>
    <p>In <em>Giorno dopo giorno</em> i morti senza tempo della stagione ermetica diventano vittime storiche. La voce si allarga: il verso si fa più lungo, il discorso più riconoscibile, l’interlocutore più concreto. Non è però corretto descrivere la svolta come una cancellazione del primo Quasimodo. Carlo Bo parlò di una crisi interna alla parola. La solitudine, il dolore e l’esilio restano, ma cambiano scala: l’“uomo solo” incontra gli uomini colpiti dalla stessa violenza.</p>
    <h2 id="s2-nobel">5. Il Nobel e l’ultima esposizione</h2>
    <p>Nel 1959 il premio Nobel porta Quasimodo al centro della scena internazionale. La motivazione ufficiale riconosce una lirica che esprime l’esperienza tragica del nostro tempo con intensità classica. In Italia il premio provoca polemiche e riapre il giudizio sul suo valore rispetto ad altri poeti. Anche questa è una frattura: il poeta dell’esilio diventa figura pubblica, viaggia, tiene discorsi, viene letto come rappresentante di una poesia nazionale. <em>La terra impareggiabile</em> e poi <em>Dare e avere</em> trasformano luoghi e viaggi in bilancio.</p>
    <p>Il riconoscimento non risolve le contraddizioni. Quasimodo porta con sé malattie, relazioni complesse, separazioni e una crescente necessità di fare i conti con l’immagine pubblica. Muore a Napoli il 14 giugno 1968 dopo un’emorragia cerebrale. La traiettoria non va romanzata come destino inevitabile: le fratture non “producono” automaticamente i versi. Offrono però il terreno documentato per comprendere perché la sua immagine del mondo oscilli fra origine perduta, solitudine e dovere di rispondere alla storia.</p>`,
  bridge:'Le fratture non spiegano meccanicamente le opere; rendono però intelligibile la visione di una realtà segnata da separazione, tempo irreversibile e dolore condiviso.',
  summary:'L’infanzia di Quasimodo è mobile prima ancora di diventare nostalgica. Il lavoro ferroviario del padre porta la famiglia in più luoghi; dopo il terremoto di Messina del 1908 vive temporaneamente in un carro merci. Nel 1919 parte per Roma, interrompe gli studi per difficoltà economiche, svolge lavori diversi e studia privatamente greco e latino. Dal 1926 il lavoro di geometra nel Genio civile lo conduce lungo la penisola: la distanza trasforma la Sicilia in origine interiore. Vittorini lo introduce nell’ambiente di <em>Solaria</em>; Firenze e poi Milano lo espongono al confronto critico. Le traduzioni dei classici dialogano profondamente con la sua poesia. La guerra vissuta a Milano rende insufficiente l’isolamento lirico e allarga la voce alle vittime della storia, senza cancellare la solitudine originaria. Il Nobel del 1959 produce un’ultima frattura fra poeta privato e figura pubblica. Queste esperienze non causano automaticamente le opere, ma rendono intelligibile la sua visione.',
  essentials:['Ricostruire la mobilità dell’infanzia e il ruolo del terremoto del 1908 senza psicologismo automatico.','Distinguere la biografia documentata dalla mitobiografia costruita anche dal poeta.','Spiegare il doppio apprendistato tecnico e classico.','Collegare il lavoro nel Genio civile alla geografia dell’esilio senza farne una causa meccanica dei versi.','Riconoscere nei <em>Lirici greci</em> un laboratorio poetico, non un’attività secondaria.','Precisare la posizione di Quasimodo durante fascismo e Resistenza.','Spiegare la guerra come allargamento della solitudine individuale al dolore storico.','Interpretare il Nobel come riconoscimento e nuova esposizione pubblica.'],
  glossary:[['Mitobiografia','Autorappresentazione che riorganizza i dati della vita per costruire un’identità simbolica.'],['Esilio','Distanza fisica e interiore dall’origine; in Quasimodo non coincide con un’espulsione politica.'],['Genio civile','Amministrazione tecnica presso cui Quasimodo lavorò come geometra dal 1926 al 1938.'],['Traduzione-ricreazione','Versione che trasferisce un testo antico dentro una sensibilità poetica moderna.'],['Frattura storica','Evento collettivo che rende insufficiente una precedente forma di interpretare il mondo.'],['Poesia civile','Poesia che assume la storia e la comunità come responsabilità, senza ridursi necessariamente a propaganda.'],['Chiara fama','Nomina accademica fondata sul riconoscimento pubblico dell’opera.'],['Ricezione','Insieme dei giudizi, usi e conflitti attraverso cui un’opera viene letta nel tempo.']],
  map:'./maps/02-fratture.svg',mapAlt:'La mobilità infantile e il terremoto incrinano l’idea di casa; la partenza e il lavoro tecnico producono distanza; Firenze, Milano e le traduzioni aprono il campo letterario; la guerra allarga il dolore dall’io alla storia; il Nobel trasforma il poeta in figura pubblica.',
  quiz:[
    {q:'Quale rapporto corretto lega il terremoto del 1908 alla poesia di Quasimodo?',options:['Spiega da solo tutte le immagini delle opere','È irrilevante perché Quasimodo era bambino','Offre un contesto documentato alla tensione fra casa, rovina e precarietà'],answer:2,explain:'La cautela critica riconosce il peso dell’esperienza senza trasformarla in causa totale.',recovery:rec('Un’infanzia senza un solo centro','Contesto biografico, non chiave universale','Un evento può rendere intelligibile una tensione senza spiegare ogni scelta formale.','La famiglia vive in un carro merci nella Messina distrutta, ma i versi hanno anche fonti letterarie e linguistiche.','Quale formula è più rigorosa?',['Il terremoto determina ogni poesia','Il terremoto offre un contesto verificabile','Il terremoto non lascia alcuna traccia'],1)},
    {q:'Che cosa mostra il periodo romano?',options:['L’intreccio fra necessità economica, lavori tecnici e studio autonomo dei classici','Una carriera universitaria lineare in ingegneria','Il rifiuto completo della cultura antica'],answer:0,explain:'Quasimodo interrompe gli studi, lavora e studia greco e latino privatamente.',recovery:rec('Partire: Roma, il lavoro, il continente','Doppio apprendistato','La formazione non è soltanto scolastica: lavoro materiale e studio dei classici procedono insieme.','Disegno tecnico e lingue antiche preparano due diversi rapporti con forma e misura.','Quale coppia descrive la formazione?',['Carriera accademica e ozio','Tecnica e studio autonomo dei classici','Politica e medicina'],1)},
    {q:'Perché i <em>Lirici greci</em> sono una frattura produttiva?',options:['Perché eliminano ogni legame con l’Ermetismo','Perché obbligano Quasimodo a una traduzione letterale e neutra','Perché mettono in scambio frammento antico, voce moderna e poesia originale'],answer:2,explain:'La ricerca universitaria parla di traduzione-ricreazione e di scambi fra lessico, immagini e forme.',recovery:rec('Firenze e Milano: entrare nella letteratura','Tradurre può trasformare chi traduce','La traduzione poetica non è un vetro neutro: mette alla prova ritmo, immagine e voce del traduttore.','Le versioni dei lirici antichi vengono lette anche come documenti della stagione ermetica.','Quale effetto è plausibile?',['La traduzione modifica anche la poesia originale','La traduzione cancella l’autore antico','La traduzione impedisce ogni invenzione'],0)},
    {q:'Quale precisazione storica è necessaria sul rapporto di Quasimodo con la guerra?',options:['Fu un comandante della Resistenza','Fu antifascista, ma non partecipò alla Resistenza','Rimase sempre iscritto al Partito fascista'],answer:1,explain:'La precisione evita un’eroicizzazione retrospettiva; la poesia civile non autorizza biografie inventate.',recovery:rec('La guerra rompe l’isolamento lirico','Impegno poetico e azione resistenziale non coincidono','Si può assumere una responsabilità civile nella scrittura senza aver partecipato militarmente alla Resistenza.','Quasimodo fu aggredito e denunciato sotto il fascismo, ma non fu partigiano.','Quale distinzione va mantenuta?',['Poesia civile e biografia politica','Poesia e linguaggio','Autore e opere'],0)},
    {q:'Che cosa cambia con <em>Giorno dopo giorno</em>?',options:['La solitudine scompare completamente','Il dolore individuale si allarga alle vittime della storia','Il poeta abbandona ogni forma lirica per il romanzo'],answer:1,explain:'La svolta riguarda scala, destinatario e discorso; non cancella i nuclei precedenti.',recovery:rec('La guerra rompe l’isolamento lirico','Allargamento, non sostituzione','La storia entra nella poesia trasformando i morti mitici in vittime concrete, ma restano dolore ed esilio.','La voce diventa più lunga e rivolta a un “noi”.','Qual è il modello più preciso?',['Prima fase cancellata dalla seconda','Continuità senza cambiamenti','Nuclei continui in una forma e scala mutate'],2)}
  ]
},
{
  short:'Visione',title:'L’immagine del mondo',card:'La realtà appare come distanza: l’isola è origine perduta, il tempo ferisce, ma la solitudine può diventare responsabilità comune.',
  question:'Come appare la realtà a Quasimodo quando memoria privata e tragedia storica vengono osservate nella stessa luce?',
  lesson:`
    <h2 id="s3-isola">1. L’isola non è un rifugio geografico</h2>
    <p>L’immagine del mondo di Quasimodo nasce da una separazione. Da una parte c’è l’isola: Sicilia, infanzia, acqua, luce, vento, mondo greco. Dall’altra ci sono il continente, le città settentrionali, il lavoro, il tempo storico. Sarebbe però povero tradurre questa polarità in “Sud felice contro Nord infelice”. L’isola è già perduta mentre viene nominata; la memoria la rende luminosa perché non può più abitarla. La Sicilia poetica è dunque un’origine costruita dalla distanza, un luogo interiore nel quale paesaggio e identità coincidono per un istante.</p>
    <p>Lo studio dell’Università di Messina sulle geografie letterarie mostra che il viaggio attraversa tutta la produzione: dalla polarità Sicilia-Lombardia fino ai numerosi luoghi italiani ed europei dell’ultima stagione. Ciò impedisce di chiudere Quasimodo in un regionalismo nostalgico. L’isola è la prima figura di un problema universale: ogni soggetto cerca un punto d’origine, ma lo riconosce quando il tempo lo ha già sottratto.</p>
    <h2 id="s3-tempo">2. Tempo, sera, solitudine</h2>
    <p>Il tempo quasimodiano non è una linea neutra. Trasforma ogni presenza in perdita possibile. La sera non designa soltanto una parte del giorno: concentra il passaggio improvviso dalla luce all’ombra, dalla presenza alla coscienza del limite. Anche la solitudine non è un semplice stato psicologico. È una condizione dell’uomo, separato dagli altri e perfino da se stesso perché il tempo rende instabile ciò che crede di possedere.</p>
    <p>Nella stagione ermetica questa visione si esprime attraverso scene rarefatte. Pochi elementi naturali — acqua, luna, vento, alberi, animali, pietre — non compongono un panorama completo; appaiono come frammenti assoluti. Il lettore non riceve una spiegazione, ma una costellazione. Il mondo sembra visibile e indecifrabile nello stesso momento. Da qui l’importanza dell’immagine: la ricerca dell’Università di Milano definisce produttiva la lettura di Quasimodo come poeta visivo, attento a cromatismo, luce e contrasto. La concretezza delle figure non elimina l’enigma; gli dà una superficie.</p>
    <h2 id="s3-mito">3. Il mito: memoria che sottrae e restituisce</h2>
    <p>La Grecia e il Mediterraneo permettono a Quasimodo di pensare il tempo su una scala più ampia della biografia. Il mito non è una fuga decorativa nell’antico. Trasforma il presente in una scena dove continuano desiderio, violenza, viaggio e morte. Traducendo i lirici greci, Quasimodo incontra testi arrivati spesso in frammenti: la mancanza non è un difetto da nascondere, ma una forma capace di parlare alla modernità. L’antico giunge come resto, così come l’infanzia giunge nella memoria.</p>
    <p>Esiste qui una tensione: il poeta può costruire una “grecità” ideale e perfino una mitobiografia di sé come siculo-greco. La critica deve distinguere il dato storico dall’autocostruzione simbolica. Ma l’operazione poetica resta decisiva: una genealogia immaginata consente di opporre alla cronaca fascista un tempo lungo e di misurare la catastrofe moderna contro archetipi più antichi. L’origine non offre innocenza; offre profondità.</p>
    <h2 id="s3-storia">4. Quando la storia entra nell’immagine</h2>
    <p>La guerra non distrugge questa visione: la costringe a cambiare referente. Prima, il morto poteva appartenere al mito o a una memoria senza data; dopo i bombardamenti di Milano, il morto è una vittima riconoscibile. Le macerie non sono più soltanto simbolo della precarietà: sono edifici e corpi nella storia. Il mondo appare allora come responsabilità reciproca. L’uomo resta solo, ma la solitudine non autorizza l’indifferenza; diventa ciò che tutti condividono.</p>
    <p>Quasimodo non approda a un ottimismo progressivo. La poesia civile non promette che la storia impari automaticamente dai propri delitti. Vede nell’uomo contemporaneo la persistenza di una violenza antica resa più efficiente dalla tecnica. Il passato mitico e il presente bellico si riflettono l’uno nell’altro: la distanza cronologica non garantisce maturità morale. Per questo il poeta deve parlare alle coscienze, non celebrare il corso inevitabile del progresso.</p>
    <h2 id="s3-verita">5. La verità come passaggio dall’anonimo alla persona</h2>
    <p>Nel pensiero di Quasimodo la poesia rivendica una verità propria. Non è la verità verificabile dello storico né il programma del politico. È il gesto che sottrae un’esperienza all’anonimato e la rende personale, quindi comunicabile. Questa fiducia attraversa sia la parola concentrata dell’Ermetismo sia il discorso civile. Cambiano sintassi, ritmo e destinatari, ma resta l’idea che il poeta debba fare esistere ciò che il linguaggio comune lascia invisibile.</p>
    <p>È anche il punto più discutibile della sua posizione. Attribuire al poeta una speciale funzione di verità rischia di ricostruire, sotto forme nuove, l’autorità del vate. La differenza sta nel contenuto di quella autorità: non comando, ma testimonianza; non certezza politica, ma esposizione del dolore. Tuttavia il confine non è garantito una volta per tutte. Da questa tensione nasce il problema espressivo della sezione successiva: quale forma può parlare come testimonianza senza imporsi come slogan o sacerdotale rivelazione?</p>`,
  bridge:'Se il mondo è insieme immagine enigmatica e dolore storico, la poetica deve passare dalla parola concentrata al discorso condiviso senza perdere precisione e libertà.',
  summary:'La visione di Quasimodo si organizza intorno alla distanza. La Sicilia non è un semplice Sud felice contrapposto al Nord: è un’origine costruita dalla memoria, riconosciuta proprio perché perduta. Il viaggio si estende poi a molte geografie e rende universale il problema dell’appartenenza. Tempo, sera e solitudine indicano la precarietà di ogni presenza; le immagini naturali sono concrete ma non immediatamente spiegabili. Il mito e i frammenti greci permettono di collegare perdita personale e durata collettiva, pur richiedendo di distinguere la storia dall’automitizzazione “siculo-greca”. Con la guerra, le figure acquistano un referente storico: i morti diventano vittime e la solitudine comune fonda una responsabilità. La poesia rivendica una verità diversa da quella del politico e dello storico: rende personale e comunicabile ciò che resterebbe anonimo. Resta però il rischio di attribuire al poeta un’autorità quasi sacerdotale; la poetica dovrà affrontare questa tensione.',
  essentials:['Spiegare l’isola come origine costruita dalla distanza.','Evitare la riduzione della geografia quasimodiana alla coppia Sud felice/Nord infelice.','Interpretare sera e solitudine come strutture della condizione umana, non meri stati d’animo.','Riconoscere la funzione conoscitiva di luce, colore e contrasto.','Spiegare perché il frammento antico può parlare alla modernità.','Distinguere la grecità storica dalla mitobiografia siculo-greca.','Mostrare come la guerra trasformi il referente delle immagini senza cancellarne i nuclei.','Discutere criticamente la pretesa di verità della poesia.'],
  glossary:[['Origine','Luogo o tempo che fonda l’identità ma viene riconosciuto attraverso la perdita.'],['Geografia interiore','Organizzazione simbolica dei luoghi secondo memoria, desiderio e distanza.'],['Frammento','Testo o immagine incompleta che fa della mancanza una risorsa di senso.'],['Cromatismo','Uso strutturale dei colori e dei contrasti luminosi nella costruzione poetica.'],['Archetipo','Figura antica e ricorrente con cui leggere esperienze di epoche diverse.'],['Referente','Realtà, oggetto o evento a cui un segno linguistico rimanda.'],['Testimonianza','Parola che assume la responsabilità di rendere visibile un’esperienza o una vittima.'],['Statuto veritativo','Tipo di verità che una forma di discorso rivendica per sé.']],
  map:'./maps/03-immagine.svg',mapAlt:'La distanza trasforma la Sicilia in isola interiore; tempo e sera rivelano la precarietà; mito e frammento danno profondità alla perdita; la guerra rende storiche le vittime; la solitudine condivisa confluisce nella poesia come testimonianza e verità problematica.',
  quiz:[
    {q:'Che cosa significa chiamare la Sicilia “origine costruita”?',options:['Che il poeta inventa senza alcun rapporto con luoghi reali','Che la memoria seleziona e trasforma il luogo vissuto','Che la Sicilia è soltanto un simbolo politico'],answer:1,explain:'L’isola poetica nasce dall’incontro fra esperienza reale, distanza e lavoro della memoria.',recovery:rec('L’isola non è un rifugio geografico','Memoria e luogo cooperano','Una geografia interiore non nega il luogo reale: lo riorganizza secondo perdita e desiderio.','Luce, vento e acque siciliane diventano figure dell’origine.','Che cosa fa la memoria?',['Riproduce tutto senza scelta','Cancella ogni dato','Seleziona e trasforma il vissuto'],2)},
    {q:'Perché Quasimodo può essere letto come “poeta visivo”?',options:['Per il ruolo di figure, cromatismo, luce e contrasto','Perché rifiuta totalmente il suono','Perché descrive fotografie in modo realistico'],answer:0,explain:'La visività riguarda la costruzione poetica delle immagini, non una semplice descrizione fotografica.',recovery:rec('Tempo, sera, solitudine','Immagine concreta ed enigma possono convivere','Colori e contrasti rendono visibile una relazione senza necessariamente spiegarla.','Pochi elementi naturali formano una costellazione, non un panorama completo.','Qual è la funzione dell’immagine?',['Decorare soltanto','Produrre una conoscenza per relazioni visive','Sostituire ogni ritmo'],1)},
    {q:'Quale funzione assume il mito?',options:['Nasconde il presente in un passato rassicurante','Dimostra la superiorità biologica dei siciliani','Mette il presente in rapporto con forme antiche di desiderio, viaggio e violenza'],answer:2,explain:'Il mito dà profondità temporale al presente; non garantisce innocenza né è un dato biografico letterale.',recovery:rec('Il mito: memoria che sottrae e restituisce','Il mito è una lente, non una fuga','La figura antica permette di riconoscere strutture che ritornano in tempi differenti.','Il frammento greco e l’infanzia perduta arrivano entrambi come resti.','Che cosa consente il mito?',['Confrontare presente e durata umana','Eliminare la storia','Provare una genealogia'],0)},
    {q:'Come cambia il morto nella poesia civile?',options:['Da vittima storica torna a essere soltanto figura ornamentale','Da figura senza tempo diventa anche vittima riconoscibile della storia','Scompare perché la poesia parla solo dei vivi'],answer:1,explain:'La guerra assegna alle immagini un referente concreto senza annullarne la profondità simbolica.',recovery:rec('Quando la storia entra nell’immagine','Il simbolo acquista un referente storico','La maceria può restare figura della precarietà e insieme indicare edifici realmente bombardati.','I morti della memoria diventano caduti e vittime della guerra.','Che cosa avviene?',['Il simbolo si collega a eventi concreti','La storia elimina ogni simbolo','La poesia smette di testimoniare'],0)},
    {q:'Qual è il rischio della concezione quasimodiana della verità poetica?',options:['Ridurre il poeta a tecnico della metrica','Ricostruire un’autorità quasi sacerdotale del poeta','Negare che il linguaggio abbia alcun valore'],answer:1,explain:'La testimonianza può trasformarsi in pretesa privilegiata di verità; la PWA lascia aperta questa tensione.',recovery:rec('La verità come passaggio dall’anonimo alla persona','Testimonianza e autorità non sono identiche','Il poeta può rendere visibile un’esperienza senza pretendere di possedere ogni verità sulla comunità.','La parola civile deve evitare sia il silenzio sia lo slogan.','Qual è il confine critico?',['Fra poesia e alfabeto','Fra testimoniare e comandare','Fra Sicilia e Calabria'],1)}
  ]
},
{
  short:'Poetica',title:'La poetica',card:'Parola assoluta, analogia, immagini e traduzione si trasformano in un discorso più ampio, ma la poesia difende la propria libertà.',
  question:'Come deve scrivere Quasimodo per dire una realtà enigmatica e, insieme, rispondere alla violenza della storia?',
  lesson:`
    <h2 id="s4-parola">1. La parola come unità di massima pressione</h2>
    <p>Nella prima stagione Quasimodo non costruisce il senso attraverso una spiegazione progressiva. Riduce i passaggi, isola i sostantivi, accosta immagini che il lettore deve attraversare. Oreste Macrì definì questa ricerca “poetica della parola”: la singola parola tende a non essere commento di una realtà già nota, ma evento capace di generare realtà. Non significa che ogni vocabolo sia misterioso; significa che il testo aumenta la pressione semantica, lasciando impliciti molti nessi.</p>
    <p>La concentrazione può produrre intensità, ma anche maniera. Già i contemporanei discussero questo limite: una formula efficace può diventare repertorio, l’oscurità può simulare profondità. Leggere Quasimodo criticamente significa tenere insieme riuscita e rischio. L’Ermetismo non è un lasciapassare che rende ogni difficoltà significativa; obbliga a osservare come la lingua costruisce davvero le relazioni.</p>
    <h2 id="s4-grammatica">2. La grammatica dell’Ermetismo forte</h2>
    <p>Il Dizionario Biografico Treccani riassume alcuni procedimenti del cosiddetto ermetismo forte. I sostantivi “assoluti”, poco determinati dal contesto, trasformano oggetti e stati in emblemi. I plurali aumentano l’indeterminatezza. I connettivi vengono soppressi o deformati, così che un rapporto logico si converte in rapporto analogico. La sintassi nominale riduce i verbi e produce immobilità; certi complementi di specificazione funzionano quasi come aggettivi inattesi. Il verso non racconta una sequenza: dispone nuclei di energia.</p>
    <p>L’analogia è centrale. Due elementi lontani vengono avvicinati senza spiegazione intermedia. Il lettore deve riconoscere una somiglianza emotiva, visiva o ritmica, non ricostruire necessariamente una causa. Da qui nasce l’impressione di una poesia chiusa. Ma “ermetico” non deve diventare sinonimo di incomprensibile: il testo propone percorsi, soltanto non li rende discorsivi.</p>
    <h2 id="s4-immagini">3. Montare immagini, organizzare la luce</h2>
    <p>Lo studio dell’Università di Milano invita a spostare l’attenzione dalla singola stranezza linguistica alla costruzione figurale. Quasimodo seleziona immagini definite e le monta per contrasto: luce e ombra, immobilità e movimento, terra e acqua, isola e città. Anche quando la sintassi rarefà il referente, l’immagine mantiene una concretezza sensoriale. La poesia diventa simile a un montaggio: il significato non sta soltanto in ciascuna figura, ma nell’urto fra le figure.</p>
    <p>Questo aspetto aiuta a comprendere la continuità con la stagione civile. Il secondo Quasimodo non abbandona le immagini per un linguaggio puramente giornalistico. Le macerie, il sangue, i fili telegrafici, le città e i corpi acquistano una referenza storica più evidente, ma restano organizzati da contrasti e condensazioni. La concretezza non nasce improvvisamente nel 1945; cambia la sua funzione ideologica e comunicativa.</p>
    <h2 id="s4-tradurre">4. Tradurre significa imparare un’altra misura</h2>
    <p>I <em>Lirici greci</em> del 1940 sono un laboratorio di poetica. Quasimodo non mira alla ricostruzione filologica neutra: traduce frammenti antichi nella lingua della poesia contemporanea. Per questo le versioni furono celebrate e contestate. L’Università di Bologna documenta come Luciano Anceschi leggesse la concordanza fra frammento greco ed essenzialità ermetica; la ricerca dell’Università di Messina insiste invece sugli scambi concreti di lessico, immagini, forme e metrica fra traduzione e poesia originale.</p>
    <p>Anche Virgilio contribuisce al cambiamento. La misura più distesa delle traduzioni prepara il “discorso” della poesia civile: versi più lunghi, maggiore oggettivazione, nessi più espliciti. Non è soltanto la guerra a modificare la forma; la pratica della traduzione offre gli strumenti per farlo. Qui si vede perché biografia, storia e tecnica non vanno separate: l’evento crea un’urgenza, il laboratorio formale rende possibile risponderle.</p>
    <h2 id="s4-civile">5. Dal monologo al dialogo</h2>
    <p>Dopo la guerra Quasimodo teorizza una poesia rivolta al mondo reale e capace di parole più comuni e ritmi più ampi. La voce non si concentra più soltanto nell’io: cerca un “noi”. Il verso diventa oratorio, elegiaco, talvolta dichiarativo. Questa apertura produce opere potenti ma espone a un nuovo rischio: la retorica civile può diventare generica proprio come l’oscurità ermetica poteva diventare maniera.</p>
    <p>Quasimodo difende perciò l’autonomia del poeta dal politico. La poesia interviene nella storia, ma non riceve dal partito né contenuti obbligatori né una missione. Il poeta dovrebbe modificare il mondo attraverso libertà e verità, non attraverso disciplina ideologica. È una posizione tesa: vuole parlare alla comunità senza esserne portavoce ufficiale. La qualità dipende dalla capacità delle opere di trasformare l’indignazione in forma, immagine e ritmo.</p>
    <h2 id="s4-continuita">6. Due stagioni o una trasformazione?</h2>
    <p>La periodizzazione scolastica — prima ermetico, poi civile — resta utile se descrive differenze verificabili. Diventa falsa quando suggerisce due autori senza rapporto. Persistono la centralità della parola, la fiducia nella poesia come verità, le immagini di perdita e una struttura elegiaca. Cambiano la lunghezza del verso, il grado di esplicitazione, il referente storico e l’interlocutore. Più che una conversione, è un allargamento conflittuale.</p>
    <p>La formula migliore non è continuità perfetta: sarebbe altrettanto semplicistica. Alcune soluzioni del dopoguerra rinunciano alla concentrazione e possono cadere nel prosastico; alcune prime poesie possono apparire chiuse in un repertorio. Le opere più significative sono i luoghi in cui Quasimodo riesce — o non riesce — a tenere insieme precisione lirica e responsabilità storica.</p>`,
  bridge:'La poetica diventa verificabile soltanto nelle opere: ogni raccolta mette alla prova il rapporto fra immagine, parola, traduzione, solitudine e storia.',
  summary:'La prima poetica di Quasimodo concentra il senso nella parola, riduce i nessi logici e costruisce analogie. L’ermetismo forte usa sostantivi assoluti, plurali indeterminati, sintassi nominale e connettivi deformati; può produrre intensità, ma anche maniera e oscurità simulata. La lettura figurale mostra immagini concrete montate attraverso luce, colore e contrasto. Questa tecnica non scompare nella poesia civile: cambia il referente delle immagini. Le traduzioni sono un laboratorio decisivo. I frammenti greci dialogano con l’essenzialità ermetica; Virgilio favorisce una misura più lunga e un discorso più oggettivato. Dopo la guerra la voce cerca il dialogo e il “noi”, con parole più comuni e ritmi ampi, ma rischia una nuova retorica. Quasimodo rivendica l’autonomia del poeta dalla politica. La distinzione fra prima stagione ermetica e seconda civile è utile solo se descrive una trasformazione: restano parola, verità e perdita; cambiano sintassi, referente e interlocutore.',
  essentials:['Definire la poetica della parola come aumento della pressione semantica.','Riconoscere i principali procedimenti dell’ermetismo forte.','Spiegare l’analogia come rapporto costruito senza passaggi logici espliciti.','Analizzare il montaggio di immagini attraverso luce e contrasto.','Trattare le traduzioni come laboratorio della poesia originale.','Collegare la misura virgiliana al passaggio verso il discorso civile.','Distinguere poesia civile e propaganda.','Descrivere la svolta come trasformazione conflittuale, non conversione totale.'],
  glossary:[['Pressione semantica','Concentrazione di più possibilità di senso in una parola o immagine.'],['Sostantivo assoluto','Nome poco determinato che assume valore emblematico.'],['Sintassi nominale','Costruzione con pochi verbi, orientata a stati e immagini più che ad azioni.'],['Connettivo','Elemento che esplicita rapporti logici fra parti del discorso.'],['Montaggio figurale','Produzione di senso attraverso selezione e accostamento delle immagini.'],['Oggettivazione','Passaggio verso una rappresentazione più esterna, articolata e condivisibile.'],['Recitativo','Andamento discorsivo e ritmico più ampio del frammento lirico concentrato.'],['Autonomia poetica','Libertà della poesia da programmi politici o filosofici imposti.']],
  map:'./maps/04-poetica.svg',mapAlt:'La parola concentrata produce pressione semantica; sostantivi assoluti, sintassi nominale e analogia formano la grammatica ermetica; il montaggio visuale organizza le immagini; le traduzioni insegnano una misura più ampia; la guerra orienta dal monologo al dialogo; continuità e mutamento confluiscono nelle opere.',
  quiz:[
    {q:'Che cosa indica la “poetica della parola”?',options:['La rinuncia a ogni immagine','La concentrazione del senso nella parola resa evento poetico','L’obbligo di usare un lessico quotidiano'],answer:1,explain:'La parola non commenta soltanto una realtà già data: concentra e genera relazioni.',recovery:rec('La parola come unità di massima pressione','Concentrare non significa decorare','La riduzione dei nessi fa sì che ogni parola sostenga più lavoro semantico.','Il testo procede per nuclei anziché per spiegazione progressiva.','Qual è l’effetto principale?',['Aumento della pressione semantica','Eliminazione del significato','Semplicità narrativa'],0)},
    {q:'Quale tratto appartiene all’ermetismo forte?',options:['Sostantivi assoluti e connettivi ridotti','Trama romanzesca lineare','Argomentazione politica esplicita'],answer:0,explain:'La grammatica ermetica converte spesso i rapporti logici in analogici.',recovery:rec('La grammatica dell’Ermetismo forte','La forma riduce i collegamenti espliciti','Sostantivi emblematici e sintassi nominale dispongono immagini più che raccontare azioni.','Un rapporto causale può diventare accostamento analogico.','Quale coppia è coerente?',['Molti verbi e cronaca','Nomi assoluti e analogia','Dialoghi e personaggi'],1)},
    {q:'Perché il montaggio figurale è importante?',options:['Perché ogni immagine vale da sola','Perché sostituisce la metrica con la pittura','Perché il senso nasce anche dall’urto e dal contrasto fra immagini'],answer:2,explain:'Luce, ombra, terra e acqua funzionano come elementi messi in relazione.',recovery:rec('Montare immagini, organizzare la luce','La relazione visuale produce senso','Il testo non è una raccolta casuale di figure: l’ordine e il contrasto le trasformano.','Isola e città, luce e maceria assumono valore dal loro rapporto.','Dove sta il significato?',['Solo nel dizionario','Anche fra le immagini','Soltanto nel titolo'],1)},
    {q:'Quale ruolo ha la traduzione nel passaggio alla poesia civile?',options:['Nessuno: è un’attività separata','Offre forme, lessico e misure più ampie per rispondere alla nuova urgenza','Impone una fedeltà letterale che blocca l’invenzione'],answer:1,explain:'L’evento storico crea l’urgenza; il laboratorio delle traduzioni fornisce strumenti formali.',recovery:rec('Tradurre significa imparare un’altra misura','Urgenza e tecnica devono incontrarsi','La guerra da sola non inventa un verso: Quasimodo dispone di pratiche maturate traducendo greci e latini.','Virgilio prepara una misura discorsiva e più lunga.','Qual è il rapporto corretto?',['Evento + laboratorio formale','Evento senza forma','Forma senza storia'],0)},
    {q:'Qual è il doppio rischio delle due stagioni?',options:['Prima la metrica, poi la prosa','Prima la maniera oscura, poi la retorica civile generica','Prima la politica, poi il silenzio assoluto'],answer:1,explain:'Ogni soluzione formale può irrigidirsi: la concentrazione in cliché o il dialogo in slogan.',recovery:rec('Due stagioni o una trasformazione?','Ogni forma può diventare formula','La qualità non dipende dall’etichetta ermetica o civile, ma dal modo in cui il testo trasforma l’esperienza.','Oscurità e chiarezza possono entrambe diventare retoriche.','Che cosa va giudicato?',['L’appartenenza a una fase','La data soltanto','La riuscita concreta della forma'],2)}
  ]
},
{
  short:'Opere',title:'Le opere decisive',card:'Dalle prime raccolte ai classici, dalla guerra al bilancio finale: poche opere mostrano davvero la trasformazione.',
  question:'In quali opere la poetica di Quasimodo diventa forma, conflitto e prova della propria verità?',
  lesson:`
    <h2 id="s5-acque"><em>Acque e terre</em>: costruire l’isola</h2>
    <p>La raccolta d’esordio del 1930 non presenta ancora un sistema perfettamente uniforme. Proprio questa eterogeneità, notata dai primi critici, permette di osservare la formazione della voce. Il titolo lega due elementi primari: l’acqua del Mediterraneo e la terra dell’origine. Nei testi più riusciti il paesaggio siciliano non è sfondo, ma struttura della coscienza. <em>Vento a Tindari</em> mette in scena la distanza: il promontorio reale, visto dall’altra sponda dello Stretto, concentra appartenenza e separazione. Il luogo chiama il soggetto proprio quando non può più coincidere con esso.</p>
    <p>In <em>Ed è subito sera</em>, lirica brevissima poi divenuta titolo della raccolta del 1942, la condizione umana viene ridotta a una sequenza estrema: individuo, luce momentanea, ferita, sera. Non serve riprodurre il testo per riconoscerne l’architettura. Lo spazio si contrae e il tempo precipita. La forza deriva dalla capacità di trasformare una vicenda minima in figura universale; il rischio, imitato infinite volte, è che la sentenza diventi formula.</p>
    <h2 id="s5-oboe"><em>Òboe sommerso</em> ed <em>Erato e Apòllion</em>: il laboratorio ermetico</h2>
    <p><em>Òboe sommerso</em> (1932) porta la lingua verso l’ermetismo forte. Il titolo stesso accosta uno strumento musicale e una condizione di immersione: la voce esiste, ma proviene da una profondità che la deforma. Sintassi rarefatta, analogie ardite, plurali e sostantivi assoluti trasformano il testo in spazio rituale. <em>Erato e Apòllion</em> (1936) accentua il rapporto con il mito e con una Sicilia originaria. La parola tende a essere cellula elementare dell’opera.</p>
    <p>Queste raccolte non vanno protette dalla critica con l’etichetta di “poesia pura”. Alcuni contemporanei denunciarono artificio e nonsenso; studi successivi hanno riconosciuto sia le autentiche riuscite sia il pericolo di un repertorio manieristico. La lettura più utile osserva caso per caso se l’analogia apre una conoscenza o nasconde un vuoto.</p>
    <h2 id="s5-greci"><em>Lirici greci</em>: l’antico diventa contemporaneo</h2>
    <p>Le versioni del 1940 occupano un posto anomalo e centrale. Quasimodo non è un filologo accademico nel senso tradizionale; usa la propria sensibilità per ricreare frammenti e voci antiche in italiano moderno. La ricezione fu polarizzata: per alcuni quelle traduzioni rendevano finalmente vivi i greci, per altri erano troppo libere. Il punto didatticamente decisivo è che la traduzione trasforma sia il testo di partenza sia il traduttore.</p>
    <p>L’essenzialità dei frammenti si accorda con il gusto ermetico, ma porta anche fuori dall’io autobiografico. Saffo, Alceo, Anacreonte e gli altri autori offrono persone, desideri, guerre e riti già condivisi da una comunità. La voce moderna impara così a farsi attraversare da altre voci. Nel lavoro su Virgilio e nei successivi classici, la metrica più distesa prepara il passaggio al discorso.</p>
    <h2 id="s5-giorno"><em>Giorno dopo giorno</em>: il dolore prende data</h2>
    <p>La raccolta del 1947, preceduta nel 1946 da <em>Con il piede straniero sopra il cuore</em>, è il centro della svolta civile. <em>Alle fronde dei salici</em> domanda come sia possibile cantare durante l’occupazione e di fronte ai morti. Il silenzio non è evasione: è coscienza dell’inadeguatezza del canto tradizionale. <em>Milano, agosto 1943</em> porta la poesia dentro la città bombardata; <em>Uomo del mio tempo</em> collega la violenza contemporanea a quella antica e rifiuta l’illusione che la tecnica abbia civilizzato moralmente l’uomo.</p>
    <p>Il verso si amplia e l’allocuzione diventa più evidente. La storia entra attraverso luoghi, vittime e responsabilità. La raccolta funziona quando la dichiarazione resta sostenuta da immagini precise; è più fragile quando il messaggio precede la forma. La guerra non autorizza automaticamente la buona poesia: aumenta la responsabilità della forma.</p>
    <h2 id="s5-vita"><em>La vita non è sogno</em> e <em>Il falso e vero verde</em>: dopo la svolta</h2>
    <p>Il titolo <em>La vita non è sogno</em> (1949) sembra correggere la rarefazione precedente: la realtà chiede presenza. Eppure nella raccolta tornano episodi siciliani e materiali classici. La storia non cancella l’isola; la costringe a convivere con il presente. <em>Il falso e vero verde</em>, nelle edizioni del 1954 e 1956, approfondisce l’aspirazione al dialogo e accompagna una riflessione esplicita sulla poesia civile.</p>
    <p>Il “verde” del titolo è già un problema di verità: natura vera o immagine ideologica? La poesia deve distinguere l’esperienza concreta dalle rappresentazioni consolatorie. Quasimodo si propone come interlocutore pubblico, ma il suo discorso resta più persuasivo quando non pretende di parlare indistintamente per tutti.</p>
    <h2 id="s5-terra"><em>La terra impareggiabile</em> e <em>Dare e avere</em>: il bilancio</h2>
    <p><em>La terra impareggiabile</em> (1958) tiene insieme Sicilia, Milano e Grecia. Non esiste più una sola opposizione spaziale: l’autore dispone una mappa di origini, storia e viaggi. Il premio Viareggio e poi il Nobel collocano questa stagione sotto una forte luce pubblica. <em>Dare e avere</em> (1966) porta già nel titolo un conto finale: che cosa ha ricevuto il poeta, che cosa ha restituito, che cosa resta insoluto?</p>
    <p>L’ultima poesia non offre una sintesi pacificata. La notorietà amplia il mondo, ma non guarisce l’esilio; i viaggi moltiplicano i luoghi, ma rendono più urgente la domanda sull’appartenenza. Queste opere mostrano che la traiettoria non è semplicemente “dal privato al pubblico”. È un movimento circolare: l’isola ritorna dentro la storia, la storia modifica il modo di guardare l’isola.</p>`,
  bridge:'Dopo le opere resta una domanda di eredità: il valore di Quasimodo dipende dal Nobel e dal ruolo storico, oppure dalla tensione ancora viva fra lirica e responsabilità?',
  summary:'<em>Acque e terre</em> costruisce la Sicilia come origine distante; <em>Vento a Tindari</em> mostra il nesso fra luogo e separazione, mentre <em>Ed è subito sera</em> comprime la condizione umana in una struttura estrema. <em>Òboe sommerso</em> ed <em>Erato e Apòllion</em> sviluppano la grammatica dell’ermetismo forte, con risultati intensi e rischi manieristici. I <em>Lirici greci</em> sono traduzioni-ricreazioni: fanno dialogare frammento antico e voce moderna e preparano un’apertura ad altre voci. <em>Giorno dopo giorno</em> dà data e luogo al dolore: occupazione, bombardamenti e vittime trasformano ritmo e interlocutore. <em>La vita non è sogno</em> e <em>Il falso e vero verde</em> proseguono la poesia civile senza eliminare mito e Sicilia. <em>La terra impareggiabile</em> e <em>Dare e avere</em> costruiscono un bilancio fra origine, Milano, Grecia e viaggi. L’intero percorso è circolare: l’isola entra nella storia e ne esce trasformata.',
  essentials:['Analizzare <em>Acque e terre</em> come costruzione dell’origine.','Spiegare l’architettura concettuale della lirica <em>Ed è subito sera</em> senza ridurla a slogan.','Riconoscere in <em>Òboe sommerso</em> la prova dell’ermetismo forte e dei suoi rischi.','Collocare i <em>Lirici greci</em> al centro, non ai margini, della produzione.','Mostrare come <em>Giorno dopo giorno</em> assegni data, luoghi e vittime al dolore.','Distinguere poesia civile riuscita e semplice dichiarazione.','Leggere <em>La terra impareggiabile</em> come mappa plurale.','Interpretare <em>Dare e avere</em> come bilancio non pacificato.'],
  glossary:[['Raccolta','Libro poetico costruito attraverso selezione, ordine e relazione fra testi.'],['Lirica breve','Testo concentrato in cui ritmo e struttura producono un significato non riducibile alla parafrasi.'],['Manierismo','Ripetizione irrigidita di procedimenti nati come innovazione.'],['Filologia','Studio storico e testuale volto a ricostruire e interpretare criticamente i testi.'],['Allocuzione','Discorso rivolto esplicitamente a un destinatario.'],['Poesia corale','Voce che assume esperienze condivise senza coincidere necessariamente con un consenso uniforme.'],['Bilancio esistenziale','Valutazione retrospettiva di ciò che una vita ha ricevuto, dato e perduto.'],['Struttura circolare','Traiettoria in cui il punto d’origine ritorna trasformato dalle esperienze successive.']],
  map:'./maps/05-opere.svg',mapAlt:'Acque e terre costruisce l’isola; Oboe sommerso porta all’ermetismo forte; i Lirici greci trasformano la traduzione in laboratorio; Giorno dopo giorno dà data al dolore; La terra impareggiabile amplia la geografia; Dare e avere produce un bilancio circolare fra origine e storia.',
  quiz:[
    {q:'Quale funzione ha Tindari in <em>Acque e terre</em>?',options:['È soltanto una descrizione turistica','Concentra appartenenza e separazione','Dimostra il rifiuto della Sicilia'],answer:1,explain:'Il promontorio reale diventa figura dell’origine vista da una distanza non colmabile.',recovery:rec('<em>Acque e terre</em>: costruire l’isola','Il luogo poetico unisce presenza e assenza','Tindari è visibile, ma il soggetto non coincide più con l’origine che rappresenta.','La distanza non indebolisce il luogo: ne aumenta la pressione simbolica.','Quale coppia definisce Tindari?',['Appartenenza e separazione','Cronaca e statistica','Tecnica e industria'],0)},
    {q:'Come vanno giudicate le analogie di <em>Òboe sommerso</em>?',options:['Sono profonde per definizione','Sono errori per definizione','Vanno verificate caso per caso: possono aprire conoscenza o diventare maniera'],answer:2,explain:'L’etichetta ermetica non sostituisce l’analisi concreta della riuscita.',recovery:rec('<em>Òboe sommerso</em> ed <em>Erato e Apòllion</em>','La difficoltà non è un valore automatico','Una forma innovativa può produrre senso oppure irrigidirsi in repertorio.','I contemporanei discussero sia l’intensità sia il rischio di nonsenso.','Qual è il criterio?',['La fama dell’autore','La riuscita della relazione nel testo','La brevità del titolo'],1)},
    {q:'Perché i <em>Lirici greci</em> sono centrali?',options:['Perché fanno incontrare frammento antico, essenzialità moderna e altre voci','Perché sono traduzioni letterali senza rapporto con la poesia originale','Perché sostituiscono tutte le raccolte di Quasimodo'],answer:0,explain:'La traduzione-ricreazione modifica ritmo, immagini e possibilità della voce moderna.',recovery:rec('<em>Lirici greci</em>: l’antico diventa contemporaneo','La traduzione è un laboratorio','Il testo antico entra in una lingua moderna, mentre il traduttore impara forme non solo sue.','Il frammento greco si accorda all’essenzialità ermetica e apre alla coralità.','Che cosa circola?',['Solo informazioni biografiche','Lessico, immagini, forme e ritmo','Soltanto titoli'],1)},
    {q:'Che cosa distingue <em>Giorno dopo giorno</em>?',options:['L’abbandono di ogni immagine','L’ingresso di luoghi, vittime e responsabilità storiche in un verso più ampio','Il ritorno integrale al poeta-vate ottocentesco'],answer:1,explain:'Il dolore assume data e referente; la forma tende al recitativo e all’allocuzione.',recovery:rec('<em>Giorno dopo giorno</em>: il dolore prende data','La storia modifica forma e referente','La città bombardata non è soltanto emblema; il verso deve nominare vittime e responsabilità.','Le immagini restano, ma sono organizzate in un discorso più esplicito.','Quale trasformazione avviene?',['Dal frammento al discorso storico','Dalla poesia al manuale tecnico','Dalla città al mito soltanto'],0)},
    {q:'Quale forma assume l’ultima fase?',options:['Una soluzione definitiva dell’esilio','Un bilancio circolare in cui luoghi e storia ritrasformano l’origine','Una cancellazione dei viaggi dopo il Nobel'],answer:1,explain:'<em>La terra impareggiabile</em> e <em>Dare e avere</em> non pacificano la traiettoria; la riaprono.',recovery:rec('<em>La terra impareggiabile</em> e <em>Dare e avere</em>','Il bilancio non è una guarigione','Rivedere la vita significa misurare scambi e perdite, non chiudere ogni conflitto.','L’isola ritorna dopo Milano, la guerra, la Grecia e i viaggi.','Che struttura emerge?',['Linea che dimentica l’inizio','Cerchio che ritorna trasformato','Elenco senza relazioni'],1)}
  ]
},
{
  short:'Conclusione',title:'Conclusione: una voce in tensione',card:'Il Nobel non chiude il giudizio: Quasimodo resta vivo dove parola privata e storia collettiva si mettono reciprocamente alla prova.',
  question:'Che cosa resta oggi di Quasimodo, oltre le formule scolastiche e oltre il prestigio del Nobel?',
  lesson:`
    <h2 id="s6-catena">1. Ricomporre i sei movimenti</h2>
    <p>Quasimodo riceve un mondo in cui progresso e catastrofe convivono, la lingua pubblica è esposta alla retorica e la poesia cerca nuove forme di autenticità. Le fratture della sua vita — mobilità infantile, terremoto, partenza, lavori tecnici, ingresso nelle riviste, traduzioni, guerra, notorietà — non costituiscono una spiegazione automatica, ma trasformano quei problemi in esperienza. Da qui nasce un’immagine del mondo fondata sulla distanza: l’origine è riconoscibile perché perduta, il tempo converte la luce in sera, la solitudine individuale può diventare condizione comune.</p>
    <p>La poetica risponde dapprima con la concentrazione: parola ad alta pressione, analogia, sintassi nominale, montaggio di immagini. La traduzione dei classici introduce altre voci e misure; la guerra obbliga a verificare se quella verità possa restare privata. Le opere civili allargano verso e interlocutore, nominano città e vittime, rischiano la retorica ma rifiutano il silenzio. Le raccolte finali riportano l’isola dentro una geografia più ampia. La traiettoria non è una linea che abbandona il passato: è un ritorno trasformato.</p>
    <h2 id="s6-nobel">2. Che cosa riconosce il Nobel</h2>
    <p>Nel 1959 l’Accademia svedese premia Quasimodo per una poesia lirica capace di esprimere con intensità classica l’esperienza tragica del tempo contemporaneo. La formula unisce esattamente i due poli del percorso: il fuoco dei classici e la storia moderna. Il premio certifica una rilevanza internazionale, non emette una sentenza eterna sul canone. Le polemiche italiane che lo accompagnano mostrano che fama istituzionale e giudizio critico non coincidono.</p>
    <p>Questo è didatticamente prezioso. Un autore non va studiato perché un premio lo rende intoccabile, né liquidato perché il gusto successivo ne ha ridimensionato alcune soluzioni. Il Dizionario Biografico arriva a una conclusione severa: l’importanza storica di Quasimodo non può essere sottovalutata anche quando si discute la sua grandezza assoluta. La scuola dovrebbe abitare questa distinzione, non nasconderla.</p>
    <h2 id="s6-eredita">3. Tre eredità verificabili</h2>
    <p>La prima eredità riguarda la parola breve. Alcune formule quasimodiane sono entrate nella memoria collettiva perché mostrano quanto un testo minimo possa organizzare spazio, tempo e condizione umana. La loro popolarità è anche un pericolo: staccate dalla traiettoria, diventano aforismi ornamentali. Studiare Quasimodo significa restituire alla brevità il lavoro formale che la sostiene.</p>
    <p>La seconda eredità è la traduzione come creazione e conflitto. I <em>Lirici greci</em> hanno inciso sul modo in cui generazioni di lettori italiani hanno immaginato la poesia antica. Oggi la filologia può discutere molte libertà, ma proprio questa discussione rende l’opera vitale: una traduzione deve avvicinare il testo o esibire la propria distanza? Quanta voce del traduttore è lecita? Quasimodo non risolve il problema; lo rende impossibile da ignorare.</p>
    <p>La terza eredità è il rapporto fra poesia e storia. Dopo una catastrofe, il poeta può tacere per non falsificare il dolore, oppure deve cercare una lingua comune? Quasimodo sceglie la seconda via, ma conserva la coscienza dell’inadeguatezza. La poesia civile è credibile non quando possiede la risposta politica corretta, bensì quando trasforma responsabilità e limite in forma.</p>
    <h2 id="s6-limiti">4. I limiti come parte dell’eredità</h2>
    <p>Una lettura celebrativa tradirebbe Quasimodo. La parola ermetica può irrigidirsi in preziosismo; il discorso civile può diventare enfatico; la figura del poeta depositario di verità può riproporre un’autorità che il Novecento aveva contestato. Perfino la Sicilia mitica rischia di cancellare la complessità storica della Sicilia reale. Questi limiti non sono note a margine: aiutano a capire che ogni risposta poetica genera un nuovo problema.</p>
    <p>La sua opera è quindi una cartina di tornasole del pieno Novecento italiano. Attraversa il passaggio dal frammento alla coralità, dall’autonomia lirica all’impegno, dalle riviste alla società mediatica del premio internazionale. Non rappresenta tutte le strade del secolo e non deve sostituire Ungaretti, Montale, Saba o le voci successive. Occupa però un incrocio nel quale i conflitti diventano visibili.</p>
    <h2 id="s6-oggi">5. Quasimodo nel presente</h2>
    <p>Nel presente digitale la parola è spesso rapida, breve e separata dal contesto. Potrebbe sembrare che la brevità quasimodiana anticipi lo slogan o il post. La somiglianza è superficiale. Nel poeta la sottrazione aumenta il tempo della lettura: poche parole costringono a sostare, a ricostruire i nessi mancanti. Nella comunicazione accelerata, invece, la brevità serve spesso a ridurre l’attenzione. La stessa misura può produrre due effetti opposti.</p>
    <p>Anche la poesia civile incontra un problema attuale. Di fronte a guerre e immagini continue di sofferenza, parlare rischia di appropriarsi del dolore altrui; tacere rischia di lasciarlo all’oblio. Quasimodo insegna non una soluzione, ma un criterio esigente: la parola deve assumersi la responsabilità della forma. Non basta dichiararsi dalla parte giusta. Occorre trovare immagini, ritmo e destinatario che non trasformino la vittima in materiale retorico.</p>
    <h2 id="s6-domanda">6. La domanda che resta</h2>
    <p>Il percorso può essere condensato così: un uomo riceve una lingua che non basta; la perdita trasforma una terra in origine; la parola concentrata tenta di custodire una verità; i classici insegnano altre misure; la guerra obbliga quella verità a uscire dall’io; le opere finali scoprono che nessuna notorietà ricompone completamente l’esilio. Ciò che resta non è la pacificazione, ma una tensione produttiva fra isola e storia.</p>
    <p>La domanda finale è quindi realmente discutibile: una poesia serve meglio la comunità quando parla con chiarezza del presente, oppure quando protegge una zona di complessità che il linguaggio pubblico vorrebbe semplificare? Quasimodo ha tentato entrambe le vie. Il suo valore più vivo sta forse non nell’aver scelto una volta per tutte, ma nell’aver reso visibile il costo di ogni scelta.</p>
    <figure class="map-wrap"><img src="./maps/sintesi.svg" alt="Il mondo moderno produce crisi della parola; le fratture trasformano la Sicilia in origine perduta; l’immagine del mondo unisce solitudine e storia; la poetica passa dalla concentrazione al discorso; le opere verificano questa tensione; l’eredità lascia aperta la responsabilità della poesia."><figcaption>Mappa conclusiva dei sei movimenti.</figcaption></figure>`,
  bridge:'Il percorso torna alla domanda iniziale: la poesia può entrare nella storia soltanto se non consegna alla politica la propria libertà formale.',
  summary:'Quasimodo riceve la crisi moderna della parola e la attraversa mediante fratture personali e storiche. La distanza trasforma la Sicilia in origine; tempo e solitudine definiscono la condizione umana; la guerra rende quel dolore condiviso. La poetica passa dalla concentrazione ermetica al discorso civile grazie anche al laboratorio delle traduzioni. Il Nobel del 1959 riconosce l’incontro fra intensità classica e tragedia contemporanea, ma non chiude il giudizio critico. Restano tre eredità: la brevità come alta pressione formale, la traduzione come creazione problematica, la poesia civile come responsabilità e non propaganda. Restano anche limiti: manierismo ermetico, enfasi civile, autorità quasi sacerdotale del poeta, mitizzazione della Sicilia. Nel presente digitale, la brevità di Quasimodo invita a rallentare anziché accelerare. La domanda finale rimane aperta: la poesia serve la comunità con la chiarezza o custodendo la complessità che il linguaggio pubblico tende a eliminare?',
  essentials:['Ricostruire l’intera catena dai problemi del mondo ricevuto alle opere finali.','Distinguere riconoscimento istituzionale e giudizio critico.','Spiegare la motivazione del Nobel come incontro fra classicità e tragedia contemporanea.','Valutare la brevità come struttura, non come slogan.','Discutere la traduzione come atto creativo e responsabile.','Definire la poesia civile attraverso forma e limite, non solo attraverso il tema.','Riconoscere i limiti di entrambe le stagioni quasimodiane.','Applicare la tensione fra chiarezza e complessità alla comunicazione contemporanea.'],
  glossary:[['Canone','Insieme mobile degli autori considerati centrali da istituzioni, critica e scuola.'],['Riconoscimento istituzionale','Legittimazione prodotta da premi, accademie e università.'],['Aforisma','Formula breve e memorabile che, isolata, può perdere la complessità del testo originario.'],['Responsabilità della forma','Dovere di trovare mezzi espressivi adeguati senza usare il dolore come materiale retorico.'],['Appropriazione','Uso dell’esperienza altrui come strumento della propria voce o immagine.'],['Cartina di tornasole','Elemento che rende visibili tensioni più generali di un’epoca.'],['Coralità','Apertura della voce individuale verso un’esperienza condivisa e plurale.'],['Eredità','Problemi, forme e possibilità che un’opera consegna a lettori e autori successivi.']],
  map:'./maps/06-conclusione.svg',mapAlt:'Il Nobel riconosce classicità e tragedia moderna ma non chiude il giudizio; restano la brevità, la traduzione e la poesia civile; i limiti includono maniera, enfasi e autorità; nel presente la responsabilità della forma mantiene aperta la tensione fra chiarezza e complessità.',
  quiz:[
    {q:'Che cosa dimostra il Nobel del 1959?',options:['Che ogni opera di Quasimodo è indiscutibilmente perfetta','Una rilevanza internazionale, non una sentenza eterna sul canone','Che la critica italiana era unanimemente favorevole'],answer:1,explain:'Il riconoscimento istituzionale è un dato storico importante, ma il giudizio estetico resta discutibile.',recovery:rec('Che cosa riconosce il Nobel','Premio e canone non coincidono','Un premio documenta una valutazione autorevole in un momento storico; non impedisce revisioni critiche.','Le polemiche italiane accompagnarono il conferimento stesso.','Che cosa è legittimo fare?',['Studiare il premio e continuare a valutare le opere','Smettere di discutere','Ignorare il Nobel'],0)},
    {q:'Qual è la differenza fra brevità quasimodiana e comunicazione accelerata?',options:['Nessuna: entrambe riducono il pensiero','La prima tende ad aumentare il tempo interpretativo, la seconda spesso a ridurlo','La poesia usa sempre più parole'],answer:1,explain:'La sottrazione ermetica chiede al lettore di ricostruire nessi; lo slogan tende a chiuderli rapidamente.',recovery:rec('Quasimodo nel presente','Breve non significa rapido','Una forma corta può chiedere molta attenzione se lascia relazioni da costruire.','La lirica minima concentra spazio, tempo e condizione umana.','Quale effetto cerca?',['Sosta interpretativa','Consumo immediato','Oblio del contesto'],0)},
    {q:'Quale criterio rende credibile la poesia civile?',options:['Il tema politico da solo','La coincidenza con un partito','La trasformazione di responsabilità e limite in immagini, ritmo e destinatario'],answer:2,explain:'Una posizione moralmente condivisibile non garantisce la riuscita poetica.',recovery:rec('Tre eredità verificabili','Il tema non sostituisce la forma','La poesia civile deve evitare di usare la vittima come pretesto per una dichiarazione generica.','In <em>Giorno dopo giorno</em> luoghi e immagini sostengono la responsabilità.','Che cosa va valutato?',['Solo l’intenzione','La forma concreta della testimonianza','La tessera politica'],1)},
    {q:'Perché i limiti fanno parte dell’eredità?',options:['Perché mostrano che ogni soluzione poetica può irrigidirsi e creare nuovi problemi','Perché annullano ogni valore dell’autore','Perché riguardano soltanto gli errori tipografici'],answer:0,explain:'Maniera, enfasi e autorità sono rischi interni alle risposte elaborate da Quasimodo.',recovery:rec('I limiti come parte dell’eredità','Un’opera consegna anche problemi','Studiare criticamente significa vedere che una soluzione efficace può diventare formula.','La parola assoluta rischia il preziosismo; il discorso civile l’enfasi.','Che cosa insegna il limite?',['Che la poesia è inutile','Che la forma richiede verifica continua','Che ogni fase è uguale'],1)},
    {q:'Quale tesi ricompone meglio l’intero percorso?',options:['Quasimodo abbandona l’isola e diventa un poeta completamente diverso','Quasimodo resta immobile nell’Ermetismo','L’origine perduta, la parola e la storia si trasformano reciprocamente senza pacificazione finale'],answer:2,explain:'La traiettoria è un ritorno trasformato: continuità di nuclei e mutamento di forme, referenti e destinatari.',recovery:rec('La domanda che resta','La traiettoria è circolare e conflittuale','La seconda stagione non cancella la prima e la prima non contiene già tutto il futuro.','L’isola ritorna dopo traduzioni, guerra, Nobel e viaggi.','Quale modello descrive il percorso?',['Sostituzione totale','Ripetizione immobile','Ritorno trasformato'],2)}
  ]
}
];
