/* Contenuti originali elaborati dal paper fornito dall'utente, con cautela nei nessi biografici e psicologici. */
window.LESSON_DATA = [
  {
    id: "mondo",
    number: "01",
    title: "Il mondo precedente",
    subtitle: "Tra romanzo moderno, fascismo e fame di assoluto",
    question: "Quale realtà storica e letteraria riceve Elsa Morante, e quale insufficienza vi riconosce?",
    color: "#7f3f45",
    lesson: `
      <h3 id="mondo-soglia">Una scrittrice sulla soglia di più mondi</h3>
      <p>Elsa Morante nasce a Roma nel 1912 e comincia a scrivere in un'Italia che attraversa fascismo, leggi razziali, guerra e ricostruzione. Questo scenario non è una cornice aggiunta dall'esterno: stabilisce quali vite siano protette, quali esposte e quali cancellate dal racconto ufficiale. Tuttavia Morante non si limita a trasferire gli eventi storici nei romanzi. Riceve anche una grande tradizione narrativa — Omero, il romanzo d'avventura, la fiaba, Cervantes, Shakespeare, il melodramma e il romanzo familiare — che le offre forme capaci di oltrepassare la cronaca. Il suo problema iniziale nasce proprio qui: come rappresentare la violenza concreta del Novecento senza ridurre l'uomo al documento sociologico, e come usare mito e immaginazione senza trasformarli in evasione?</p>
      <p>La posizione di Morante nel secolo è perciò laterale e centrale insieme. Laterale, perché non aderisce stabilmente a una scuola e difende con durezza la propria autonomia. Centrale, perché affronta alcuni nodi decisivi del dopoguerra: il rapporto fra individuo e masse, fra politica e innocenza, fra memoria privata e catastrofe collettiva. Definirla semplicemente “anti-neorealista” sarebbe povero. Condivide con il neorealismo l'attenzione ai corpi colpiti dalla guerra, agli umili e alle disuguaglianze; rifiuta però l'idea che la realtà possa essere esaurita dalla registrazione dei fatti o da una tesi politica già pronta.</p>
      <h3 id="mondo-storia">La Storia pubblica e le vite senza voce</h3>
      <p>Il fascismo consegna alla giovane scrittrice un linguaggio pubblico fatto di ordine, forza, patria e destino. Dopo il 1945, anche le narrazioni della ricostruzione possono assumere una forma troppo lineare: caduta della dittatura, Resistenza, rinascita democratica, progresso. Morante incrina entrambe le retoriche. La sua attenzione va a ciò che le grandi parole non riescono a contenere: paura, fame, dipendenza, vergogna, desiderio di essere amati. Nei suoi libri la Storia con la maiuscola non coincide con tutta la storia umana; è spesso il nome di un meccanismo di dominio che decide sopra le persone e poi le trasforma in numeri.</p>
      <p>Questa distinzione non implica che ogni istituzione sia identica o che ogni progetto politico sia inutile. È una protesta letteraria contro l'astrazione: qualunque ideale deve essere misurato sui suoi effetti. Nel futuro romanzo <em>La Storia</em>, le date e i grandi eventi compariranno accanto alla vicenda quasi invisibile di Ida e Useppe. Le due scale non si eliminano: il racconto mostra che l'evento mondiale diventa reale quando raggiunge una cucina, una scuola, un rifugio, il sistema nervoso di un bambino. La vita minuta non sostituisce la storia collettiva; ne diventa la prova morale.</p>
      <h3 id="mondo-letteratura">Oltre le etichette del dopoguerra</h3>
      <p>Nel clima neorealista il romanzo è chiamato a testimoniare il presente, le lotte sociali e la guerra appena conclusa. Morante partecipa a questa urgenza, ma recupera strumenti che possono apparire inattuali: genealogie complicate, narratori appassionati, atmosfere favolose, simboli, eccessi melodrammatici, strutture epiche. <em>Menzogna e sortilegio</em>, pubblicato nel 1948, non adotta la lingua asciutta della cronaca; costruisce un universo familiare dominato da racconti falsi, desideri assoluti e memorie deformate. La “menzogna” non è soltanto un errore da correggere. È anche la forma immaginaria con cui i personaggi tentano di sopportare una vita insufficiente.</p>
      <p>In questa scelta si riconosce il carattere onnivoro della formazione morantiana. La fiaba le permette di isolare conflitti elementari; l'epica dà grandezza a vite che la società giudica minori; il romanzo ottocentesco offre famiglie, passioni e durata; la modernità introduce coscienze divise e narratori non affidabili. Morante non mescola queste tradizioni per gusto ornamentale. Le usa perché nessun solo realismo basta a dire una realtà in cui il bisogno di assoluto convive con la miseria materiale.</p>
      <h3 id="mondo-tensione">Il limite ereditato: realtà senza verità, immaginazione senza responsabilità</h3>
      <p>Il mondo precedente lascia dunque una doppia insufficienza. Da una parte, il linguaggio del Potere tratta gli individui come categorie: razza, classe, nazione, nemico. Dall'altra, l'immaginazione può costruire idoli consolatori e chiudere i personaggi dentro un sortilegio narcisistico. Morante non sceglie semplicemente la fantasia contro la storia. Cerca una finzione capace di smascherare le falsità sociali e, nello stesso tempo, di raggiungere una verità affettiva che il documento non possiede da solo.</p>
      <p>Questa ricerca prepara le fratture biografiche: l'origine familiare complessa, l'indipendenza conquistata con il lavoro, la guerra vissuta in fuga, il matrimonio con Alberto Moravia, le amicizie e le perdite. Sarebbe meccanico dedurre i romanzi da questi fatti. È più rigoroso dire che tali esperienze rendono evidente il problema già posto dal secolo: chi possiede la verità di una vita? Il nome legale, la famiglia, lo Stato, l'amante, la memoria o il racconto? Quando nessuna risposta basta, la scrittura diventa il luogo in cui realtà e sortilegio devono affrontarsi senza annullarsi.</p>`,
    summary: "Morante riceve un Novecento segnato da fascismo, guerra e ricostruzione, ma anche una tradizione narrativa vastissima: epica, fiaba, melodramma, romanzo familiare e modernismo. Condivide con il neorealismo l'attenzione agli umili e alla violenza storica, senza credere che cronaca e ideologia esauriscano il reale. La Storia con la maiuscola indica soprattutto il punto di vista astratto del Potere; la vita minuta ne misura gli effetti sui corpi. All'opposto, nemmeno l'immaginazione è innocente: può rivelare ciò che il documento non vede, ma può anche diventare menzogna consolatoria. Il problema iniziale è quindi doppio: evitare una realtà priva di verità interiore e una fantasia priva di responsabilità. Le fratture della vita renderanno più urgente la domanda su chi abbia il diritto di raccontare una persona.",
    essentials: [
      "Spiegare perché fascismo, guerra e ricostruzione agiscono sulle vite e non restano semplice sfondo.",
      "Collocare Morante in rapporto al neorealismo senza identificarla né opporla schematicamente ad esso.",
      "Distinguere la Storia del Potere dalla pluralità delle esperienze individuali.",
      "Mostrare la funzione conoscitiva di epica, fiaba e romanzo familiare.",
      "Comprendere che anche l'immaginazione può diventare una menzogna consolatoria.",
      "Formulare la tensione iniziale fra realtà documentaria e verità affettiva."
    ],
    vocabulary: [
      ["Neorealismo", "Orizzonte culturale del dopoguerra attento alla guerra e alla società, con cui Morante dialoga senza aderirvi come a un programma."],
      ["Storia", "Nel lessico critico morantiano, il corso pubblico dominato dal Potere e osservato dalle conseguenze sulle vittime."],
      ["Epica", "Forma ampia che conferisce rilievo collettivo anche a personaggi socialmente marginali."],
      ["Fiaba", "Struttura narrativa che rende visibili conflitti elementari attraverso metamorfosi, prove e simboli."],
      ["Sortilegio", "Potere ambiguo dell'immaginazione: può rivelare il reale oppure imprigionare in un'illusione."],
      ["Astrazione", "Riduzione delle persone a categorie generali che ne cancellano la singolarità."]
    ],
    map: "assets/maps/01-mondo.svg",
    mapAlt: "Il Novecento produce fascismo, guerra e narrazioni di progresso; il neorealismo chiede testimonianza; epica e fiaba ampliano il realismo; la Storia astratta schiaccia le vite; l'immaginazione può rivelare o ingannare; la doppia tensione conduce alle fratture biografiche.",
    questions: [
      { q: "Qual è il problema iniziale della scrittura morantiana?", options: ["Unire la concretezza storica a una verità che mito e immaginazione possono rivelare", "Sostituire interamente la storia con la fiaba", "Applicare senza variazioni il programma neorealista"], correct: 0, explanation: "Morante cerca una forma che non perda né i corpi della storia né la profondità simbolica dell'esperienza.", anchor: "mondo-soglia", recovery: ["Due esigenze insieme", "Documento e immaginazione sono strumenti parziali: la scrittura li mette in tensione.", "In La Storia le date pubbliche convivono con la vicenda di Ida e Useppe."] },
      { q: "In che rapporto sta Morante con il neorealismo?", options: ["Lo ignora perché racconta solo mondi fantastici", "Ne condivide l'urgenza del reale, ma non una forma o un'ideologia obbligatorie", "Ne segue rigidamente lo stile documentario"], correct: 1, explanation: "L'attenzione agli umili è comune, mentre mito, epica e interiorità rendono autonoma la sua ricerca.", anchor: "mondo-letteratura", recovery: ["Vicino e oltre", "Appartenere a un'epoca non significa obbedire a un'etichetta.", "Menzogna e sortilegio esce nel dopoguerra ma usa una costruzione romanzesca ampia e visionaria."] },
      { q: "Che cosa verifica la vita minuta nei romanzi di Morante?", options: ["La superiorità della famiglia sulla politica", "L'irrilevanza delle date storiche", "Gli effetti concreti delle decisioni e delle violenze pubbliche"], correct: 2, explanation: "La piccola storia non cancella la grande: mostra che cosa essa fa ai corpi e ai legami.", anchor: "mondo-storia", recovery: ["La prova delle conseguenze", "Un'idea politica va giudicata anche da ciò che produce nelle vite.", "Un bombardamento è un dato militare e insieme una casa perduta."] },
      { q: "Perché la menzogna è un tema più complesso del semplice errore?", options: ["Perché ogni falsità diventa vera se raccontata bene", "Perché può essere una costruzione con cui un personaggio sopporta o deforma il reale", "Perché Morante considera inutile distinguere vero e falso"], correct: 1, explanation: "Il sortilegio protegge e imprigiona: la finzione ha una funzione ambivalente.", anchor: "mondo-letteratura", recovery: ["L'ambivalenza del racconto", "Una fantasia può consolare senza per questo essere innocente.", "Idealizzare una persona allevia la solitudine ma impedisce di vederla davvero."] },
      { q: "Quale limite del mondo ricevuto prepara le fratture?", options: ["Il Potere riduce le persone a categorie e l'immaginazione può chiuderle in idoli", "La tradizione italiana è priva di romanzi familiari", "La fiaba non può parlare del Novecento"], correct: 0, explanation: "Morante deve evitare sia l'astrazione politica sia l'illusione privata.", anchor: "mondo-tensione", recovery: ["Due forme di irrealtà", "Si può falsificare una vita con una statistica o con un'immagine idealizzata.", "Chiamare qualcuno 'nemico' lo riduce; adorarlo come perfetto lo rende ugualmente invisibile."] }
    ]
  },
  {
    id: "fratture",
    number: "02",
    title: "Le fratture della vita",
    subtitle: "Origini, guerra, legami e perdite senza biografismo",
    question: "Quali esperienze mettono in crisi il mondo ricevuto e come cambiano le domande della scrittura?",
    color: "#a05a3f",
    lesson: `
      <h3 id="fratture-metodo">La biografia è un contesto, non una chiave universale</h3>
      <p>La vita di Elsa Morante contiene fratture che dialogano con i suoi libri: la situazione familiare irregolare, l'autonomia precoce, la guerra, relazioni intense, separazioni e lutti. Il rischio didattico consiste nel trasformare ogni personaggio in una maschera dell'autrice. Non possediamo una formula per cui un trauma reale generi automaticamente una scena narrativa. Possiamo invece osservare che alcune esperienze rendono intelligibili domande insistenti: che cosa fonda un'identità? Perché l'amore produce insieme salvezza e dipendenza? Come continua a vivere chi ha perduto il proprio oggetto assoluto?</p>
      <p>Morante nasce da Irma Poggibonsi ed è riconosciuta dal marito della madre, Augusto Morante; il padre biologico è Francesco Lo Monaco. Questa situazione non “spiega” da sola <em>Menzogna e sortilegio</em>, ma offre un contesto per capire la sua attenzione ai nomi, alle genealogie, ai segreti e alle verità familiari. L'identità, nei romanzi, non è un nucleo trasparente: nasce anche dallo sguardo altrui e dai racconti che una famiglia ripete su se stessa.</p>
      <p>La prudenza interpretativa non indebolisce il legame fra vita e letteratura; lo rende verificabile. Invece di cercare equivalenze fra persone reali e personaggi, conviene confrontare problemi, trasformazioni e differenze. La forma romanzesca non conserva un fatto intatto: lo sposta, lo combina con altri materiali e gli attribuisce una funzione nuova.</p>
      <h3 id="fratture-autonomia">Autodidatta, scrittrice, non appendice di qualcuno</h3>
      <p>Da giovane Morante lascia la famiglia e si mantiene con lezioni, collaborazioni e scritti per periodici. La formazione da autodidatta alimenta una libertà non priva di costo: può scegliere letture lontane fra loro, ma deve conquistare uno spazio professionale in un ambiente letterario ancora fortemente maschile. Pubblica racconti anche destinati all'infanzia, frequenta classici, musica e pensiero filosofico. Questa ampiezza prepara una voce che non accetta la separazione rigida fra letteratura alta e popolare.</p>
      <p>L'incontro con Alberto Moravia e il matrimonio del 1941 la collocano nel centro della cultura romana. Sarebbe però scorretto definirla attraverso il marito. Il confronto con Moravia è affettivo e intellettuale, talvolta competitivo, e rende ancora più visibile l'esigenza di un'autonomia autoriale. Le loro poetiche restano differenti: Moravia tende spesso all'analisi razionale dei rapporti borghesi; Morante costruisce universi in cui passione, mito e giudizio storico si accendono reciprocamente. La relazione offre un ambiente di scambio, non la causa della sua grandezza.</p>
      <h3 id="fratture-guerra">La guerra vissuta dal margine</h3>
      <p>Dopo l'8 settembre 1943 Morante e Moravia lasciano Roma e trovano rifugio nelle campagne presso Fondi, in Ciociaria. Moravia è esposto anche per l'origine ebraica paterna; Morante ha a sua volta ascendenze ebraiche per parte materna. La precarietà, la vicinanza ai contadini e l'esperienza di una violenza che attraversa il quotidiano offrono un contesto decisivo per la futura attenzione agli esclusi. Non bisogna però immaginare una linea diretta dalla fuga a un singolo romanzo: fra esperienza e forma intervengono decenni di letture, elaborazione e scelte compositive.</p>
      <p>Ciò che cambia è la scala dello sguardo. Il conflitto non coincide più con generali e strategie; si deposita nella fame, nei rifugi, nei corpi vulnerabili e nella paura di essere riconosciuti. Questa prospettiva maturerà soprattutto in <em>La Storia</em>, dove l'eccezionale evento bellico è visto da chi non ha alcun controllo su di esso. La frattura storica non consegna una facile coscienza politica: lascia la domanda più dura su come raccontare vittime che non possono convertire il dolore in eroismo.</p>
      <h3 id="fratture-perdite">Separazioni, Bill Morrow e il tempo del dopo</h3>
      <p>All'affermazione letteraria seguono legami e rotture importanti. Morante e Moravia si separano nel 1962. Nello stesso periodo la morte del giovane artista americano Bill Morrow, con il quale Morante aveva avuto un rapporto intenso, costituisce una perdita profonda. Anche qui occorre evitare la diagnosi retroattiva: non si può ridurre <em>Il mondo salvato dai ragazzini</em> o <em>La Storia</em> a una risposta privata a quel lutto. Si può però riconoscere che morte prematura, innocenza esposta e desiderio di salvezza assumono da allora una nuova urgenza.</p>
      <p>Negli ultimi anni malattia, immobilità e isolamento rendono ancora più aspra la ricerca. <em>Aracoeli</em> attraversa memoria materna, corpo e fallimento del ritorno senza offrire una cura narrativa. Persino il viaggio diventa discesa in ciò che non può essere recuperato. La biografia non determina l'opera, ma mostra il costo delle sue domande: l'immaginazione può salvare qualcosa senza mentire? Dalle fratture emerge così un'immagine del mondo in cui il Potere produce irrealtà, gli innocenti vedono ciò che gli adulti rimuovono e la salvezza, se esiste, non coincide con un lieto fine.</p>`,
    summary: "Le fratture della vita di Morante vanno collegate ai testi senza biografismo. L'origine familiare complessa offre un contesto per i temi di identità, nome e genealogia, ma non causa automaticamente i romanzi. L'indipendenza economica e la formazione autodidatta favoriscono una cultura onnivora; il matrimonio con Moravia crea confronto, non dipendenza artistica. La fuga in Ciociaria dopo l'8 settembre 1943 rende concretamente visibile la guerra dal punto di vista di chi la subisce, prospettiva che maturerà in La Storia. La separazione da Moravia, la morte di Bill Morrow e le malattie degli ultimi anni intensificano le domande sulla perdita, senza autorizzare diagnosi psicologiche dell'opera. La questione che resta è se l'immaginazione possa custodire gli scomparsi senza trasformarli in idoli. Da qui nasce una visione conflittuale di Realtà, Potere, innocenza e salvezza.",
    essentials: [
      "Distinguere il contesto biografico da una spiegazione causale automatica dei testi.",
      "Collegare con prudenza origini familiari e interesse per nomi, genealogie e segreti.",
      "Spiegare il valore dell'autonomia professionale e della formazione autodidatta.",
      "Riconoscere nel rapporto con Moravia uno scambio fra autori autonomi.",
      "Descrivere la guerra in Ciociaria come esperienza della storia dal margine.",
      "Leggere separazioni, lutti e malattia come contesti che rendono urgenti perdita e memoria."
    ],
    vocabulary: [
      ["Biografismo", "Riduzione meccanica dell'opera a episodi della vita dell'autore."],
      ["Genealogia", "Rete delle discendenze e dei nomi attraverso cui una famiglia costruisce la propria identità."],
      ["Autodidatta", "Persona che forma autonomamente la propria cultura fuori da un percorso istituzionale completo."],
      ["Autonomia autoriale", "Capacità di definire una poetica propria anche dentro relazioni e ambienti influenti."],
      ["Trauma", "Ferita che può continuare a incidere nel tempo; non è una spiegazione totale di un'opera."],
      ["Elaborazione", "Lavoro nel tempo che trasforma un'esperienza in memoria, pensiero o forma artistica."]
    ],
    map: "assets/maps/02-fratture.svg",
    mapAlt: "Le origini familiari rendono leggibile il problema dell'identità; l'autonomia produce libertà culturale; Moravia offre confronto senza dipendenza; la fuga in Ciociaria mostra la guerra dal margine; separazioni e lutti intensificano la domanda sulla perdita; le fratture confluiscono in una nuova immagine del mondo.",
    questions: [
      { q: "Qual è il modo corretto di usare la biografia di Morante?", options: ["Come prova che ogni personaggio rappresenta l'autrice", "Come contesto che rende leggibili domande, senza determinare le opere", "Come elemento irrilevante da escludere"], correct: 1, explanation: "Fra esperienza e romanzo intervengono immaginazione, letture, distanza e costruzione formale.", anchor: "fratture-metodo", recovery: ["Contesto, non causa unica", "Una somiglianza biografica apre un'interpretazione ma non la dimostra da sola.", "Una genealogia complessa aiuta a capire l'interesse per i segreti familiari, ma non scrive Menzogna e sortilegio."] },
      { q: "Che cosa favorisce la formazione autodidatta?", options: ["Una cultura libera di attraversare classici, fiaba, musica e filosofia", "Il rifiuto di ogni lettura precedente", "L'adesione obbligatoria al neorealismo"], correct: 0, explanation: "Morante costruisce un patrimonio eterogeneo e non subordinato a una scuola.", anchor: "fratture-autonomia", recovery: ["Una formazione onnivora", "L'autodidatta può mettere in dialogo tradizioni che l'accademia tiene separate.", "Omero e i racconti per l'infanzia possono entrare nello stesso laboratorio narrativo."] },
      { q: "Come va interpretato il rapporto con Moravia?", options: ["Come origine esclusiva della carriera di Morante", "Come prova che le loro poetiche coincidono", "Come scambio affettivo e intellettuale fra due scrittori autonomi"], correct: 2, explanation: "L'ambiente condiviso è importante, ma la voce di Morante resta irriducibile a quella del marito.", anchor: "fratture-autonomia", recovery: ["Relazione senza riduzione", "Un confronto può influire senza cancellare l'indipendenza.", "Moravia analizza spesso il mondo borghese; Morante intreccia mito, passione e storia."] },
      { q: "Che cosa modifica soprattutto l'esperienza della guerra in Ciociaria?", options: ["La trasforma immediatamente in una scrittrice neorealista", "Rende visibile la guerra attraverso fame, paura e vulnerabilità quotidiana", "Le fa abbandonare ogni forma fantastica"], correct: 1, explanation: "Il conflitto viene osservato dal margine e dai suoi effetti sui non protagonisti.", anchor: "fratture-guerra", recovery: ["La guerra vista dal basso", "Il grande evento entra nella vita attraverso bisogni e pericoli concreti.", "Cercare cibo o un rifugio mostra la guerra diversamente da un bollettino militare."] },
      { q: "Quale domanda intensificano le perdite?", options: ["Se l'immaginazione possa custodire l'assente senza idealizzarlo", "Se la letteratura debba rinunciare alla memoria", "Se ogni romanzo debba avere un lieto fine"], correct: 0, explanation: "Il lutto rende urgente una memoria capace di amare senza falsificare.", anchor: "fratture-perdite", recovery: ["Memoria e idolo", "Ricordare non significa trasformare chi è morto in un'immagine perfetta.", "Un ritratto fedele conserva anche contraddizioni e distanze."] }
    ]
  },
  {
    id: "immagine",
    number: "03",
    title: "L'immagine del mondo",
    subtitle: "Realtà, Irrealtà e lo scandalo del Potere",
    question: "Come appare la realtà quando viene guardata dalle vittime, dai bambini e dagli esclusi?",
    color: "#416b6b",
    lesson: `
      <h3 id="immagine-realta">Realtà e Irrealtà: una distinzione morale</h3>
      <p>Nel pensiero di Morante, soprattutto negli scritti degli anni Sessanta e Settanta, Realtà e Irrealtà non coincidono banalmente con vero e falso. L'Irrealtà è la vita ridotta a ruolo, prestigio, possesso, ideologia e obbedienza; è il mondo in cui una persona vale solo per la posizione che occupa. La Realtà è invece la presenza irriducibile degli esseri viventi, percepita prima che vengano classificati. Questa distinzione ha una forza morale e poetica più che sistematica: non forma una filosofia chiusa, ma orienta lo sguardo e il giudizio.</p>
      <p>Per questo l'immaginazione non appartiene automaticamente all'Irrealtà. Un mito può smascherare le categorie sociali e restituire una creatura alla sua unicità; una cronaca apparentemente esatta può servire il Potere. Allo stesso modo, una fantasia narcisistica può diventare prigione. La linea decisiva passa fra le forme che aumentano l'attenzione alla vita e quelle che la sostituiscono con un idolo. Il romanzo deve attraversare entrambe, perché gli esseri umani vivono di desideri e racconti, non di soli fatti.</p>
      <h3 id="immagine-potere">La Storia come scandalo del Potere</h3>
      <p>Morante guarda con diffidenza alle filosofie che leggono la storia come progresso necessario. Guerre, persecuzioni e gerarchie le appaiono variazioni di una lunga violenza: pochi dispongono della vita di molti, e i vincitori costruiscono la narrazione pubblica. La formula dello “scandalo” indica questa ripetizione. Non significa che ogni epoca sia uguale o che le lotte politiche non producano differenze; significa che nessuna idea di progresso può giustificare la sofferenza concreta come semplice prezzo del futuro.</p>
      <p>Il suo anarchismo va inteso anzitutto come rifiuto del dominio, non come programma dettagliato di governo. Il Potere tende a trasformare relazioni vive in gerarchie e individui in strumenti. Qui il dialogo con Simone Weil è illuminante: la forza rende cosa chi la subisce e spesso anche chi la esercita; l'attenzione, al contrario, riconosce l'altro senza possederlo. Morante non costruisce però un trattato weiliano. Trasforma questa opposizione in personaggi, corpi e destini narrativi.</p>
      <h3 id="immagine-innocenti">Ragazzini, animali, poeti: figure e non categorie pure</h3>
      <p>I bambini, gli animali, gli umili e alcuni poeti occupano un posto privilegiato perché non controllano la macchina storica e ne rivelano il costo. Useppe, Arturo e le figure del <em>Mondo salvato dai ragazzini</em> possiedono uno sguardo non ancora interamente adattato alle convenzioni adulte. La loro innocenza non è ignoranza felice. È esposizione: vedono e patiscono senza disporre degli schermi con cui gli adulti normalizzano la violenza.</p>
      <p>Morante distingue provocatoriamente i “Felici Pochi” dagli “Infelici Molti”. Questa antitesi non va trasformata in sociologia o in aristocrazia dello spirito. Funziona come immagine polemica: alcuni conservano un contatto con la vita, molti accettano l'Irrealtà del consumo e del Potere. Ma i romanzi complicano lo schema. L'innocenza è vulnerabile, può essere distrutta; i suoi portatori non fondano una comunità stabile. La salvezza promessa dal titolo <em>Il mondo salvato dai ragazzini</em> resta una sfida, non un risultato garantito.</p>
      <p>Ne deriva una concezione non lineare della conoscenza. Chi possiede istruzione e autorità può restare cieco alla sofferenza; chi non sa interpretare le cause può percepirne con precisione gli effetti. Morante non celebra l'ignoranza: separa il sapere usato per dominare dall'attenzione capace di lasciarsi modificare da ciò che vede. L'innocente non conosce meno in assoluto; conosce diversamente e paga spesso questa apertura.</p>
      <h3 id="immagine-amore">Amore assoluto, corpo e rischio dell'idolo</h3>
      <p>In questa visione l'amore è una forza ambivalente. Può riconoscere l'altro nella sua realtà oppure trasformarlo nell'oggetto di un bisogno assoluto. I personaggi morantiani cercano spesso nella madre, nell'amante o nell'eroe un paradiso capace di cancellare la separazione. Proprio tale richiesta rende il legame fragile: nessuna persona reale può coincidere con l'immagine totale che l'altro pretende. Il narcisismo, utile come categoria interpretativa in alcuni casi, non è una diagnosi universale; nomina piuttosto la tendenza ad amare il proprio sogno nell'altro.</p>
      <p>Il corpo impedisce alla fantasia di chiudersi perfettamente. Fame, sessualità, malattia, epilessia, crescita e morte riportano il personaggio al limite. In <em>La Storia</em> la violenza pubblica si iscrive nei corpi di Ida e Useppe; in <em>Aracoeli</em> il viaggio della memoria incontra decadimento e impossibilità del ritorno. Se questa è l'immagine del mondo — Potere astratto contro vita singolare, desiderio di assoluto contro limite corporeo — nasce un problema espressivo: quale forma può tenere insieme documento e mito, pietà e giudizio, senza fare propaganda né offrire consolazione? La poetica sarà la risposta operativa.</p>`,
    summary: "Morante distingue Realtà e Irrealtà in senso morale: la prima è la presenza irriducibile dei viventi, la seconda è la loro riduzione a ruolo, prestigio, merce o ideologia. Il Potere produce Irrealtà attraverso gerarchie e violenza; la Storia appare scandalosa quando sacrifica persone concrete a un futuro astratto. Il dialogo con Simone Weil illumina forza, sventura e attenzione, ma i romanzi non sono trattati filosofici. Bambini, animali, umili e poeti mostrano il costo del dominio perché non ne controllano i meccanismi. I “Felici Pochi” e gli “Infelici Molti” sono un'antitesi polemica, non categorie sociali rigide. Anche l'amore è ambiguo: può riconoscere una persona o trasformarla in idolo. Il corpo spezza le fantasie di onnipotenza. Una visione così conflittuale richiede una forma capace di unire storia e mito senza propaganda.",
    essentials: [
      "Definire Realtà e Irrealtà come orientamenti morali, non come semplice vero e falso.",
      "Spiegare perché la critica del Potere non equivale a dichiarare identiche tutte le politiche.",
      "Collegare Simone Weil ai temi di forza, sventura e attenzione con cautela critica.",
      "Interpretare bambini, animali e umili come punti di vista esposti alla violenza.",
      "Leggere Felici Pochi e Infelici Molti come antitesi poetica e polemica.",
      "Mostrare l'ambivalenza dell'amore e la funzione di limite esercitata dal corpo."
    ],
    vocabulary: [
      ["Realtà", "Verità vivente e singolare degli esseri prima della loro riduzione a ruoli o strumenti."],
      ["Irrealtà", "Sistema di immagini, gerarchie e ideologie che sostituisce la vita concreta."],
      ["Potere", "Forza che dispone degli altri e tende a trasformarli in mezzi o categorie."],
      ["Sventura", "Condizione in cui una forza impersonale colpisce insieme corpo, dignità e possibilità di parola."],
      ["Attenzione", "Disponibilità a vedere l'altro senza imporgli subito un'immagine o un uso."],
      ["Felici Pochi", "Figure che conservano un contatto non addomesticato con la vita e resistono all'Irrealtà."],
      ["Narcisismo", "Tendenza ad amare nell'altro un'immagine del proprio desiderio anziché la sua differenza."]
    ],
    map: "assets/maps/03-immagine.svg",
    mapAlt: "Il Potere produce Irrealtà riducendo i viventi a ruoli; la Storia rende visibile lo scandalo della forza; l'attenzione riconosce la Realtà singolare; bambini, animali e poeti la testimoniano; l'amore può diventare riconoscimento o idolo; il corpo impone il limite; questa visione richiede una nuova poetica.",
    questions: [
      { q: "Che cosa indica l'Irrealtà in Morante?", options: ["Ogni opera fantastica", "La sola menzogna pronunciata consapevolmente", "La riduzione della vita a ruoli, prestigio, consumo e ideologia"], correct: 2, explanation: "L'Irrealtà può presentarsi anche come discorso ufficialmente vero, se cancella la singolarità.", anchor: "immagine-realta", recovery: ["Non è solo falso", "L'Irrealtà è un modo di vivere e guardare che sostituisce la persona con una funzione.", "Considerare un individuo soltanto come consumatore ne oscura bisogni e storia."] },
      { q: "Perché la critica morantiana del progresso non annulla ogni differenza politica?", options: ["Perché chiede di giudicare ogni progetto anche dalle conseguenze sulle persone", "Perché approva qualsiasi potere democratico", "Perché riguarda soltanto le guerre antiche"], correct: 0, explanation: "La sua obiezione è contro il sacrificio del presente concreto a un futuro astratto.", anchor: "immagine-potere", recovery: ["Progresso sotto verifica", "Un fine dichiarato buono non rende automaticamente giusti i mezzi.", "Una riforma va valutata anche da chi viene escluso o danneggiato."] },
      { q: "Quale funzione hanno spesso bambini e animali?", options: ["Offrire sempre un lieto fine", "Mostrare il costo del Potere da una posizione vulnerabile", "Rappresentare persone incapaci di conoscere"], correct: 1, explanation: "La loro esposizione rende visibile ciò che il linguaggio adulto normalizza.", anchor: "immagine-innocenti", recovery: ["Vulnerabilità conoscitiva", "Non controllare il Potere permette di mostrarne le conseguenze, ma espone alla ferita.", "Useppe percepisce la guerra nel corpo prima di comprenderne le cause storiche."] },
      { q: "Come vanno letti i Felici Pochi?", options: ["Come una classe sociale realmente censita", "Come un partito politico organizzato", "Come immagine polemica di chi conserva contatto con la vita"], correct: 2, explanation: "L'opposizione è poetica e morale, non una descrizione sociologica rigida.", anchor: "immagine-innocenti", recovery: ["Una figura, non un'anagrafe", "Le categorie poetiche concentrano una tensione senza classificare definitivamente le persone.", "Un poeta può resistere all'Irrealtà in un momento e cedere in un altro."] },
      { q: "Perché l'amore è ambivalente?", options: ["Può riconoscere l'altro oppure sostituirlo con un'immagine assoluta", "È sempre una forma di dominio", "Non incide mai sull'identità"], correct: 0, explanation: "Il desiderio di fusione può diventare attenzione oppure possesso dell'immagine amata.", anchor: "immagine-amore", recovery: ["Amore o idolo", "Amare una persona richiede tollerare che non coincida con il nostro bisogno.", "Un figlio idealizzato smette di essere visto nelle sue paure reali."] }
    ]
  },
  {
    id: "poetica",
    number: "04",
    title: "La poetica",
    subtitle: "Il romanzo come incantesimo di verità",
    question: "Come deve scrivere Morante per raccontare una realtà insieme storica, psichica e mitica?",
    color: "#54628a",
    lesson: `
      <h3 id="poetica-realismo">Un realismo che attraversa l'invisibile</h3>
      <p>La poetica di Morante nasce dal rifiuto di una scelta obbligata: o documento o fantasia. Il romanzo deve registrare fame, guerra, denaro, corpi e rapporti di classe; deve però anche mostrare desideri, immagini assolute, paure infantili e racconti con cui i personaggi interpretano se stessi. Per questa ragione si parla talvolta di realismo visionario o traumatico. Sono definizioni critiche utili, purché non diventino etichette totali. Indicano una scrittura in cui l'evento esterno continua a vivere nella memoria, nella percezione e nel corpo.</p>
      <p>La narrazione può allora essere frammentata, retrospettiva, ossessiva o ciclica. Non perché ogni irregolarità formale riproduca clinicamente un trauma, ma perché il tempo vissuto non coincide sempre con la cronologia. In <em>Aracoeli</em> il viaggio presente è invaso dal ricordo; in <em>La Storia</em> la successione delle date pubbliche contrasta con il tempo affettivo dei personaggi. Il montaggio rende percepibile la sproporzione fra ciò che i manuali considerano importante e ciò che una coscienza non riesce a dimenticare.</p>
      <h3 id="poetica-mito">Mito, fiaba e alibi: la finzione come conoscenza</h3>
      <p>Mito e fiaba non coprono la realtà: la ingrandiscono, isolando forze elementari come abbandono, gelosia, prova, metamorfosi, paradiso perduto. Arturo trasforma l'isola e il padre in figure eroiche; Elisa ricostruisce una genealogia sotto l'effetto del sortilegio familiare. Il lettore vede contemporaneamente la potenza di quei miti e la loro insufficienza. La finzione conosce perché permette di entrare nell'immagine che governa un personaggio e di osservarne le crepe.</p>
      <p>Morante usa il termine “alibi” per riflettere sulla capacità poetica di assumere altre identità. Non si tratta dell'alibi giudiziario che evita una colpa, ma di una metamorfosi immaginativa: l'io esce dai propri confini e presta voce a creature diverse. Questa facoltà è eticamente preziosa solo se non pretende di possedere interamente l'altro. Il romanziere crea mondi e nello stesso tempo deve ricordare che le creature narrate eccedono la sua tesi.</p>
      <h3 id="poetica-forme">Voce, epica e contaminazione dei registri</h3>
      <p>La lingua morantiana cambia molto da un'opera all'altra. Può essere sontuosa e avvolgente in <em>Menzogna e sortilegio</em>, luminosa e iniziatica nell'<em>Isola di Arturo</em>, plurale e provocatoria nel <em>Mondo salvato dai ragazzini</em>, più accessibile ma strutturalmente complessa in <em>La Storia</em>, franta e dolorosa in <em>Aracoeli</em>. L'unità della poetica non consiste quindi in un solo stile. Sta nell'energia con cui la voce cerca di conferire dignità epica a vite considerate minori.</p>
      <p>Anche il narratore cambia funzione. Talvolta una prima persona ricorda e deforma; altrove una voce ampia conosce più dei personaggi, oppure documenti e sommari interrompono il racconto. La scelta del punto di vista stabilisce che cosa il lettore può sapere e quanto deve fidarsi. Morante usa questa distanza per farci abitare un incanto senza confonderlo del tutto con la verità.</p>
      <p>Morante contamina romanzo, cronaca, canto, teatro, filastrocca, manifesto, documento e favola. Il registro alto può affiancarsi a una voce popolare; la tenerezza al sarcasmo; la narrazione onnisciente a una prospettiva infantile. Questa pluralità impedisce alla realtà di essere monopolizzata da un linguaggio unico. Ma comporta anche un rischio: la voce autoriale può apparire assoluta, emotivamente intensa, talvolta incline a orientare fortemente la pietà del lettore. Le polemiche su <em>La Storia</em> nasceranno anche da questo punto.</p>
      <h3 id="poetica-responsabilita">Pietà senza propaganda</h3>
      <p>Per Morante l'arte ha un compito morale, ma non deve illustrare un programma di partito. La responsabilità dello scrittore consiste nel contrastare l'Irrealtà e restituire presenza a chi il Potere tratta come scarto. Ciò non significa costruire personaggi puramente buoni. La pietà letteraria è attenzione alla vulnerabilità, non assoluzione automatica. Ida, Arturo, Elisa e Manuele sono anche contraddittori, opachi, incapaci di capire se stessi.</p>
      <p>Questa responsabilità riguarda pure il lettore. Il testo non chiede soltanto di apprendere che una vittima ha sofferto; costruisce una durata nella quale siamo costretti a sostare accanto a lei. Ritmo, ripetizione e focalizzazione trasformano così l'emozione in una domanda di giudizio. La commozione vale quando aumenta l'attenzione, non quando la sostituisce con una risposta già pronta.</p>
      <p>Il corpo è uno strumento decisivo di questa responsabilità. Una teoria può giustificare la necessità della guerra; un corpo affamato o colpito mostra ciò che la teoria omette. Allo stesso tempo, il simbolo impedisce che il corpo resti soltanto caso clinico. Epilessia, maternità, sessualità e malattia assumono risonanze storiche e mitiche senza perdere la materialità. Questa poetica verrà messa alla prova da opere molto diverse: la famiglia stregata, l'isola dell'adolescenza, il poema politico, il romanzo delle vittime e il viaggio finale nella memoria.</p>`,
    summary: "La poetica di Morante rifiuta l'alternativa fra documento e fantasia. Il suo realismo comprende corpi e condizioni storiche, ma anche memoria, desiderio e mito. Frammentazione e ciclicità rendono la differenza fra cronologia pubblica e tempo vissuto, senza funzionare come traduzione clinica automatica del trauma. Mito e fiaba isolano conflitti elementari e mostrano sia la potenza sia l'insufficienza delle immagini dei personaggi. L'“alibi” è la facoltà di assumere immaginativamente altre identità. La lingua varia da un'opera all'altra e contamina epica, cronaca, canto, documento e registro popolare. L'arte possiede per Morante una responsabilità morale, ma non deve diventare propaganda. La pietà è attenzione alla vulnerabilità, non idealizzazione. Il corpo rende visibile ciò che le teorie astratte omettono e il simbolo ne amplia il significato.",
    essentials: [
      "Spiegare perché il realismo morantiano comprende anche memoria, mito e percezione.",
      "Collegare tempo narrativo e tempo vissuto senza automatismi clinici.",
      "Definire mito e fiaba come strumenti conoscitivi e ambivalenti.",
      "Comprendere l'alibi come metamorfosi immaginativa dell'io narrante.",
      "Riconoscere la contaminazione di generi e registri nelle diverse opere.",
      "Distinguere responsabilità morale dell'arte e propaganda ideologica.",
      "Analizzare il corpo come luogo in cui storia e simbolo si incontrano."
    ],
    vocabulary: [
      ["Realismo visionario", "Rappresentazione che unisce precisione materiale e intensità simbolica o fantastica."],
      ["Tempo vissuto", "Durata soggettiva in cui ricordo e presente possono sovrapporsi alla cronologia."],
      ["Alibi", "Facoltà poetica di uscire dall'identità fissa e assumere immaginativamente altre vite."],
      ["Contaminazione", "Incontro deliberato fra generi, toni e linguaggi differenti."],
      ["Registro", "Livello linguistico e tonale scelto dalla voce narrativa."],
      ["Pietà", "Attenzione alla vulnerabilità che non elimina contraddizioni e responsabilità."],
      ["Propaganda", "Scrittura subordinata alla dimostrazione di una tesi politica prestabilita."]
    ],
    map: "assets/maps/04-poetica.svg",
    mapAlt: "La visione di Realtà e Irrealtà richiede un realismo visionario; il tempo vissuto produce montaggio e ciclicità; mito e fiaba rivelano immagini profonde; l'alibi permette metamorfosi; registri e generi si contaminano; pietà e corpo contrastano l'astrazione; la poetica confluisce nelle opere.",
    questions: [
      { q: "Che cosa rende visionario il realismo di Morante?", options: ["L'abbandono dei fatti storici", "L'unione di realtà materiale, memoria, desiderio e simbolo", "L'uso esclusivo di narratori fantastici"], correct: 1, explanation: "Il visibile è raccontato insieme alle immagini interiori che gli danno significato.", anchor: "poetica-realismo", recovery: ["Reale su più piani", "Una condizione materiale e il modo in cui viene vissuta fanno parte dello stesso evento narrativo.", "La fame è un bisogno fisico, ma anche paura, vergogna e memoria."] },
      { q: "Perché la narrazione può essere ciclica o frammentata?", options: ["Perché il tempo vissuto non coincide sempre con la cronologia", "Perché Morante ignora l'ordine degli eventi", "Perché ogni personaggio soffre della stessa patologia"], correct: 0, explanation: "Il ritorno del ricordo mostra la durata affettiva degli eventi.", anchor: "poetica-realismo", recovery: ["Due tempi", "Il calendario procede in avanti; la coscienza torna su ciò che non ha concluso.", "Un viaggio presente può riaprire improvvisamente una scena infantile."] },
      { q: "Qual è la funzione del mito nei personaggi?", options: ["Nascondere definitivamente la loro realtà", "Dimostrare che l'infanzia è sempre felice", "Mostrare l'immagine che li governa e le crepe di quell'immagine"], correct: 2, explanation: "Il lettore entra nel sortilegio del personaggio ma ne vede anche il limite.", anchor: "poetica-mito", recovery: ["Dentro e fuori il sortilegio", "La narrazione rende credibile una fantasia e contemporaneamente ne mostra il costo.", "Arturo vede il padre come eroe, mentre gli eventi incrinano il mito."] },
      { q: "Che cos'è l'alibi poetico?", options: ["Una giustificazione per falsificare i documenti", "La possibilità immaginativa di assumere identità diverse", "Una tecnica per evitare il punto di vista dei personaggi"], correct: 1, explanation: "L'alibi libera temporaneamente l'io dai propri confini attraverso la metamorfosi narrativa.", anchor: "poetica-mito", recovery: ["Uscire dall'io", "Immaginare un'altra vita non significa possederla, ma tentare di ascoltarla.", "Una narratrice adulta può assumere la prospettiva vulnerabile di un bambino."] },
      { q: "Come si distingue la pietà dalla propaganda?", options: ["La pietà vede la vulnerabilità senza ridurre il personaggio a esempio di una tesi", "La pietà evita qualunque giudizio morale", "La propaganda usa sempre uno stile difficile"], correct: 0, explanation: "L'attenzione resta aperta alle contraddizioni, mentre la propaganda assegna funzioni prestabilite.", anchor: "poetica-responsabilita", recovery: ["Persona prima della tesi", "Un personaggio credibile eccede il messaggio che potrebbe rappresentare.", "Ida è vittima della storia, ma conserva paure e scelte non idealizzate."] }
    ]
  },
  {
    id: "opere",
    number: "05",
    title: "Le opere più significative",
    subtitle: "Famiglie stregate, isole, ragazzini e vittime della Storia",
    question: "In quali forme la poetica di Morante diventa personaggio, conflitto e struttura?",
    color: "#4d6280",
    lesson: `
      <h3 id="opere-menzogna"><em>Menzogna e sortilegio</em>: il romanzo della famiglia narrata</h3>
      <p>Pubblicato nel 1948 e vincitore del Premio Viareggio, <em>Menzogna e sortilegio</em> mette in scena Elisa, narratrice che ricostruisce una genealogia familiare dominata da passioni, fantasie e autoinganni. La famiglia non è soltanto un gruppo di persone: è una macchina narrativa. Ognuno ama immagini, status e racconti che spesso sostituiscono l'altro reale. La menzogna assume perciò una forma affettiva: protegge dalla mediocrità e insieme impedisce relazioni autentiche.</p>
      <p>Il romanzo usa una lingua ampia, teatrale e deliberatamente inattuale rispetto alla sobrietà neorealista. Il sortilegio opera anche sul lettore, attirato dalla forza delle passioni mentre ne riconosce la distruttività. La memoria di Elisa non è un documento neutrale: ordina, giudica e tenta di liberarsi dalle storie ricevute. L'opera mette alla prova il nesso fra identità e racconto senza autorizzare una lettura puramente autobiografica.</p>
      <h3 id="opere-arturo"><em>L'isola di Arturo</em>: educazione e caduta del mito</h3>
      <p>Nel 1957 <em>L'isola di Arturo</em> ottiene il Premio Strega. Arturo cresce a Procida trasformando l'isola in un regno e il padre Wilhelm in un eroe. La prima persona retrospettiva conserva l'incanto del ragazzo e, nello stesso tempo, lascia percepire la coscienza adulta che ricorda. L'isola è protezione e prigione; il mito paterno alimenta l'identità di Arturo ma deve spezzarsi perché la crescita abbia inizio.</p>
      <p>Il romanzo di formazione non conduce a una maturità pacificata. La conoscenza arriva attraverso gelosia, desiderio, vergogna e disillusione. Nunziata e Wilhelm resistono alle immagini costruite dal ragazzo, costringendolo a scoprire che gli altri hanno desideri propri. La partenza finale non cancella l'isola: mostra che crescere significa portare con sé la perdita del proprio assoluto infantile.</p>
      <h3 id="opere-ragazzini"><em>Il mondo salvato dai ragazzini</em>: forma aperta e rivolta</h3>
      <p>La raccolta del 1968 rompe i confini tradizionali: poesia, canzone, manifesto, teatro e gioco tipografico convivono. I ragazzini non sono soltanto giovani per età. Sono figure di una vitalità non normalizzata, capace di opporsi all'Irrealtà adulta. La distinzione fra Felici Pochi e Infelici Molti organizza una provocazione morale contro consumo, ideologia e obbedienza.</p>
      <p>La forma aperta è parte del significato. Un messaggio contro le gerarchie non può parlare con una sola voce autoritaria; deve moltiplicare ritmi, generi e destinatari. Eppure il titolo non garantisce una salvezza storica. La festa linguistica convive con perdita e morte. L'utopia resta fragile, esposta alla macchina del Potere che tenta di riassorbirla.</p>
      <h3 id="opere-storia"><em>La Storia</em>: l'epica degli esclusi e la controversia</h3>
      <p>Pubblicato nel 1974 in edizione economica per raggiungere un pubblico ampio, <em>La Storia</em> racconta Roma durante e dopo la Seconda guerra mondiale attraverso Ida Ramundo, i figli Nino e Useppe e una costellazione di esseri marginali. Ai sommari degli eventi mondiali segue la vita di chi non decide nulla. Questa struttura rende visibile la sproporzione fra il linguaggio della storia pubblica e la vulnerabilità individuale.</p>
      <p>Useppe concentra innocenza, percezione poetica ed esposizione al dolore; la sua epilessia non è una semplice allegoria, ma un dato corporeo che acquista risonanza storica e simbolica. Il successo fu enorme e la critica si divise. Alcuni videro nel romanzo una potenza epica e una difesa radicale delle vittime; altri gli rimproverarono sentimentalismo, populismo o una visione immobile della storia, incapace di riconoscere conflitto sociale e possibilità di cambiamento. Una lettura matura non deve scegliere per devozione. La forza emotiva del libro è indiscutibile; resta legittimo interrogare il modo in cui orienta la pietà e rappresenta l'azione politica.</p>
      <h3 id="opere-aracoeli"><em>Aracoeli</em>: memoria, corpo e ritorno impossibile</h3>
      <p>Nell'ultimo romanzo, pubblicato nel 1982, Manuele viaggia in Andalusia cercando il luogo d'origine della madre Aracoeli. Il viaggio geografico viene continuamente interrotto da memorie, fantasie e frammenti corporei. L'oggetto cercato non può essere recuperato: il paradiso materno è già perduto e la memoria non lo ricompone senza deformarlo. L'identità di Manuele, il suo disagio, il desiderio e l'esperienza della differenza sessuale resistono a una diagnosi unica.</p>
      <p><em>Aracoeli</em> porta al limite il progetto morantiano. Il mito materno non salva; la parola non ripara pienamente; il viaggio non diventa formazione. Eppure il romanzo non è un semplice fallimento della speranza. La sua forma franta testimonia ciò che non può essere pacificato. Dalla genealogia incantata del primo romanzo al ritorno impossibile dell'ultimo, le opere mostrano che raccontare non restituisce l'innocenza, ma può impedire al Potere e all'oblio di avere l'ultima parola.</p>`,
    summary: "Le opere principali mettono alla prova la stessa tensione in forme diverse. Menzogna e sortilegio ricostruisce una famiglia governata da passioni e autoinganni attraverso la memoria non neutrale di Elisa. L'isola di Arturo narra la formazione come caduta del mito paterno e perdita dell'assoluto infantile. Il mondo salvato dai ragazzini contamina poesia, manifesto e gioco per opporre una vitalità anarchica all'Irrealtà. La Storia affianca eventi mondiali e vite marginali, creando un'epica degli esclusi; la sua grande forza emotiva generò anche accuse di sentimentalismo e immobilismo politico. Aracoeli mette in scena un ritorno impossibile verso la madre e una memoria incapace di restaurare il paradiso perduto. Il percorso non conduce a una salvezza certa: la narrazione non ripara tutto, ma impedisce che persone e ferite siano completamente cancellate.",
    essentials: [
      "Analizzare Menzogna e sortilegio come genealogia costruita da memoria e autoinganno.",
      "Spiegare la formazione di Arturo come necessaria caduta del mito paterno.",
      "Collegare la forma plurale del Mondo salvato dai ragazzini alla rivolta antigerarchica.",
      "Mostrare la struttura a due scale di La Storia: eventi pubblici e vite marginali.",
      "Ricostruire con equilibrio la controversia critica sul romanzo del 1974.",
      "Interpretare Aracoeli come viaggio della memoria e ritorno impossibile.",
      "Riconoscere l'evoluzione dal sortilegio familiare alla testimonianza dell'irreparabile."
    ],
    vocabulary: [
      ["Genealogia narrativa", "Storia familiare ricostruita da una voce che seleziona e interpreta il passato."],
      ["Romanzo di formazione", "Racconto del passaggio verso l'età adulta attraverso prove e trasformazioni."],
      ["Forma aperta", "Opera che attraversa generi e registri senza chiudersi in una struttura unica."],
      ["Epica degli esclusi", "Racconto ampio che attribuisce rilievo storico a vite prive di potere."],
      ["Sentimentalismo", "Uso dell'emozione percepito come eccessivo o come orientamento troppo diretto del lettore."],
      ["Ricezione", "Insieme delle reazioni di pubblico e critica che accompagnano un'opera."],
      ["Memoria frammentata", "Ricordo che ritorna per immagini e scarti anziché come cronaca continua."]
    ],
    map: "assets/maps/05-opere.svg",
    mapAlt: "Menzogna e sortilegio trasforma la famiglia in racconto; L'isola di Arturo mette in crisi il mito paterno; Il mondo salvato dai ragazzini traduce la rivolta in forma aperta; La Storia affianca cronologia pubblica e vittime; Aracoeli porta la memoria verso un ritorno impossibile; tutte le opere resistono alla cancellazione senza promettere una salvezza certa.",
    questions: [
      { q: "Che funzione ha la memoria di Elisa in Menzogna e sortilegio?", options: ["Registra neutralmente tutti i fatti", "Ricostruisce e giudica le narrazioni familiari da cui tenta di liberarsi", "Elimina dalla storia ogni forma di menzogna"], correct: 1, explanation: "Elisa è una narratrice coinvolta: il suo racconto è insieme eredità e tentativo di distacco.", anchor: "opere-menzogna", recovery: ["Memoria che costruisce", "Ricordare significa sempre selezionare e dare ordine.", "Elisa eredita le versioni familiari e le ricompone dal proprio punto di vista."] },
      { q: "Che cosa significa crescere per Arturo?", options: ["Conservare intatto il mito del padre", "Abbandonare ogni legame con l'isola", "Scoprire che gli altri non coincidono con le sue immagini"], correct: 2, explanation: "La formazione nasce dalla rottura dell'assoluto infantile e dal riconoscimento dell'alterità.", anchor: "opere-arturo", recovery: ["Caduta del mito", "L'altro diventa reale quando smette di essere il personaggio della nostra fantasia.", "Wilhelm non corrisponde all'eroe costruito da Arturo."] },
      { q: "Perché Il mondo salvato dai ragazzini usa molti generi?", options: ["Per tradurre la rivolta contro le gerarchie in una forma plurale", "Per nascondere l'assenza di un tema", "Per imitare un manuale scolastico"], correct: 0, explanation: "Canzone, manifesto e teatro impediscono a una sola voce di monopolizzare il messaggio.", anchor: "opere-ragazzini", recovery: ["Forma e rivolta", "Una poetica antigerarchica cerca anche strutture non rigide.", "Il passaggio dal canto al manifesto cambia il rapporto con il lettore."] },
      { q: "Qual è la struttura decisiva di La Storia?", options: ["La separazione completa fra cronologia e personaggi", "L'alternanza fra eventi mondiali e vite prive di potere", "La biografia di un comandante militare"], correct: 1, explanation: "Le due scale fanno sentire la pressione del corso pubblico sulle esistenze marginali.", anchor: "opere-storia", recovery: ["Due scale narrative", "La cronologia generale acquisisce peso quando incontra corpi e case.", "Un anno di guerra viene seguito dall'esperienza quotidiana di Ida e Useppe."] },
      { q: "Perché la ricezione di La Storia resta discutibile?", options: ["Perché il libro non ebbe lettori", "Perché la critica concordò sul suo valore politico", "Perché la potenza verso le vittime convive con dubbi su sentimentalismo e immobilismo"], correct: 2, explanation: "Il conflitto critico riguarda proprio il rapporto fra pietà, forma e interpretazione della storia.", anchor: "opere-storia", recovery: ["Una forza controversa", "Un'opera può essere emotivamente potente e insieme sollevare obiezioni politiche.", "La centralità delle vittime commuove, ma può sembrare ridurre lo spazio dell'azione collettiva."] },
      { q: "Che cosa fallisce nel viaggio di Manuele?", options: ["Il progetto di ricostruire integralmente il paradiso materno", "La possibilità di raggiungere materialmente l'Andalusia", "La conoscenza di ogni evento politico"], correct: 0, explanation: "La memoria non restituisce la madre né un'identità integra; il ritorno resta impossibile.", anchor: "opere-aracoeli", recovery: ["Ritorno senza restaurazione", "Visitare un'origine non riporta il passato alla vita.", "Il luogo cercato riapre frammenti, ma non ricompone Aracoeli."] }
    ]
  },
  {
    id: "conclusione",
    number: "06",
    title: "Conclusione",
    subtitle: "Guardare la Storia con gli occhi di chi la subisce",
    question: "Quale eredità lascia Morante e quale sua tensione resta aperta?",
    color: "#80693d",
    lesson: `
      <h3 id="conclusione-catena">Dalla realtà ricevuta alla forma del romanzo</h3>
      <p>Il percorso può ora essere ricomposto. Morante riceve un Novecento in cui fascismo, guerra e ideologie parlano il linguaggio delle masse, mentre neorealismo e ricostruzione chiedono alla letteratura di testimoniare. Le fratture della vita — origini familiari complesse, autonomia, guerra, relazioni e perdite — non producono automaticamente i libri, ma rendono più urgente la domanda su identità, innocenza e memoria. Da qui emerge un'immagine del mondo fondata sul conflitto fra Realtà e Irrealtà: da una parte la vita singolare, dall'altra le astrazioni del Potere e gli idoli privati.</p>
      <p>La poetica risponde unendo ciò che le scuole tendono a separare. Documento e mito, corpo e simbolo, romanzo popolare ed epica, voce infantile e giudizio storico diventano strumenti di una stessa ricerca. Le opere verificano la risposta: la famiglia è sortilegio, l'isola è mito destinato a incrinarsi, i ragazzini incarnano una rivolta fragile, Ida e Useppe misurano lo scandalo della storia, Manuele scopre che la memoria non restituisce il paradiso perduto.</p>
      <h3 id="conclusione-eredita">Un'eredità letteraria e morale</h3>
      <p>L'eredità di Morante non consiste in una formula stilistica da imitare. La sua lingua cambia troppo perché si possa ridurla a un modello uniforme. Resta invece un criterio di attenzione: una grande narrazione deve rispondere davanti alla più piccola delle vite che coinvolge. Questo principio mette in crisi sia la propaganda sia una letteratura chiusa nel puro gioco formale. Il romanzo può inventare liberamente, ma la libertà trova una misura nella presenza dell'altro.</p>
      <p>Morante allarga inoltre la possibilità dell'epica moderna. Al centro non pone il condottiero vittorioso, ma bambini, donne impaurite, animali e persone segnate dalla dipendenza o dalla perdita. Non li rende automaticamente santi: attribuisce loro il diritto alla complessità e alla grandezza narrativa. In questo modo storia, maternità, infanzia e marginalità cessano di essere temi minori e diventano luoghi da cui giudicare un'intera civiltà.</p>
      <p>Conta anche la sua difesa dell'ambizione del romanzo. In un secolo che spesso oppone sperimentazione e racconto, costruisce opere ampie, leggibili e insieme difficili da classificare. Non rinuncia alla trama, all'emozione o alla partecipazione del pubblico, ma le sottopone a un controllo critico continuo. Un'opera può rivolgersi a molti senza semplificare il conflitto e può usare forme popolari senza consegnarsi alla propaganda o al consumo passivo.</p>
      <h3 id="conclusione-limiti">Le tensioni che non vanno pacificate</h3>
      <p>Una lettura critica deve conservare anche i problemi. La contrapposizione fra Felici Pochi e Infelici Molti rischia, se irrigidita, di trasformarsi in un'altra gerarchia. La visione della Storia come ripetizione del Potere difende le vittime, ma può ridurre la capacità umana di organizzarsi e cambiare le istituzioni. La centralità dell'innocenza può far sembrare più autentico chi non agisce rispetto a chi assume responsabilità politiche. Sono obiezioni serie, non confutazioni definitive.</p>
      <p>Anche la potenza emotiva di <em>La Storia</em> resta ambivalente. La pietà porta il lettore vicino a Ida e Useppe, ma una narrazione molto orientata può ridurre lo spazio del giudizio autonomo. E tuttavia l'accusa di sentimentalismo può diventare un modo per svalutare emozioni, maternità e vulnerabilità considerate indegne della “grande” letteratura. La discussione migliore tiene insieme entrambi i rischi: manipolare il dolore e, all'opposto, rifiutarlo per difendere una freddezza scambiata per rigore.</p>
      <h3 id="conclusione-oggi">Morante nel presente: chi paga le nostre astrazioni?</h3>
      <p>Nel presente le forme del Potere non coincidono con quelle del Novecento, ma la domanda morantiana conserva forza. Quando parliamo di crescita, sicurezza, emergenza, mercato o identità nazionale, chi scompare dentro queste parole? Quali corpi pagano una decisione presentata come inevitabile? Morante non offre un programma amministrativo e non basta per risolvere i conflitti politici. Offre però un criterio di sospetto verso ogni discorso che domanda vittime senza pronunciarne i nomi.</p>
      <p>La sua fiducia nei ragazzini non va trasformata in culto ingenuo della giovinezza. Indica la necessità di uno sguardo capace di sorprendersi prima di accettare l'ordine esistente come naturale. Anche l'arte svolge questa funzione solo se resiste ai propri sortilegi: deve creare immagini potenti e poi permetterci di vederne la costruzione. La letteratura salva il mondo non perché impedisce la morte, ma perché contesta l'annullamento simbolico delle vite.</p>
      <h3 id="conclusione-domanda">La domanda che resta aperta</h3>
      <p>Alla fine rimane una tensione non risolta: si può difendere l'innocenza senza trasformarla in impotenza? Morante mostra con radicalità la colpa dei sistemi che schiacciano chi non ha potere. Ma una comunità giusta deve anche agire, organizzarsi, scegliere e talvolta esercitare autorità limitata. Il rifiuto di ogni dominio è una bussola morale; non è ancora una politica completa.</p>
      <p>Proprio qui l'opera resta viva. Non ci consegna una dottrina da ripetere, ma un conflitto da abitare: azione senza sacrificio degli innocenti, immaginazione senza menzogna, amore senza possesso, memoria senza culto del passato. Guardare con gli occhi degli ultimi non significa parlare al loro posto con certezza assoluta. Significa obbligare ogni nostra idea a incontrare la vita che potrebbe ferire. È una richiesta scomoda, e la letteratura di Morante continua a formularla senza addomesticarla.</p>`,
    summary: "Il percorso conduce dal Novecento delle masse alle vite che ne subiscono il peso. Le fratture biografiche rendono urgenti identità e perdita senza determinare i testi. La visione oppone la Realtà singolare all'Irrealtà prodotta dal Potere e dagli idoli; la poetica unisce documento, mito, corpo e simbolo. Le opere conferiscono dignità epica a bambini, donne, animali ed esclusi. L'eredità di Morante è un criterio: ogni grande narrazione deve rispondere delle vite che coinvolge. Restano tensioni reali: Felici Pochi e Infelici Molti possono irrigidirsi; la critica della Storia può oscurare l'azione politica; la pietà può diventare orientamento eccessivo, mentre l'accusa di sentimentalismo può svalutare la vulnerabilità. La domanda finale è se si possa difendere l'innocenza senza trasformarla in impotenza. Morante non offre una dottrina, ma costringe l'azione a misurarsi con chi potrebbe ferire.",
    essentials: [
      "Ricostruire la catena fra contesto, fratture, visione, poetica e opere.",
      "Definire l'eredità di Morante come criterio di attenzione alle vite singolari.",
      "Spiegare in che senso l'autrice rinnova l'epica moderna attraverso gli esclusi.",
      "Discutere i limiti dell'antitesi fra Felici Pochi e Infelici Molti.",
      "Valutare con equilibrio potenza emotiva e rischio di sentimentalismo.",
      "Applicare al presente la domanda su chi paghi il costo delle astrazioni.",
      "Argomentare la tensione fra difesa dell'innocenza e necessità dell'azione."
    ],
    vocabulary: [
      ["Eredità", "Problema, criterio o forma che un'opera consegna a lettori e scrittori successivi."],
      ["Epica moderna", "Racconto di ampiezza collettiva che può porre al centro anche vite senza potere."],
      ["Vulnerabilità", "Esposizione di un essere vivente alla ferita, alla dipendenza e alla perdita."],
      ["Ambivalenza", "Compresenza di possibilità opposte nello stesso valore o procedimento."],
      ["Impotenza", "Condizione di chi non riesce a trasformare il proprio giudizio in azione efficace."],
      ["Autorità limitata", "Potere sottoposto a regole, controllo e responsabilità verso le persone."],
      ["Annullamento simbolico", "Cancellazione di una vita dal racconto e dalla memoria anche quando è realmente esistita."]
    ],
    map: "assets/maps/06-conclusione.svg",
    mapAlt: "Il mondo delle masse mette in crisi le vite singolari; le fratture rendono urgenti identità e memoria; Realtà e Irrealtà organizzano la visione; documento e mito formano la poetica; le opere costruiscono un'epica degli esclusi; l'eredità chiede chi paghi le astrazioni; la domanda finale unisce innocenza e azione.",
    questions: [
      { q: "Qual è il criterio centrale dell'eredità morantiana?", options: ["Ogni grande narrazione deve rispondere delle vite concrete che coinvolge", "Ogni romanzo deve usare bambini come protagonisti", "Ogni scrittore deve rifiutare la storia contemporanea"], correct: 0, explanation: "La grande scala viene verificata dalla presenza irriducibile del singolo.", anchor: "conclusione-eredita", recovery: ["Una misura morale", "Un discorso collettivo resta astratto finché non considera i suoi effetti sulle persone.", "Una politica di sicurezza va valutata anche dalla vita di chi viene fermato o escluso."] },
      { q: "In che senso Morante rinnova l'epica?", options: ["Elimina ogni evento collettivo", "Attribuisce grandezza narrativa a figure normalmente marginali", "Ripropone senza cambiamenti gli eroi antichi"], correct: 1, explanation: "Bambini, donne e animali diventano misure della storia comune.", anchor: "conclusione-eredita", recovery: ["Eroi senza potere", "L'epica moderna può raccontare chi subisce gli eventi, non soltanto chi li guida.", "Useppe acquista rilievo universale pur non controllando nulla della guerra."] },
      { q: "Quale rischio contiene l'antitesi Felici Pochi/Infelici Molti?", options: ["Cancellare ogni distinzione morale", "Ridurre l'importanza dell'infanzia", "Irrigidirsi in una nuova gerarchia fra puri e compromessi"], correct: 2, explanation: "Una figura polemica diventa ingiusta se classifica una volta per tutte le persone.", anchor: "conclusione-limiti", recovery: ["L'antitesi sotto critica", "Anche una distinzione nata contro il Potere può diventare esclusiva.", "Chi oggi resiste può domani conformarsi, e viceversa."] },
      { q: "Come va affrontata la controversia sul sentimentalismo?", options: ["Negando che il romanzo orienti le emozioni", "Rifiutando ogni emozione come manipolazione", "Tenendo insieme il rischio di guidare la pietà e quello di svalutare la vulnerabilità"], correct: 2, explanation: "Il giudizio critico deve esaminare la tecnica emotiva senza disprezzare il dolore narrato.", anchor: "conclusione-limiti", recovery: ["Emozione e rigore", "Commuovere non è automaticamente manipolare; occorre vedere come il testo costruisce l'effetto.", "La morte di un bambino può essere narrata con forza e insieme richiedere analisi formale."] },
      { q: "Che uso contemporaneo possiamo fare della domanda morantiana?", options: ["Rifiutare qualunque istituzione", "Chiedere chi paga concretamente parole come progresso o sicurezza", "Sostituire la politica con la poesia"], correct: 1, explanation: "Morante offre un controllo morale delle astrazioni, non un programma amministrativo completo.", anchor: "conclusione-oggi", recovery: ["Dalle parole ai corpi", "Un concetto pubblico va tradotto nelle sue conseguenze visibili.", "Dire 'emergenza' non basta: bisogna osservare chi perde diritti o protezione."] },
      { q: "Quale domanda conclude il percorso?", options: ["Se si possa difendere l'innocenza senza ridurla all'impotenza", "Se ogni fantasia sia falsa", "Se la storia possa essere cancellata dai romanzi"], correct: 0, explanation: "La compassione deve misurarsi con il problema dell'azione e della responsabilità.", anchor: "conclusione-domanda", recovery: ["Innocenza e azione", "Proteggere chi è vulnerabile richiede anche decisioni e organizzazione.", "Una comunità deve limitare il potere senza rinunciare a intervenire contro la violenza."] }
    ]
  }
];

window.FINAL_QUIZ = {
  title: "Verifica finale — Elsa Morante in sei movimenti",
  questions: [
    { q: "Quale tensione fondamentale nasce dal mondo precedente?", options: ["Tra poesia e teatro", "Tra realtà storica e verità che l'immaginazione può rivelare", "Tra Roma e la provincia"], correct: 1, explanation: "Morante cerca una forma che tenga insieme fatti, corpi, mito e vita interiore.", anchor: "mondo-tensione", recovery: ["La doppia esigenza", "Il documento non esaurisce l'esperienza e la fantasia non è automaticamente vera.", "La guerra è insieme cronologia pubblica e paura vissuta."] },
    { q: "Che cosa insegnano le fratture biografiche?", options: ["Che ogni personaggio coincide con Morante", "Che i romanzi sono confessioni senza forma", "Che le esperienze rendono urgenti certe domande senza determinare i testi"], correct: 2, explanation: "Biografia e opera dialogano attraverso elaborazione e scelte formali, non per causa automatica.", anchor: "fratture-metodo", recovery: ["Nesso prudente", "Un fatto di vita offre un contesto interpretativo, non una spiegazione totale.", "L'origine familiare rende leggibile il tema della genealogia senza causare il romanzo."] },
    { q: "Quale immagine del mondo emerge?", options: ["La vita singolare resiste alle astrazioni del Potere e agli idoli privati", "Ogni fantasia appartiene all'Irrealtà", "La storia garantisce necessariamente il progresso"], correct: 0, explanation: "Realtà e Irrealtà distinguono attenzione alla vita e riduzione a ruolo o immagine.", anchor: "immagine-realta", recovery: ["Realtà contro riduzione", "La singolarità viene negata sia dalla categoria politica sia dall'idealizzazione.", "Una persona non coincide né con l'etichetta di nemico né con quella di eroe perfetto."] },
    { q: "Quale poetica risponde a questa visione?", options: ["Una cronaca priva di simboli", "Una sola lingua uniforme per tutte le opere", "Un realismo visionario che contamina documento, mito e registri"], correct: 2, explanation: "La pluralità formale permette di rappresentare insieme condizioni materiali e immagini interiori.", anchor: "poetica-forme", recovery: ["Molte forme per il reale", "Nessun registro possiede da solo tutta la realtà.", "La cronaca storica può affiancarsi alla prospettiva infantile e al simbolo."] },
    { q: "Quale opera affianca esplicitamente eventi mondiali e vite marginali?", options: ["L'isola di Arturo", "La Storia", "Aracoeli"], correct: 1, explanation: "I sommari storici e la vicenda di Ida, Nino e Useppe costruiscono due scale in conflitto.", anchor: "opere-storia", recovery: ["Storia e microstoria", "La struttura alterna ciò che accade nel mondo e ciò che subiscono i personaggi.", "Una data bellica precede la scena domestica in cui se ne sente il costo."] },
    { q: "Quale problema resta aperto alla fine?", options: ["Difendere l'innocenza senza trasformarla in impotenza", "Dimostrare che il Potere è sempre necessario", "Scegliere una volta per tutte fra verità e immaginazione"], correct: 0, explanation: "La compassione deve incontrare la necessità di agire, organizzare e assumere responsabilità.", anchor: "conclusione-domanda", recovery: ["Dalla pietà all'azione", "Proteggere la vulnerabilità richiede interventi, ma senza sacrificare le persone a un'astrazione.", "Limitare un'autorità non significa rinunciare a fermare la violenza."] }
  ]
};
