(()=>{
  'use strict';
  const STORAGE='gbprof-pavese-v1';
  const fresh=()=>({completed:[],last:0,notes:'',font:'normal',attempts:{},attemptHistory:{},retests:{}});
  let state=load();
  let current=0;
  const $=(selector,root=document)=>root.querySelector(selector);
  const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const home=$('#home'),lessonView=$('#lessonView'),nav=$('#sectionNav'),cards=$('#journeyCards');

  function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return fresh()}}
  function save(){localStorage.setItem(STORAGE,JSON.stringify(state));updateProgress()}
  function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
  function setPanel(panel){$$('.tabs button',lessonView).forEach(b=>{const active=b.dataset.panel===panel;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$$('.panel',lessonView).forEach(p=>p.hidden=p.dataset.panel!==panel)}
  function updateProgress(){const done=new Set(state.completed);const pct=Math.round(done.size/LESSONS.length*100);$('#progressBar').value=done.size;$('#progressText').value=`${pct}%`;$$('.nav-item').forEach((el,i)=>el.classList.toggle('done',done.has(i)));$$('.journey-card').forEach((el,i)=>el.classList.toggle('done',done.has(i)))}
  function buildHome(){
    cards.innerHTML=LESSONS.map((s,i)=>`<button class="journey-card" type="button" data-open-section="${i}"><span class="number">${i+1}</span><h2>${s.title}</h2><p>${s.card}</p></button>`).join('');
    nav.innerHTML=LESSONS.map((s,i)=>`<button class="nav-item" type="button" data-open-section="${i}"><span class="nav-number">${i+1}</span><span><strong>${s.short}</strong><small>${s.title}</small></span></button>`).join('');
    $('#sourceList').innerHTML=`<p>I cinque lavori forniti sono stati usati come base perché coerenti e già corredati di fonti. Sono state attenuate le causalità psicologiche non dimostrabili e sono stati verificati cronologia, opere e contesto con fonti istituzionali e universitarie.</p><ul>${SOURCES.map(s=>`<li><a href="${s.url}" target="_blank" rel="noopener">${s.label}</a> — ${s.use}</li>`).join('')}</ul><p><strong>Metodo:</strong> i dati biografici non vengono trattati come cause automatiche delle opere. Le formulazioni interpretative sono presentate come nessi di lettura, non come diagnosi dell'autore.</p>`;
  }
  function glossaryHtml(items){return `<dl class="glossary">${items.map(x=>`<div><dt>${x[0]}</dt><dd>${x[1]}</dd></div>`).join('')}</dl>`}
  function renderSection(index){
    current=Math.max(0,Math.min(LESSONS.length-1,index));state.last=current;save();const s=LESSONS[current];
    home.classList.remove('active');lessonView.classList.add('active');
    lessonView.innerHTML=`<header class="lesson-head"><div><p class="eyebrow">Movimento ${current+1} di 6</p><h1>${s.title}</h1><p class="question">${s.question}</p></div><span class="section-mark" aria-hidden="true">0${current+1}</span></header>
      <div class="tabs" role="tablist" aria-label="Materiali della sezione"><button role="tab" data-panel="lesson" aria-selected="true">Lezione</button><button role="tab" data-panel="summary" aria-selected="false" tabindex="-1">Sintesi</button><button role="tab" data-panel="essentials" aria-selected="false" tabindex="-1">Irrinunciabili</button><button role="tab" data-panel="glossary" aria-selected="false" tabindex="-1">Vocabolario</button><button role="tab" data-panel="map" aria-selected="false" tabindex="-1">Mappa</button><button role="tab" data-panel="quiz" aria-selected="false" tabindex="-1">Verifica</button></div>
      <section class="panel" data-panel="lesson"><div class="lesson-copy">${s.lesson}<div class="bridge"><strong>Ponte:</strong> ${s.bridge}</div></div></section>
      <section class="panel" data-panel="summary" hidden><div class="summary-card"><p class="eyebrow">In circa due minuti</p><h2>La traiettoria essenziale</h2><p>${s.summary}</p></div></section>
      <section class="panel" data-panel="essentials" hidden><div class="essentials"><p class="eyebrow">Ciò che devi saper spiegare</p><h2>Saperi irrinunciabili</h2><ol>${s.essentials.map(x=>`<li>${x}</li>`).join('')}</ol></div></section>
      <section class="panel" data-panel="glossary" hidden>${glossaryHtml(s.glossary)}</section>
      <section class="panel" data-panel="map" hidden><figure class="map-wrap"><img src="${s.map}" alt="${escapeHtml(s.mapAlt)}"><figcaption>La mappa nomina le relazioni della sezione. Puoi ingrandirla con il gesto di zoom del dispositivo.</figcaption></figure></section>
      <section class="panel" data-panel="quiz" hidden>${quizHtml(current)}</section>
      <footer class="lesson-footer"><button class="button" type="button" data-prev ${current===0?'disabled':''}>← Precedente</button><button class="button ${state.completed.includes(current)?'':'primary'}" type="button" data-complete>${state.completed.includes(current)?'Completata ✓':'Segna come completata'}</button><button class="button primary" type="button" data-next>${current===LESSONS.length-1?'Torna alla copertina':'Successiva →'}</button></footer>`;
    $$('.nav-item').forEach((el,i)=>el.classList.toggle('current',i===current));bindLesson();closeDrawers();location.hash=`section-${current+1}`;mainFocus();
  }
  function quizHtml(index){const prior=state.attempts[index];return `<form class="quiz-form" data-quiz="${index}"><div class="quiz-intro"><p class="eyebrow">Verifica formativa</p><h2>Controlla i nessi, non la memoria meccanica</h2><p>Cinque domande, tre opzioni, una sola corretta. Formula: <strong>voto = max(1, arrotonda(percentuale × 10))</strong>. Dopo la correzione vedrai soltanto gli errori e il recupero necessario.</p></div>${LESSONS[index].quiz.map((q,qi)=>`<div class="quiz-card"><fieldset><legend>${qi+1}. ${q.q}</legend>${q.options.map((o,oi)=>`<label class="option"><input type="radio" name="q${qi}" value="${oi}" required><span><strong>${String.fromCharCode(65+oi)}.</strong> ${o}</span></label>`).join('')}<div class="feedback" data-feedback="${qi}" hidden></div></fieldset></div>`).join('')}<div class="quiz-actions"><button class="button primary" type="submit">Correggi il test</button>${prior?'<button class="button" type="button" data-show-recovery>Rivedi l’ultimo recupero</button>':''}</div><div data-result></div><div data-recovery></div></form>`}
  function bindLesson(){
    $$('.tabs button',lessonView).forEach(btn=>btn.addEventListener('click',()=>setPanel(btn.dataset.panel)));
    $('.tabs',lessonView).addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;const buttons=$$('.tabs button',lessonView),pos=buttons.indexOf(document.activeElement),next=(pos+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next].focus();setPanel(buttons[next].dataset.panel)});
    $('[data-prev]',lessonView).addEventListener('click',()=>renderSection(current-1));
    $('[data-next]',lessonView).addEventListener('click',()=>current===LESSONS.length-1?showHome():renderSection(current+1));
    $('[data-complete]',lessonView).addEventListener('click',e=>{if(!state.completed.includes(current))state.completed.push(current);save();e.currentTarget.textContent='Completata ✓';e.currentTarget.classList.remove('primary');toast('Movimento completato')});
    const form=$('[data-quiz]',lessonView);form.addEventListener('submit',gradeQuiz);const show=$('[data-show-recovery]',form);if(show)show.addEventListener('click',()=>renderRecovery(current,state.attempts[current].wrong));
  }
  function gradeQuiz(event){event.preventDefault();const form=event.currentTarget,index=Number(form.dataset.quiz),quiz=LESSONS[index].quiz,data=new FormData(form),answers=quiz.map((_,i)=>Number(data.get(`q${i}`))),wrong=[];quiz.forEach((q,i)=>{const ok=answers[i]===q.answer;const feedback=$(`[data-feedback="${i}"]`,form);feedback.hidden=false;feedback.className=`feedback ${ok?'correct':'wrong'}`;feedback.innerHTML=`<strong>${ok?'Corretto':'Da rivedere'}.</strong> ${q.explain}`;if(!ok)wrong.push(i)});const correct=quiz.length-wrong.length,pct=Math.round(correct/quiz.length*100),vote=Math.max(1,Math.round(pct/10));const attempt={date:new Date().toISOString(),answers,wrong,correct,pct,vote};if(state.attempts[index])state.attemptHistory[index]=[...(state.attemptHistory[index]||[]),state.attempts[index]];state.attempts[index]=attempt;save();const result=$('[data-result]',form);result.innerHTML=`<div class="result ${wrong.length?'bad':''}"><strong>${correct}/${quiz.length} · ${pct}% · voto ${vote}/10</strong><p>${wrong.length?`Hai ${wrong.length} ${wrong.length===1?'nesso da riparare':'nessi da riparare'}. Sotto compaiono esclusivamente i tuoi errori.`:'Tutti i nessi sono solidi. Puoi segnare la sezione come completata.'}</p></div>`;renderRecovery(index,wrong);result.scrollIntoView({behavior:'smooth',block:'center'})}
  function renderRecovery(index,wrong){const target=$('[data-recovery]',lessonView);if(!wrong.length){target.innerHTML='';return}target.innerHTML=`<div class="recovery-list"><h2>Recupero mirato</h2>${wrong.map(qi=>{const r=LESSONS[index].quiz[qi].recovery;return `<section class="recovery-card"><p class="eyebrow">Errore ${qi+1} · ancora: ${r.anchor}</p><h3>${r.concept}</h3><p>${r.clarification}</p><p><strong>Esempio dalla lezione:</strong> ${r.example}</p><div class="micro-check" data-micro="${qi}"><p><strong>Nuova domanda:</strong> ${r.q}</p>${r.options.map((o,oi)=>`<label class="option"><input type="radio" name="micro-${qi}" value="${oi}"><span>${o}</span></label>`).join('')}<button class="button" type="button" data-check-micro="${qi}">Controlla</button><p class="status" data-micro-status="${qi}" role="status"></p></div></section>`}).join('')}<button class="button primary" type="button" data-retest>Rifai soltanto le domande sbagliate</button><div data-retest-area></div></div>`;$$('[data-check-micro]',target).forEach(btn=>btn.addEventListener('click',()=>{const qi=Number(btn.dataset.checkMicro),r=LESSONS[index].quiz[qi].recovery,choice=$(`input[name="micro-${qi}"]:checked`,target),status=$(`[data-micro-status="${qi}"]`,target);status.textContent=!choice?'Scegli una risposta.':Number(choice.value)===r.answer?'Corretto: il nesso è stato ricostruito.':'Non ancora: torna al chiarimento e distingui causa, forma ed effetto.'}));$('[data-retest]',target).addEventListener('click',()=>renderRetest(index,wrong))}
  function renderRetest(index,wrong){const area=$('[data-retest-area]',lessonView),quiz=LESSONS[index].quiz;area.innerHTML=`<div class="quiz-form" data-retest-form><h3>Secondo tentativo: solo gli errori</h3>${wrong.map(qi=>`<div class="quiz-card"><fieldset><legend>${qi+1}. ${quiz[qi].q}</legend>${quiz[qi].options.map((o,oi)=>`<label class="option"><input type="radio" name="rq${qi}" value="${oi}"><span>${o}</span></label>`).join('')}</fieldset></div>`).join('')}<button class="button primary" type="button" data-submit-retest>Aggiorna il risultato</button><div data-retest-result></div></div>`;const box=$('[data-retest-form]',area);$('[data-submit-retest]',box).addEventListener('click',()=>{const choices=wrong.map(qi=>$(`input[name="rq${qi}"]:checked`,box));if(choices.some(choice=>!choice)){toast('Rispondi a tutte le domande del recupero');return}const still=wrong.filter((qi,pos)=>Number(choices[pos].value)!==quiz[qi].answer),recovered=wrong.length-still.length;state.retests[index]=[...(state.retests[index]||[]),{date:new Date().toISOString(),asked:wrong,recovered,still}];const original=state.attempts[index],totalCorrect=original.correct+recovered,pct=Math.round(totalCorrect/quiz.length*100),vote=Math.max(1,Math.round(pct/10));save();$('[data-retest-result]',area).innerHTML=`<div class="result ${still.length?'bad':''}"><strong>Recuperate ${recovered}/${wrong.length} · risultato aggiornato ${totalCorrect}/${quiz.length} · voto ${vote}/10</strong><p>Il primo tentativo resta memorizzato; questo aggiornamento non lo cancella.${still.length?` Restano da consolidare le domande ${still.map(i=>i+1).join(', ')}.`:' Tutti gli errori sono stati recuperati.'}</p></div>`})}
  function showHome(){lessonView.classList.remove('active');home.classList.add('active');location.hash='home';$$('.nav-item').forEach(el=>el.classList.remove('current'));closeDrawers();mainFocus()}
  function mainFocus(){requestAnimationFrame(()=>{$('#main').focus();window.scrollTo({top:0,behavior:'smooth'})})}
  function openDrawer(el){closeDrawers();el.classList.add('open');el.setAttribute('aria-hidden','false');$('#backdrop').hidden=false;const id=el.id==='sidebar'?'#menuButton':'#toolsButton';$(id).setAttribute('aria-expanded','true')}
  function closeDrawers(){[$('#sidebar'),$('#toolsPanel')].forEach(el=>{el.classList.remove('open');el.setAttribute('aria-hidden','true')});$('#menuButton').setAttribute('aria-expanded','false');$('#toolsButton').setAttribute('aria-expanded','false');$('#backdrop').hidden=true}
  function bindGlobal(){
    document.addEventListener('click',e=>{const trigger=e.target.closest('[data-open-section]');if(trigger)renderSection(Number(trigger.dataset.openSection))});
    $('#menuButton').addEventListener('click',()=>openDrawer($('#sidebar')));$('#toolsButton').addEventListener('click',()=>openDrawer($('#toolsPanel')));$('#closeMenu').addEventListener('click',closeDrawers);$('#closeTools').addEventListener('click',closeDrawers);$('#backdrop').addEventListener('click',closeDrawers);
    $('#continueButton').addEventListener('click',()=>renderSection(state.last||0));$('#homeContinue').addEventListener('click',()=>renderSection(state.last||0));
    $('.brand').addEventListener('click',e=>{e.preventDefault();showHome()});
    $('#openNotesButton').addEventListener('click',()=>{$('#notesArea').value=state.notes;$('#notesDialog').showModal();closeDrawers()});$('#saveNotes').addEventListener('click',()=>{state.notes=$('#notesArea').value;save();$('#notesStatus').textContent='Appunti salvati su questo dispositivo.'});$('#downloadNotes').addEventListener('click',()=>{const blob=new Blob([$('#notesArea').value],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='appunti-pavese.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});
    $('#resetButton').addEventListener('click',()=>{$('#resetDialog').showModal();closeDrawers()});$('#confirmReset').addEventListener('click',()=>{localStorage.removeItem(STORAGE);state=fresh();applyFont();buildHome();updateProgress();showHome();toast('Dati locali azzerati')});
    $('#installButton').addEventListener('click',()=>{$('#installDialog').showModal();closeDrawers()});
    $$('[data-font]').forEach(btn=>btn.addEventListener('click',()=>{state.font=btn.dataset.font;save();applyFont()}));
    window.addEventListener('hashchange',()=>{const match=location.hash.match(/^#section-(\d)$/);if(match&&Number(match[1])-1!==current)renderSection(Number(match[1])-1);else if(location.hash==='#home')showHome()});
    document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawers()});
  }
  function applyFont(){document.body.classList.remove('font-small','font-large');if(state.font!=='normal')document.body.classList.add(`font-${state.font}`);$$('[data-font]').forEach(b=>b.classList.toggle('active',b.dataset.font===state.font))}
  buildHome();bindGlobal();applyFont();updateProgress();const initial=location.hash.match(/^#section-(\d)$/);if(initial)renderSection(Number(initial[1])-1);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
