window.CALVINO_PART2 = [
  {
    id: "poetica",
    short: "Poetica",
    title: "La precisione del gioco",
    question: "Perché Calvino usa fiaba, scienza e combinatoria invece di affidarsi a un solo modo di raccontare?",
    map: "./maps/04-poetica.svg",
    mapAlt: "Mappa della poetica di Calvino: distanza conoscitiva, modelli, scienza, combinatoria, lettore e Lezioni americane",
    lesson: `
      <p class="lede">La poetica di Calvino nasce da una difficoltà: il mondo è troppo intricato per essere restituito da una sola forma narrativa. La soluzione non è rinunciare alla realtà, ma moltiplicare gli strumenti con cui la si interroga. Fiaba, allegoria, dato scientifico, struttura geometrica e racconto che riflette su se stesso diventano esperimenti conoscitivi. Il gioco, in questa prospettiva, non è il contrario della serietà: è una disciplina che permette di cambiare punto di vista senza falsificare ciò che si osserva.</p>

      <h2>La distanza che rende visibile</h2>
      <p>Nelle opere di Calvino la fantasia non funziona come un rifugio consolatorio. Serve piuttosto a introdurre una distanza. Se si resta incollati alle cose, si rischia di confondere il coinvolgimento con la comprensione; se ci si allontana troppo, il mondo diventa un’astrazione senza vita. Calvino cerca una misura mobile fra questi estremi. Nel <em>Barone rampante</em>, Cosimo vive sugli alberi, ma continua a leggere, amare, discutere e prendere parte alle vicende degli uomini. La separazione fisica rende possibile una partecipazione diversa. Il fantastico crea così uno straniamento: ciò che sembrava abituale appare improvvisamente problematico.</p>
      <p>Questa distanza non produce neutralità. Al contrario, consente alla scrittura di mettere in rilievo scissioni, automatismi e contraddizioni. Il visconte diviso in due metà, l’armatura vuota di Agilulfo, le città impossibili descritte da Marco Polo sono figure che condensano problemi reali senza ridurli a una tesi. L’allegoria calviniana non possiede una chiave unica: orienta il lettore, ma gli lascia il compito di verificare fin dove l’immagine spiega il mondo e dove invece mostra i propri limiti.</p>

      <h2>Il racconto come modello, non come copia</h2>
      <p>Calvino costruisce spesso congegni narrativi molto visibili. Un modello semplifica alcuni rapporti per renderli osservabili, come fa una mappa: non coincide con il territorio, ma permette di attraversarlo. Questa idea spiega la cura per le simmetrie, le serie e le cornici. Nelle <em>Città invisibili</em> cinquantacinque città sono distribuite in undici categorie e inserite nel dialogo fra Marco Polo e Kublai Kan. L’ordine non elimina l’enigma delle città; crea invece una rete di confronti fra memoria, desiderio, segni, scambi, morti, cielo e continuità urbana.</p>
      <p>Il modello calviniano è dichiaratamente parziale. Non promette una formula totale capace di chiudere il reale. Ogni struttura produce conoscenza proprio perché seleziona e mette in relazione, ma deve restare correggibile da altri sguardi. Per questo l’opera di Calvino alterna attrazione per l’ordine e consapevolezza di ciò che sfugge all’ordine. Il labirinto non viene abolito: viene sfidato attraverso mappe provvisorie. L’esattezza non è quindi rigidità; è responsabilità nella scelta delle parole e nella costruzione dei rapporti.</p>

      <h2>Scienza, comicità e cambi di scala</h2>
      <p>Nelle <em>Cosmicomiche</em> un enunciato scientifico posto all’inizio del racconto fornisce una spinta all’immaginazione. Calvino non trasforma la narrativa in un manuale di cosmologia. Prende un’ipotesi o una conoscenza scientifica e la sottopone a una torsione narrativa: Qfwfq ricorda la formazione della Luna, la distanza fra le galassie o la comparsa di forme viventi come se fossero esperienze familiari. L’effetto è insieme comico e conoscitivo. Il lettore passa dall’intimità di desideri, gelosie e rivalità alla scala del cosmo, poi torna a guardare l’umano da quella distanza smisurata.</p>
      <p>Qfwfq è dunque un mediatore fra umano e non umano, fra tempi quotidiani e tempi cosmici. La scienza sottrae l’uomo alla pretesa di essere il centro dell’universo; il racconto, però, rende percepibili concetti che altrimenti resterebbero astratti. Letteratura e scienza non vengono confuse: conservano metodi diversi e proprio per questo possono dialogare. La prima esplora immagini, linguaggi e possibilità; la seconda fornisce teorie sottoposte a controllo. Calvino usa la tensione fra le due per rinnovare l’immaginazione e per mostrare che anche il modo di rappresentare il mondo ha una storia.</p>

      <h2>Combinatoria, Oulipo e lettore attivo</h2>
      <p>A Parigi Calvino si confronta con strutturalismo, semiotica e letteratura potenziale. La conferenza <em>Cibernetica e fantasmi</em> del 1967 riflette sulla scrittura come processo di combinazione; l’ingresso formale nell’Oulipo avviene però soltanto nel 1973. Il gruppo sperimenta vincoli capaci di generare possibilità inattese. Il vincolo non soffoca necessariamente la libertà: delimita un campo nel quale l’invenzione può scoprire percorsi che l’abitudine avrebbe escluso.</p>
      <p><em>Il castello dei destini incrociati</em> nasce dalla disposizione dei tarocchi: una prima versione appare nel 1969, mentre l’edizione ampliata Einaudi è del 1973. Le carte sono immagini finite, ma i loro rapporti producono molte storie. In <em>Se una notte d’inverno un viaggiatore</em>, dieci inizi di romanzo interrotti mettono al centro un Lettore e una Lettrice. Non è una profezia di Internet: è una riflessione sul desiderio di continuare a leggere, sull’industria culturale, sulla traduzione, sull’autorità dell’autore e sul carattere sempre incompleto dell’esperienza testuale. Il lettore non riceve un significato già confezionato: deve riconoscere strutture, confrontare ipotesi e prendere posizione.</p>

      <h2>Le cinque proposte compiute</h2>
      <p>Le <em>Lezioni americane</em> dovevano essere le conferenze Norton per Harvard nell’anno accademico 1985-1986. Calvino morì prima di tenerle. Completò cinque testi: <em>Leggerezza</em>, <em>Rapidità</em>, <em>Esattezza</em>, <em>Visibilità</em> e <em>Molteplicità</em>. La progettata sesta lezione, <em>Consistency</em>, traducibile con «Coerenza», non fu scritta: non possiamo attribuirle un contenuto che non possediamo.</p>
      <p>I cinque valori non sono ricette isolate. La leggerezza sottrae peso senza negare la gravità del mondo; la rapidità riguarda il ritmo mentale e narrativo, non la fretta; l’esattezza richiede disegno, immagini nitide e lessico preciso; la visibilità difende la capacità di generare immagini interiori; la molteplicità pensa il romanzo come rete di relazioni e conoscenze. Insieme descrivono una letteratura agile e rigorosa, capace di attraversare il labirinto senza fingere di possederne l’unica mappa.</p>

      <div class="bridge"><strong>Ponte verso le opere.</strong> Ora bisogna verificare come questi principi cambino forma nei libri: dal bosco partigiano alla città industriale, dal cosmo alle biblioteche e agli osservatori di Palomar.</div>
    `,
    summary: "La poetica di Calvino risponde alla complessità del reale costruendo modelli parziali e controllabili. Fantasia e allegoria introducono una distanza conoscitiva: non fanno fuggire dal mondo, ma rendono visibili scissioni e automatismi. Le strutture delle Città invisibili mostrano che l’ordine letterario funziona come una mappa, utile proprio perché non coincide con il territorio. Nelle Cosmicomiche il dato scientifico alimenta racconti che cambiano continuamente scala; Qfwfq media fra umano e non umano. La combinatoria, discussa già in Cibernetica e fantasmi del 1967, trova un ambiente congeniale nell’Oulipo, cui Calvino aderisce formalmente nel 1973. Il castello dei destini incrociati usa i tarocchi per generare narrazioni, mentre Se una notte d’inverno un viaggiatore coinvolge attivamente chi legge. Le Lezioni americane compiute sono cinque: Leggerezza, Rapidità, Esattezza, Visibilità e Molteplicità. La sesta, Coerenza, rimase non scritta. Il gioco calviniano è quindi un metodo rigoroso per esplorare possibilità, non un’evasione né una profezia tecnologica.",
    essentials: [
      "La fantasia calviniana introduce una distanza conoscitiva e non coincide con la fuga dalla realtà.",
      "Il modello letterario seleziona rapporti del mondo senza pretendere di riprodurlo integralmente.",
      "Nelle Cosmicomiche Qfwfq media fra esperienza umana e scale cosmiche non umane.",
      "Calvino tenne la conferenza Cibernetica e fantasmi nel 1967 ed entrò formalmente nell’Oulipo nel 1973.",
      "Il castello dei destini incrociati ebbe una prima versione nel 1969 e un’edizione ampliata nel 1973.",
      "Se una notte d’inverno un viaggiatore mette in scena il rapporto fra autore, testo, editoria e lettore.",
      "Calvino completò cinque Lezioni americane; la progettata lezione sulla Coerenza non fu scritta."
    ],
    glossary: [
      {t: "Straniamento", d: "Procedimento che rende insolito ciò che è abituale per costringere a osservarlo di nuovo."},
      {t: "Modello", d: "Costruzione selettiva che rende leggibili alcuni rapporti senza coincidere con l’intera realtà."},
      {t: "Combinatoria", d: "Produzione di percorsi narrativi attraverso la disposizione regolata di elementi finiti."},
      {t: "Oulipo", d: "Laboratorio di letteratura potenziale cui Calvino aderì formalmente nel 1973."},
      {t: "Vincolo", d: "Regola scelta per delimitare il campo creativo e generare possibilità inattese."},
      {t: "Metaletteratura", d: "Scrittura che riflette sui propri procedimenti, sull’autore e sull’atto di leggere."},
      {t: "Molteplicità", d: "Valore che concepisce l’opera come rete di relazioni, prospettive e saperi."}
    ],
    quiz: [
      {q: "A che cosa serve principalmente la distanza fantastica in Calvino?", o: ["A rendere nuovamente visibili i problemi del reale", "A cancellare i conflitti storici", "A sostituire ogni ragionamento con il sogno"], a: 0, e: "La fantasia opera come straniamento: cambia il punto di osservazione senza negare il mondo.", r: "Concetto: distanza conoscitiva. Chiarimento: separarsi non equivale a disinteressarsi. Esempio: Cosimo vive sugli alberi ma continua a partecipare alla vita degli uomini. Rivedi: La distanza che rende visibile.", check: "Perché Cosimo non è un semplice evasore?"},
      {q: "Quando entrò formalmente Calvino nell’Oulipo?", o: ["Nel 1967", "Nel 1973", "Nel 1979"], a: 1, e: "Il 1967 è l’anno di Cibernetica e fantasmi; l’adesione formale all’Oulipo risale al 1973.", r: "Concetto: cronologia della combinatoria. Chiarimento: contatto culturale e adesione formale non coincidono. Esempio: Calvino riflette sulla combinazione nel 1967, ma diventa membro dell’Oulipo nel 1973. Rivedi: Combinatoria, Oulipo e lettore attivo.", check: "Quale testo del 1967 anticipa questa ricerca?"},
      {q: "Quale descrizione rende meglio la funzione di Qfwfq?", o: ["Uno scienziato che dimostra formule", "Un eroe umano collocato al centro del cosmo", "Un mediatore narrativo fra scale umane e non umane"], a: 2, e: "Qfwfq rende narrabili fenomeni cosmici passando fra esperienza quotidiana e tempi smisurati.", r: "Concetto: cambi di scala. Chiarimento: le Cosmicomiche non sono un manuale scientifico. Esempio: desideri e gelosie vengono raccontati sullo sfondo della formazione della Luna o delle galassie. Rivedi: Scienza, comicità e cambi di scala.", check: "Che effetto produce il passaggio dal quotidiano al cosmo?"},
      {q: "Quali Lezioni americane furono effettivamente completate?", o: ["Leggerezza, Rapidità, Esattezza, Visibilità e Molteplicità", "Leggerezza, Ironia, Memoria, Tecnologia e Coerenza", "Sei lezioni complete, compresa Coerenza"], a: 0, e: "I testi compiuti sono cinque; Coerenza era progettata ma non fu scritta.", r: "Concetto: eredità critica documentata. Chiarimento: il titolo Sei proposte non significa che esistano sei testi compiuti. Esempio: Molteplicità è la quinta lezione completa, mentre Consistency resta un progetto. Rivedi: Le cinque proposte compiute.", check: "Quale lezione progettata non possediamo?"},
      {q: "Perché un vincolo può favorire l’invenzione?", o: ["Perché rende inutile il lettore", "Perché delimita il campo e fa emergere combinazioni inattese", "Perché garantisce una sola interpretazione"], a: 1, e: "La regola non chiude automaticamente il testo: può produrre percorsi che l’abitudine non avrebbe trovato.", r: "Concetto: letteratura potenziale. Chiarimento: libertà e regola non sono sempre opposte. Esempio: i tarocchi del Castello sono un insieme finito che genera molte storie. Rivedi: Combinatoria, Oulipo e lettore attivo.", check: "Quale oggetto visivo vincola le storie del Castello?"}
    ]
  },
  {
    id: "opere",
    short: "Opere",
    title: "Molti libri, una ricerca",
    question: "Come cambia la scrittura di Calvino senza perdere il problema centrale del rapporto fra mente e mondo?",
    map: "./maps/05-opere.svg",
    mapAlt: "Mappa cronologica delle opere di Calvino dal Sentiero dei nidi di ragno a Palomar e alle Lezioni americane",
    lesson: `
      <p class="lede">L’opera di Calvino non procede come una scala in cui ogni gradino cancella il precedente. Realismo, fiaba, critica sociale, scienza e combinatoria convivono e ritornano sotto forme nuove. Per orientarsi è utile seguire alcune costellazioni di libri, non rinchiudere l’autore in fasi rigide. Il problema che le attraversa è stabile: come rappresentare un mondo complesso senza ridurlo a una spiegazione unica?</p>

      <h2>Il bosco della Resistenza: raccontare senza retorica</h2>
      <p><em>Il sentiero dei nidi di ragno</em>, pubblicato nel 1947, nasce dall’esperienza partigiana ma evita il monumento celebrativo. La guerra viene osservata attraverso Pin, un ragazzo marginale che non comprende pienamente i codici degli adulti. Il suo sguardo produce insieme concretezza e straniamento: armi, tradimenti e paura entrano in una narrazione che conserva qualcosa dell’avventura e della fiaba. I partigiani non sono eroi senza contraddizioni; compongono un gruppo diseguale, segnato da motivazioni, debolezze e risentimenti differenti.</p>
      <p>La scelta di Pin permette a Calvino di raccontare la Resistenza dall’interno senza trasformarla in un trattato politico. La prefazione del 1964 chiarirà retrospettivamente il carattere plurale del neorealismo: non una scuola con regole uniformi, ma molte voci nate dall’urgenza del dopoguerra. Anche i racconti di <em>Ultimo viene il corvo</em>, raccolti nel 1949, mostrano la compresenza di precisione visiva, violenza storica e deformazione fiabesca. Il fantastico, dunque, non compare improvvisamente dopo una fase puramente realistica: è già un modo di selezionare e rendere leggibile l’esperienza.</p>

      <h2>Gli antenati: tre figure dell’incompletezza</h2>
      <p><em>Il visconte dimezzato</em> del 1952, <em>Il barone rampante</em> del 1957 e <em>Il cavaliere inesistente</em> del 1959 furono riuniti nel 1960 con il titolo <em>I nostri antenati</em>. I tre racconti spostano l’azione in tempi remoti o immaginari, ma interrogano problemi moderni. Medardo è materialmente diviso e mostra l’insufficienza delle identità ridotte a una sola qualità. Cosimo sceglie gli alberi e sperimenta una distanza che non elimina le relazioni. Agilulfo esiste come volontà, regola e armatura, ma non possiede un corpo.</p>
      <p>Non è prudente assegnare a ogni figura un significato politico esclusivo. Il Visconte può richiamare un mondo lacerato, ma la sua scissione coinvolge anche il rapporto dell’individuo con se stesso. Il Barone riflette sulla posizione dell’intellettuale, e nello stesso tempo racconta crescita, desiderio e fedeltà a una scelta. Il Cavaliere mette alla prova identità, disciplina e vuoto. La forma fiabesca mantiene aperta la pluralità dei significati: rende il problema memorabile senza esaurirlo in un’equazione.</p>

      <h2>La vita difficile: città, industria e responsabilità</h2>
      <p>Negli anni Cinquanta e Sessanta Calvino continua a osservare direttamente l’Italia contemporanea. <em>La speculazione edilizia</em>, apparsa in rivista nel 1957 e in volume nel 1963, mette in scena la trasformazione violenta del paesaggio ligure e l’ambiguità di un intellettuale che tenta di partecipare al meccanismo economico che critica. <em>La nuvola di smog</em>, pubblicata per la prima volta nel 1958 e poi in volume nel 1965, trasforma l’inquinamento in presenza quasi impalpabile e pervasiva. La realtà industriale non è soltanto uno sfondo: modifica gesti, linguaggi e percezioni.</p>
      <p><em>Marcovaldo</em>, in volume dal 1963, segue un manovale che cerca tracce di natura nella città industriale. I funghi, la neve, gli animali e le stagioni sembrano promettere un altrove, ma ogni evasione incontra merci, pubblicità, inquinamento o sfruttamento. La comicità non offre una riconciliazione facile. <em>La giornata d’uno scrutatore</em>, anch’essa del 1963, concentra invece la crisi dell’intellettuale militante nell’esperienza elettorale al Cottolengo. Il contatto con corpi fragili e forme radicali di dipendenza incrina le categorie politiche astratte senza rendere inutile la responsabilità civile.</p>

      <h2>Il cosmo diventa racconto</h2>
      <p>Con <em>Le cosmicomiche</em> del 1965 e <em>Ti con zero</em> del 1967 la scienza diventa un dispositivo narrativo. Ogni storia prende slancio da un enunciato scientifico, ma procede attraverso memoria, desiderio, competizione e comicità. Qfwfq assume forme e posizioni incompatibili con una biografia umana: attraversa ere cosmiche, cambiamenti della materia e nascita della vita. Questa impossibilità è precisamente la sua funzione. Il personaggio collega scale che l’esperienza ordinaria tiene separate.</p>
      <p>Le raccolte cosmicomiche hanno anche una storia editoriale complessa: racconti vengono ripresi, spostati e riordinati in volumi successivi. Non esiste quindi una sola sequenza naturale e definitiva. Questo dato aiuta a comprendere la poetica di Calvino: l’architettura del libro produce significato. Le <em>Cosmicomiche</em> avviano inoltre una riflessione metaletteraria destinata a svilupparsi nelle opere successive, perché mostrano continuamente il passaggio da un’informazione sul mondo a una forma narrativa.</p>

      <h2>Tarocchi, città, lettori e osservatori</h2>
      <p>Una prima versione del <em>Castello dei destini incrociati</em> esce nel 1969; l’edizione Einaudi ampliata è del 1973. Personaggi senza voce raccontano disponendo tarocchi sul tavolo: ogni carta entra in più percorsi e nessuna storia possiede definitivamente le immagini. <em>Le città invisibili</em> del 1972 costruiscono invece una griglia di cinquantacinque città e undici categorie dentro il dialogo fra Marco Polo e Kublai Kan. Il catalogo non descrive luoghi visitabili; interroga memoria, desiderio, linguaggio, morte e forme dell’abitare.</p>
      <p><em>Se una notte d’inverno un viaggiatore</em> del 1979 trasforma il Lettore e la Lettrice in personaggi alla ricerca della continuazione di dieci romanzi interrotti. Il libro parla del piacere e della frustrazione della lettura, dei falsi, delle traduzioni e delle istituzioni che fanno circolare i testi. <em>Palomar</em> del 1983 riduce apparentemente la scala: un uomo osserva un’onda, il seno di una bagnante, un geco, il cielo. Ogni tentativo di descrizione esatta genera nuove difficoltà. Le <em>Lezioni americane</em>, pubblicate postume nel 1988, rendono espliciti cinque valori già sperimentati nei libri. Non chiudono il percorso in una formula: consegnano al futuro un metodo di attenzione.</p>

      <div class="bridge"><strong>Ponte verso la conclusione.</strong> Attraversando queste opere emerge una continuità: Calvino cambia congegno ogni volta che il precedente rischia di diventare un’abitudine e di non vedere più il mondo.</div>
    `,
    summary: "Le opere di Calvino formano costellazioni sovrapposte più che fasi chiuse. Il sentiero dei nidi di ragno racconta la Resistenza attraverso Pin, evitando sia il documento impersonale sia la celebrazione eroica. I nostri antenati riunisce tre figure dell’incompletezza: il corpo diviso, l’uomo sugli alberi e l’armatura senza corpo. La speculazione edilizia, La nuvola di smog, Marcovaldo e La giornata d’uno scrutatore affrontano trasformazioni urbane, industria e crisi dell’intellettuale. Le Cosmicomiche e Ti con zero usano dati scientifici per cambiare scala e decentrare l’umano. Il castello dei destini incrociati costruisce storie con i tarocchi; Le città invisibili organizza cinquantacinque città in undici categorie; Se una notte d’inverno un viaggiatore mette il lettore dentro il romanzo; Palomar mostra la difficoltà di osservare con esattezza. Le Lezioni americane, pubblicate postume, esplicitano cinque valori già attivi nell’opera. La continuità non sta in uno stile immobile, ma nella ricerca di forme adeguate a problemi sempre nuovi.",
    essentials: [
      "Il sentiero dei nidi di ragno fu pubblicato nel 1947 e adotta il punto di vista marginale di Pin.",
      "I nostri antenati riunisce nel 1960 tre racconti pubblicati nel 1952, 1957 e 1959.",
      "La speculazione edilizia apparve in rivista nel 1957 e in volume nel 1963.",
      "Marcovaldo e La giornata d’uno scrutatore uscirono in volume nel 1963.",
      "Le cosmicomiche del 1965 e Ti con zero del 1967 trasformano conoscenze scientifiche in dispositivi narrativi.",
      "Il castello dei destini incrociati ebbe una versione nel 1969 e un’edizione ampliata nel 1973.",
      "Le città invisibili è del 1972, Se una notte d’inverno un viaggiatore del 1979 e Palomar del 1983.",
      "Le Lezioni americane furono pubblicate postume nel 1988."
    ],
    glossary: [
      {t: "Neorealismo", d: "Costellazione plurale di voci del dopoguerra, non scuola dotata di una poetica unica."},
      {t: "Allegoria", d: "Figura narrativa che rende percepibile un problema senza necessariamente fissargli un solo significato."},
      {t: "Macrotesto", d: "Insieme di racconti il cui ordine e le cui relazioni producono un significato ulteriore."},
      {t: "Qfwfq", d: "Narratore cosmicomico che collega tempi e scale umani, biologici e cosmici."},
      {t: "Cornice", d: "Struttura che contiene e mette in rapporto più racconti, come il dialogo Polo-Kan."},
      {t: "Metaromanzo", d: "Romanzo che rappresenta e interroga i meccanismi della scrittura e della lettura."},
      {t: "Costellazione", d: "Raggruppamento aperto di opere e problemi che evita una rigida successione di fasi."}
    ],
    quiz: [
      {q: "Perché Pin è decisivo nel Sentiero dei nidi di ragno?", o: ["Perché espone una teoria completa della Resistenza", "Perché rappresenta il capo ideale dei partigiani", "Perché il suo sguardo marginale evita una rappresentazione celebrativa"], a: 2, e: "Pin vede gli adulti senza dominarne i codici e rende la guerra concreta, fiabesca e contraddittoria.", r: "Concetto: punto di vista. Chiarimento: il romanzo non elimina la storia, ma la filtra attraverso una coscienza parziale. Esempio: Pin incontra partigiani diversi, fragili e non monumentalizzati. Rivedi: Il bosco della Resistenza: raccontare senza retorica.", check: "Che cosa non comprende pienamente Pin?"},
      {q: "In quale anno i tre racconti furono riuniti come I nostri antenati?", o: ["Nel 1960", "Nel 1952", "Nel 1973"], a: 0, e: "I singoli testi uscirono nel 1952, 1957 e 1959; la riunione con il titolo I nostri antenati è del 1960.", r: "Concetto: cronologia editoriale. Chiarimento: pubblicazione dei racconti e costituzione della trilogia sono eventi diversi. Esempio: Il cavaliere inesistente del 1959 entra l’anno dopo nel volume comune. Rivedi: Gli antenati: tre figure dell’incompletezza.", check: "Qual è il secondo racconto della trilogia per data?"},
      {q: "Che cosa accade normalmente ai tentativi di Marcovaldo di ritrovare la natura?", o: ["Producono una fuga definitiva dalla città", "Incontrano merci, inquinamento o meccanismi di sfruttamento", "Dimostrano che città e campagna sono identiche"], a: 1, e: "La natura appare nella città, ma non costituisce un altrove incontaminato e facilmente raggiungibile.", r: "Concetto: critica della città industriale. Chiarimento: la comicità non garantisce una soluzione consolatoria. Esempio: funghi, neve e animali vengono intercettati dall’organizzazione urbana e commerciale. Rivedi: La vita difficile: città, industria e responsabilità.", check: "Perché la natura non è un rifugio semplice per Marcovaldo?"},
      {q: "Quale opera organizza cinquantacinque città in undici categorie?", o: ["Palomar", "Ti con zero", "Le città invisibili"], a: 2, e: "Le città invisibili usa una griglia rigorosa dentro il dialogo tra Marco Polo e Kublai Kan.", r: "Concetto: architettura del libro. Chiarimento: il catalogo non è casuale e non descrive città turistiche. Esempio: memoria, desiderio, segni e città continue sono alcune delle categorie. Rivedi: Tarocchi, città, lettori e osservatori.", check: "Chi sono i due interlocutori della cornice?"},
      {q: "Quale continuità collega le opere molto diverse di Calvino?", o: ["La ricerca di forme capaci di rappresentare la complessità senza chiuderla", "L’uso esclusivo del realismo documentario", "La rinuncia progressiva ai problemi sociali"], a: 0, e: "Calvino cambia strumenti, ma conserva il problema del rapporto fra forme mentali e mondo.", r: "Concetto: costellazioni, non fasi chiuse. Chiarimento: una nuova forma non cancella necessariamente le precedenti. Esempio: precisione visiva e fiaba sono già presenti nei racconti resistenziali e ritornano altrove. Rivedi: Molti libri, una ricerca.", check: "Perché non conviene dividere Calvino in compartimenti rigidi?"}
    ]
  },
  {
    id: "conclusione",
    short: "Conclusione",
    title: "Abitare il labirinto",
    question: "Quale responsabilità affida Calvino alla letteratura quando nessuna mappa può coincidere con il mondo?",
    map: "./maps/06-sintesi.svg",
    mapAlt: "Mappa conclusiva: complessità, distanza, esattezza, molteplicità e responsabilità del lettore",
    lesson: `
      <p class="lede">Calvino non offre una formula capace di sciogliere definitivamente il labirinto. Offre qualcosa di più utile: un modo di entrarvi senza scambiare la prima strada per l’unica possibile. La sua opera insegna a costruire mappe precise e insieme a ricordare che ogni mappa seleziona. Da qui nasce una responsabilità condivisa fra autore e lettore: osservare, collegare, verificare, cambiare scala e riconoscere ciò che resta fuori dal modello.</p>

      <h2>Una continuità fatta di cambiamenti</h2>
      <p>Dal bosco partigiano di Pin all’onda osservata da Palomar, Calvino modifica continuamente strumenti e linguaggi. Il cambiamento non è capriccio né semplice desiderio di essere moderno. Ogni forma rischia, con l’uso, di diventare automatica: il neorealismo può irrigidirsi in formula celebrativa, l’allegoria in chiave scolastica, la scienza in ornamento, la combinatoria in meccanismo senza necessità. Calvino cambia rotta quando il dispositivo non produce più conoscenza.</p>
      <p>La continuità sta allora nel metodo. La pagina deve mettere alla prova il rapporto fra ordine mentale e resistenza del mondo. Nei primi racconti la realtà storica entra attraverso una voce parziale; negli Antenati una figura impossibile concentra un conflitto; nelle Cosmicomiche il narratore attraversa scale inconciliabili; nelle opere combinatorie una struttura finita apre molte letture; in Palomar la descrizione più minuziosa scopre nuovi margini di incertezza. L’insuccesso di una rappresentazione non è sempre una sconfitta: può mostrare con esattezza perché il reale non si lascia chiudere.</p>

      <h2>La leggerezza porta il peso</h2>
      <p>La parola più celebre delle Lezioni americane è anche la più facile da fraintendere. Leggerezza non significa superficialità o indifferenza. Perseo affronta Medusa guardandone l’immagine riflessa nello scudo: evita lo sguardo diretto che pietrifica, ma non evita il compito. La distanza è una strategia per sostenere il peso e agire. In modo analogo, la fiaba e il comico permettono a Calvino di avvicinare guerra, alienazione, inquinamento, fragilità e morte senza trasformare la pagina in una massa inerte.</p>
      <p>La leggerezza ha bisogno dell’esattezza. Senza precisione, diventerebbe vaghezza; senza leggerezza, l’esattezza potrebbe ridursi a inventario. Anche rapidità, visibilità e molteplicità si correggono reciprocamente. La rapidità dà ritmo ai passaggi del pensiero, ma non autorizza la fretta. La visibilità genera immagini, ma deve resistere agli stereotipi. La molteplicità apre la rete dei rapporti, ma richiede una forma che renda quei rapporti leggibili. I valori non sono slogan separati: costituiscono un sistema di tensioni.</p>

      <h2>Conoscere significa cambiare scala</h2>
      <p>Una delle operazioni più profonde di Calvino è il passaggio fra scale. Pin guarda una guerra più grande di lui; Marcovaldo cerca una foglia dentro la metropoli; Qfwfq racconta passioni quasi domestiche nel tempo delle galassie; Marco Polo comprime imperi in città immaginarie; Palomar tenta di isolare un’onda e scopre che ogni onda dipende dal mare. Cambiare scala relativizza la presunta centralità dell’osservatore e fa emergere relazioni invisibili al livello precedente.</p>
      <p>Questo movimento possiede anche una portata etica. Chi considera assoluta la propria prospettiva trasforma facilmente gli altri in dettagli. Chi sa spostarsi fra il vicino e il lontano comprende invece che ogni conoscenza è situata, senza per questo concludere che tutte le affermazioni siano equivalenti. Calvino non predica un relativismo pigro. Pretende modelli precisi, parole controllate e architetture verificabili; nello stesso tempo rifiuta che una costruzione parziale si presenti come totalità. L’umiltà dello sguardo non elimina il rigore: ne stabilisce il limite responsabile.</p>

      <h2>Il lettore completa senza possedere</h2>
      <p>La centralità del lettore non nasce soltanto in <em>Se una notte d’inverno un viaggiatore</em>, anche se lì diventa personaggio e tema. Ogni allegoria non univoca e ogni struttura a rete richiedono un’attività di confronto. Leggere non significa scegliere arbitrariamente qualsiasi significato. Significa formulare ipotesi, sostenerle con elementi del testo e correggerle quando non spiegano abbastanza. Il lettore collabora con l’opera proprio perché incontra vincoli.</p>
      <p>Questa idea distingue molteplicità da confusione. Nel <em>Castello</em> le carte possono generare percorsi diversi, ma non qualsiasi carta può occupare qualsiasi posizione senza conseguenze. Nelle <em>Città invisibili</em> il lettore può seguire molte traiettorie, ma la serie è ordinata con precisione. Nel metaromanzo del 1979 gli inizi interrotti liberano il desiderio e insieme lo frustrano. Calvino non anticipa magicamente Internet: analizza condizioni antiche e moderne della lettura, come l’incompletezza, la circolazione dei testi, il bisogno di continuità e il rapporto fra libertà e forma.</p>

      <h2>Un metodo ancora necessario</h2>
      <p>Nel presente siamo circondati da informazioni, immagini e narrazioni che competono per l’attenzione. Sarebbe facile trasformare Calvino in un profeta delle tecnologie digitali, ma sarebbe un modo povero di attualizzarlo. La sua utilità non dipende dall’avere previsto strumenti che non conobbe. Dipende dall’aver pensato con rigore problemi più generali: come selezionare senza falsificare, come collegare saperi differenti, come difendere l’immaginazione dagli automatismi, come conservare precisione dentro la molteplicità.</p>
      <p>La letteratura non sostituisce la scienza, la storia o la politica. Possiede però una capacità specifica: può far convivere prospettive, scale, linguaggi e possibilità incompatibili in altri discorsi. Non fornisce una conoscenza totale, ma allena a riconoscere le forme con cui costruiamo il mondo. La conclusione di Calvino resta quindi aperta e operativa: il labirinto non si vince osservandolo dall’esterno né abbandonandosi al caso. Lo si abita costruendo passaggi, controllando le mappe e mantenendo vivo il sospetto che esista ancora una strada non vista.</p>

      <div class="bridge"><strong>Ponte verso la verifica finale.</strong> I sei movimenti formano un solo ragionamento: un mondo complesso produce fratture, le fratture cambiano lo sguardo, e lo sguardo inventa forme capaci di orientare senza imprigionare.</div>
    `,
    summary: "La continuità dell’opera di Calvino non consiste in un unico stile, ma nel metodo con cui ogni forma viene sottoposta a verifica. La letteratura costruisce mappe del reale sapendo che nessuna mappa coincide con il territorio. La leggerezza non rimuove il peso: crea la distanza necessaria per affrontarlo; insieme a rapidità, esattezza, visibilità e molteplicità forma un sistema di valori che si limitano e si rafforzano reciprocamente. Il cambiamento di scala, da Pin a Qfwfq e Palomar, decentra l’osservatore e rende visibili nuove relazioni. Questa umiltà non conduce al relativismo: interpretazioni e modelli devono restare precisi, testuali e correggibili. Anche il lettore partecipa alla costruzione del significato, ma dentro i vincoli dell’opera. Calvino non va trasformato in un profeta di Internet. È attuale perché insegna a selezionare senza falsificare, collegare saperi differenti e resistere agli automatismi delle immagini e del linguaggio. Abitare il labirinto significa costruire passaggi senza dichiarare definitiva la propria mappa.",
    essentials: [
      "La continuità di Calvino risiede in un metodo di ricerca, non nell’uso permanente dello stesso stile.",
      "Una mappa letteraria rende leggibili alcuni rapporti proprio perché non coincide con l’intero territorio.",
      "La leggerezza affronta il peso attraverso distanza e precisione; non equivale a superficialità.",
      "I cinque valori compiuti delle Lezioni americane funzionano come un sistema di tensioni reciproche.",
      "Cambiare scala ridimensiona la centralità dell’osservatore e rende visibili relazioni nuove.",
      "Il lettore formula interpretazioni libere ma deve verificarle attraverso i vincoli del testo.",
      "Attribuire a Calvino una profezia di Internet confonde una lettura attuale con un fatto storico.",
      "Per Calvino la letteratura orienta nel labirinto senza promettere una conoscenza totale."
    ],
    glossary: [
      {t: "Labirinto", d: "Figura della complessità del reale e della difficoltà di trovare percorsi senza una mappa definitiva."},
      {t: "Leggerezza", d: "Sottrazione di peso che permette di affrontare il reale senza esserne pietrificati."},
      {t: "Scala", d: "Livello spaziale o temporale da cui un fenomeno viene osservato e narrato."},
      {t: "Prospettiva situata", d: "Punto di vista consapevole della propria posizione e dei propri limiti."},
      {t: "Vincolo testuale", d: "Elemento concreto dell’opera che orienta e limita le interpretazioni possibili."},
      {t: "Responsabilità", d: "Obbligo di costruire e verificare forme senza presentare il parziale come totalità."},
      {t: "Attualizzazione", d: "Lettura che collega un’opera al presente senza attribuirle previsioni storicamente infondate."}
    ],
    quiz: [
      {q: "Dove si trova la continuità più profonda dell’opera di Calvino?", o: ["Nell’uso invariabile della fiaba", "Nel metodo che verifica e rinnova le forme", "Nell’abbandono progressivo della storia"], a: 1, e: "Calvino cambia strumenti quando una forma rischia di diventare automatica, ma conserva il problema della conoscenza del mondo.", r: "Concetto: continuità dinamica. Chiarimento: cambiare stile non significa perdere coerenza. Esempio: Pin, Qfwfq e Palomar usano dispositivi diversi per misurare il rapporto fra sguardo e realtà. Rivedi: Una continuità fatta di cambiamenti.", check: "Quando Calvino sente il bisogno di cambiare dispositivo?"},
      {q: "Che cosa significa leggerezza nelle Lezioni americane?", o: ["Evitare ogni tema doloroso", "Scrivere soltanto testi brevi", "Sottrarre peso per affrontare il reale senza esserne pietrificati"], a: 2, e: "L’immagine di Perseo chiarisce che la distanza serve ad affrontare Medusa, non a fuggire.", r: "Concetto: leggerezza responsabile. Chiarimento: il contrario della pesantezza non è l’indifferenza. Esempio: Perseo guarda Medusa attraverso lo scudo e può così agire. Rivedi: La leggerezza porta il peso.", check: "Quale oggetto consente a Perseo di guardare indirettamente?"},
      {q: "Quale effetto produce il cambiamento di scala?", o: ["Decentra l’osservatore e mostra relazioni prima invisibili", "Dimostra che tutte le interpretazioni sono equivalenti", "Elimina la necessità di parole precise"], a: 0, e: "Passare dal dettaglio al cosmo o viceversa modifica i rapporti percepibili senza cancellare il rigore.", r: "Concetto: scala e conoscenza. Chiarimento: una prospettiva limitata può essere corretta da un’altra scala. Esempio: Palomar isola un’onda e scopre la sua dipendenza dal mare. Rivedi: Conoscere significa cambiare scala.", check: "Che cosa scopre Palomar osservando una sola onda?"},
      {q: "In che senso il lettore è attivo?", o: ["Può attribuire al testo qualsiasi significato", "Formula ipotesi e le verifica nei vincoli dell’opera", "Sostituisce completamente l’autore"], a: 1, e: "La collaborazione del lettore è reale, ma non arbitraria: carte, serie e parole pongono limiti verificabili.", r: "Concetto: interpretazione vincolata. Chiarimento: molteplicità non significa confusione. Esempio: i tarocchi del Castello generano più storie, ma la loro posizione produce conseguenze. Rivedi: Il lettore completa senza possedere.", check: "Che cosa limita le interpretazioni del lettore?"},
      {q: "Perché è scorretto chiamare Calvino profeta di Internet?", o: ["Perché rifiutò ogni macchina", "Perché non si occupò mai di lettura", "Perché una connessione contemporanea non è una previsione storica"], a: 2, e: "Le sue riflessioni su combinazione e lettore sono attuali, ma non autorizzano ad attribuirgli la previsione di una tecnologia specifica.", r: "Concetto: attualizzazione controllata. Chiarimento: somiglianza concettuale e profezia non coincidono. Esempio: Se una notte riflette su testi interrotti, editoria e desiderio di lettura, non descrive il Web. Rivedi: Un metodo ancora necessario.", check: "Quali problemi generali rendono Calvino attuale?"}
    ]
  }
];

window.CALVINO_FINAL = [
  {q: "Quale bisogno del dopoguerra costituisce il punto di partenza del percorso?", o: ["Raccontare un’esperienza collettiva senza ridurla a formula", "Cancellare ogni rapporto fra letteratura e storia", "Restaurare i modelli celebrativi ottocenteschi"], a: 0, e: "Il mondo precedente consegna a Calvino l’urgenza del racconto e, insieme, il rischio della retorica.", r: "Concetto: eredità del dopoguerra. Chiarimento: il neorealismo fu una pluralità di voci, non una scuola uniforme. Esempio: la Resistenza genera storie condivise ma richiede forme capaci di conservarne le contraddizioni. Rivedi: sezione Il mondo precedente.", check: "Perché il neorealismo non va definito una scuola unica?"},
  {q: "Quale frattura politica e poetica si concentra fra 1956 e 1957?", o: ["L’ingresso di Calvino nell’Oulipo", "La crisi dopo i fatti d’Ungheria e l’uscita dal PCI", "La pubblicazione delle Lezioni americane"], a: 1, e: "La crisi del 1956 precede l’uscita ufficiale dal PCI nell’agosto 1957 e si intreccia con una ricerca di nuove forme.", r: "Concetto: frattura politico-poetica. Chiarimento: non è un passaggio dal pieno impegno alla fuga astratta. Esempio: mentre si distacca dal PCI, Calvino lavora alle Fiabe, al Barone e alla Speculazione edilizia. Rivedi: sezione Le fratture.", check: "In quale anno Calvino uscì ufficialmente dal PCI?"},
  {q: "Quale immagine riassume meglio il mondo di Calvino?", o: ["Un sistema perfettamente chiuso", "Un caos privo di ogni relazione", "Un labirinto che richiede mappe parziali e correggibili"], a: 2, e: "Il mondo è complesso e plurale: le strutture aiutano a orientarsi, ma nessuna coincide con la totalità.", r: "Concetto: immagine del mondo. Chiarimento: ordine e disordine restano in tensione. Esempio: le città di Marco Polo formano una griglia precisa che non esaurisce l’impero. Rivedi: sezione Immagine del mondo.", check: "Perché una mappa utile deve restare correggibile?"},
  {q: "Quale rapporto lega vincolo e invenzione nella poetica combinatoria?", o: ["Il vincolo può generare possibilità inattese", "Il vincolo impone sempre una sola storia", "L’invenzione richiede assenza totale di regole"], a: 0, e: "Una regola delimita il campo e rende esplorabili combinazioni che l’abitudine non avrebbe prodotto.", r: "Concetto: combinatoria. Chiarimento: regola e libertà possono collaborare. Esempio: le carte finite del Castello generano molte narrazioni incrociate. Rivedi: Combinatoria, Oulipo e lettore attivo.", check: "In quale anno Calvino aderì formalmente all’Oulipo?"},
  {q: "Quale successione editoriale del Castello dei destini incrociati è corretta?", o: ["Edizione unica nel 1979", "Prima versione nel 1969, edizione ampliata nel 1973", "Prima versione nel 1973, edizione ridotta nel 1983"], a: 1, e: "Separare le due date evita di confondere la genesi dell’opera con la sua forma ampliata Einaudi.", r: "Concetto: opere e storia editoriale. Chiarimento: un titolo può indicare configurazioni testuali diverse. Esempio: il nucleo del 1969 viene ampliato nell’edizione del 1973. Rivedi: Tarocchi, città, lettori e osservatori.", check: "Quale dispositivo iconico genera le storie del Castello?"},
  {q: "Quale conclusione esprime meglio l’eredità di Calvino?", o: ["La letteratura possiede finalmente la mappa totale", "Tutte le letture sono vere allo stesso modo", "La letteratura orienta con forme precise senza imprigionare il reale"], a: 2, e: "Il rigore costruisce passaggi nel labirinto, mentre la molteplicità impedisce di presentare il parziale come totalità.", r: "Concetto: responsabilità della forma. Chiarimento: apertura e precisione non sono opposte. Esempio: le cinque Lezioni compiute propongono valori che si limitano e si rafforzano reciprocamente. Rivedi: Un metodo ancora necessario.", check: "Quale lezione progettata non fu scritta?"}
];
