/* Contenuti redazionali: fonti e criteri in docs/dossier-fonti.md */
const SCIASCIA_SECTIONS = [
  {
    id: "mondo",
    number: "01",
    title: "Il mondo precedente",
    subtitle: "La Sicilia, l’Italia repubblicana e la promessa incompiuta della ragione",
    question: "Che cosa riceve Sciascia da un’isola in cui la legge dello Stato esiste, ma non sempre diventa giustizia?",
    lesson: [
      { id: "mondo-sicilia", heading: "Una periferia che è già il centro", text: `Leonardo Sciascia nasce a Racalmuto nel 1921 e cresce in una Sicilia che sarebbe un errore considerare soltanto periferica. L’isola è, per lui, un osservatorio concentrato dei problemi italiani: la distanza fra norma e pratica, fra istituzioni e cittadini, fra parola pubblica e verità concreta. Il paesaggio delle zolfare, della piccola proprietà, dei notabili e delle dipendenze personali non è uno sfondo pittoresco. È un sistema di rapporti. Chi possiede lavoro, protezione, informazioni o relazioni può condizionare la vita di chi non li possiede. Per questo “Regalpetra”, il paese immaginario dietro cui si riconosce Racalmuto, diventa una lente: ciò che accade in piccolo permette di leggere ciò che la nazione preferisce non vedere. La Sicilia ricevuta da Sciascia contiene insieme immobilità e trasformazione. Il fascismo ha imposto una lingua ufficiale e una rappresentazione ordinata della società; la guerra ha rivelato la fragilità di quell’ordine; la Repubblica promette diritti, scuola e partecipazione. Eppure le vecchie gerarchie non scompaiono per decreto. Cambiano abito, entrano nei partiti, nelle amministrazioni, negli scambi elettorali. La prima tensione del suo mondo è dunque questa: la modernità giuridica avanza, ma può convivere con strutture arcaiche di potere.` },
      { id: "mondo-dopoguerra", heading: "Dalla dittatura alla Repubblica: la prova dei fatti", text: `Sciascia appartiene alla generazione che vede il passaggio dal fascismo alla democrazia e deve misurare la distanza fra le parole solenni e gli effetti reali. Nel dopoguerra la Costituzione trasforma il cittadino in titolare di diritti; la scuola e il suffragio universale allargano formalmente lo spazio pubblico. Ma una democrazia non vive solo nei testi giuridici: dipende dalla possibilità di conoscere i fatti, chiamare le cose con il loro nome, controllare chi governa. In Sicilia questa prova è resa più difficile dalla mafia, a lungo negata o ridotta a costume locale, e da una rete di silenzi che collega paura, interesse e opportunismo. Sciascia comprende presto che il potere più efficace non è sempre quello che proibisce apertamente. Può essere quello che confonde, allude, rinvia, fa sparire le responsabilità dentro procedure apparentemente regolari. Il contesto nazionale amplia il problema. La Guerra fredda irrigidisce le appartenenze politiche: spesso si giudica un’affermazione non per la sua verità, ma per il campo da cui proviene. L’intellettuale rischia di diventare portavoce di un partito o ornamento morale del potere. Sciascia riceve dunque anche questo dilemma: come difendere la democrazia senza trasformare la fedeltà politica in obbedienza? La sua risposta futura sarà scomoda, perché pretenderà di esercitare la critica anche verso il campo che sente più vicino.` },
      { id: "mondo-letteratura", heading: "Una tradizione da usare, non da venerare", text: `Il mondo precedente è anche letterario. Il Verismo ha mostrato la durezza dei rapporti sociali siciliani, ma Sciascia non si limita all’impersonalità o al determinismo. Pirandello gli consegna l’instabilità dell’identità, il sospetto verso le forme sociali e la capacità di vedere il rovescio comico o tragico delle certezze. Manzoni offre qualcosa di ancora più decisivo: il nesso fra letteratura, documento e responsabilità morale. La Storia della colonna infame dimostra che ricostruire un processo significa interrogare non solo l’errore, ma le condizioni che lo rendono possibile e le responsabilità di chi avrebbe potuto evitarlo. Accanto alla tradizione italiana agiscono gli illuministi — Voltaire, Montesquieu, Verri, Beccaria — con la loro battaglia contro fanatismo, tortura e arbitrio. Chiamare Sciascia “neo-illuminista” è utile solo se non immaginiamo una fiducia ingenua nel progresso. Egli eredita la ragione come metodo di controllo, non come garanzia di vittoria. Legge inoltre il poliziesco europeo, da Poe a Simenon e Dürrenmatt: un genere costruito sulla promessa che gli indizi conducano alla soluzione. Proprio questa promessa diventerà il suo laboratorio critico. Che cosa accade quando l’investigatore capisce, ma la verità non può tradursi in giustizia? Il giallo, entrando in Sicilia e nell’Italia repubblicana, perde l’innocenza del meccanismo perfetto.` },
      { id: "mondo-limite", heading: "Il limite del mondo ricevuto", text: `La tensione che prepara tutte le fratture successive è la separazione fra verità, legge e giustizia. In un ordine ideale, i fatti vengono accertati, la legge li qualifica e la giustizia ristabilisce una misura comune. Nel mondo osservato da Sciascia, questi passaggi possono spezzarsi. Si può conoscere una colpa senza poterla provare; si può applicare una procedura formalmente corretta e produrre un’ingiustizia; si può difendere un’istituzione occultandone gli errori e finire così per indebolirla. La mafia è una manifestazione concreta di questa frattura, non la sua unica forma. Anche la burocrazia, la ragion di Stato, il conformismo dei partiti e la manipolazione del linguaggio possono costruire zone di irresponsabilità. Ecco perché ridurre Sciascia a “scrittore della mafia” è fuorviante: significherebbe confondere il caso più visibile con la domanda generale. Il suo vero oggetto è il potere quando sottrae i propri atti alla verifica. Da questo mondo egli eredita però anche strumenti di resistenza: la scuola, il libro, la conversazione, l’archivio, l’ironia. Non sono armi spettacolari. Servono a mantenere distinguibili le parole e i fatti. La letteratura nasce nel punto in cui la promessa democratica incontra il suo fallimento parziale e decide di non coprirlo.` },
      { id: "mondo-ponte", heading: "Ponte: quando il contesto diventa esperienza", text: `Finché queste tensioni restano coordinate storiche, non spiegano ancora uno scrittore. Diventano decisive quando attraversano la sua esperienza: la formazione durante il fascismo, il lavoro negli uffici e nella scuola, l’osservazione della povertà, l’incontro con editori e intellettuali, l’impegno politico seguito dalla scelta della distanza. Nessun episodio produce automaticamente un’opera; una biografia non è una macchina causale. Tuttavia alcune esperienze rendono intelligibile la costanza con cui Sciascia tornerà sulla lingua, sull’educazione, sugli archivi, sui processi e sulla solitudine del giudizio. Il mondo precedente gli consegna una domanda: come può un individuo ragionare liberamente dentro istituzioni e comunità che chiedono appartenenza? Le fratture della sua vita non cancelleranno questa domanda. La renderanno personale, urgente e infine letteraria.` }
    ],
    summary: `Sciascia riceve una Sicilia in cui la modernità giuridica convive con gerarchie, dipendenze personali e silenzi. Il passaggio dal fascismo alla Repubblica promette cittadinanza, ma rende visibile la distanza fra Costituzione e vita concreta. Mafia, burocrazia, appartenenze della Guerra fredda e conformismo possono separare verità, legge e giustizia. La tradizione gli offre strumenti diversi: Verga per i rapporti sociali, Pirandello per la crisi delle forme, Manzoni per il rapporto fra documento e responsabilità, gli illuministi per la critica dell’arbitrio, il poliziesco per la logica dell’indagine. Da questo intreccio nasce il problema che guiderà l’opera: che valore ha comprendere i fatti quando il potere impedisce alla verità di diventare giustizia? Le esperienze biografiche trasformeranno questa domanda storica in una scelta personale di scrittura e di giudizio.`,
    essentials: [
      "Spiegare perché la Sicilia è per Sciascia una lente dell’Italia, non un mondo separato.",
      "Distinguere la modernità delle leggi dalla persistenza di rapporti di potere informali.",
      "Collegare fascismo, Repubblica e Guerra fredda al problema della libertà di giudizio.",
      "Riconoscere i contributi di Manzoni, Illuminismo, Pirandello e poliziesco.",
      "Argomentare perché Sciascia non può essere ridotto a scrittore della mafia.",
      "Definire la frattura fra verità, legge e giustizia."
    ],
    vocab: [
      ["Neo-illuminismo", "Uso moderno e non ingenuo della ragione per criticare arbitrio, fanatismo e abuso."],
      ["Ragion di Stato", "Giustificazione di atti o segreti in nome della conservazione dello Stato."],
      ["Regalpetra", "Paese letterario che trasforma Racalmuto in osservatorio della società siciliana."],
      ["Omertà", "Silenzio sostenuto da paura, interesse o appartenenza, che ostacola l’accertamento dei fatti."],
      ["Giallo", "Genere d’indagine fondato su indizi, investigatore e soluzione di un enigma."],
      ["Responsabilità", "Possibilità di attribuire decisioni e conseguenze a soggetti riconoscibili."]
    ],
    map: "assets/maps/01-mondo.svg",
    mapAlt: "Mappa: Sicilia e dopoguerra producono una distanza tra legge e giustizia; Manzoni, Illuminismo, Pirandello e giallo forniscono strumenti che confluiscono nella domanda sul potere verificabile.",
    questions: [
      { stem: "Perché Regalpetra è più di un semplice paese immaginario?", options: ["Perché idealizza una Sicilia senza conflitti", "Perché concentra rapporti sociali utili a leggere anche l’Italia", "Perché sostituisce ogni riferimento alla storia"], correct: 1, feedback: "Regalpetra concentra in scala locale tensioni che riguardano la nazione.", recovery: ["Sicilia come lente", "Il luogo particolare rende visibile un meccanismo generale.", "Le dipendenze personali del paese aiutano a leggere il rapporto nazionale fra cittadini e potere.", "mondo-sicilia"] },
      { stem: "Quale frattura struttura il mondo ricevuto da Sciascia?", options: ["Fra poesia e prosa", "Fra campagna e città soltanto", "Fra verità, legge e giustizia"], correct: 2, feedback: "Conoscenza dei fatti, procedura legale ed esito giusto possono separarsi.", recovery: ["Tre termini distinti", "Sapere, applicare una norma e fare giustizia non coincidono automaticamente.", "Un fatto può essere noto ma non provato in tribunale.", "mondo-limite"] },
      { stem: "Che cosa offre Manzoni al laboratorio di Sciascia?", options: ["Un modello per interrogare documenti e responsabilità", "Il rifiuto della storia in favore della fantasia", "Una lingua esclusivamente dialettale"], correct: 0, feedback: "Manzoni collega ricostruzione storica, documento e responsabilità morale.", recovery: ["Manzoni e il documento", "La storia va ricostruita rispettando prove, dubbi e responsabilità.", "La Colonna infame interroga come un errore giudiziario diventi possibile.", "mondo-letteratura"] },
      { stem: "In che senso Sciascia è neo-illuminista?", options: ["Crede che il progresso vinca sempre", "Usa la ragione come metodo critico senza garantirne la vittoria", "Rifiuta dubbio e ironia"], correct: 1, feedback: "La ragione controlla miti e abusi, ma resta fragile e può essere sconfitta.", recovery: ["Ragione non trionfale", "Il metodo razionale conserva valore anche quando non domina la realtà.", "L’investigatore può capire il delitto senza ottenere giustizia.", "mondo-letteratura"] },
      { stem: "Perché la definizione “scrittore della mafia” è insufficiente?", options: ["Perché Sciascia non scrive mai di mafia", "Perché la mafia compare solo nelle poesie", "Perché la mafia è un caso del problema più ampio del potere sottratto alla verifica"], correct: 2, feedback: "Il centro è il rapporto fra potere, verità e responsabilità.", recovery: ["Dal caso alla domanda", "La mafia è decisiva, ma non esaurisce l’indagine sciasciana.", "Anche burocrazia e ragion di Stato possono occultare responsabilità.", "mondo-limite"] }
    ]
  },
  {
    id: "fratture",
    number: "02",
    title: "Le fratture della vita",
    subtitle: "Maestro, testimone, politico irregolare: imparare a stare dentro e fuori",
    question: "Quali esperienze trasformano il problema storico della giustizia in una responsabilità personale di scrittura?",
    lesson: [
      { id: "fratture-formazione", heading: "Formarsi sotto una lingua ufficiale", text: `Sciascia attraversa l’adolescenza e la formazione nel fascismo. L’esperienza non va trasformata in una spiegazione totale, ma offre un contesto importante: il regime mostra quanto la lingua pubblica possa allontanarsi dai fatti e quanto l’uniformità verbale possa servire a cancellare il conflitto. A Caltanissetta, nell’Istituto magistrale, incontra insegnanti e letture che aprono spazi diversi; fra queste, l’insegnamento di Vitaliano Brancati rende percepibile la forza dell’ironia contro la retorica. La guerra spezza poi la pretesa di ordine del regime. Fame, notizie contraddittorie, caduta delle autorità e occupazione alleata fanno vedere la storia non come racconto lineare, ma come esperienza discontinua. Da questa formazione deriva una diffidenza stabile verso le parole troppo compatte: patria, popolo, ordine, emergenza possono diventare schermi se non sono sottoposte a verifica. Non significa che Sciascia rifiuti la politica o le istituzioni. Al contrario, le prende sul serio abbastanza da non accettarne il linguaggio automatico. La prima frattura è quindi linguistica e civile: fra ciò che il potere dice di essere e ciò che produce nella vita delle persone.` },
      { id: "fratture-lavoro", heading: "Gli uffici e la scuola: vedere la Repubblica dal basso", text: `Prima dell’affermazione letteraria Sciascia lavora in un ufficio legato all’ammasso del grano e poi insegna nelle elementari di Racalmuto. Sono osservatori concreti. L’ufficio mette davanti agli occhi la mediazione burocratica: moduli, disposizioni e gerarchie attraverso cui lo Stato incontra il cittadino. La scuola mostra una frattura ancora più profonda, quella fra italiano e dialetto, istruzione e povertà, cittadinanza formale e possibilità reale di prendere parola. Il maestro non incontra un’astratta “questione meridionale”, ma bambini, famiglie, assenze, lavori precoci, parole che non coincidono con quelle dei manuali. Gli studi universitari sulla lingua di Sciascia invitano a non semplificare il suo rapporto col dialetto. Egli ne riconosce la ricchezza culturale e lo lascia agire nell’italiano, ma vede anche il rischio che l’assenza di una lingua comune limiti l’accesso ai diritti. In questa tensione matura l’idea che l’italiano sia soprattutto ragionare: distinguere, connettere, rendere comunicabile un’esperienza. Le parrocchie di Regalpetra nasce da questo sguardo, ibridando memoria, inchiesta e racconto. La scuola non “causa” l’opera, ma rende intelligibile la sua attenzione alle voci escluse e alla precisione della lingua.` },
      { id: "fratture-editoria", heading: "Dalla provincia alla rete dei libri", text: `La scrittura mette Sciascia in rapporto con case editrici, riviste, artisti e lettori. Il dialogo con Italo Calvino ed Einaudi è decisivo non perché trasformi un autore locale in autore nazionale, ma perché sottopone i testi a un confronto rigoroso. Sciascia impara il lavoro della forma, la selezione, la misura; nello stesso tempo conserva una posizione periferica che diventa libertà di osservazione. La collaborazione con Sellerio e l’interesse per libri dimenticati, documenti, incisioni e microstorie ampliano la sua figura: scrittore, saggista, curatore, lettore che riattiva archivi. Il rapporto con la fotografia di Ferdinando Scianna mostra un’altra forma di conoscenza: l’immagine può documentare e insieme interpretare. Questa rete non elimina la solitudine, ma le dà strumenti. Sciascia può parlare dalla Sicilia senza essere confinato nella categoria del regionalismo. Può usare casi locali per interrogare inquisizione, impostura, mafia, scienza e Stato. La frattura è qui produttiva: entrare nell’industria culturale senza lasciarsi assorbire da una scuola, da un genere o da un gruppo. La sua opera conserverà infatti una mobilità irregolare fra romanzo, cronaca, saggio, pamphlet e nota critica.` },
      { id: "fratture-politica", heading: "L’impegno e il dissenso", text: `Sciascia non osserva la politica da una torre. È consigliere comunale a Palermo nelle liste del Partito comunista, poi deputato nazionale e parlamentare europeo per il Partito radicale. Queste appartenenze, diverse fra loro, mostrano una disponibilità all’azione e insieme l’impossibilità di identificarsi stabilmente con una disciplina di partito. La rottura più significativa non è il passaggio da una sigla all’altra, ma la scelta di giudicare i casi senza subordinare il ragionamento alla convenienza del proprio campo. L’affaire Moro, le polemiche sul terrorismo e l’articolo sui “professionisti dell’antimafia” rendono questa posizione duramente controversa. Su alcuni giudizi è legittimo dissentire; trasformare però il dissenso in scomunica significa perdere il nucleo della sua esperienza: la democrazia ha bisogno di lealtà critica, non di obbedienza. Sciascia paga questa scelta con l’isolamento e con interpretazioni spesso riduttive. L’esperienza politica conferma che il potere non vive soltanto nel governo; agisce anche nelle parole d’ordine, nelle identità collettive e nella pressione morale a non complicare la narrazione comune.` },
      { id: "fratture-solitudine", heading: "Malattia, ultimi libri e solitudine del giudizio", text: `Negli ultimi anni, segnati dalla malattia, la scrittura diventa più scarna e allegorica senza perdere il rapporto con il presente. Porte aperte, Il cavaliere e la morte e Una storia semplice mettono al centro individui che cercano una verità limitata dentro apparati più forti di loro. Sarebbe improprio derivare direttamente queste opere dalla condizione fisica dell’autore. È più prudente osservare una consonanza: la fragilità del corpo rende ancora più visibile la sproporzione fra individuo e potere, mentre la forma breve elimina tutto ciò che non è necessario. La traiettoria biografica non conduce a un eroe puro. Conduce a una postura: stare abbastanza dentro le istituzioni da conoscerne il linguaggio, abbastanza fuori da non confondere appartenenza e verità. Da qui nasce la sua immagine del mondo. La realtà non è un caos assoluto, perché gli indizi esistono e la ragione può collegarli; non è neppure un ordine trasparente, perché interessi e paure interrompono il percorso dalla conoscenza alla giustizia. La frattura decisiva diventa allora la solitudine di chi vede senza poter delegare ad altri la responsabilità del giudizio.` }
    ],
    summary: `Le fratture biografiche di Sciascia non spiegano meccanicamente le opere, ma rendono intelligibile la sua postura. La formazione nel fascismo e la guerra mostrano lo scarto fra lingua ufficiale e realtà. Il lavoro negli uffici e nella scuola rivela la Repubblica dal basso: burocrazia, povertà, distanza fra italiano e dialetto, accesso diseguale alla cittadinanza. Il rapporto con Calvino, Einaudi, Sellerio, la fotografia e gli archivi porta la provincia dentro una rete culturale nazionale senza cancellarne l’autonomia. L’esperienza politica, dal PCI ai radicali, culmina in un dissenso che rifiuta la disciplina dell’appartenenza. Negli ultimi libri la fragilità individuale si misura con apparati opachi. Ne deriva una postura insieme interna ed esterna alle istituzioni: conoscerne le regole, ma non delegare loro il proprio giudizio.`,
    essentials: [
      "Spiegare lo scarto fra lingua ufficiale fascista e realtà vissuta.",
      "Collegare scuola e uffici alla visione concreta della cittadinanza.",
      "Descrivere il rapporto non folklorico di Sciascia con il dialetto.",
      "Riconoscere il ruolo del confronto editoriale e degli archivi.",
      "Distinguere impegno politico e disciplina di partito.",
      "Definire la solitudine del giudizio come responsabilità, non isolamento estetico."
    ],
    vocab: [
      ["Lingua ufficiale", "Lessico pubblico che può descrivere la realtà oppure coprirne i conflitti."],
      ["Cittadinanza linguistica", "Possibilità di capire e usare la lingua comune per esercitare diritti."],
      ["Ibridazione", "Incontro fra racconto, memoria, documento, saggio e altri generi."],
      ["Militanza", "Partecipazione attiva a una causa o organizzazione politica."],
      ["Lealtà critica", "Fedeltà ai principi che include il controllo del proprio schieramento."],
      ["Postura", "Modo stabile di collocarsi intellettualmente davanti a fatti e poteri."
      ]
    ],
    map: "assets/maps/02-fratture.svg",
    mapAlt: "Mappa: formazione fascista, guerra, scuola, uffici, editoria e politica mettono in crisi le parole ufficiali e producono la postura interna ed esterna da cui nasce la solitudine del giudizio.",
    questions: [
      { stem: "Qual è la prima frattura civile della formazione di Sciascia?", options: ["Fra lingua pubblica del potere ed effetti reali", "Fra romanzo e poesia", "Fra Sicilia e ogni cultura europea"], correct: 0, feedback: "Il fascismo rende visibile come una lingua compatta possa occultare i fatti.", recovery: ["Parole e conseguenze", "La propaganda non è solo stile: altera il rapporto fra cittadini e realtà.", "La parola “ordine” può coprire violenza e censura.", "fratture-formazione"] },
      { stem: "Che cosa insegna l’esperienza scolastica?", options: ["Che il dialetto va cancellato", "Che lingua comune e possibilità di cittadinanza sono collegate", "Che la povertà non incide sull’istruzione"], correct: 1, feedback: "Per Sciascia la lingua comune amplia la possibilità di capire e far valere i diritti.", recovery: ["Lingua e cittadinanza", "Valorizzare il dialetto non significa rinunciare all’accesso all’italiano.", "Capire un modulo o una legge richiede strumenti linguistici condivisi.", "fratture-lavoro"] },
      { stem: "Quale effetto ha la rete editoriale sulla scrittura?", options: ["Cancella la prospettiva siciliana", "Impone un solo genere letterario", "Offre confronto e forma senza eliminare l’autonomia periferica"], correct: 2, feedback: "Il confronto nazionale disciplina la forma, mentre la periferia resta un punto di osservazione.", recovery: ["Centro e periferia", "Entrare in una rete culturale non obbliga a perdere la propria prospettiva.", "Calvino ed Einaudi offrono un vaglio formale, non una nuova identità.", "fratture-editoria"] },
      { stem: "Che cosa distingue l’impegno politico di Sciascia?", options: ["L’obbedienza costante allo stesso partito", "La pretesa di giudicare anche il proprio campo", "Il rifiuto di ogni incarico pubblico"], correct: 1, feedback: "La lealtà ai principi include la critica delle appartenenze.", recovery: ["Dissenso interno", "La democrazia richiede controllo anche verso chi sentiamo vicino.", "Sciascia cambia collocazione ma non rinuncia alla verifica dei casi.", "fratture-politica"] },
      { stem: "Come va collegata la malattia agli ultimi libri?", options: ["Come causa automatica delle trame", "Come fatto irrilevante da ignorare", "Come contesto prudente per leggere fragilità e forma scarna"], correct: 2, feedback: "La consonanza è plausibile, ma non autorizza uno psicologismo causale.", recovery: ["Biografia senza automatismi", "Un’esperienza può rendere intelligibile una tensione senza produrre direttamente un’opera.", "Fragilità fisica e individuo isolato sono consonanti, non equivalenti.", "fratture-solitudine"] }
    ]
  },
  {
    id: "immagine",
    number: "03",
    title: "L’immagine del mondo",
    subtitle: "Una ragione necessaria che non basta a salvare la verità",
    question: "Se la ragione può capire ma non sempre vincere, che cosa resta all’individuo?",
    lesson: [
      { id: "immagine-verita", heading: "La verità esiste, ma arriva ferita", text: `Il mondo di Sciascia non è relativista nel senso pigro per cui tutte le versioni si equivalgono. I fatti oppongono resistenza: un uomo è stato ucciso, un documento contiene una frase, una procedura ha avuto conseguenze. La verità è cercabile attraverso indizi, confronti, contraddizioni. Eppure non arriva mai in uno spazio neutro. Testimoni, investigatori, giudici, giornalisti e politici agiscono dentro rapporti di forza. Per questo la verità può essere intuita e perfino ricostruita senza diventare pubblicamente efficace. Nei suoi gialli l’enigma non fallisce perché il mondo sia privo di senso; fallisce perché la conoscenza incontra interessi capaci di neutralizzarla. È una differenza decisiva. Se non esistesse verità, l’indagine sarebbe un gioco vuoto. Se la verità vincesse sempre, il giallo classico basterebbe. Sciascia abita lo spazio intermedio: la ragione scopre abbastanza da rendere colpevole il silenzio, non abbastanza da garantire il lieto fine istituzionale.` },
      { id: "immagine-potere", heading: "Il potere come rete di irresponsabilità", text: `Il potere sciasciano raramente coincide con un tiranno solo. È una rete: notabili, funzionari, gerarchie ecclesiastiche, mafiosi, partiti, apparati di sicurezza, professionisti della parola. Ognuno può compiere un gesto limitato e dichiarare di non controllare l’insieme. Così la responsabilità si dissolve. Il potere moderno è forte proprio quando appare impersonale, quando trasforma una decisione in procedura e una scelta in necessità tecnica. L’allusione sostituisce l’ordine esplicito; il favore sostituisce il diritto; il segreto di Stato sostituisce la spiegazione. In questo sistema la mafia non è un residuo esotico. È una forma estrema e rivelatrice della confusione fra interesse privato e autorità pubblica. La “linea della palma” indica che tale logica può risalire la penisola: non perché ogni luogo diventi Sicilia, ma perché reti di protezione e silenzio possono modernizzarsi. Il potere teme soprattutto la precisione delle domande: chi sapeva? chi decise? quale documento manca? A queste domande oppone narrazioni generali, emergenze e formule che rendono impossibile attribuire un atto.` },
      { id: "immagine-storia", heading: "La storia non chiude i casi", text: `Per Sciascia il passato non è un deposito di esempi edificanti. È un archivio di casi riapribili. Inquisitori, impostori, processi e persecuzioni permettono di osservare il presente con una distanza critica. La storia ufficiale tende a chiudere: stabilisce una versione, ordina cause, assegna ruoli. La letteratura riapre quando torna ai documenti e ascolta ciò che la versione consolidata ha escluso. Non si tratta di inventare complotti dietro ogni lacuna. Al contrario, il metodo richiede di distinguere prova, ipotesi e possibilità. Il dubbio responsabile è diverso dal sospetto illimitato: accetta che alcuni punti restino incerti. In questo senso Sciascia è vicino a Manzoni. La giustizia non dipende solo dall’esattezza finale, ma dall’onestà della procedura con cui si tratta l’incertezza. Un potere ingiusto trasforma una supposizione utile in certezza comoda; uno scrittore responsabile segnala il limite delle prove. La memoria diventa così un’azione presente: impedisce che la conclusione amministrativa coincida con la fine del pensiero.` },
      { id: "immagine-individuo", heading: "L’individuo solo e la dignità del giudizio", text: `I personaggi sciasciani più memorabili non sono supereroi. Spesso sono funzionari, professori, giudici, investigatori: uomini interni a un’istituzione che, a un certo punto, scoprono di dover scegliere fra la logica dell’apparato e la fedeltà ai fatti. La loro solitudine non deriva da superiorità morale assoluta. Possono sbagliare, essere ingenui, arrivare tardi. La dignità sta nel non falsificare ciò che hanno compreso. Il capitano Bellodi, il professor Laurana, il piccolo giudice di Porte aperte o il Vice del Cavaliere e la morte rappresentano varianti di questa situazione. La ragione non li protegge, ma consente loro di non diventare complici interiori della menzogna. È una morale esigente e poco consolatoria: il valore di un atto non dipende soltanto dal successo. Tuttavia Sciascia non glorifica la sconfitta. Mostra piuttosto quanto costi una società che lascia soli coloro che esercitano responsabilmente il giudizio.` },
      { id: "immagine-espressione", heading: "Dal mondo alla necessità della forma", text: `Un mondo così non può essere raccontato con una forma che prometta armonia. Il narratore onnisciente, capace di spiegare ogni intenzione, rischierebbe di possedere una certezza che i documenti non consentono. Il giallo perfettamente risolto trasformerebbe il ragionamento in meccanismo consolatorio. Il saggio puro, d’altra parte, potrebbe perdere la tensione concreta delle vite coinvolte. Sciascia deve quindi costruire forme ibride: racconti-inchiesta, romanzi brevi, parodie poliziesche, montaggi di documenti, dialoghi, cronache. La sua poetica nascerà dal bisogno di far vedere contemporaneamente due movimenti: la mente che collega gli indizi e il potere che interrompe la conclusione. La chiarezza della prosa non elimina l’ambiguità del reale; la rende misurabile. La domanda espressiva è ormai definita: come scrivere con precisione senza fingere di sapere più di quanto le prove consentano?` }
    ],
    summary: `Per Sciascia la verità non è relativa: i fatti resistono e gli indizi possono essere collegati. Tuttavia la conoscenza nasce dentro rapporti di forza e può non tradursi in giustizia. Il potere appare come rete di irresponsabilità: ordini allusivi, procedure, favori, segreti e appartenenze dissolvono l’autore delle decisioni. La storia resta un archivio di casi da riaprire, ma il dubbio deve distinguere prova, ipotesi e possibilità. L’individuo giusto non è infallibile: conserva la dignità di non falsificare ciò che ha compreso, anche quando resta solo. Da questa immagine del mondo deriva una necessità formale. Né il giallo perfettamente risolto né il saggio astratto bastano; occorre una scrittura ibrida che mostri insieme la ricerca razionale e l’interruzione politica della verità.`,
    essentials: [
      "Distinguere la verità cercabile dalla sua efficacia pubblica.",
      "Descrivere il potere come rete che dissolve la responsabilità.",
      "Spiegare il valore della metafora della linea della palma.",
      "Separare dubbio responsabile e sospetto senza limiti.",
      "Interpretare la solitudine dell’individuo come fedeltà ai fatti.",
      "Collegare questa visione alla necessità di forme ibride."
    ],
    vocab: [
      ["Verità processuale", "Verità che può essere provata secondo regole e produrre effetti giuridici."],
      ["Irresponsabilità", "Dissoluzione dell’autore di una decisione dentro una rete o procedura."],
      ["Linea della palma", "Metafora dell’espansione verso nord di logiche mafiose e clientelari."],
      ["Dubbio responsabile", "Sospensione del giudizio proporzionata ai limiti delle prove."],
      ["Apparato", "Organizzazione istituzionale capace di agire attraverso ruoli e procedure."],
      ["Ibridazione", "Forma che intreccia generi diversi per rappresentare una realtà complessa."]
    ],
    map: "assets/maps/03-immagine.svg",
    mapAlt: "Mappa: gli indizi rendono la verità cercabile, ma le reti di potere dissolvono responsabilità; storia e dubbio riaprono i casi, l’individuo conserva il giudizio e ciò richiede forme ibride.",
    questions: [
      { stem: "Qual è la posizione di Sciascia sulla verità?", options: ["Ogni versione vale quanto le altre", "La verità è cercabile ma può restare senza efficacia pubblica", "La verità appartiene sempre alle istituzioni"], correct: 1, feedback: "Gli indizi resistono, ma potere e procedure possono neutralizzarne gli effetti.", recovery: ["Verità ferita", "Conoscere un fatto e farlo riconoscere pubblicamente sono due passaggi diversi.", "Un investigatore può capire chi è colpevole senza ottenere una condanna.", "immagine-verita"] },
      { stem: "Come opera soprattutto il potere moderno nei testi di Sciascia?", options: ["Come rete che frammenta decisioni e responsabilità", "Solo attraverso ordini violenti espliciti", "Come forza completamente esterna allo Stato"], correct: 0, feedback: "La rete rende ogni gesto parziale e l’insieme apparentemente senza autore.", recovery: ["Rete di irresponsabilità", "Il potere può nascondersi nella distribuzione dei ruoli.", "Un funzionario esegue, un politico suggerisce, nessuno ammette di decidere.", "immagine-potere"] },
      { stem: "Che cosa significa riaprire un caso storico?", options: ["Inventare una spiegazione segreta", "Rifiutare ogni documento ufficiale", "Tornare alle prove e alle voci escluse distinguendo ipotesi e certezze"], correct: 2, feedback: "La riapertura è critica documentaria, non complottismo.", recovery: ["Archivio critico", "Il dubbio vale quando resta proporzionato alle fonti.", "Una lacuna autorizza una domanda, non una certezza arbitraria.", "immagine-storia"] },
      { stem: "Dove sta la dignità dei personaggi investigatori?", options: ["Nella loro infallibilità", "Nel non falsificare ciò che hanno compreso", "Nel vincere sempre contro l’apparato"], correct: 1, feedback: "Il valore del giudizio non coincide con il successo finale.", recovery: ["Fedeltà ai fatti", "L’individuo può perdere senza rendere falsa la propria ricerca.", "Il giudice può essere sconfitto ma rifiutare una sentenza conveniente.", "immagine-individuo"] },
      { stem: "Perché servono forme narrative ibride?", options: ["Per tenere insieme indagine razionale e limiti delle prove", "Per evitare ogni rapporto con la storia", "Per rendere la lingua deliberatamente oscura"], correct: 0, feedback: "L’ibridazione unisce concretezza narrativa, documenti e argomentazione.", recovery: ["Forma necessaria", "Un solo genere non rappresenta insieme fatti, ipotesi e conflitto politico.", "Il racconto-inchiesta usa documenti senza rinunciare alla tensione narrativa.", "immagine-espressione"] }
    ]
  },
  {
    id: "poetica",
    number: "04",
    title: "La poetica",
    subtitle: "Il giallo sabotato, il documento interrogato, la lingua che ragiona",
    question: "Come si scrive una verità incompleta senza trasformarla né in favola consolatoria né in sospetto arbitrario?",
    lesson: [
      { id: "poetica-giallo", heading: "Usare il giallo contro la consolazione del giallo", text: `Il poliziesco classico promette un piacere ordinato: il delitto rompe l’equilibrio, l’investigatore ricompone gli indizi, la soluzione ristabilisce la leggibilità del mondo. Sciascia conserva il motore dell’indagine ma ne altera l’esito. Il lettore non può delegare completamente il ragionamento al detective, perché la soluzione può restare incompleta, essere cancellata o non produrre giustizia. Il giallo diventa “imperfetto” in senso intenzionale: la mancata chiusura non è un difetto tecnico, ma la forma di una società in cui il colpevole dispone di protezioni superiori alla prova. In A ciascuno il suo il professor Laurana legge correttamente alcuni segni ma non comprende abbastanza la rete umana in cui si muove; in Il giorno della civetta Bellodi ricostruisce il meccanismo, mentre altri lavorano a dissolverlo. Il lettore è costretto a una posizione meno comoda: sa più della versione ufficiale, ma non può rifugiarsi nella vittoria finale. La poetica trasforma così un genere popolare in educazione al pensiero critico.` },
      { id: "poetica-documento", heading: "Il documento non parla da solo", text: `Nei racconti-inchiesta e nelle ricostruzioni storiche Sciascia usa lettere, verbali, cronache, atti giudiziari e testimonianze. Non li tratta come blocchi di verità già pronti. Ogni documento è prodotto da qualcuno, in una situazione, per un destinatario e con uno scopo. Leggerlo significa osservare parole scelte, omissioni, contraddizioni e contesto. L’autore monta i frammenti e rende visibile il proprio atto interpretativo; quando formula un’ipotesi, non dovrebbe cancellarne il carattere ipotetico. È qui che il modello manzoniano della Colonna infame diventa decisivo. La scrittura storica responsabile non entra liberamente nella mente dei protagonisti: si muove fra prova e supposizione. La scomparsa di Majorana e L’affaire Moro portano questo metodo nel Novecento. Non sono semplici dossier, perché la disposizione dei materiali produce significato; non sono romanzi liberi, perché persone e documenti impongono limiti. La letteratura diventa un modo di leggere il reale quando le carte ufficiali non bastano o sono state interpretate troppo in fretta.` },
      { id: "poetica-lingua", heading: "Una lingua nitida, non innocente", text: `La prosa di Sciascia appare spesso limpida, breve, controllata. Sarebbe però sbagliato confondere chiarezza con semplicità ingenua. Le frasi sono costruite come passaggi di un ragionamento; allusione, inciso, ripresa e opposizione obbligano il lettore a valutare rapporti. Gli studi linguistici mostrano un’evoluzione: dalle componenti regionali e popolari delle prime opere a una medietà espressiva capace di accogliere tradizione, burocratismi, termini giuridici e tracce del siciliano. Il dialetto non funziona come decorazione folklorica. Può nominare un oggetto culturale, caratterizzare una voce, inserire nell’italiano una sintassi o un ritmo dell’isola. La lingua della ragione conserva dunque un ordito locale. Questa tensione riflette l’immagine del mondo: l’italiano rende comunicabile e discutibile l’esperienza, il siciliano ricorda ciò che la lingua nazionale rischia di appiattire. Anche l’ironia è uno strumento di precisione. Non serve a evitare il giudizio, ma a far crollare le parole solenni che pretendono di sottrarsi al controllo.` },
      { id: "poetica-generi", heading: "Brevità, montaggio e contaminazione", text: `Sciascia preferisce spesso forme brevi e ad alta densità: romanzo corto, racconto, pamphlet, nota, conversazione critica. La brevità non riduce la complessità; elimina passaggi ornamentali e lascia che ogni dettaglio abbia peso. Il montaggio accosta scene, documenti, dialoghi e commenti senza produrre sempre una spiegazione totale. Questa tecnica chiede al lettore di costruire relazioni. I confini fra fiction e non-fiction diventano mobili, ma non arbitrari. Nel romanzo un caso inventato può rivelare un meccanismo storico; nell’inchiesta un fatto reale viene disposto con strumenti narrativi. La parodia permette di assumere una forma e insieme mostrarne il fallimento: Il contesto e Todo modo somigliano a gialli, ma trasformano l’indagine in una radiografia grottesca del potere. L’intertestualità è altrettanto importante. Citare, riscrivere e conversare con Manzoni, Voltaire, Pirandello o Borges significa collocare il caso presente in una biblioteca di problemi. Per Sciascia scrivere è spesso riscrivere: riaprire un testo precedente perché illumini una responsabilità attuale.` },
      { id: "poetica-lettore", heading: "Il lettore come giudice non sovrano", text: `Questa poetica assegna al lettore un compito etico. Deve collegare indizi, distinguere livelli di certezza, riconoscere le strategie linguistiche del potere. Ma non diventa un giudice onnipotente. Non può colmare ogni vuoto con ciò che desidera credere. Sciascia educa contemporaneamente alla ricerca e al limite: sospettare delle versioni comode, ma sospettare anche del proprio sospetto. È una lezione preziosa nell’epoca dell’informazione accelerata. La forma sciasciana chiede di domandare sempre quale prova sostiene un’affermazione, quale alternativa è stata esclusa, chi trae vantaggio da una narrazione. Le opere più significative mettono alla prova questa poetica in contesti diversi: mafia, impostura storica, potere politico-religioso, scienza, terrorismo, pena di morte. Non ripetono una formula; verificano fino a che punto il metodo dell’indagine regga quando cresce la pressione del potere.` }
    ],
    summary: `La poetica di Sciascia nasce dal bisogno di rappresentare una verità cercabile ma ostacolata. Il giallo viene sabotato: conserva indizi e investigatore, ma perde la soluzione consolatoria. Il documento non è una prova autosufficiente; va interrogato nella sua situazione, nelle omissioni e nel montaggio. La lingua è nitida e argomentativa, attraversata da allusione, ironia, lessico giuridico e ordito siciliano. La brevità concentra il peso dei dettagli; l’ibridazione unisce romanzo, saggio, cronaca, pamphlet e archivio. Citazioni e riscritture collegano il caso presente a una biblioteca di problemi. Il lettore deve ragionare senza diventare sovrano: cercare indizi, graduare le certezze e controllare anche il proprio sospetto. Le opere verificano questo metodo su mafia, giustizia, scienza e ragion di Stato.`,
    essentials: [
      "Spiegare perché il giallo imperfetto è una scelta formale e politica.",
      "Descrivere il documento come oggetto situato e interpretabile.",
      "Riconoscere chiarezza, allusione, ironia e ordito siciliano nella prosa.",
      "Collegare brevità e densità del significato.",
      "Distinguere ibridazione dei generi e arbitrio inventivo.",
      "Definire il lettore come ricercatore responsabile e limitato."
    ],
    vocab: [
      ["Giallo imperfetto", "Indagine che non ristabilisce pienamente ordine e giustizia."],
      ["Montaggio", "Disposizione significativa di scene, documenti e commenti."],
      ["Allusione", "Strategia che comunica indirettamente e richiede inferenza."],
      ["Pamphlet", "Testo breve e polemico che interviene su un problema pubblico."],
      ["Intertestualità", "Relazione esplicita o implicita fra un testo e testi precedenti."],
      ["Non-fiction", "Scrittura narrativa vincolata a persone, fatti e documenti reali."
      ]
    ],
    map: "assets/maps/04-poetica.svg",
    mapAlt: "Mappa: la verità ostacolata si traduce in giallo imperfetto, documento interrogato, lingua nitida, montaggio breve e generi ibridi, che affidano al lettore un’indagine responsabile.",
    questions: [
      { stem: "Perché il giallo di Sciascia è detto imperfetto?", options: ["Perché manca di indizi", "Perché l’autore non conosce il genere", "Perché la soluzione può non ristabilire la giustizia"], correct: 2, feedback: "La mancata chiusura rappresenta il potere che neutralizza la verità.", recovery: ["Giallo sabotato", "L’imperfezione è intenzionale e storicamente significativa.", "Bellodi ricostruisce, ma la rete politica tenta di cancellare l’esito.", "poetica-giallo"] },
      { stem: "Come tratta Sciascia un documento?", options: ["Come prodotto situato da interrogare", "Come verità che non richiede contesto", "Come ostacolo inutile alla fantasia"], correct: 0, feedback: "Autore, destinatario, scopo e omissioni partecipano al significato.", recovery: ["Documento situato", "Una carta prova qualcosa, ma va letta nelle condizioni in cui è nata.", "Una lettera privata e un verbale ufficiale hanno scopi diversi.", "poetica-documento"] },
      { stem: "Quale funzione ha il dialetto nella prosa?", options: ["Solo comicità folklorica", "Conservare un ordito culturale dentro la lingua del ragionamento", "Sostituire completamente l’italiano"], correct: 1, feedback: "Le tracce siciliane nominano esperienze e intensificano la comunicazione.", recovery: ["Ordito linguistico", "Il dialetto agisce come memoria culturale, non come costume decorativo.", "Una parola locale può nominare un referente che l’italiano appiattisce.", "poetica-lingua"] },
      { stem: "Che rapporto c’è fra brevità e complessità?", options: ["La brevità elimina ogni ambiguità", "La brevità impoverisce necessariamente il pensiero", "La brevità concentra il peso di dettagli e relazioni"], correct: 2, feedback: "La forma corta aumenta la densità e chiede partecipazione al lettore.", recovery: ["Densità", "Meno pagine non significano meno nessi.", "Un dettaglio isolato in un romanzo breve può orientare l’intera indagine.", "poetica-generi"] },
      { stem: "Qual è il compito del lettore?", options: ["Collegare indizi e graduare le certezze", "Riempire ogni lacuna con un complotto", "Accettare la versione del narratore senza verifica"], correct: 0, feedback: "Il lettore indaga, ma deve rispettare i limiti delle prove.", recovery: ["Giudizio limitato", "Pensiero critico significa controllo delle fonti e anche di sé.", "Una lacuna autorizza una domanda, non qualsiasi risposta.", "poetica-lettore"] }
    ]
  },
  {
    id: "opere",
    number: "05",
    title: "Le opere più significative",
    subtitle: "Cinque laboratori in cui la verità incontra il potere",
    question: "Dove il metodo di Sciascia diventa conflitto narrativo e quale limite rivela ogni opera?",
    lesson: [
      { id: "opere-regalpetra", heading: "Le parrocchie di Regalpetra: dare forma a un paese", text: `Nel 1956 Le parrocchie di Regalpetra inaugura la forma matura dello sguardo sciasciano. Regalpetra è Racalmuto trasformata: non una copia fotografica, ma un luogo letterario capace di tenere insieme storia, cronaca, memoria, scuola, zolfare e rapporti sociali. L’opera sfugge alle classificazioni rigide. Non è soltanto inchiesta, perché la voce ordina e interpreta; non è soltanto autobiografia, perché l’io si apre a esperienze collettive; non è romanzo tradizionale, perché conserva il peso del documento. Il maestro osserva povertà e disuguaglianza senza idealizzare il popolo. Anche gli esclusi possono riprodurre pregiudizi e dipendenze. Il bersaglio non è una colpa antropologica dei siciliani, ma un sistema che rende normale il sopruso. Qui nasce la strategia fondamentale: partire dal microcosmo per interrogare la nazione. La precisione dei dettagli locali impedisce al discorso civile di diventare astratto.` },
      { id: "opere-civetta", heading: "Il giorno della civetta: sapere senza poter vincere", text: `Pubblicato nel 1961, Il giorno della civetta porta la mafia dentro il romanzo italiano quando la sua stessa esistenza viene ancora minimizzata nel discorso pubblico. L’omicidio iniziale attiva l’indagine del capitano Bellodi, carabiniere settentrionale che cerca di applicare la logica della prova in un ambiente regolato da silenzio e protezioni. Il romanzo non oppone semplicemente un Nord razionale a un Sud irrazionale: Bellodi comprende che il meccanismo mafioso comunica con interessi politici nazionali. La celebre “linea della palma” rompe l’idea della mafia come residuo confinato. La struttura gialla conduce a una conoscenza plausibile, ma l’apparato lavora per screditarla. La verità dell’investigatore e la verità processuale si separano. Il finale non annulla la ricerca: mostra il costo politico della sua sterilizzazione. L’opera fonda così un’antimafia non retorica, attenta al rapporto fra criminalità, classe dirigente e produzione delle versioni ufficiali.` },
      { id: "opere-ciascuno", heading: "A ciascuno il suo: l’intelligenza senza competenza del mondo", text: `Nel 1966 A ciascuno il suo radicalizza il giallo imperfetto. Il professor Laurana riconosce un indizio linguistico e segue una catena di connessioni che lo avvicina alla verità. È colto, curioso, capace di leggere; ma interpreta la società come se fosse soltanto un testo. Non comprende fino in fondo sguardi, interessi, convenienze e pericoli. La sua intelligenza è reale e insufficiente. Sciascia mette così in discussione la figura dell’intellettuale: possedere gli strumenti della cultura non garantisce di capire le forme concrete del potere. La comunità, alla fine, ricompone una versione accettabile e classifica Laurana come uomo ingenuo. Il lettore conosce l’ingiustizia di questo giudizio ma deve riconoscere anche il limite del protagonista. La ragione ha bisogno di coraggio, esperienza e comprensione dei rapporti umani; altrimenti può consegnarsi da sola alla rete che pretende di smascherare.` },
      { id: "opere-majorana", heading: "La scomparsa di Majorana: il confine dell’ipotesi", text: `La scomparsa di Majorana, del 1975, ricostruisce il caso reale del fisico sparito nel 1938 e propone l’ipotesi di una scelta volontaria legata anche alla percezione delle conseguenze della fisica nucleare. Il libro è esemplare e controverso proprio perché mette alla prova il confine fra documento e interpretazione. Sciascia legge lettere, testimonianze, tempi e caratteri; costruisce una figura morale di Majorana e usa la letteratura per rendere pensabile ciò che l’archivio non chiude. La forza dell’opera non coincide con la dimostrazione definitiva dell’ipotesi. Sta nella domanda sulla responsabilità dello scienziato e nel modo in cui un’assenza obbliga a esaminare le narrazioni disponibili. Il lettore deve distinguere ciò che le carte attestano, ciò che l’autore inferisce e ciò che resta possibile. Qui l’inchiesta diventa anche autoritratto indiretto: lo scrittore riconosce nel fisico la solitudine di chi sottrae la propria coscienza alle aspettative dell’apparato.` },
      { id: "opere-moro", heading: "L’affaire Moro e Porte aperte: lo Stato davanti all’individuo", text: `L’affaire Moro, pubblicato nel 1978 dopo il sequestro e l’uccisione del presidente della Democrazia cristiana, legge le lettere dalla prigionia contro la tendenza a considerarle parole non autentiche. Sciascia insiste sulla persona concreta di Moro, stretta fra il linguaggio delle Brigate rosse e quello della ragion di Stato. Il libro interviene in una ferita ancora aperta e suscita contestazioni: proprio per questo va letto distinguendo la legittimità delle domande dalla discussione sulle singole conclusioni. La letteratura presta attenzione alle parole quando la politica le riduce a funzioni. In Porte aperte, del 1987, un piccolo giudice nella Palermo fascista rifiuta che la richiesta esemplare della pena di morte sostituisca il diritto. Il caso è diverso, il nucleo comune no: l’istituzione tende a usare l’individuo per confermare la propria immagine. Il giudice non nega il delitto; nega che la giustizia coincida con la vendetta pubblica. Dalle prime cronache all’ultimo decennio, Sciascia verifica la stessa domanda in campi differenti: come impedire che la necessità collettiva cancelli la persona e la precisione dei fatti?` }
    ],
    summary: `Cinque opere mostrano la coerenza e le variazioni del laboratorio sciasciano. Le parrocchie di Regalpetra trasforma un paese in microcosmo nazionale e ibrida memoria, inchiesta e racconto. Il giorno della civetta separa conoscenza investigativa e giustizia processuale, collegando mafia e potere politico. A ciascuno il suo mostra il limite dell’intellettuale che legge gli indizi ma non la rete sociale. La scomparsa di Majorana usa documenti e ipotesi per interrogare la responsabilità scientifica, senza chiudere definitivamente il caso. L’affaire Moro restituisce peso alle parole della persona prigioniera contro i linguaggi contrapposti degli apparati; Porte aperte oppone il diritto alla vendetta di Stato. In ogni testo l’indagine produce verità parziali e misura la pressione con cui il potere tenta di renderle innocue.`,
    essentials: [
      "Spiegare la forma ibrida e il microcosmo di Regalpetra.",
      "Collegare Il giorno della civetta alla separazione fra verità e giustizia.",
      "Interpretare il limite intellettuale di Laurana.",
      "Distinguere documenti, inferenze e possibilità nel caso Majorana.",
      "Descrivere il conflitto di linguaggi nell’Affaire Moro.",
      "Collegare Porte aperte al rifiuto della giustizia come vendetta."
    ],
    vocab: [
      ["Microcosmo", "Luogo circoscritto che rende leggibili dinamiche più ampie."],
      ["Verità processuale", "Ricostruzione dei fatti riconosciuta secondo prove e procedure giudiziarie."],
      ["Intellettuale", "Figura che usa strumenti culturali per interpretare e intervenire nello spazio pubblico."],
      ["Inferenza", "Conclusione ragionata ottenuta da indizi, distinta dalla prova diretta."],
      ["Affaire", "Caso pubblico in cui fatti, interpretazioni e conflitto politico restano intrecciati."],
      ["Pena di morte", "Sanzione statale definitiva che Porte aperte interroga sul piano del diritto e della civiltà."
      ]
    ],
    map: "assets/maps/05-opere.svg",
    mapAlt: "Mappa: Regalpetra costruisce il microcosmo; Civetta separa verità e giustizia; A ciascuno il suo limita l’intellettuale; Majorana misura l’ipotesi; Moro e Porte aperte oppongono persona e apparato.",
    questions: [
      { stem: "Quale forma caratterizza Le parrocchie di Regalpetra?", options: ["Un romanzo fantastico puro", "Un’ibridazione di memoria, inchiesta e racconto", "Un trattato economico senza voce autoriale"], correct: 1, feedback: "Il libro usa più forme per fare del paese un microcosmo.", recovery: ["Regalpetra ibrida", "Il luogo reale viene trasformato da una voce che documenta e interpreta.", "Scuola, zolfare e storia convivono senza diventare un catalogo.", "opere-regalpetra"] },
      { stem: "Che cosa fallisce nel Giorno della civetta?", options: ["La capacità di Bellodi di collegare gli indizi", "L’esistenza di qualsiasi responsabile", "La trasformazione della conoscenza in giustizia efficace"], correct: 2, feedback: "L’apparato neutralizza sul piano pubblico ciò che l’indagine ha compreso.", recovery: ["Verità senza esito", "La soluzione cognitiva non garantisce la soluzione giudiziaria.", "Bellodi ricostruisce, ma le protezioni politiche dissolvono il caso.", "opere-civetta"] },
      { stem: "Qual è il limite del professor Laurana?", options: ["Legge i segni ma non comprende abbastanza la rete sociale", "Non sa riconoscere alcun indizio", "È parte consapevole dell’organizzazione criminale"], correct: 0, feedback: "La cultura testuale non basta a muoversi nei rapporti concreti di potere.", recovery: ["Intelligenza insufficiente", "Capire una parola non equivale a capire chi può colpire.", "Laurana ricostruisce il nesso ma sottovaluta persone e convenienze.", "opere-ciascuno"] },
      { stem: "Come va letta l’ipotesi su Majorana?", options: ["Come prova scientifica definitiva", "Come costruzione interpretativa fondata su indizi ma non conclusiva", "Come invenzione priva di documenti"], correct: 1, feedback: "Il libro rende pensabile una possibilità e ne espone il margine ipotetico.", recovery: ["Gradi di certezza", "Documento, inferenza e possibilità non sono sinonimi.", "Una lettera attesta parole; la motivazione della scomparsa resta interpretata.", "opere-majorana"] },
      { stem: "Che cosa accomuna L’affaire Moro e Porte aperte?", options: ["Il rifiuto di ogni istituzione", "L’ambientazione nella stessa epoca", "La difesa della persona contro l’uso che l’apparato ne fa"], correct: 2, feedback: "In entrambi i casi l’individuo rischia di diventare funzione della necessità pubblica.", recovery: ["Persona e apparato", "Lo Stato si giudica anche dal modo in cui tratta il singolo.", "Moro viene ridotto a funzione politica; il condannato a esempio punitivo.", "opere-moro"] }
    ]
  },
  {
    id: "conclusione",
    number: "06",
    title: "Conclusione",
    subtitle: "La ragione dopo la sconfitta: un’eredità senza catechismo",
    question: "È ancora civile una verità che non riesce a vincere, oppure diventa soltanto testimonianza?",
    lesson: [
      { id: "conclusione-traiettoria", heading: "Ricomporre i sei movimenti", text: `Il percorso di Sciascia parte da un mondo in cui la legge moderna convive con poteri informali e attraversa esperienze che rendono personale quella contraddizione: fascismo, guerra, scuola, uffici, editoria, politica. Da qui emerge un’immagine del mondo precisa. La verità non è un’invenzione arbitraria; può essere cercata nei fatti e nei documenti. Ma il potere agisce sulla distanza fra conoscere e rendere efficace ciò che si conosce. La poetica traduce questa visione in forme: giallo senza consolazione, documento interrogato, romanzo breve, racconto-inchiesta, lingua nitida e allusiva. Le opere mettono alla prova il metodo su mafia, impostura, scienza, terrorismo, pena di morte. La conclusione non è che la ragione fallisca e debba essere abbandonata. È più dura: la ragione resta l’unico strumento condivisibile proprio quando non garantisce la vittoria. Rinunciarvi perché è fragile significherebbe consegnare il campo alla forza, al mito e all’appartenenza cieca.` },
      { id: "conclusione-eredita", heading: "Un classico civile, non un oracolo", text: `Sciascia è diventato un classico civile perché offre un metodo di attenzione: leggere le parole del potere, seguire le responsabilità, non confondere una causa giusta con l’infallibilità di chi la rappresenta. Ma un classico non è un oracolo. Alcuni interventi pubblici restano controversi e possono essere criticati. Difendere la sua eredità non significa trasformare ogni giudizio in profezia confermata. Significa preservare il diritto di sottoporre anche Sciascia al metodo che egli esigeva dagli altri: prove, contesto, distinzione fra ipotesi e certezza. Questa reciprocità lo salva dalla santificazione. La sua figura è più utile se resta irregolare, capace di errore e tuttavia necessaria. Una cultura democratica non si misura dalla quantità di icone civili che espone, ma dalla capacità di accettare domande scomode senza ridurle a tradimento.` },
      { id: "conclusione-presente", heading: "Dal segreto di Stato all’opacità digitale", text: `L’attualità di Sciascia non dipende dal fatto che ogni vicenda contemporanea ripeta un suo romanzo. Dipende dalla permanenza del problema: chi costruisce le versioni pubbliche e con quali prove? Oggi l’opacità non nasce soltanto dalla scarsità di informazioni. Può nascere dall’eccesso: documenti, dichiarazioni, immagini e commenti si accumulano fino a rendere difficile stabilire gerarchie di affidabilità. La lezione sciasciana impedisce due scorciatoie opposte. La prima è credere automaticamente alla versione istituzionale; la seconda è considerare falsa ogni versione istituzionale e vero qualunque racconto alternativo. In entrambi i casi il giudizio viene delegato. Il suo lettore ideale controlla fonti, interessi, lessico e omissioni; accetta di concludere “non so ancora” quando le prove non bastano. Nell’ambiente digitale, la precisione diventa una forma di resistenza alla velocità.` },
      { id: "conclusione-scuola", heading: "Perché portarlo a scuola", text: `A scuola Sciascia non serve soltanto per parlare di mafia. Serve per esercitare la cittadinanza linguistica e documentaria. Una classe può confrontare titolo, verbale, testimonianza e commento; può distinguere fatto, inferenza e giudizio; può osservare come una risposta formalmente corretta nasconda una domanda decisiva. L’interdisciplinarità è naturale: letteratura e storia per il contesto, diritto per procedure e garanzie, educazione civica per responsabilità istituzionale, scienze per il caso Majorana, media literacy per le fonti. Tuttavia la scuola tradirebbe Sciascia se trasformasse il percorso in un repertorio di frasi da ricordare. La competenza essenziale è saper ricostruire il nesso: un mondo produce una crisi; la crisi modifica lo sguardo; lo sguardo esige una forma; la forma viene verificata nelle opere. Il test più serio non chiede “che cosa pensava Sciascia?”, ma “con quali passaggi e quali limiti possiamo sostenerlo?”.` },
      { id: "conclusione-domanda", heading: "La domanda che resta aperta", text: `Resta infine una questione non risolvibile con una formula. Se un individuo ricostruisce la verità ma non riesce a trasformarla in giustizia, il suo lavoro è politicamente sconfitto oppure conserva un valore civile? Sciascia sembra rispondere che la testimonianza precisa impedisce almeno una seconda vittoria del potere: far credere che nulla fosse conoscibile. Ma questa risposta non basta del tutto. Una democrazia non può accontentarsi di produrre testimoni nobili e sconfitti; deve costruire istituzioni capaci di non lasciarli soli. Qui la letteratura incontra il suo limite e la sua forza. Non emette sentenze, non sostituisce tribunali, non governa. Può però rendere intollerabile una versione comoda e conservare la domanda finché la società sarà in grado di riprenderla. Conserva inoltre il lessico necessario per nominare l’abuso: senza parole precise, perfino l’indignazione diventa facilmente manipolabile. La vera eredità di Sciascia non è il pessimismo. È l’obbligo di continuare a distinguere, anche quando distinguere non conviene, e di chiedere alle istituzioni non una promessa astratta di trasparenza, ma procedure controllabili e responsabilità riconoscibili.` }
    ],
    summary: `La traiettoria di Sciascia unisce Sicilia, fratture biografiche, ragione critica, forme investigative e opere civili. La ragione non garantisce la vittoria, ma resta l’unico metodo condivisibile contro forza, mito e appartenenza. L’autore va letto come classico, non come oracolo: i suoi giudizi sono discutibili e devono essere sottoposti allo stesso controllo delle prove che egli richiede. Nel presente digitale l’opacità nasce anche dall’eccesso di informazioni; perciò occorre evitare sia la fiducia automatica nelle istituzioni sia il sospetto automatico contro di esse. A scuola Sciascia permette di esercitare cittadinanza linguistica e documentaria. La domanda finale resta aperta: una verità sconfitta è ancora civile? La letteratura non sostituisce la giustizia, ma può impedire che il potere presenti l’ingiustizia come realtà incomprensibile.`,
    essentials: [
      "Ricostruire la catena dai contesti alle opere senza salti causali.",
      "Spiegare perché la fragilità della ragione non giustifica il suo abbandono.",
      "Leggere Sciascia criticamente, senza santificarlo.",
      "Applicare il metodo alle fonti digitali e alle versioni pubbliche.",
      "Collegare letteratura, diritto, storia, scienza ed educazione civica.",
      "Argomentare il valore e il limite della testimonianza letteraria."
    ],
    vocab: [
      ["Classico civile", "Autore che offre strumenti durevoli per discutere responsabilità e vita pubblica."],
      ["Media literacy", "Capacità di valutare fonti, linguaggi e interessi nei media."],
      ["Santificazione", "Trasformazione di un autore in autorità sottratta alla critica."],
      ["Testimonianza", "Conservazione responsabile di fatti o interpretazioni anche senza vittoria immediata."],
      ["Opacità informativa", "Difficoltà di capire prodotta da segreto, confusione o eccesso di dati."],
      ["Cittadinanza documentaria", "Capacità di leggere prove, procedure e versioni per partecipare alla vita pubblica."
      ]
    ],
    map: "assets/maps/06-conclusione.svg",
    mapAlt: "Mappa di sintesi: mondo ricevuto mette in crisi la giustizia; fratture producono responsabilità; immagine del mondo esige indagine; poetica confluisce nelle opere; le opere lasciano un metodo civile e una domanda aperta.",
    questions: [
      { stem: "Qual è la conclusione sulla ragione?", options: ["Va abbandonata perché non vince sempre", "Resta necessaria proprio senza garanzia di vittoria", "Coincide con la versione delle istituzioni"], correct: 1, feedback: "La fragilità del metodo non rende preferibili forza o appartenenza.", recovery: ["Ragione necessaria", "Un metodo vale anche perché rende gli errori controllabili.", "La prova può fallire in tribunale senza diventare equivalente a una voce arbitraria.", "conclusione-traiettoria"] },
      { stem: "Come va trattato Sciascia come classico?", options: ["Sottoponendo anche lui a prove e contesto", "Accettando ogni giudizio come profezia", "Separando completamente opere e spazio pubblico"], correct: 0, feedback: "La fedeltà migliore applica all’autore il suo stesso metodo critico.", recovery: ["Classico non oracolo", "Un autore resta vivo se può essere discusso con rigore.", "Si possono difendere le domande dell’Affaire Moro e contestarne alcune conclusioni.", "conclusione-eredita"] },
      { stem: "Quale doppia scorciatoia va evitata oggi?", options: ["Leggere libri e documenti", "Usare fonti universitarie e giornalistiche", "Credere sempre alle istituzioni o sempre alle versioni alternative"], correct: 2, feedback: "Entrambe le posizioni delegano il giudizio invece di verificare.", recovery: ["Due automatismi", "Fiducia cieca e sospetto cieco hanno la stessa struttura.", "Una fonte istituzionale va controllata; una fonte alternativa non è vera solo perché alternativa.", "conclusione-presente"] },
      { stem: "Qual è la competenza scolastica essenziale?", options: ["Memorizzare etichette sull’autore", "Ricostruire nessi e gradi di certezza", "Ripetere una citazione fuori contesto"], correct: 1, feedback: "Il metodo chiede passaggi argomentati, fonti e limiti.", recovery: ["Competenza, non catechismo", "Sapere significa spiegare come si arriva a una tesi.", "Distinguere fatto, inferenza e giudizio vale più di una data isolata.", "conclusione-scuola"] },
      { stem: "Quale forza conserva la letteratura quando non produce giustizia?", options: ["Può impedire che l’ingiustizia appaia incomprensibile", "Può sostituire automaticamente i tribunali", "Può garantire una soluzione definitiva"], correct: 0, feedback: "La testimonianza precisa conserva fatti e domande per una ripresa futura.", recovery: ["Valore della testimonianza", "La letteratura non governa, ma può rendere contestabile una versione comoda.", "Un caso archiviato può restare leggibile grazie a documenti e racconto.", "conclusione-domanda"] }
    ]
  }
];

const SCIASCIA_SOURCES = [
  { label: "Università di Bologna · Percorso di letture", url: "https://site.unibo.it/griseldaonline/it/didattica/marco-laudieri-leonardo-sciascia" },
  { label: "Università di Bologna · Sciascia e Manzoni", url: "https://site.unibo.it/griseldaonline/it/didattica/carlo-varotti-leonardo-sciascia-manzoni-luogo-comune-stupidita" },
  { label: "Università di Bologna · Sciascia lettore", url: "https://site.unibo.it/griseldaonline/it/didattica/agostino-arciuolo-sciascia-lettore" },
  { label: "Università di Bologna · Gialli imperfetti (tesi)", url: "https://amsdottorato.unibo.it/8005/1/TesiFaienza%20%281%29.pdf" },
  { label: "Università di Palermo · La lingua di Sciascia (tesi)", url: "https://iris.unipa.it/retrieve/d6d8681a-c8ef-4884-8ef0-c90b6814ddfb/LA%20LINGUA%20DI%20SCIASCIA.pdf" },
  { label: "Università di Palermo · Sciascia maestro", url: "https://iris.unipa.it/retrieve/handle/10447/284295/555668/2018%20Castiglione%20-%20L.%20Sciascia%20maestro%20-%20Il%20Giannone.pdf" }
];

const SCIASCIA_FINAL_TEST = [
  { stem: "Quale catena riassume correttamente il percorso?", options: ["Opere → biografia → contesto senza nessi", "Mondo ricevuto → fratture → sguardo → forma → opere → eredità", "Poetica → date → giudizio definitivo"], correct: 1, feedback: "Il metodo ricostruisce ponti causali prudenti fra i sei movimenti.", recovery: ["La catena", "Ogni sezione prepara un problema per quella successiva.", "La frattura modifica lo sguardo; lo sguardo rende necessaria una forma.", "conclusione-traiettoria"] },
  { stem: "Quale problema generale rivela la mafia nelle opere?", options: ["Il potere che si sottrae alla verifica", "L’inferiorità naturale di una regione", "La fine di ogni istituzione"], correct: 0, feedback: "La mafia è una forma concreta del problema potere-verità-responsabilità.", recovery: ["Caso e struttura", "Un fenomeno locale rende visibile un meccanismo generale.", "La rete mafiosa mostra come protezioni private penetrino nell’autorità pubblica.", "mondo-limite"] },
  { stem: "Che cosa significa stare dentro e fuori le istituzioni?", options: ["Rifiutare ogni incarico", "Usare un ruolo senza conoscere le regole", "Conoscere le istituzioni senza delegare loro il giudizio"], correct: 2, feedback: "La postura sciasciana unisce partecipazione e autonomia critica.", recovery: ["Postura", "La competenza interna permette una critica precisa; la distanza evita l’obbedienza.", "Il giudice applica il diritto ma resiste alla pressione dell’apparato.", "fratture-solitudine"] },
  { stem: "Perché la ragione è detta fragile?", options: ["Perché non distingue prove e opinioni", "Perché può conoscere senza riuscire a produrre giustizia", "Perché coincide con la propaganda"], correct: 1, feedback: "La sua fragilità è politica, non l’assenza di valore conoscitivo.", recovery: ["Conoscere e vincere", "Un ragionamento corretto può essere neutralizzato da interessi più forti.", "Bellodi capisce, ma il caso viene indebolito.", "immagine-verita"] },
  { stem: "Quale scelta formale rappresenta meglio quella fragilità?", options: ["Il giallo che non ristabilisce pienamente l’ordine", "La favola con morale univoca", "Il catalogo cronologico senza narratore"], correct: 0, feedback: "Il giallo imperfetto conserva l’indagine e ne mostra il limite storico.", recovery: ["Forma e mondo", "L’esito interrotto traduce narrativamente una giustizia ostacolata.", "La soluzione è compresa ma non diventa sentenza.", "poetica-giallo"] },
  { stem: "Quale eredità è più fedele a Sciascia?", options: ["Ripetere i suoi giudizi come dogmi", "Diffidare sempre e senza prove", "Verificare versioni, attribuire responsabilità e accettare i limiti delle prove"], correct: 2, feedback: "Il metodo vale anche contro la santificazione dello stesso autore.", recovery: ["Eredità critica", "La precisione richiede prove, contesto e possibilità di correggersi.", "Una versione alternativa va controllata quanto quella ufficiale.", "conclusione-eredita"] }
];
